### PR TITLE
feat(WhatsApp Business node): WhatsApp node

### PR DESCRIPTION
**Pull request by valya**
Converted #3350 into the new declarative style and finished some of the functionality.

### CODE REVIEW

**Comment by pucilpet** [comment]
Sorry for butting in... I have been actually testing this node on my workflows and I found something that is missing.

On Template Components -> Parameters

Only "Text" is available as a parameter, but for headers of the template messages you can use image, video and document objects also.

See https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#interactive-object (Header object)
Example of the template message with the image header: https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-message-templates#media-based

**Comment by luizeof** [comment]
@valya hello ... can you convert to community node ?

**Comment by RicardoE105** [comment]
@pucilpet got added

**Comment by imagina** [comment]
does anyone have this as a community node

**Comment by RicardoE105** [comment]
@imagina this is going to be merged soon.

**Comment by thomazmachado** [comment]
Guys, please help... How can I install it? After I install in VSCODE, every time that I try to install the community node in n8n it says that couldn't find the folder or something like this!

PLEASE HELP ME. How can I install it correctly?

**Comment by luizeof** [comment]
@thomazmachado this is not a community node

**Comment by thomazmachado** [comment]
> @thomazmachado this is not a community node

so how can I install it??

**Comment by luizeof** [comment]
@thomazmachado I don't know if it's ready to use. but you can checkout this pull request.

**Comment by thomazmachado** [comment]
> @thomazmachado I don't know if it's ready to use. but you can checkout this pull request.

Luiz, não sei porque tô falando em inglês kkkk vi que vc é BR...

Cara, seguinte: eu instalei tudo no vscode certinho. Instalei o node, importei o git do n8n. Depois tbm instalei as pastinhas desse branch de whatsapp lá dentro. Mas não entra de jeito nenhum no app. Como vc fez pra aparecer na listinha de Credentials? Pra mim não aparece nem a credential e muito menos o node.

Por favor me ajuda man?

**Comment by thomazmachado** [comment]
> @thomazmachado I don't know if it's ready to use. but you can checkout this pull request.

quando puder, ajuda <3

**Comment by thomazmachado** [comment]
@luizeof or @valya  can you help me please? 

I'm having trouble installing this pull request in vscode for testing.

**Comment by luizeof** [comment]
> @luizeof or @valya  can you help me please? 
> 
> I'm having trouble installing this pull request in vscode for testing.

what problem exactly?

**Comment by luizeof** [comment]
Try these steps:

- checkout this pull request 
- run: `npm i`
- run: `npm run build`
- run: `npm run dev`

Open localhost:5678

**Comment by thomazmachado** [comment]
> Try these steps:
> 
> * checkout this pull request
> * run: `npm i`
> * run: `npm run build`
> * run: `npm run dev`
> 
> Open localhost:5678

THANK YOU! IT WORKED

**Review by RicardoE105 — APPROVED** [review]

**Comment by janober** [comment]
Got released with `n8n@0.196.0`

**Comment by Joffcom** [comment]
^ "Fixed" issue in our workflow.

**Comment by imagina** [comment]
Is there an entry missing for this parameter or are we not setting it right?
image

Documentation: https://developers.facebook.com/docs/whatsapp/cloud-api/guides/send-message-templates#:~:text=the%20whatsapp_business_messaging%20permission.-,Text%2DBased%20Message%20Templates,-To%20send%20a talk about a language parameter in the template
image

**Comment by Joffcom** [comment]
Hey @imagina,

Can you open a post on our community support forum so that this doesn't get lost?

**Pull request merged**
