### PR TITLE
Add HackerNews node

### PR DESCRIPTION
**Pull request by ivov**
Hi team!

I made a very simple node for the Hacker News API. Tests and linter running successfully.

I'm part of the [MLH Fellowship](https://github.com/MLH-Fellowship). Please let me know if you have any comments!

### CODE REVIEW

**Comment by RicardoE105** [comment]
Hey @ivov, thanks. Just checked it out real quick a noticed the following:

On the UI you just added operation which is ok but in all the nodes that consume a REST API we usually have resources and operations. You have articles, username and query, I would do something like this:

Resource  Operation

Article       Get

User          Get

Search      Query

Keep in mind that as the search -> query can return multiples items, you need to have a returnAll and limit fields, which will give more flexibility to the user, for example returning either just a limited number of results or all of them. Check the image below.

image

The article operation returns all the comments than an article has on the array of children. It's so much nested data that breaks the UI, I would add a switch called 'Include comments' by default would be false, so if set to false, the comments are deleted before returning the data. The other options would be providing a field parameter to the endpoint( as long as that feature is supported) so that the user can just pick the fields available.

The search operation returns all the data within the hits array. This would sadly not play well when you try to connect this node to others, as the other nodes will receive always one element as input even when the query returned many items. So something like this has to be done. 			

```
 let responseData = await this.helpers.request(options);

  responseData = responseData.hits

```

The tags field on the search operation it's not required to make the call, so it has to be moved to a Collection named 'Additional Fields' or 'Filters' or 'Options'. In general, just the fields required to make the operation are shown.

If something it's not clear or does not make sense, please let me know.

**Comment by ivov** [comment]
@RicardoE105 Thanks so much for the detailed feedback! I think I understand now how to better align with the codebase conventions. I'll be pushing again soon!

**Comment by ivov** [comment]
@RicardoE105 Regarding the handling of `responseData.hits`, your advice was right. The reassignment `responseData = responseData.hits` produces an array of items. I thought it was an array of an array of items because the UI shows an extra pair of square brackets.

Untitled0

**Comment by janober** [comment]
Great, thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.74.0

**Pull request merged**
