### PR TITLE
[WIP] Mattermost initial node

### PR DESCRIPTION
**Pull request by milekz**
Mattermost integration v0.01

### CODE REVIEW

**Comment by janober** [comment]
Started to check the code and wrote some comments. Then realized that it is still WIP. Can you please add `[WIP]` to the title that it is obvious and then write here once it is ready to be merged. I check it then.

Thanks a lot for working on it! Looking forward to merge it. Have a great upcoming weekend!

**Comment by milekz** [comment]
Name changed, ready to merge.

**Comment by janober** [comment]
Sorry. Do not understand. It is ready to be merged? It looks like the code is still the same and the node so still not functional yet.

**Comment by milekz** [comment]
Can you please do the code review and let me know if any more isses are there

**Comment by janober** [comment]
Did you test the node? Because I am just wondering because the code looks more or less totally identical to the Slack-Node. This does not have to be wrong but if I look at the endpoints that get used they are the Slack-Endpoints and not the one from Mattermost.

For example for Channel-Create:
In your code, it uses the endpoint "channels.create" (the one Slack uses) but according to the Mattermost documentation (https://api.mattermost.com/#tag/channels) it would be "channels" and that seems to be the case for all the ones I just checked.

**Comment by janober** [comment]
I am very sorry but I have to close this pull-request. I can just not release anything like that to users. Without doing a diff it looks like over 99% of the code is still from the Slack-Node and did not get changed at all to work with Mattermost. The main thing that changed is the name of the node.

When I have a short look at the Mattermost API here: https://api.mattermost.com/#tag/posts%2Fpaths%2F~1posts%2Fpost it simply looks like it can not work as all the parameters have the wrong names (as they are still named according to the Slack API). Already starting with the most important property "message" which is called "text". The "accessToken" is somehow called "Mattermost URI". So the naming is confusing and right now either the URI or the accessToken is missing but both are needed.

My time is currently sadly very limited and for me, it sadly looks like you are trying to release something that does not work. I am really very thankful for everybody who wants to contribute to the project but all contributions really have to be properly tested by the users which created them else it harms the project more than it helps.

**Comment by janober** [comment]
Started now with a basic Mattermost-Node (still WIP) in a new branch which can be found here:
https://github.com/n8n-io/n8n/commit/bc08c7da2d28ea6fa57b48119df9c3b4564fd5bc

That should show you what I was talking about above.

**Pull request closed without merging**
