### PR TITLE
Fix/freshdesk node

### PR DESCRIPTION
**Pull request by RicardoE105**
@janober found the issue. It's fixed now!

### CODE REVIEW

**Comment by janober** [comment]
Great! Thanks a lot!

**Comment by janober** [comment]
@RicardoE105 Perfect. Thanks a lot. Got merged.

**Comment by airmoi** [comment]
Hi @RicardoE105 
I'm very interested with FreshDesk node.
Do you plan to implement more functions or would you mind if I add support for other endpoints ?

**Comment by RicardoE105** [comment]
Hi @airmoi 

Go ahead, feel free to add as many resources as you want.

**Comment by RicardoE105** [comment]
@airmoi Let me know if you have any questions!

**Pull request merged**
