### PR TITLE
New tools added in the last year - N8N-3291

### PR DESCRIPTION
**Pull request by mcolomer**
Add tool Text/Get HTML Code From Markdown (2022-03-11)
Add tool Text/Get Text Without HTML (2022-03-09)
Add tool Text/Get Markdown Text From HTML (2022-03-09)
Add tool Text/Get Spin String (2022-01-18)
Add tool Personal/Get LinkedIn URI By Phone (2021-11-16)
Add tool Internet/Get Long Version Of Shortened URL (2021-11-14)
Add tool Finance/Check Crypto Wallet Is Valid (2021-11-10)
Add tool Internet/Get Last Feed Entry By Domain (2021-10-23)
Add tool Internet/Get Feed Entries By Domain (2021-10-22)
Add tool Personal/Get LinkedIn URI By Email (2021-10-21)
Add tool Company/Get Decision Makers By Search Engine (2021-10-20)
Add tool Company/Get Decision Maker By Search Engine (2021-10-19)
Add tool Communication/Get Personal Email By Social Network Profile (2021-10-15)
Add tool Geographic/Get Location By Parameters (2021-09-28)
Add tool Company/Get GitHub URI By Company's Domain (2021-09-16)
Add tool Company/Get YouTube URI By Company's Domain (2021-09-16)
Add tool Company/Get Pinterest URI By Company's Domain (2021-09-15)
Add tool Company/Get Instagram URI By Company's Domain (2021-09-14)
Add tool Product/Get ISBN13 Code By ISBN10 Code (2021-09-12)
Add tool Product/Get ISBN10 Code By ISBN13 Code (2021-09-11)
Add tool Product/Get Book By ISBN (2021-09-10)
Add tool Company/Get Facebook URI By Company's Domain (2021-09-08)
Add tool Company/Get Twitter URI By Company's Domain (2021-09-07)
Add tool Company/Get LinkedIn URI By Company's Domain (2021-09-06)
Add tool Product/Get Data By VIN Number (2021-08-05)
Add tool Product/Check VIN Number Is Valid (2021-08-04)
Add tool Communication/Get Search LinkedIn Contacts Url (2021-07-25)
Add tool Geographic/Get Time Data By Coordinates (2021-05-25)
Add tool Communication/Check Email Is Catchall (2021-05-13)
Add tool Geographic/Get Time Data By Postal Address (2021-05-06)
Add tool Communication/Get Email By Firstname, Lastname And Company (2021-05-01)
Add tool Finance/Get Swift Code Lookup (2021-04-27)
Add tool Image/Get OCR Text From Image (2021-04-26)
Add tool Geographic/Get Normalized Country (2021-03-31)
Add tool Communication/Get Parsed And Validated Phone (2021-03-30)

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with `n8n@0.176.0`

**Comment by janober** [comment]
Got released with `n8n@0.176.0`

**Comment by mcolomer** [comment]
Thank you Jan!

**Pull request merged**
