### PR TITLE
fix: Loop node no input data shown

### PR DESCRIPTION
**Pull request by michael-radency**
## Summary

fix for:
Schema view: no input data shown for first node after a loop node
You can't switch to table/JSON view either.

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/NODE-1533/schema-view-no-input-data-shown-for-first-node-after-a-loop-node

### CODE REVIEW

**Review by ShireenMissi — DISMISSED** [review]
LGTM 🎉

**Review by ShireenMissi — COMMENTED** [review]
As discussed on Linear, this fix shouldn't be merged for now.

**Review by ShireenMissi — APPROVED** [review]
LGTM 🎉

**Comment by janober** [comment]
Got released with [`n8n@1.53.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.53.1)

**Pull request merged**
