### PR TITLE
fix(Split In Batches Node): Fix issue with pairedItem

### PR DESCRIPTION
**Pull request by janober**
Fixes the pairedItem issue in combination with the Split in Batches node if data outside of the loop does get accessed.

### CODE REVIEW

**Review by agobrech — APPROVED** [review]
LGTM, is it the only node that would benefit from this fix?

**Comment by janober** [comment]
Exactly. It is the only node that messes up the "history" and needs so an overwrite.

**Comment by janober** [comment]
Thanks a lot for the review. Got merged.

**Comment by janober** [comment]
Got released with `n8n@0.207.0`

**Pull request merged**
