### PR TITLE
Upgrade to ESLint 8

### PR DESCRIPTION
**Pull request by ivov**

### CODE REVIEW

**Review by alexgrozav — CHANGES_REQUESTED** [review]
Happy to see this finally getting upgraded!

Can you change the `lint` and `lintfix` commands to use `eslint` instead of `tslint`? Also, can you please remove tslint references (including `tslint.json`)?

**Comment by ivov** [comment]
Thanks!

Package by package:
- /cli, /core, /node-dev, /workflow: Removed `tslint` dependency
- /design-system, /editor-ui, /nodes-base: Kept `tslint` because still in use

Where `tslint` is still in use, we first need to reconcile those rules with our `.eslintrc.js`, remove `tslint` dep, remove `tslint` exceptions, remove `tslint` from the commands, run ESLint, add its exceptions. This additional work is [tracked separately](https://linear.app/n8n/issue/N8N-4119/phase-out-tslint).

**Review by alexgrozav — APPROVED** [review]
Great work, @ivov!

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with `n8n@0.188.0`

**Pull request merged**
