### PR TITLE
fix headerRow option

### PR DESCRIPTION
**Pull request by lublak**
Returns the data in the same format whether with or without header row.
The current solution is rather poor. You write the columns as an array in a column called row.

### CODE REVIEW

**Comment by janober** [comment]
hm, honestly not sure what to do with this as it is a breaking change. Was an easy change before it got released but now sadly not anymore.

**Comment by lublak** [comment]
@janober Unfortunately, I have no idea what the best thing to do is. But the current solution doesn't really fit. 
Either it is changed quickly or you live with the dirty design. And I have to say again, it's not pretty.
Is there another solution?

**Comment by lublak** [comment]
@janober I'm working first with an internal fork, although I would like to work on the official release, just because of the updates.
But just for the clarity if my workflow throws an error and I want to look at the csv import. (I work a lot with csv files without header, so it is very important for me to have it in a readable form).

If it is not wanted here because it is a breaking change, you can close it.

**Comment by janober** [comment]
Thanks a lot. I thought now about it some more.

For now, I will leave it as it is. For two reasons:
1. To avoid a breaking change
2. It works now already similar to how Google Sheet node returns RAW data

**Pull request closed without merging**
