### PR TITLE
replace pdf-parse

### LINKED ISSUE #1244: replace pdf-parse
**Describe the bug**

pdf-parse looks like complete unsupported and it use an old pdf.js version.

**Expected behavior**

A maintained alternative of pdf-parse should used with newer pdf.js.

**Additional context**

Currently i'm look into it, if we just can use pdf.js without wrapper. Since pdf.js closed some issues.
I copied the tests of pdf-parse and write a new wrapper based on the new version with the npm package https://www.npmjs.com/package/pdfjs-dist. I make a pull request if it is simple to integrate. 

**Some links**

https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/package.json
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/ReadPdf.node.ts
https://gitlab.com/autokent/pdf-parse

**Update 2020-12-17**

I readed alot about transform in textContent and how to read pdf with pdfjs.
I implemented a dirty js library to test it out and it works fine.
Currently i try to implement a tool that get some outline information (bookmarks).
After that i translate to code to typescript.
But at the moment I don’t know whether I should create an external library with a test environment which will then be integrated or whether the implementation should be built directly into the node direct on pdfjs without extra dependencies

**Update 2021-02-02**

Through other projects, it took a little longer, but the rewriting in typescript is progressing. It just depends on this pull request:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50979

**Update 2021-04-15**

Sorry for the delay, but I have now built a typescript project.
(https://github.com/lublak/pdfdataextract)
There are still 3.5 things missing.

**Update 2022-01-17**

And another delay (sry). But the development has begun and we are gradually replacing it. Plus more functions that were missing will be added.
Other functions will also follow, but they still need a bit of work: https://github.com/lublak/pdfdataextract/tree/contentinfoextractor

**Todos**

- [x] tests (jest is already done, only pdf examples are missing)
- [x] npm release
- [ ] rewriting the current node

and the 3.5 thing: 
- [x] improve the code

### PR DESCRIPTION
**Pull request by lublak**

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @lublak,

Let me know when you are ready for review and I will take a look.

**Comment by lublak** [comment]
@Joffcom
There is a small distinction between pdf-parse and pdfdataextract in the json structure returned.

| pdf-parse                | pdfdataextract |
|---------------------|----------------|
| numpages               | pages              |
| version                    | -                     |
| numrender              | -                     |
| -                             | fingerprint       |
| -                             | outline             |
| -                             | permissions      |
| text -> string(\n\n)  | text -> string[] |

so if we merge it now, we have a breaking changes.
The question is what is wanted, a breaking change or that the structure is adapted to the old version.

```js
{
  numpages : pages,
  version: '2.10.377',
  numrender: text.length,
  fingerprint: fingerprint,
  outline: outline,
  permissions: permissions,
  text: text.join('\n\n')
}
```

**Comment by lublak** [comment]
Another question: [package-lock.json](https://github.com/n8n-io/n8n/pull/2690/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519).
Should something like this be pushed with?

**Comment by Joffcom** [comment]
Hey @lublak,

I think where possible reducing the amount of breaking changes is always worth doing that way it won't come as a surprise to anyone that upgrades without checking the release notes.

With the package-lock.json it is an interesting one and one for @janober to answer.

**Comment by lublak** [comment]
@Joffcom i think jear. But also there can be an extra option for "array" result. Without joining it. What about the extra data? like fingerprint, outline and permissions.

**Pull request closed without merging**
