### PR TITLE
refactor(core): Use an IoC container to manage singleton classes [Part-1] (no-changelog)

### PR DESCRIPTION
**Pull request by netroy**
This is also a step towards automatic dependency injection, and automatic dependency mocking for unit tests.

### CODE REVIEW

**Review by krynble — CHANGES_REQUESTED** [review]
Code looks good but executions in `own` mode are not working. They show up in the execution list as failed. I have created a workflow with Schedule + Set node, and it fails right away.

**Comment by netroy** [comment]
Looks like `typedi` has issues with circular dependencies.
Since the `PurgeInvalidWorkflowConnections` migration, `NodeTypes` and `LoadNodesAndCredentials` depend on each other. as a short term fix I've changed some imports to be dynamic, but in the long run we need to get rid of circular dependencies like these.

**Review by krynble — DISMISSED** [review]
Looking good, everything runs as expected now.

Do you have plans to migrate other singletons as well, such as the LoggerProxy?

**Comment by netroy** [comment]
> Do you have plans to migrate other singletons as well, such as the LoggerProxy?
Yeah. There is already a part 2 in progress, where all singletons will using this pattern, and we'll also have automatic constructor injection wherever possible.

**Review by krynble — APPROVED** [review]

**Comment by janober** [comment]
Got released with `n8n@0.217.1`

**Pull request merged**
