### PR TITLE
Fix timezone in google calendar

### PR DESCRIPTION
**Pull request by 5pecia1**
Google Calendar can't apply timezone about create, update, allday.
So, I modify timezone variable name and return format.

* change timezone additionalFields variable name in Google.Calendar.nodes.ts from timeZone to timezone
* add timezone information to formated code

Signed-off-by: 5pecia1 <pdpxpd@gmail.com>

### CODE REVIEW

**Comment by michael-radency** [comment]
@5pecia1 Hi, thank you, added fixes for nodelinter issues

**Review by michael-radency — APPROVED** [review]

**Comment by 5pecia1** [comment]
@michael-radency Thank you!

**Comment by janober** [comment]
Thanks a lot for fixing this. Got merged.

**Comment by janober** [comment]
Got released with `n8n@0.167.0`

**Pull request merged**
