### PR TITLE
fix(nodes-base): display scope as text for xero auth credentials

### PR DESCRIPTION
**Pull request by jhaltercmu2020**
display scope as text in order to be able to add more scopes to my xero credential

The PR updates the Xero Credentials node to allow for scopes to be added.

## Review / Merge checklist
- [ ] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @jhaltercmu2020,

Thanks for the PR, This is something we have been talking about doing internally but it likely won't be done like this.

Sadly as much as we like getting PRs in this case as we are starting to think about implementing something around this we won't be accepting this PR at this time and I am going to move it to closed.

Let me know if you have any questions around this.

**Comment by jhaltercmu2020** [comment]
> Hey @jhaltercmu2020,
> 
> Thanks for the PR, This is something we have been talking about doing internally but it likely won't be done like this.
> 
> Sadly as much as we like getting PRs in this case as we are starting to think about implementing something around this we won't be accepting this PR at this time and I am going to move it to closed.
> 
> Let me know if you have any questions around this.

@Joffcom Understandable, I am sure there are many ways to fix this issue. I have a Xero scope that I need to add in order to make one of our requests work. Do you have any suggestions on how to work around this issue for now given the scope that I need to use is currently not in the list of hidden scopes?

**Comment by Joffcom** [comment]
Hey @jhaltercmu2020,

At the moment while it isn't ideal the best option would be to create a new generic oauth2 credential that has the extra scopes you need this will then allow you to use it in the HTTP request node as needed. The annoying thing about this is it does mean you will have one credential for the node and another for the http requests.

Something we have been thinking about is having 3 options for scopes so a read only, read and write then custom which lets you put in whatever you want which I think would solve the issue here.

Out of interest whch call are you trying to make, It could be that we could update the node to include this in the future as well.

**Comment by jhaltercmu2020** [comment]
> Hey @jhaltercmu2020,
> 
> At the moment while it isn't ideal the best option would be to create a new generic oauth2 credential that has the extra scopes you need this will then allow you to use it in the HTTP request node as needed. The annoying thing about this is it does mean you will have one credential for the node and another for the http requests.
> 
> Something we have been thinking about is having 3 options for scopes so a read only, read and write then custom which lets you put in whatever you want which I think would solve the issue here.
> 
> Out of interest whch call are you trying to make, It could be that we could update the node to include this in the future as well.

@Joffcom We want to push attachments using the Xero node. The required scope is: `accounting.attachments`.

**Pull request closed without merging**
