### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by youghi00715**
## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Comment by netroy** [comment]
why are you creating spam PRs?

**Comment by youghi00715** [comment]
this is not a spam , just testing.

**Comment by netroy** [comment]
trying to check if we secure our CI secrets?

**Comment by youghi00715** [comment]
trying to see if your workflows are secured or not , i just saw a pull_request_target workflow i want just to check it, 
no bad intentions don't worry :)

**Comment by netroy** [comment]
> just saw a pull_request_target workflow 

That workflow has long been disabled. Even if it was vulnerable, it's not worth spending time on.

> no bad intentions don't worry :)

It's hard to not worry now a days, especially when anonymous github users reassure me that I don't need to worry 😅

**Pull request closed without merging**
