### PR TITLE
Clickup OAuth2 support

### PR DESCRIPTION
**Pull request by Rupenieks**

### CODE REVIEW

**Comment by RicardoE105** [comment]
@Robarelli This is ready to merge. Thanks.

These are the changes I made:

1. Remove server property for credentials as it was not being used.
2. Changed authentication from type options to type string.

@janober I did not merge it cuz I had to make a small change to the requestOAuth2 function to make work with ClickUp and we had agreed that any changes to the core have to be notified. Basically it just removes the Bearer string from the header when the keepBearer parameter is set to false. By default, this is set to true since as of now this is only integration I have seen that requires sending the token on the header without the 'bearer' string.

**Comment by janober** [comment]
@RicardoE105 there seem to be more and more parameters. Instead of adding more and more, it is probably better to start to replace them (`keepBearer = true, tokenType?: string, property?: string`) with a single parameter like  `settings` instead. That makes it a little bit less messy and better and easier to extend in the future.

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.83.0

**Pull request merged**
