### PR TITLE
Add offset option to Airtable List method

### PR DESCRIPTION
**Pull request by flybluewolf**

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot for the contribution!

Sadly do not understand how it can be used or for which use cases it is helpful, can you please explain why you added it and how you want to use it. Becuase I just tested it and realized then that I can not just put a number in there like 10 (to start with the 11th entry as I expected), it has to be a special offset value that the Airtable API did return in a previous request. But as n8n does not return the value anywhere and rather handles all of that underneath the hood I wonder about possible use-cases. Thanks!

**Comment by flybluewolf** [comment]
> Thanks a lot for the contribution!
> 
> Sadly do not understand how it can be used or for which use cases it is helpful, can you please explain why you added it and how you want to use it. Becuase I just tested it and realized then that I can not just put a number in there like 10 (to start with the 11th entry as I expected), it has to be a special offset value that the Airtable API did return in a previous request. But as n8n does not return the value anywhere and rather handles all of that underneath the hood I wonder about possible use-cases. Thanks!

@janober , The API of Airtable is limited to 5 requests per second per base. When we have thousands of rows,   it's low performance  that all results was returned in once call and possible reached the limit of Airtable. The attachment is my sample.
Untitled

**Review by flybluewolf — COMMENTED** [review]
@janober  Please review these changes. Thanks.

**Comment by Joffcom** [comment]
Hey @flybluewolf,

So would you be using this to put in your own rate limiting to make sure you don't hit the API limits? Maybe take 10 records then process them and loop back with the offset ID to process the next batch something like this...

image

The tricky bit with requests like this is it can be hard to understand the why, I am happy that it works and doesn't break the normal functionality although there is a tweak I would make, I would move the Offset option higher up so the options list is alphabetical and the description seems to be `Specify the offset of the first hit to return.` I am not sure "hit" is the right word maybe record would be better so something like `Specify the offset id of the first record to return.`

If you can run through the changes and get it updated to use the latest changes in the master branch I can get this moved to the next review step, This isn't of course a promise that we will add this feature in but we will be looking at it and will let you know what is likely to happen.

<details><summary>Example Workflow Here</summary>
<p>

```json
{
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        240,
        300
      ]
    },
    {
      "parameters": {
        "operation": "list",
        "application": "appdLSbMZvNp4Ib0X",
        "table": "Orders",
        "returnAll": false,
        "limit": 5,
        "additionalOptions": {
          "offset": "={{$node[\"Set\"].json[\"offset\"]}}"
        }
      },
      "name": "Airtable",
      "type": "n8n-nodes-base.airtable",
      "typeVersion": 1,
      "position": [
        680,
        300
      ],
      "credentials": {
        "airtableApi": {
          "id": "5",
          "name": "Airtable account"
        }
      }
    },
    {
      "parameters": {
        "values": {
          "string": [
            {
              "name": "offset"
            }
          ]
        },
        "options": {}
      },
      "name": "Set",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        460,
        300
      ]
    },
    {
      "parameters": {
        "conditions": {
          "string": [
            {
              "value1": "={{$node[\"Airtable\"].json[\"offset\"]}}",
              "operation": "isEmpty"
            }
          ],
          "boolean": []
        }
      },
      "name": "IF",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        1080,
        300
      ],
      "executeOnce": true
    },
    {
      "parameters": {
        "values": {
          "string": [
            {
              "name": "offset",
              "value": "={{$node[\"Set\"].json[\"offset\"] = $node[\"Airtable\"].json[\"offset\"]}}"
            }
          ]
        },
        "options": {}
      },
      "name": "Update Offset",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        580,
        520
      ]
    },
    {
      "parameters": {},
      "name": "Fake processing",
      "type": "n8n-nodes-base.noOp",
      "typeVersion": 1,
      "position": [
        900,
        300
      ]
    },
    {
      "parameters": {},
      "name": "Finished!",
      "type": "n8n-nodes-base.noOp",
      "typeVersion": 1,
      "position": [
        1280,
        160
      ]
    },
    {
      "parameters": {},
      "name": "More to process",
      "type": "n8n-nodes-base.noOp",
      "typeVersion": 1,
      "position": [
        1080,
        520
      ]
    }
  ],
  "connections": {
    "Start": {
      "main": [
        [
          {
            "node": "Set",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Airtable": {
      "main": [
        [
          {
            "node": "Fake processing",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Set": {
      "main": [
        [
          {
            "node": "Airtable",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "IF": {
      "main": [
        [
          {
            "node": "Finished!",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "More to process",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Update Offset": {
      "main": [
        [
          {
            "node": "Airtable",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Fake processing": {
      "main": [
        [
          {
            "node": "IF",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "More to process": {
      "main": [
        [
          {
            "node": "Update Offset",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```
</p>
</details>

**Comment by nivb06** [comment]
Hi flybluewolf, thanks for contributing to n8n!
I am closing this ticket as this functionality can already be solved with existing functionality
Thanks,
n8n-team

**Pull request closed without merging**
