### PR TITLE
feat(CraftMyPDF Node): New node

### PR DESCRIPTION
**Pull request by Juneezee**
## Summary

This PR adds a new [CraftMyPDF](https://craftmypdf.com/) node that allows automated PDF creation and manipulation. 7 most-used core APIs are implemented in this PR:

/cc @bktan81 (creator of CraftMyPDF)

> [!NOTE]
> CraftMyPDF API reference: https://craftmypdf.com/docs/index.html

1. [Create a PDF](https://craftmypdf.com/docs/index.html#tag/PDF-Generation-API/operation/create)

   https://github.com/user-attachments/assets/6668d372-5fe7-4601-a158-bf4739eb8cae

2. [Create a PDF asynchronously](https://craftmypdf.com/docs/index.html#tag/PDF-Generation-API/operation/create-async)

   https://github.com/user-attachments/assets/26e95c1d-6982-456b-ab9e-534e2c810e35

3. [Merge PDF URLs](https://craftmypdf.com/docs/index.html#tag/PDF-Manipulation-API/operation/merge-pdfs)

   https://github.com/user-attachments/assets/ce7df4de-06e4-4c55-81f6-ec1b85266d18

4. [Add watermark to a PDF](https://craftmypdf.com/docs/index.html#tag/PDF-Manipulation-API/operation/add-watermark)

   https://github.com/user-attachments/assets/16918c09-88a1-45b2-ad40-553c57b7bcbc

5. [Create an image](https://craftmypdf.com/docs/index.html#tag/Image-Generation-API/operation/create-image)

   https://github.com/user-attachments/assets/23a59f70-4a1b-421c-89c6-0561876557c9

6. [List transactions](https://craftmypdf.com/docs/index.html#tag/Account-Management-API/operation/list-transactions)

   https://github.com/user-attachments/assets/8300f276-c9aa-4915-952c-de229c3378d4

7. [Get account information](https://craftmypdf.com/docs/index.html#tag/Account-Management-API/operation/get-account-info)

   https://github.com/user-attachments/assets/715761eb-97b0-4b37-8d64-27e0f49a359a

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @Juneezee,

Thanks for the PR, We have created "GHC-355" as the internal reference to get this reviewed.

One of us will be in touch if there are any changes needed, in most cases this is normally within a couple of weeks but it depends on the current workload of the team.

**Comment by Joffcom** [comment]
Hey @Juneezee 

Thanks for the contribution, We have now created a Community Node Repository which is our preferred method for new node submissions.

Once a node has been published to the Community Node Repository users will be able to install the node from their n8n interface and will be able to use your node quicker, You will also be able to update the node as needed without needing to wait for the review process.

In the future we may reach out to you about including your node in our main release, But for now I am going to close this PR.

You can find more information in the links below, If you have any questions about this or need any help let us know.

Building Community Nodes: https://docs.n8n.io/integrations/community-nodes/build-community-nodes/

Submitting Community Nodes: https://docs.n8n.io/integrations/creating-nodes/deploy/submit-community-nodes/

Published Nodes: https://www.npmjs.com/search?q=keywords:n8n-community-node-package

**Comment by Juneezee** [comment]
Hi @Joffcom, thank you for your response.

Could you please clarify if there is anything in this PR that does not comply with n8n's standards or guidelines? Are there any prerequisite requirements that must be met for a new node to be integrated into the main release of n8n?

Additionally, I would appreciate any insight into what made https://github.com/n8n-io/n8n/pull/10777 acceptable, but not this PR.

Thank you for your time and guidance.

**Comment by Joffcom** [comment]
Hey @Juneezee,

Sorry for the delay, new nodes are currently only being added to the core by us based on requests and internal roadmap as adding a new node involves more than reviewing and testing the PR. Once added we are then committed to documenting, testing and maintaining the node moving forward.

The node you have found is one we hired a contractor to create for us based on requests from internal users and external users.

In terms of standards / guidelines there are a few things below from a quick look...

1) There are no tests
2) It doesn't use the declarative style which is preferred
3) The error output doesn't look like it includes the item index that caused it
4) The GenericFunctions is using code marked as deprecated `IRequestOptions` and `requestWithAuthentication`

Other than that the node does look good it just isn't something for right now sadly.

**Pull request closed without merging**
