### PR TITLE
:sparkles: multipart data

### PR DESCRIPTION
**Pull request by RicardoE105**
@janober I do not know what I did before. This is the right pull request. 

https://community.n8n.io/t/receiving-a-form-submission/467/4

### CODE REVIEW

**Comment by janober** [comment]
Really cool. Perfect. Thanks a lot for taking care of that!

**Comment by janober** [comment]
I just tested it. But somehow did not work for me. If I make the curl request like provided in the issue:
```bash
curl -X POST -F 'email=john@foo.com' -F 'name=john' http://localhost:5678/webhook-test/264/webhook/test
```
the body is somehow empty for me.

**Comment by RicardoE105** [comment]
@janober will try it but I tested it with postman using multipart data and worked perfectly

**Comment by RicardoE105** [comment]
just ran that command and worked fine.

image

image

**Comment by janober** [comment]
Very confusing. Thanks. Will check again.

**Comment by janober** [comment]
Not the slightest idea what I did do wrong before (maybe forgot to build the node first?!?!) no matter what, it works perfectly as you said.

So thanks a lot and sorry for the confusion! Got merged.

**Comment by janober** [comment]
Got released with n8n@0.52.0

**Pull request merged**
