### PR TITLE
Todoist Integration [WIP]

### PR DESCRIPTION
**Pull request by RicardoE105**

### CODE REVIEW

**Comment by RicardoE105** [comment]
@janober is this posible? 

`         type: 'multiOptions',
                typeOptions: {
					loadOptionsMethod: 'getTags',
				},`

Loading the options of a `multioptions` type element dynamically?

**Comment by RicardoE105** [comment]
@janober  As you can see here  ### https://developer.todoist.com/rest/v1/#create-a-new-task you can add multiples tags by to each new tags, the multipleOptions option type is perfect, but looks like it does not let you pull the options dynamically, cuz if it did I could pull all the tags from the account so that the user can pick the ones he wants to attach to that task.

**Comment by janober** [comment]
@RicardoE105 You are right that was really not possible. Fixed that now with that commit:
https://github.com/n8n-io/n8n/commit/c206658f8b99253b3a4b5a18f2db8291d5128ed6

So should now work fine.

**Comment by RicardoE105** [comment]
Hey @janober it’s done. Test it and let me know 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by janober** [comment]
Great, thanks a lot got merged!

I did remove the lodash and moment code. Even though it works because dependencies have them as dependencies they should not really be used as that could change anytime. So they should then be added as dependencies of "n8n-nodes-base". But normally try to avoid that if possible. In this case it seemed like it was possible. But can you maybe explain why you used moment? I removed it and it still works for me like before. Was there some edge case or something?

Apart from that only:
 - fixed indentation (spaces -> tabs)
 - set default value for resource (actually not sure anymore that is best but because that is what happens currently everywhere also wanted to do that for now here. Will however maybe change in the future)
-added some missing semicolons

**Comment by RicardoE105** [comment]
Hey @janober, 

With regard moment I think it’s just I’m biased to use it on every time I need to handle dates cuz it allows me to format the dates on various forms, but you are right here was not needed. 

With regard the indentation I don’t know why my editor does not show me those errors, gotta check if I have installed tslint. 

With regard the not setting the resource as default I do agree with you as we add more resources we should have one as a default. 


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by janober** [comment]
Got released with n8n:0.34.0

**Pull request merged**
