### PR TITLE
chore: Add `server_type` tag to Sentry errors (no-changelog)

### PR DESCRIPTION
**Pull request by ivov**
https://n8nio.slack.com/archives/C069HS026UF/p1729067696334869?thread_ts=1729066739.745339&cid=C069HS026UF

### CODE REVIEW

**Review by netroy — COMMENTED** [review]
1. Can we set the tag globally, but using `Sentry.setTag` instead?
2. Should we convert this file to start using DI as well, so that we can stop doing `Container.het` ?

**Comment by ivov** [comment]
1. Done
2. Tracking here: https://linear.app/n8n/issue/PAY-2113

**Review by netroy — APPROVED** [review]

**Comment by ivov** [comment]
Thanks! I should've double checked the auto-import.

**Comment by janober** [comment]
Got released with [`n8n@1.64.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.64.0)

**Pull request merged**
