### PR TITLE
replace glob-promise with fast-glob

### PR DESCRIPTION
**Pull request by lublak**

### CODE REVIEW

**Comment by lublak** [comment]
What are the advantages?

- Higher performance
- Posix brackets
- Regular expression syntax

**Comment by krynble** [comment]
Hi @lublak 

Thank you for your contribution. I updated this branch to the latest changes and created another PR: https://github.com/n8n-io/n8n/pull/2096

I will be closing this one and send the other for evaluation.

**Comment by janober** [comment]
Thanks a lot. Got merged with #2096

**Comment by janober** [comment]
Got released with 0.135.0

**Pull request closed without merging**
