### PR TITLE
Jira Server support

### PR DESCRIPTION
**Pull request by RicardoE105**
@janober This should work now with both versions. The only issue is the displayOptions properties on credentials are not working. It always shows all fields.

### CODE REVIEW

**Comment by janober** [comment]
Yes, displayOptions are not supported on credentials. The selection how to authenticate would have to happen on the node like on the HTTP Request Node. And depending on what got selected it would have to use different credentials.

**Comment by RicardoE105** [comment]
@janober should work now. I added as well the getAll operation as it was requested here: https://community.n8n.io/t/jira-integration-got-created/35/12?u=ricardoe105

**Comment by janober** [comment]
Great thanks a lot @RicardoE105 . Looks good on first sight. Will check it out later properly. Wish you a great weekend!

**Comment by janober** [comment]
Great, thanks a lot! Got merged.

**Comment by janober** [comment]
Got released with n8n@0.52.0

**Pull request merged**
