### PR TITLE
fix(redis Node): fix issue with hash values not being correctly saved

### PR DESCRIPTION
**Pull request by Joffcom**

### CODE REVIEW

**Comment by janober** [comment]
Will that not be a breaking change? Or is there no chance at all that it worked before?

**Comment by Joffcom** [comment]
@janober it is breaking, I was chatting to @RicardoE105 about this yesterday and if we should take the breaking route or light versioning.

I will be updating this today to mark it as breaking.

**Comment by janober** [comment]
What are the reasons not to use light-versioning? 

And can we not even avoid a new version and make it work both ways by checking for the type of value?

**Comment by Joffcom** [comment]
@janober updated to use light versioning and added a workflow to the linear ticket for testing.

**Comment by Joffcom** [comment]
Closing... Turns out it is working as expected it is just an issue with how it is being used. Will update docs shortly

**Pull request closed without merging**
