### PR TITLE
Refactor deal product expansion in Pipedrive node

### PR DESCRIPTION
**Pull request by ivov**
This PR refactors the Pipedrive node's deal product expansion contributed at #1993.

### CODE REVIEW

**Comment by RicardoE105** [comment]
@rodrigoscdc, thanks very much for your contribution.

**Comment by rodrigoscdc** [comment]
@RicardoE105 it's my pleasure to help improve with minor things in this wonderful project.

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.132.0

**Pull request merged**
