### PR TITLE
Fix 'run start' for Windows

### PR DESCRIPTION
**Pull request by YoniFei**
As brought up [here](https://community.n8n.io/t/trying-to-run-on-according-to-instructions-windows-10-fails/152), the current 'npm run' command doesn't work on windows.
This is a silly matter I could only find addressed [here](https://stackoverflow.com/questions/50243229/run-batch-file-in-npm-script).

No reason to think this syntax won't work for Mac/Linux, but I tested on Linux anyhow.
Please validate that it works for Mac as well.

### CODE REVIEW

**Comment by janober** [comment]
Great thanks a lot!

Acutally looking at the line do not remember why I did it like that. Should actually also be possible without the "cd". At least in Linux it works. Can you please try if either one of the following two works?

  - `packages/cli/bin/n8n`
  - `./packages/cli/bin/n8n`

Because that would be cleaner.

**Comment by YoniFei** [comment]
I tried both previously, neither work.

**Comment by janober** [comment]
Thanks! Hm can sadly not merge it like that because that breaks it for Linux users.

Does this one work on Windows? `cd packages/cli/bin && ./n8n`

Because on Linux it does.

**Comment by YoniFei** [comment]
It doesn't.. I've numerous variations, this is the only one that works on Windows.
I didn't test for this specifically on Linux, just a general 'cd folder && some_executable', which does work.
[run-script-os](https://www.npmjs.com/package/run-script-os) seems like a possible solution.

This is silly..

**Comment by janober** [comment]
Yes, making it work for different operating systems is always fun ;-)

I just checked `run-script-os` seems like a good solution!

**Comment by YoniFei** [comment]
Alright, in the latest commit in that case.
Want to begin working on the Stripe integration, no dev environment will be a little annoying but I'll just keep rebuilding for production.

**Comment by janober** [comment]
Great thanks a lot for fixing that and happy to welcome you as a contributor!

About the dev environment. You should still be able to get it up and running just a little bit more complicated. Instead of running `npm run dev` in the main folder you would just have to run it in these two separate:

  - packages/cli
  - packages/nodes-base

The other packages do not change anyway so they do not matter. 

Thanks for looking into the stripe integration!

**Pull request merged**
