### PR TITLE
Stateless and static Webhooks 

### PR DESCRIPTION
**Pull request by janober**

### CODE REVIEW

**Comment by RicardoE105** [comment]
Hey pal, This is based on the feedback you gave me.

- Set the uuid as default for webhook nodes
- Improve error message when uuid/method is duplicated
- Now the model does not have the autoincrement id

@janober

**Comment by RicardoE105** [comment]
Hey pal, This is based on the feedback you gave me.

- Set the uuid as default for webhook nodes
- Improve error message when uuid/method is duplicated
- Now the model does not have the autoincrement id

@janober

**Comment by RicardoE105** [comment]
@janober Ok just added a fix for the issue with the test webhooks

**Comment by AhmetHuseyinDOK** [comment]
We hope this feature to solve some issues with scaling. I wonder when this pull will be merged to master.

**Comment by janober** [comment]
Is sadly not ready yet @AhmetHuseyinDOK . Needs still to get implemented for other databases. Development is happening in this branch:
https://github.com/n8n-io/n8n/tree/static-stateless-webhooks

I hope however that we can merge it next week.

**Pull request closed without merging**
