### PR TITLE
:sparkles: Add SecurityScorecard node

### PR DESCRIPTION
**Pull request by mluhta**
This node implements part of the [SecurityScorecard](https://securityscorecard.com) API.

Features include:
* Listing/Creating/Editing portfolios
* Generating/Downloading reports
* Sending invites
* Getting industry statistics
* Getting company statistics/scorecards

The API documentation of SecurityScorecard can be found at https://securityscorecard.readme.io/reference

Their API is a bit weird, the parameters can differ between two similar endpoints and there is apparently no versioning but everything should work at the moment. And just to be clear I'm not affiliated with SecurityScorecard :).

### CODE REVIEW

**Comment by RicardoE105** [comment]
@mluhta really cool. Thanks for your contribution. Tried to test it but it seems like with the free account I do not have access to the API. Can you confirm? If not I will have to email them to see if they can give me access to the API. If you have a test account with API access I could use that as well. Thanks.

**Comment by mluhta** [comment]
@RicardoE105 The free plan doesn't indeed seem to have API access. I have access to an enterprise account through work but I sadly can't get a test account for you.
image

**Comment by RicardoE105** [comment]
@mluhta thanks for confirming. Gonna send an email to SecurityScorecard to see if they can get me access. Will keep you posted.

**Comment by janober** [comment]
As an update. Neither @RicardoE105 nor I got an answer from them yet. So not sure when we can test and merge the node.

**Comment by mluhta** [comment]
@janober Okay, thanks for the update. I'll contact them too next week, they might be on a holiday at the moment.

**Comment by janober** [comment]
Sadly still nothing. I started now one last attempt and reached out to an employee via LinkedIn. Sadly do not have more time to invest in it. If they are not interested then we can not force it.

**Comment by janober** [comment]
Got an answer. So with some luck we will get some credentials soon and can then merge the PR.

**Comment by RicardoE105** [comment]
@mluhta finally was able to review. It was working well. However, I made some improvements here #1247. If you can test it and provide feedback would be aswersome. Again, thanks very much for your contribution.

**Comment by mluhta** [comment]
> @mluhta finally was able to review. It was working well. However, I made some improvements here #1247. If you can test it and provide feedback would be aswersome. Again, thanks very much for your contribution.

Great! I'll check it next week

**Comment by janober** [comment]
Thanks a lot. Got merged with #1371

**Comment by janober** [comment]
Got released with n8n@0.105.0

**Pull request closed without merging**
