### PR TITLE
Create ExpertAI-AgentTool

### PR DESCRIPTION
**Pull request by phoenicxai**
Create ExpertAI-AgentTool

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Comment by phoenicxai** [comment]
Create ExpertAI-AgentTool

**Review by phoenicxai — COMMENTED** [review]
Create ExpertAI-AgentTool

**Comment by Joffcom** [comment]
Hey @phoenicxai,

Thanks for the PR, We have created "GHC-593" as the internal reference to get this reviewed.

One of us will be in touch if there are any changes needed, in most cases this is normally within a couple of weeks but it depends on the current workload of the team.

**Comment by Joffcom** [comment]
Closing as there is nothing here

**Pull request closed without merging**
