### PR TITLE
Jira Software Cloud Integration [WIP]

### PR DESCRIPTION
**Pull request by RicardoE105**

### CODE REVIEW

**Comment by RicardoE105** [comment]
Hey @janober, Implemented almost all issue operations which are I believe what most people would use. Let me know if something

**Comment by janober** [comment]
Great work like always @RicardoE105! Thanks a lot!

I just checked the node and found the following:

Issue: Create
 - the "Parent Issue Key" should maybe be moved in "Additional Fields" as in the most cases it will not be set as I understand it.

Issue: Update
 - Could "Issue Type", "Summary" and "Parent Issue Key" be moved in "Additional Fields"? Or do they always have to be set? If so it is fine but by default should the "update" operation not change anything. It should only update the fields which got added specifically.
 - "Additional Fields" should be renamed to "Update Fields"
Both changes would be important to make sure that all the nodes work in a similar fashion. In this case that is for example how the ActiveCampaign and Pipedrive Nodes work.

Issue: Get & Issue: Transitions
 - Some of the description texts are very long (example: "Properties). They should probably have line breaks (the HTML <br /> ones) in them. Normally try to have lines of max 70-80 characters that the descriptions are readable easier.
 - Are all the fields always needed or could some or most of them moved in something like "Options"? Normally should only the fields which have to be set (like here "Issue Key") be on the main level. All other ones should normally be added manually unless they are very important. That makes it easier for users to know what they have to do and also makes sure that they do not get intimated. They can then simply start with the most basic option and if it does not do what they want they can still check the options.

**Comment by RicardoE105** [comment]
@janober cool pal. Sounds good. Gonna make the changes.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by janober** [comment]
@RicardoE105 Great, thanks a lot!

**Comment by RicardoE105** [comment]
@janober Fixes added, let me know if something pal.

**Comment by janober** [comment]
Great thanks @RicardoE105 ! Sadly is getting late here so I will not be able to fully check now. Will try the next days and then directly release a new version.

Had however a short look. Think there was a misunderstanding about the length of the description texts. I did not mean how long they are in the code. What I meant is how they get displayed to the user. And if they are very long, like they are now, it displays them simply as one line which spans the whole screen. So it is better to add HTML line breaks ("<br />") so that they get displayed as a smaller block with multiple lines as it looks nicer and so easer to read for the users.

**Comment by RicardoE105** [comment]
@janober you mean using <br/>?

**Comment by janober** [comment]
Sorry did not see that it got converted. Yes exactly like here for example:
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Airtable/Airtable.node.ts#L284

**Comment by janober** [comment]
Perfect! Thanks a lot got merged!

**Pull request merged**
