### PR TITLE
Add `collection_item_*` events to Webflow Trigger node

### PR DESCRIPTION
**Pull request by Rirush**
This PR extends Webflow Trigger node, by adding support for CMS related events.

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot for your contribution @Rirush!

Made some minor changes to for example display the "All Collections" only then when it is actually used. Most importantly did I have to however disable this option and the Collection selection filtering as it did simply not work for me. If I did filter for "Category" but then changed a "Product" it did still trigger. Sadly did not have much time to debug, code does also look correct to me but something must be wrong (and did also not find any information in the documentation how the "filter" property works exactly). Btw. you can ignore that it says now `cid` instead of `_cid` in the code. That was me just trying to debug, sadly without luck, and then forgot to change it back after the last try. So if you try again you should change it again to `_cid`

You can find my commit with the changes here:
https://github.com/n8n-io/n8n/commit/77da5b70bc5f71322bdf00d7d4af13592e52fa9b

**Comment by Rirush** [comment]
In this case, it might be possible that there is no way to filter by collection ID on Webflow's side. I wasn't able to find any documentation how the `filter` works as well. Perhaps the way to do it, is somehow check collection ID when webhook is triggered, and discard events that with ID not matching selected one?

**Comment by janober** [comment]
Yes but that is then also something that can be very easily be done with an IF-Node. Would be great to figure out how the "filter" works exactly as it is not only important for collections also for others. Did google some more but sadly no success. We can then leave it for now like this and at some point add the filters correctly or if it is really necessary really do it within the node at a later point. Would be easy to add this feature later, would be much more complicated to remove it again.

**Comment by janober** [comment]
Got released with n8n@0.119.0

**Pull request merged**
