### PR TITLE
Add user node to salesforce

### PR DESCRIPTION
**Pull request by YEriin**
this pr will support query users from sfdc.

### CODE REVIEW

**Comment by RicardoE105** [comment]
@YEriin this is awesome. Thanks very much. Will check and let you know.

**Comment by RicardoE105** [comment]
@YEriin checked this and it works as expected. Will probably be merged soon and add it to the next release. Thanks and nice work.

**Comment by janober** [comment]
Thanks a lot. Got merged with #933

**Comment by janober** [comment]
Got released with n8n@0.81.0

**Pull request closed without merging**
