### PR TITLE
Add Taiga functionality for User Stories and Tasks

### PR DESCRIPTION
**Pull request by cmprmsd**
As some people discussed here (https://community.n8n.io/t/taiga-project-management-partly-created/2138) Taiga provides more features for API interaction.

I added some functionality to create, update and get `tasks` as well as `user stories` in addition to the existing `issues` integration.

As discussed in https://community.n8n.io/t/nested-displayoptions-for-having-multiple-fields-with-the-same-name/5431 I tried nesting the displayOptions, which did not work for me. So I circumvented this problem by copying the operationFields.

I'm not able to come up with the correct implementation and hope you can help me out merging these changes into your project.
The code is working so far. I tested several automations with triggers e.g. changing user story status id's when a task within a story is closed. 

Maybe some do-betters for future updates on this node:
* split the operationFields into multiple files for better readability
* Instead of copying all fields for each type aggregate all overlapping fields that the different types have in common (e.g. `assigned_to` etc.)

I hope this can be merged though and worked on in future updates as it provides already some additional functionality!

Feel free to edit :+1:

### CODE REVIEW

**Comment by cmprmsd** [comment]
I remember, why I did the IP change.. When running N8n in Docker, the webhook trigger will not work as Taiga is never on the same host and `localhost` will be configured in the Taiga webhooks.

If you know how to make this configurable in the credential page, that would be highly appreciated, as N8n could run behind any type of NAT.

**Comment by RicardoE105** [comment]
@cmprmsd thanks very much for your contribution. I reviewed it and noticed that you changed the name of the parameter in the exiting resource "issues." For example, [here]( https://github.com/n8n-io/n8n/pull/1896/files#diff-921ac9b56b1eccd4e84c422cd81830599d280d9c7e92732219fcf77f3f748ff6R338). That would sadly be a breaking change. Is that really need it?

**Comment by cmprmsd** [comment]
Hi Eduardo, 

You are welcome :)

We could change it back to issueID for backward compability. However, the name would be misleading, as the ID now refers to issues, tasks and user stories. 

I guess for future readability that change would bring a benefit.

**Comment by RicardoE105** [comment]
@cmprmsd That would be cool. We will soon release node versioning. It will allow us to improve the node later without breaking for people using the current version.

**Comment by cmprmsd** [comment]
If I understand you correctly you can choose the version of your nodes in the future? 

Should we better wait for this feature then? ☺️ 

It might be possible to have it backwards compatible, but this would require a lot of duplicate code 😷

**Comment by cmprmsd** [comment]
This PR is replaced with the patches from https://github.com/n8n-io/n8n/pull/1970

So I'll close this one. :)

**Comment by janober** [comment]
Got released with n8n@0.130.0

**Pull request closed without merging**
