### PR TITLE
stackby trigger added in n8n

### PR DESCRIPTION
**Pull request by smituparmar**

### CODE REVIEW

**Comment by smituparmar** [comment]
Hey @RicardoE105, can you have look at it. We are very excited to announce a new update with n8n in our community too.

**Review by RicardoE105 — COMMENTED** [review]
Why was this removed?

**Comment by RicardoE105** [comment]
@smituparmar can you please check the comments I added? Thanks.

**Comment by smituparmar** [comment]
I added things which are mandatory for triggers and made changes accordingly 😅

**Comment by RicardoE105** [comment]
@smituparmar ok, when you push the changes I will continue with the review.

**Comment by RicardoE105** [comment]
@smituparmar any update here?

**Comment by smituparmar** [comment]
We will get back to you with new updates

**Comment by janober** [comment]
Any updates @smituparmar ?

**Comment by smituparmar** [comment]
I am so sorry but I am no longer handling this due to some reasons...you can close it and I will talk with my superiors and will handle it accordingly with new merge

**Pull request closed without merging**
