### PR TITLE
✨ Add ClickHouse node

### PR DESCRIPTION
**Pull request by arjunChouksey**
#### This pull request introduces n8n  to ClickHouse (*an open source and column based OLAP*) .

Following points are associated with ClickHouse Node for n8n :

- added credentials requirement for connecting ClickHouseDb Client.
- Support for **Custom Queries**, **Insert**, **Update** operations for ClickHouse Node.
- Here are few screen shorts regarding creating credentails, inserting and executing custom queries for ClickHouse Node.

Screen Shot 2022-01-30 at 1 43 34 AM

Screen Shot 2022-01-30 at 1 44 17 AM

Screen Shot 2022-01-30 at 1 44 27 AM

### CODE REVIEW

**Comment by arjunChouksey** [comment]
@Joffcom  any updates on this pull request ...

**Comment by arjunChouksey** [comment]
Hey @Joffcom, I was curious to know that my pull request is not yet accepted. So can you please guide me on, what did I exactly miss in this pull request.

**Comment by Joffcom** [comment]
Hey @arjunChouksey,

It is a bit of a tricky one, At the moment we are prioritizing requests that improve / fix issues with existing nodes. Once we are at a better number with those we can then start working through the new nodes , I know there are about 50 new node PRs waiting.

Shouldn't be too much longer, The bit that might lead to this taking a bit longer once we start is the use of that extra package. We tend to prefer using HTTP requests where possible as adds less weight and if there is an issue we don't have to wait as long for it to be resolved.

**Comment by vaenow** [comment]
Please check and merge

**Comment by Joffcom** [comment]
Hey @arjunChouksey,

Thanks for the contribution, We have now created a Community Node Repository which is our preferred method for new node submissions.

Once a node has been published to the Community Node Repository users will be able to install the node from their n8n interface and will be able to use your node quicker, You will also be able to update the node as needed without needing to wait for the review process.

In the future we may reach out to you about including your node in our main release, But for now I am going to close this PR.

You can find more information in the links below, If you have any questions about this or need any help let us know.

Building Community Nodes: https://docs.n8n.io/integrations/community-nodes/build-community-nodes/
Submitting Community Nodes: https://docs.n8n.io/integrations/creating-nodes/deploy/submit-community-nodes/
Published Nodes: https://www.npmjs.com/search?q=keywords:n8n-community-node-package

**Pull request closed without merging**
