### PR TITLE
:sparkles: TheHive & Cortex nodes

### PR DESCRIPTION
**Pull request by nadouani**
Hi n8n team, 

This contribution contains the integrations of TheHive Project in the form of three nodes:

- [TheHive](https://github.com/TheHive-Project/TheHive) node 
	- Alert
	    - List alerts
	    - Fetch one alert
	    - Create an alert
	    - Update an alert
	    - Search alerts
	    - Count alerts (API v1 only)
	    - Merge an alert into existing Case
	    - Promote an alert into new Case
	    - Execute a responder
	- Observable
	    - List observables
	    - Fetch one observable
	    - Create an observable
	    - Update an observable
	    - Search observables
	    - Count observables (API v1 only)
	    - Execute an analyzer
	    - Execute a responder
	- Case
	    - List cases
	    - Fetch one case
	    - Create a case
	    - Update a case
	    - Search cases
	    - Count cases (API v1 only)
	    - Execute a responder
	- Task
	    - List task (specified Case)
	    - Fetch one task
	    - Create a task
	    - Update a task
	    - Search tasks
	    - Count tasks (API v1 only)
	    - Execute a responder
	- Log
	    - List logs
	    - Fetch one log
	    - Create a log
	    - Execute a responder
- [Cortex](https://github.com/TheHive-Project/Cortex) node
	- Analyzer
	    - Execute
	- Responder
	    - Execute 
	- Job
	    - Get Job
	    - Get Report
- TheHive-Trigger node

The nodes development was initiated in this forum [post](https://community.n8n.io/t/thehive-project-integration/1508/) and we tried to deliver a good quality nodes, So if there are any changes to make, feel free to contact us with your suggestions

Best regards!

### CODE REVIEW

**Comment by RicardoE105** [comment]
@nadouani that is what I called a CONTRIBUTION. thanks very much will check when I have time and let you know.

**Comment by nadouani** [comment]
Kudos to @MedAliMarz 😊

**Comment by RicardoE105** [comment]
Hey, @nadouani  @MedAliMarz I’m about to review the nodes. I wonder if you can give me access to a sandbox instance for TheHive and Cortex? That would speed up the review process. Thanks.

**Comment by nadouani** [comment]
@RicardoE105 We will make sure to provide that. We don't have it ready but we can build a server with all the tools.

**Comment by RicardoE105** [comment]
That would be awesome @nadouani. When you have that ready shoot me an email to ricardo@n8n.io. Thanks very much.

**Comment by RicardoE105** [comment]
Hey, guys @nadouani @MedAliMarz

I reviewed the nodes, firstly nice work everything seems to be working fine 👍 . However, I made some changes mostly related to formatting and keeping consistency with the other nodes.

The Cortex node is almost done, the only resource I have not been able to test is 'responder' cuz there is no responder created on the instance you provided. Can you please create a responder for me or tell me how to create one? Also If you can review the changes I made to the node and provide feedback would be perfect.

About The Hive node, I changed the Alert resource to keep consistency with the other nodes. I wonder if you can pick it from here #952 and adjust the other resources?

After that, I can review it again and then merge it.

Please feel free to ask me any questions you might have and again thanks very much for the contribution.

**Comment by MedAliMarz** [comment]
Hey @RicardoE105,
Thank you for reviewing the code. 
This week, I will work on changing the code of 'TheHive' node to meet n8n coding standards and I will try to finish it as soon as possible, so you can continue with the nodes review
Have a nice day;)

**Comment by MedAliMarz** [comment]
Hey @RicardoE105,
As I mentioned, I added the commit in this PR for consistency, any feedback or future changes are welcomed ;)
Have a nice day!

**Comment by RicardoE105** [comment]
@MedAliMarz thanks very much. I Will review it as soon as I can.

**Comment by RicardoE105** [comment]
@MedAliMarz ok made some improvements, mostly related to formating. I wonder if your IDE linter shows you the warnings? 

Also could not test the following resources/operations:

- Observable update gives me an error, checked the request it seems to be sending the data correctly.

- All execute responders. I do not know how to create a responder so that they load on the UI and then execute it.

Also, there are some resources that have getAll and search. Is it possible to somehow merge both of them under the name getAll? or is there a restriction?

Please make sure you make the changes on top of these improvements. Thanks in advance. Let me know if you have any questions.

**Comment by MedAliMarz** [comment]
@RicardoE105 Thank you for your efforts,
Concerning the 'observable' update operation, I tested it using the different API versions and it works fine (as shown in screenshots). If you can provide me with more details I will try to reproduce the error and troubleshoot it 

update_v0 update_v1

About the responder config it is quite straightforward (no need for a full config as the goal in only reaching the endpoint) the steps:
-  connect using org-admin account 
-  choose organization page  
-  select responder tab
-  enable a responder (example mailer_1_0)
responder_config

The responders list change based on the selected resources (for example mailer_1_0 works for alert and case), currently there is a few responders but their output helps a lot in case enrichment

 
execute_responder


Concerning the search operation, some resources requires a separate getAll operation (for example, CISRT deals with huge number of observable each day, grouping them by a case facilitate the job and the same concept can be applied for a workflow using n8n,  having the option to select observable for a specified case make the workflow clear and fast)

Also, I am sorry about the poor formatting, it's my fault I forget to do it before committing the code, and I would be glad if you can point me to the right linter config.

Feel free to ping me or @nadouani for any feedback/proposition,
Have a great week ahead!

**Comment by nadouani** [comment]
Hello @RicardoE105, just wanted to explain the difference between getAll and search:
- `getAll` allows fetching the observables (and most certainly tasks) of a given `Case`(incident)
- `search` aims to find observables (tasks) in the entire database.

Concerning the Responders, on the demo platform, there is a responder that works for case objects. If you need more responders to test all the node options, then I'll enable a fake responder for that.

**Comment by RicardoE105** [comment]
Thanks, both @nadouani @MedAliMarz for the clarification. This is helpful. We Will continue reviewing this week, we are close.

**Comment by nadouani** [comment]
Hello @RicardoE105 any update on this one? I just wanted to up it :)

**Comment by RicardoE105** [comment]
@nadouani was reviewing right now. I tried to add a responder, but I cannot see the organization menu option, probably cuz I do not have admin permissions on the instance you created for me. Can you make an admin so that I can add enable the responders? The only thing missing to test is the responders. As soon as that is sorted out, I can move forward. Sorry for the late response.

**Comment by nadouani** [comment]
Hey @RicardoE105 Mea Culpa, I was testing on a different platform from the one I shared with you. Let me update the one you are using to add some responders

**Comment by RicardoE105** [comment]
No problem at all. Let me when I can test and I will make it my priority. Thanks.

**Comment by nadouani** [comment]
@RicardoE105 you should be able to see some test responders on all the objects (cases, alerts, tasks, observables and task logs)

**Comment by RicardoE105** [comment]
Ahh that was fast. Thanks.

**Comment by RicardoE105** [comment]
@nadouani ok another thing. I cannot add a webhook URL via the UI (to test the trigger). Can you add mine? I'm gonna send it via email. Thanks.

**Comment by nadouani** [comment]
@RicardoE105 I updated the service to call the provided webhook URL on all TheHive events

**Comment by RicardoE105** [comment]
@nadouani Thanks very much.

Also, checked the Cortex node and realized that when executing a responder in the parameter Entity Object a JSON has to be provided, which is ok but it must be optional to send the data as JSON. Check the image below. As you can see, if you want to send the data as JSON the parameter JSON Parameters has to be set to true else; the customer can provide each property independently. I would add it myself to speed up the process, but I could not find the docs for the endpoint `POST /responder/${responderId}/run`. Sorry I did not mention it before but had not tested the execute responder operation until today.

Hope that makes sense. Aside from that so far everything is working as expected.

<a href="https://www.loom.com/share/c7d840a872204e37afafc61da975d793"> <p>26 October, 2020 - Loom Recording - Watch Video</p>  </a>

**Comment by MedAliMarz** [comment]
Hi @RicardoE105, I changed the responder operation parameters as you mentioned, but i couldn't commit the code to #952.
If there is any other changes or suggestions just ping me, Have a nice day ;)

**Comment by RicardoE105** [comment]
Ahh thanks very much. Will try to review tomorrow. I will let you know.

**Comment by nadouani** [comment]
Hello @RicardoE105, any news about this PR, would you like us to fix something else?

**Comment by RicardoE105** [comment]
Hey @nadouani, reviewing today the last changes. Will keep you posted. Sorry for the waiting.

**Comment by RicardoE105** [comment]
@nadouani @MedAliMarz ok, it's working as expected gonna pass it to my coworking for internal review, and then it will be merged. Thanks.

**Comment by MedAliMarz** [comment]
@RicardoE105  Awesome, Thank your for your efforts ;)

**Comment by RicardoE105** [comment]
@nadouani @MedAliMarz  Hey guys, my coworker review the node, and the thing he keeps asking is what every field does. is there a place where I can see a small description of each field? This can be added as a description of each field.  Thanks.

**Comment by MedAliMarz** [comment]
Hey @RicardoE105 , the fields' descriptions can be easily found in [Cortex docs](https://github.com/TheHive-Project/CortexDocs/blob/master/api/api-guide.md) or in [TheHive docs](https://github.com/TheHive-Project/TheHiveDocs/tree/master/api). Thank you.

**Comment by nadouani** [comment]
Hello @RicardoE105 what do you mean by "what every field does"? which fields? The ones describing the data model?

**Comment by RicardoE105** [comment]
Yes, The ones describing the data model. What @MedAliMarz sent me I think will work. Thanks.

**Comment by RicardoE105** [comment]
@nadouani @MedAliMarz quick update. Added the descriptions and pass it to my coworker again. If everything is ok with him this will be probably merged this week. Thanks for the patience.

**Comment by MedAliMarz** [comment]
@RicardoE105 That's great, thank you

**Comment by RicardoE105** [comment]
@nadouani @nadouani guys, quick question. When creating a case with `Impact Status` the API responds with `ImpactStatus: null`. Is that expected? I did a quick check and it seems the data sends correctly. Am I missing something? The same happens with`Resolution Status`. 

image

**Comment by nadouani** [comment]
Hello @RicardoE105 it sounds expected to me since the status is still set to "Open".

"Impact" and "resolution status" are only taken into account when setting the status to "Resolved"

**Comment by RicardoE105** [comment]
Got it, then those fields should not be in the create operation. When creating a case, it seems like the status cannot be set. By default will always be open; thus, `Impact Status` and `Resolution Status` will never be used there. Can you confirm?

**Comment by nadouani** [comment]
I would allow creating cases with closed status, if it doesn't work, it means it's a bug in TheHive side, note the node's end.

Is this something that prevent from accepting the node?

**Comment by RicardoE105** [comment]
ahh yes, my coworker is brand new to The Hive Project and he keeps asking me these questions that I do not know how to answer. I guess we can expect the same questions for people using the node. They might think something like is a bug with the node as we are misleading them with what we are showing is possible in the UI. Either way, I'm gonna change it myself if that is ok with you.

**Comment by nadouani** [comment]
Ok got it. Yes please go ahead :)

**Comment by RicardoE105** [comment]
@nadouani @MedAliMarz  quick question, how do I make the `alert:getAll` return all records by default? just like the `case:getAll` works. I printed both requests and both seem to be the same but one returns all records and the other none.

Alert:getAll
```
{
headers: { Authorization: 'Bearer {{token}}' },
method: 'POST',
 qs: { range: '0-100' },
uri: 'https://n8n.lab.strangebee.com/api/alert/_search',
body: { query: { _and: [] } },
json: true
}
```

Case:getAll
```
{
headers: { Authorization: 'Bearer {{token}}' },
method: 'POST',
qs: { range: '0-100' },
uri: 'https://n8n.lab.strangebee.com/api/case/_search',
body: { query: { _and: [] } },
 json: true
}
```

**Comment by nadouani** [comment]
It looks like the demo platform is suffering from some bug in 4.0.0 release of TheHive. We are going to upgrade it so you can test that again. Is this a good plan?

**Comment by nadouani** [comment]
The API call is correct, the issue is in TheHive 4.0.0 side.

**Comment by RicardoE105** [comment]
@nadouani sounds good. Thanks.

**Comment by nadouani** [comment]
Hi @RicardoE105 I've updated the demo server to 4.0.2 version. Could you please give it a try? Thanks

**Comment by janober** [comment]
Thanks a lot. Got merged with #952

**Comment by nadouani** [comment]
Good news! Thank you guys

**Comment by MedAliMarz** [comment]
Awesome, thank you a lot @RicardoE105.

**Comment by janober** [comment]
Thanks all of you!

Just got released with n8n@0.96.0

**Pull request closed without merging**
