### PR TITLE
fix(editor): Prevent text edit dialog from re-opening in same tick

### PR DESCRIPTION
**Pull request by alexgrozav**
Github issue / Community forum post (link here to close automatically):

### CODE REVIEW

**Review by MiloradFilipovic — CHANGES_REQUESTED** [review]
I am now unable to open the modal by clicking in the parameter input right after I close it. Have to click outside of input and then click back in to open in (button seems to work well after closing).

https://github.com/n8n-io/n8n/assets/2598782/0e03b062-3907-4fef-a5b4-4842a3e9f333

**Comment by alexgrozav** [comment]
> I am now unable to open the modal by clicking in the parameter input right after I close it. Have to click outside of input and then click back in to open in (button seems to work well after closing).
> 
>  Screen.Recording.2023-07-28.at.14.14.27.mov

Good point. Fixed by blurring the input after closing the modal.

**Review by MiloradFilipovic — APPROVED** [review]
Thanks for fixing. Looks good

**Comment by janober** [comment]
Got released with [`n8n@1.2.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.2.1)

**Pull request merged**
