### PR TITLE
Add ability to edit Sort property of Wekan Card

### PR DESCRIPTION
**Pull request by ChrisMagnuson**

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot for the PR. I did just check it out but I am honestly a little bit confused. What kind of value is expected there? The type is set to number but the default value is an empty string. Should that be a 0? The documentation is sadly also not very helpful as it does not give any example. Additionally is it according to the documentation not a number, rather a string.

**Comment by ChrisMagnuson** [comment]
@janober Thank you so much for looking at this.

The [Card schema](https://wekan.github.io/api/v5.58/#tocs_cards) in the latest Wekan API documentation shows that Sort is of type number but the [edit_card method](https://wekan.github.io/api/v5.58/#edit_card) indicates the sort parameter is of type string.

The Card schema is correct and the edit_card method documentation is incorrect and Sort/sort should be a number.

As for the default I think it would be best not to specify one if possible.

The meaning of the value of sort is completely relative and to the other values of sort already specified on other cards in the same list-swimlane. 

If for instance you wanted to default to the card being at the top of the list the value for sort would always have to be less than whatever the smallest already used value of all other cards in that list-swimlane which could be a negative number so something like 0 doesn't really have a consistent meaning as a default.

Is it acceptable to have no default specified or should I go ahead and set it to 0 without any obvious better choice?

**Comment by ChrisMagnuson** [comment]
It looks like sort is of type number and has default value of 0 in the [code for wekan](https://github.com/wekan/wekan/blob/master/models/cards.js#L271) so I will mirror that and update this pull request.

**Comment by janober** [comment]
Thanks a lot. Got merged.

Sounds like a complicated sort system that is hard to keep track of. Did now set the default value to 0 as an empty string is not a number and is so an invalid value. By default, nothing does get sent, only if the user adds that property.

Will be released with the next version.

**Comment by ChrisMagnuson** [comment]
@janober Sorry I didn't get an updated pull request sent over, thank you for making the correction yourself and merging this in, much appreciated!

**Pull request merged**
