### PR TITLE
feat(Telegram Node): Add support for sending messages to forum topics

### PR DESCRIPTION
**Pull request by chrtkv**
Hey there,

This pull request adds possibility to send messages directly to topics within groups (https://telegram.org/blog/topics-in-groups-collectible-usernames#topics-in-groups). 

Could you please review it? Let me know if you have any questions or concerns

### CODE REVIEW

**Comment by IgorKha** [comment]
Please approve this features

**Comment by pwqw** [comment]
According to the [sendMessage API doc](https://core.telegram.org/method/messages.sendMessage) the field must be `top_msg_id`.

Otherwise it is usable to place this option as an additional field.

**Comment by pwqw** [comment]
The PR https://github.com/n8n-io/n8n/pull/6639 differs from this, in that:
- The Topic ID field is an **Additional Field**.
- It also includes `sendChatAction` within the list of operations.
- And suggests clearer descriptions.

**Comment by Joffcom** [comment]
Hey @chrtkv,

Thanks for the PR, I am just reviewing this now so we can get it merged in.

**Review by Joffcom — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.0.3`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.0.3)

**Pull request merged**
