### PR TITLE
🚀  OneSimpleAPI - New Features | Social Profiles (Instragram & Spotify Artists)

### PR DESCRIPTION
**Pull request by Joffcom**
Added new Resource: Social Profile.

Added new Operation Instagram - Returns information about an instragram Profile like Name, Picture, Bio text, Follower and Following Count and last 5 posts.

Added new Operation Spotify - Returns information about a Spotify Artists profile like Name, picture, bio, fan count, top songs.

I went with "Social Profile" over information or website as the Resource as there could be more social options added in the future so this may make life easier / reduce possible breaking changes in the future.

Also fixed a couple of typos.

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot. Looks like you use for some reason spaces instead of tabs and for that reason did literally every line change. Can you please change it to our default "tabs". It will then be much easier to see what changed exactly.Thanks!

**Comment by Joffcom** [comment]
Will do, It looks like I have my desktop and Mac set up to use different options.

**Comment by janober** [comment]
Great, thanks a lot!

**Comment by janober** [comment]
Great, thanks a lot. Looks now much better and is directly clear what changed. Will review and merge soon.

**Comment by Joffcom** [comment]
I have made a config change on the Mac I currently have so anything I do in the next few weeks won't have the same issue.

**Comment by janober** [comment]
I did just start to review the changes and tested the new functionality but it does sadly not work for me. If I request Instagram data (tested with "oliviarodrigo", their example in the docs or "instagram") I always get `405 ERROR: Method not allowed - please check you are using the right HTTP method`.

Does it work for you?

**Comment by Joffcom** [comment]
Hey @janober,

Just gave it a test here and it looks like it is failing from CURL as well, Looks to be an issue on the One Simple API side. I have reported it to the chap that runs it so he can look on the back-end.

**Comment by janober** [comment]
Just tested again. Seems to be working now. Got merged.

**Comment by janober** [comment]
Got released with `n8n@0.153.0`

**Pull request merged**
