### PR TITLE
:sparkles: Microsoft Outlook node

### PR DESCRIPTION
**Pull request by mluhta**
This node implements parts of Microsoft Graph API's Mail functionality, mainly focusing on sending/receiving emails. It has the following operations:

### Message
- [x] Create
- [x] Create Reply
- [x] Delete
- [x] Get
- [x] Get MIME content
- [x] List
- [x] Send
- [x] Send Draft
- [x] Update
- [x] Add Attachment
- [x] Download Attachment
- [x] Get Attachment
- [x] List Attachments

### Folder
- [x] Create
- [x] Delete
- [x] Get
- [x] List
- [x] List Children
- [x] List Messages
- [x] Update

API docs:
* https://docs.microsoft.com/en-us/graph/api/resources/message?view=graph-rest-1.0

Feature request:
* https://community.n8n.io/t/o365-outlook-integration/3326

### CODE REVIEW

**Comment by RicardoE105** [comment]
@mluhta Really amazing contribution. I just reviewed it, and everything seems to be working as expected. However, I made some changes so that it works similarly to other nodes. Let me know if you have any questions about the changes. Thanks very much. Looking forward to what you are going to build next with n8n.

**Comment by mluhta** [comment]
@RicardoE105 Hey, thanks for reviewing the PR quickly. I have a couple of questions:

* Folder's update operation was removed during the refactoring, is there a reason for that or was it simply missed?
* Is the Folder Message resource needed? As it only has one operation I think the best place for the get folder messages operation would be under the Folder -resource.

Moving the attachment operations to their own resource was a good idea, I was thinking of doing it myself too but wanted to keep the menu structure as close to the REST API as possible. It's better that way though as the Message's operations aren't too crowded now. 👍

**Comment by RicardoE105** [comment]
> Folder's update operation was removed during the refactoring, is there a reason for that or was it simply missed?

Just checked the original PR [here](https://github.com/n8n-io/n8n/blob/40bdf7fa5422c788324ec6709e6c8fada0ce2252/packages/nodes-base/nodes/Microsoft/Outlook/MailFolderDescription.ts) and there is no folder:update operation. Am I missing something?

> Is the Folder Message resource needed? As it only has one operation I think the best place for the get folder messages operation would be under the Folder -resource. 

Right now has just one operation but it can grow to has other operations down the road.

**Comment by mluhta** [comment]
> > Folder's update operation was removed during the refactoring, is there a reason for that or was it simply missed?
> 
> Just checked the original PR [here](https://github.com/n8n-io/n8n/blob/40bdf7fa5422c788324ec6709e6c8fada0ce2252/packages/nodes-base/nodes/Microsoft/Outlook/MailFolderDescription.ts) and there is no folder:update operation. Am I missing something?
> 
Ahh, my bad. It seems that I forgot to add the operation to the list, but it has been otherwise implemented. Not tested though because it was missing from the operation list 😄 One issue I had with the update operation though was that because I can't know if the user is editing a normal folder or a search folder, the menu currently shows fields for both.

> > Is the Folder Message resource needed? As it only has one operation I think the best place for the get folder messages operation would be under the Folder -resource.
> 
> Right now has just one operation but it can grow to has other operations down the road.

Are there any other operations in the API related to that though? I don't recall there is anything else that would fit under that resource. Like I said I just want to keep the structure as close to the API specifications as possible, but yeah it's your call.

**Comment by janober** [comment]
Thanks a lot. Got merged with #1272

**Comment by janober** [comment]
Got released with n8n@0.100.0

**Pull request closed without merging**
