### PR TITLE
Launch Darkly node added

### PR DESCRIPTION
**Pull request by nikozzilla**
**Launch Darkly node**

- Supports access token for authentication.

Apis:
- User Setting
    - updateFlagSettingsForUser
- Segments
    - patchSegment

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @nikozila,

Thanks for the contribution, We recently released our Community Node Repository which is our preferred method for new node submissions.

It also allows users to gain access to your node and any updates without needing to update n8n itself.

You can find more information on building community nodes here: https://docs.n8n.io/integrations/community-nodes/build-community-nodes/

Let me know if you have any questions on this one.

**Comment by nikozila** [comment]
Hey @Joffcom, thanks.
I will take a look.

**Comment by nikozila** [comment]
Dear @Joffcom 
I published this node to npm
https://www.npmjs.com/package/n8n-nodes-launch-darkly
What next?

**Comment by Joffcom** [comment]
Hey @nikozila,

That is it really, So now users will be able to add your node from the n8n interface. From here we may at some point reach out to you about including the node in our main release but for now I think we can mark this one as closed.

Let me know if you have any other questions on this one.

**Comment by nikozila** [comment]
Thank you very much @Joffcom. let's close this.

**Pull request closed without merging**
