### PR TITLE
Adding HumHub node

### PR DESCRIPTION
**Pull request by valentina98**
A new node for HumHub.
[https://www.humhub.com/en](url)

### CODE REVIEW

**Comment by samuk** [comment]
Hi is anyone able to review this one, please?

@valentina98 could you merge this pull to update the readme too please? https://github.com/digital-boss/n8n-nodes-humhub/pulls

**Review by samuk — COMMENTED** [review]
Looks good to me

**Comment by samuk** [comment]
@ivov would you be able to review this one, please?

**Comment by ivov** [comment]
> @ivov would you be able to review this one, please?

Up to @csuermann and @sirdavidoff

**Comment by samuk** [comment]
Great, thanks

Hopefully @csuermann or @sirdavidoff can review this one soon.

**Comment by samuk** [comment]
@csuermann or @sirdavidoff  could you review this module please?

**Comment by ivov** [comment]
@samuk The module is available as a community node

https://www.npmjs.com/package/@digital-boss/n8n-nodes-humhub

https://docs.n8n.io/integrations/community-nodes/installation/

**Comment by Joffcom** [comment]
Hey @valentina98,

Thanks for the contribution, It looks like you have already published this node to the Community Node Repository which is our preferred method for new node submissions.

In the future we may reach out to you about including your node in our main release, But for now I am going to close this PR. If you have any questions about this or need any help let us know.

**Pull request closed without merging**
