### PR TITLE
MongoDB node

### PR DESCRIPTION
**Pull request by lucafaggianelli**
MongoDB node with the ability to find, insert and update documents into MongoDB

### CODE REVIEW

**Comment by janober** [comment]
Thanks! Looks good! As it is a draft I guess you are still working on it and you tell me once it is ready to be checked and released?

**Comment by lucafaggianelli** [comment]
I've used it a little more and it's still working... For now this is the best test I can do 😂

**Comment by janober** [comment]
Great, thanks a lot! I will check it out later and merge if I do not come across any problems.

**Comment by janober** [comment]
Merged and released with 0.30.0

Made a few changes like:
 - Did set default MongoDB port in credentials
 - Indentation fixes
 - Missing semicolons
 - Fixed partly "update" but does still not work for me

"Insert" and "find" worked perfectly but had problems with "update". One problem was that it did not include the "filter-field" automatically if it was not set also in "fields". So I added that. Got then the error "the update operation document must contain atomic operators." which could be fixed by adding "$set" to updateOne() but even then it did not update the document for me.
Can you please have a look at that again. Not sure if I used it wrong or if there is still something broken. (I used Mongo 4.2)

**Comment by lucafaggianelli** [comment]
Jan, sorry for responding so late.

A note about credentials, mongodb connection string supports 2 schemes `mongodb:` and `mongodb+srv:` (for DNS seedlist, see here https://docs.mongodb.com/manual/reference/connection-string/#dns-seedlist-connection-format). The latter doesn't accept a port parameter, so in n8n I create the connection string using 1 scheme or the other based on the presence or not of the port in the credentials, maybe this is ambiguous and should be highlighted somewhere.

About update, I'll take a look at it, I fear it's missing the `$set` operator, which should be added manually as node param.

**Pull request merged**
