### PR TITLE
AWS DynamoDB Error improvements, Optional GetAll Scan FilterExpression - N8N-3701

### LINKED ISSUE #2650: AWS DynamoDB Scan operation requires FilterExpression
**Describe the bug**
In the DynamoDB Node the Scan operation (Get All Items -> Scan) requires FilterExpression, which in fact is optional.

https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html#Scan.FilterExpression

See also: https://community.n8n.io/t/aws-dynamodb-get-all-items/10375/4

**Expected behavior**
Field should be optional.

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu Linux 18.04]
 - n8n Version [e.g. 0.119.0]
 - Node.js Version [e.g. 14.16.0]
 - Database system [e.g. SQLite; n8n uses SQLite as default otherwise changed]
 - Operation mode [e.g. own; operation modes are `own`, `main` and `queue`. Default is `own`]

**Additional context**

### PR DESCRIPTION
**Pull request by ctrl-freak**
Fixes n8n-io/n8n#2650, resubmission of #3305 from branch instead of master

- Returns AWS JSON error messages not in the response body.
- FilterExpression optional in UI (https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html#Scan.FilterExpression).
- ExpressionAttributeValues only added to request body when not empty (Get All acted differently to other actions).

### CODE REVIEW

**Comment by michael-radency** [comment]
Hello @ctrl-freak thank you for your contribution, I did commit some fixes

**Comment by ctrl-freak** [comment]
https://github.com/n8n-io/n8n/pull/3318/commits/f1a747f7e08c34cb5e64dd3205e8f68c2470762d reintroduces a duplication of code, but it's better that it's in the `if scan` statement, so I've removed the latter lines.

**Comment by RicardoE105** [comment]
@ctrl-freak @michael-radency  had a look at the PR. 

Why did we remove the FilterExpression parameter when querying (not scanning). What am I missing? This looks to me like a breaking change. That parameter can be sent when querying as well. 

image

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html#DDB-Query-request-FilterExpression

**Comment by michael-radency** [comment]
> The FilterExpression parameter is still in the request; before [d0f0e8d](https://github.com/n8n-io/n8n/commit/d0f0e8dbad2a59c3d4c3d16074b1d304df95029a) the FilterExpression value was retrieved via `getNodeParameter` twice on :312 and :324

Hi @ctrl-freak , that are different filterExpressions one is for field when scan is true, other one for option in Options when scan is false, I did restore code related to that

**Comment by ctrl-freak** [comment]
> Hi @ctrl-freak , that are different filterExpressions one is for field when scan is true, other one for option in Options when scan is false, I did restore code related to that

I see what you mean now; sorry, that's my inexperience with how n8n works. Will keep it in mind for the future.

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Pull request merged**
