### PR TITLE
Use env variable MONGO_NON_ROOT_USERNAME

### PR DESCRIPTION
**Pull request by wernersmit**
MONGO_NON_ROOT_USERNAME specified in .env, but hardcoded n8nuser value used.

### CODE REVIEW

**Comment by janober** [comment]
@wernersmit Thanks a lot for fixing that! Is merged!

Be however aware that I advise people to use Postgres instead. There are issues with MongoDB regarding dots in node-names and when bigger amounts of data have to get saved (like for past workflow executions). That is why I think about maybe dropping Mongo support in the future.

**Comment by wernersmit** [comment]
All good @janober - it's a pleasure. Noted, thanks. Will try out with Postgres instead. Thanks for the heads-up.

**Comment by janober** [comment]
Sure, I just want to avoid any problems for people if they are avoidable. I started with Mongo and switched then very fast to Postgres for the above reasons. And never had a problem since.

**Comment by janober** [comment]
Is part of n8n@0.25.0

**Pull request merged**
