### PR TITLE
fix(Redis Node): Fix adding sets data types

### LINKED ISSUE #6339: Redis Node :  Set operation for sets-type doesn't work
**Describe the bug**
When I try to set a value for the 'sets' type in my node, it simply doesn't work.

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to a test workflow, 
2. Click on "add node", type "Redis" and  click "Set the value of a key in Redis"
3. Choose accordingly, operation = set, key type sets. 
4. Fill key and value areas. 
5. After an execution nothing happens 

Screenshot 2023-05-30 at 9 33 31 PM

**Expected behaviour**
I'd like to see the changes on Redis's side. 

**Environment **

- OS:  Ubuntu Server 22.04 x64
- n8n Version: 0.228.2
- Node.js Version: 16.19.1
- Database system: MySQL
- Operation mode: own
- Redis version: 6.0.16

**Additional context**
I've installed n8n using docker. Error repeats itself, whether the key exists or not under the Redis environment.

### PR DESCRIPTION
**Pull request by mbakgun**
Fixes #6339

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @mbakgun,

Thanks for the PR, I have added this to my list to check today so we can hopefully get it included in the next release.

**Comment by Joffcom** [comment]
@mbakgun fell behind a bit today but I will be checking this first thing tomorrow morning.

**Comment by Joffcom** [comment]
Hey @mbakgun,

I have just tried to give this a test and it is failing to build, It may be better to try and update `setValue` which is what we typically call. For this though `clientSet()` is getting 2 arguments but it expects 0 so that will need to be reworked.

**Comment by mbakgun** [comment]
Thank you for the suggestion, @Joffcom. I've now understood it, and the directives have helped me a lot 🙏. However, some parts still remain uncertain for me. 

I've changed the **setValue** function as you mentioned and added a new else-if like below,

```typescript
..
 else if (type === 'sets') {
	const clientSadd = util.promisify(client.sadd).bind(client);
	for (let index = 0; index < (value as string[]).length; index++) {
		await clientSadd(keyName, index, (value as IDataObject)[index]!.toString());
		}
	}
``` 

Even though redis/index.d.ts has the following declarations, I'm still getting an error while trying to build the project ; 
error TS2554: Expected 0 arguments, but got 3.

```typescript
   /**
   * Append one or multiple members to a set.
   */
   sadd: OverloadedKeyCommand<string, number, R>;
   SADD: OverloadedKeyCommand<string, number, R>;
``` 

Any help would be appreciated. Thank you once more 👑

**Comment by mbakgun** [comment]
Thank you for the suggestion, @Joffcom. I've now understood it, and the directives have helped me a lot 🙏

**Comment by mbakgun** [comment]
Hi @Joffcom , can you please review the fix ?  🙏

**Comment by Joffcom** [comment]
@mbakgun this seems to work ok for me using the example on the Redis website. Thanks.

**Review by Joffcom — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.12.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.12.2)

**Pull request merged**
