### PR TITLE
add Beeminder node

### PR DESCRIPTION
**Pull request by mutdmour**
- add support for Beeminder to send datapoints (https://community.n8n.io/t/beeminder-integration/143)
- allows users to send datapoints to specific goals as well update, delete and read datapoints for a specific goal
- Beeminder api https://api.beeminder.com/#postdata
- creating this as draft to collect feedback from n8n maintainers and Beeminder community (https://forum.beeminder.com/t/n8n-integration/7659)
- working on documentation meanwhile

Screen Shot 2021-01-08 at 6 53 31 PM

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot @mutdmour ! Just got merged with #1325

**Comment by mutdmour** [comment]
@janober thanks for merging. just want to note there's a typo that was lost between different branches 
https://github.com/n8n-io/n8n/search?q=beeminderpiRequestAllItems

**Comment by mutdmour** [comment]
here you go https://github.com/n8n-io/n8n/pull/1337

**Comment by janober** [comment]
Got released with n8n@0.102.0

**Pull request closed without merging**
