### PR TITLE
Add Trello Label, Checklist and CheckItem api

### PR DESCRIPTION
**Pull request by trojanh**
Adds Following Trello API
 - Checklist Create, Get, GetAll, Delete
 - CheckItem Get, Update, delete and Get all completed `checkItems`
 - Label API for CRUD and add/remove label from card

### CODE REVIEW

**Comment by trojanh** [comment]
@janober how about refactoring the code like below
```
const BOARD = {
  OPTIONS: {...},
  GET: {
     ID: {...},
     ADDITIONAL_FIELDS: {...}
  },
  DELETE: {
    ID: {...}
  },
...
}
```
and then destructing it in the `properties` array, like 

```
...
properties: [
   ...,
   BOARD.OPTIONS,
   BOARD.GET.ID,
   BOARD.GET.ADDITIONAL_FIELDS,
   ...,
   BOARD.DELETE.ID,
   ...
]
```

This will help us organize the code related to particular operations in a single object and could be easily be updated and used as an object.

I wanted to suggest this for this file as its become too large and might only grow more. If we need to add some more fields if API gets updated then it will be really complex to find and make such change. I understand that API don't update that frequently but even from a readability point of view this will help.

Let me know your thoughts.

**Comment by janober** [comment]
Great, thanks a lot. Got merged.

Refactoring the code as you described sounds good to me. The file is with almost 3000 lines really way too long. Alternatively you can also check how the latest nodes got split apart like for example the Segment-Node.

**Comment by trojanh** [comment]
yeah, I observed`ActiveCampaign` node yesterday while working on Disqus changes and its a lot neater and organized, I will raise a PR for the refactored code. Thanks @janober .

**Comment by janober** [comment]
Yes, totally agree. 

Great thanks a lot!

Please make sure to pull first that it also includes the few changes I made.

**Comment by trojanh** [comment]
yeah @janober , I will be raising a new PR against `master` so no worries 👍

**Comment by janober** [comment]
Got released with n8n@0.50.0

**Pull request merged**
