### PR TITLE
fix(workflowExecute): support pin data for nodes with multiple outputs

### PR DESCRIPTION
**Pull request by ultrabug**
The execution logic lacks a way to support pinning data for nodes with multiple outputs and forces pinned result data to have one element only. This commit fixes that so that n8n at least honors the pinned data length. Work will have to be conducted further to allow it from the UI as well.

### CODE REVIEW

**Comment by janober** [comment]
Would that not break all existing pinned data?

**Comment by ultrabug** [comment]
@janober our testing demonstrates that this logic preserves the pinned data for all types of nodes.

Any reason why you fear this when looking at the diff? I must admit that TS is not my primary language...

**Comment by janober** [comment]
Just because of the way the code looks like, does it seem like it would cause problems because the expected type changed. Anyway, let's see.

**Comment by netroy** [comment]
@ultrabug Can you please re-open a new PR against the `master` branch instead?
in generally when contributing to aproject, please avoid creating PRs against branches internal to the project, and also avoid using branch names that already exist.
I tried rebasing this PR, but because of the branch name (and my limited git skills), I'm unable to update this PR.

**Comment by ultrabug** [comment]
done https://github.com/n8n-io/n8n/pull/6556

**Pull request closed without merging**
