### PR TITLE
Refactor Pipedrive deal filters expansion

### PR DESCRIPTION
**Pull request by ivov**
This PR refactors the Pipedrive deal filters contributed at #2069.

### CODE REVIEW

**Comment by rodrigoscdc** [comment]
@ivov could you implement `loadOptionsMethod: 'getFilterIds'` on Activity: getAll
```
{
        displayName: 'Filter ID ',
        name: 'filterId',
        type: 'options',
        typeOptions:{
	        loadOptionsMethod: 'getFilterIds',
        },
        default: '',
        description: 'The ID of the Filter to use (will narrow down results if used together with user_id parameter)',
},
```

**Comment by RicardoE105** [comment]
@rodrigoscdc just added it.

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.134.0

**Pull request merged**
