### PR TITLE
Add Taiga integration

### PR DESCRIPTION
**Pull request by renanfilipe**
- Creates a Taiga node for managing issues.
- Creates a TaigaTrigger node to handle its events via webhook.

### CODE REVIEW

**Comment by RicardoE105** [comment]
@renanfilipe just reviewed the node and made some changes. As I do not have much experience with Taiga can you please check it out and provide feedback? Tomorrow will check the trigger. The changes can be found here #939. Also, I added support for Taiga self-hosted but did not test it as I do not have access to a self-hosted instance. If you have one please test the self-hosted credential. Thanks very much. Let me know if you have any questions.

**Comment by RicardoE105** [comment]
@renanfilipe reviewed and added some changes to the trigger now. If you can provide feedback would be cool. Again, Thanks.

**Comment by MatheusRV** [comment]
LGFM. Could some one merge this? I need it inside N8N ASAP.

**Comment by janober** [comment]
Thanks a lot. Got merged with #939

**Comment by janober** [comment]
Got released with n8n@0.83.0

**Pull request closed without merging**
