### PR TITLE
refactor(core): Make new configs consistent (no-changelog)

### PR DESCRIPTION
**Pull request by ivov**
- Remove redundant typings
- Remove remaining `readonly` modifiers [ref](https://github.com/n8n-io/n8n/pull/10286#discussion_r1701946658)
- Add `.config.` infix for searchability
- Convert `email.ts` into `user-management.config.ts`

### CODE REVIEW

**Comment by netroy** [comment]
need to resolve the conflict

**Review by netroy — APPROVED** [review]
PR description says `Remove redundant typings`, but I don't seen that change. also, I'm guessing we need explicit typings for decorator metadata?

**Comment by ivov** [comment]
> PR description says `Remove redundant typings`, but I don't seen that change. also, I'm guessing we need explicit typings for decorator metadata?

These leftover typings below. We used to have them to prevent `readonly` from overly constraining the type, but with `readonly` gone we can rely on natural inference.

Capture 2024-08-14 at 10 47 41@2x

**Comment by janober** [comment]
Got released with [`n8n@1.55.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.55.0)

**Pull request merged**
