### PR TITLE
openshift template added

### PR DESCRIPTION
**Pull request by nagyzekkyandras**
I added my openshift template, which I use in my company.

You have to logging in the cluster and process the template.

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot @NAndras95! That is really great!

I tried it today and it seems to start up correctly. There seems to be however the part missing which makes n8n web-accessible. Do you also have some code or documentation regarding that, as I was not able to do that. Thanks!

**Comment by NAndras95** [comment]
@janober Thank you for your feedback!

I tried it on our new clusters (3.11 and 4.7) and it needs 1 min to start fully.
(When it is in a loading state I have a standart Openshift page with an "Application is not available" on it.)
After the 1 min the auth window appeard and I was able to log in to the application and use it.

We are using wildcard DNS for dev environments, so we don't have to do any other configuration.
Are you use someting like this? Or a hostfile?

**Comment by NAndras95** [comment]
@janober you used a normal Openshift cluster or you used Minishift?
Which version of Openshift you used for testing?

**Comment by janober** [comment]
I created a DevSanbox on https://www.openshift.com

All I did there is did load your template file. I guess it deploys then totally fine but have no idea how to then access it. I guess a "route" or something like that is missing or needed in this case.  I tried to create one myself but because I have no idea how it works was sadly not very successful.

**Comment by Joffcom** [comment]
Hey @nagyzekkyandras,

As part of our recent documentation changes we have started having the templates in their own repos with doc links, At the moment we are not planning on adding anymore but may look to change that in the future.

For now I am going to mark this PR as closed and if we bring in the change in the future I will let you know so we can provide the credit link.

Let me know if you have any questions on this one.

**Pull request closed without merging**
