### PR TITLE
add iconv-lite for encoding/decoding

### PR DESCRIPTION
**Pull request by lublak**

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot!

Do you maybe have a basic example where it caused problems without this change? That we can verify and merge. Thanks!

**Comment by lublak** [comment]
@janober I get some files with win1251 codepage. nodejs does not support it. Iconv-lite supports it and also the native of nodejs.
Also, I choose iconv-lite instead of iconv (full) because it is lighter and faster.
Also it ist fully implemented in js. (no native code)

**Comment by janober** [comment]
Makes sense. Found some files to test here:
https://www.kaggle.com/rtatman/character-encoding-examples?select=olaf_Windows-1251.txt

Works now great and got merged. Will be released with the next version.

Thanks a lot for your contribution!

**Comment by janober** [comment]
Got released with n8n@0.113.0

**Pull request merged**
