### PR TITLE
Add Workflow & n8n Trigger nodes

### PR DESCRIPTION
**Pull request by MedAliMarz**
This PR split the Activation Trigger functionality into two new nodes: Workflow Trigger & n8n Trigger

- [X] Add n8n Trigger node
- [X] Add Workflow Trigger node
    - [X] add activate event
    - [X] add save event
    - ~~[ ] add deactivate event~~
- [X] Update nodes descriptions & icons
- [X] Deprecate Activation Trigger node

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot. We also still have to add an entry to the breaking changes file:
https://github.com/n8n-io/n8n/tree/master/packages/cli

**Comment by krynble** [comment]
Closing this one in favor of https://github.com/n8n-io/n8n/pull/1680 that adds the breaking changes notice

**Comment by janober** [comment]
Thanks a lot. Got merged with #1680

**Comment by janober** [comment]
Got released with n8n@0.117.0

**Pull request closed without merging**
