### PR TITLE
Add CC property to email

### PR DESCRIPTION
**Pull request by Libermentix**
Thanks for such a great tool! We make use of it on a regular basis. 

I took the liberty to extend the e-mail CC property to the Node's settings. 

As this is my first PR on your repo, let me know if this suffices the way it is.

### CODE REVIEW

**Comment by janober** [comment]
Happy to welcome you as n8n contributor! Thanks a lot for the addition and great to know that n8n is helpful for you!

Sorry for the late merge. Everything was a little bit crazy with the release. It will be faster the next time.

**Comment by janober** [comment]
Will release a version with the addition within the next hours.

**Comment by Libermentix** [comment]
cool! happy to be on-board.

**Comment by janober** [comment]
That makes you actually contributor Nr. 5 ;-)

Btw. did just release nan@0.24.0

It is on npm but docker-image is still building.

**Pull request merged**
