### PR TITLE
🔖 Discord Node v2.0

### PR DESCRIPTION
**Pull request by Timeraa**
Hello! 👋 

I've recently found this project while searching for IFTTT & Zapier alternatives *that don't rip you off*.

While I was testing it out I found a lot of good use cases for myself & my projects but I've came to the conclusion that the Discord node is really really basic and therefore misses a lot of features like `username`, `avatarUrl` etc. fields.

So I updated the Discord node and changed it's version to 2.0.

If needed I can also update the linked Documentation of the node as with this PR it would be outdated.

Any changes, suggestions... welcome!

Cheers~

### CODE REVIEW

**Comment by child-duckling** [comment]
Nice! The only thing this need is a trigger that a node-red module has. I'll be all set

**Comment by LucasCtrl** [comment]
Can't wait to see this!
I really would like to be able to send an embed in Discord.

**Comment by Byter09** [comment]
Can't wait for this to be merged! :D

**Comment by janober** [comment]
Thanks a lot for your contribution @Timeraa. Got merged with #2918

**Comment by janober** [comment]
Got released with `n8n@0.173.0`

**Pull request closed without merging**
