### PR TITLE
Feature/Salesforce Auth - JWT Bearer Flow

### PR DESCRIPTION
**Pull request by camcelroy**
Salesforce Authentication - OAuth 2.0 JWT Bearer Flow for Server-to-Server Integration
https://help.salesforce.com/articleView?id=remoteaccess_oauth_jwt_flow.htm&type=5

The existing Salesforce OAuth configuration is great for standard user accounts, but is not the ideal approach for certain server-to-server integrations, especially when wishing for the API calls to be made as a salesforce user for which password credentials are not set.

This implementation was modeled after the similar GoogleApi JWT credentials, giving user choice between the previous web server flow and this new JWT bearer flow.  In all cases the enhancement was done so as. to ensure that any previously existing nodes and configurations are not impacted by the additional authentication option.

New authentication supports both production and sandbox salesforce environments.

### CODE REVIEW

**Comment by RicardoE105** [comment]
@camcelroy ahhh had missed this PR. Will review as soon as I can. Thanks your contribution.

**Comment by RicardoE105** [comment]
@camcelroy just tested it and it's working as expected, thanks for your contribution. We will let you know when is released.

**Comment by camcelroy** [comment]
Thanks @RicardoE105 !  As we continue to adopt N8N, we will likely have some additional worthwhile contributions.  Do you prefer another method of communicating outside of creating a PR?  Happy to do whatever is best for the project.

**Comment by RicardoE105** [comment]
@camcelroy that is good to hear. Looking forward to it. Either here or ricardo@n8n.io it's fine.

**Comment by janober** [comment]
Thanks a lot. Got merged with #1082

**Comment by janober** [comment]
Got released with n8n@0.91.0

**Pull request closed without merging**
