### PR TITLE
fix(editor): Reset last interacted with when resetting the workspace on new canvas (no-changelog)

### PR DESCRIPTION
**Pull request by alexgrozav**
## Summary

https://github.com/user-attachments/assets/14810fc1-4da7-401b-a674-42b6aed49410

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/N8N-7803/debugging-an-execution-adds-phantom-connections

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Review by MiloradFilipovic — APPROVED** [review]
Works as expected!
@alexgrozav does it makes sense to add some tests for this?

**Comment by alexgrozav** [comment]
> Works as expected! @alexgrozav does it makes sense to add some tests for this?

For sure, however e2e tests aren't ready for the new canvas yet. I'll take a note to add tests for this as well.

**Comment by janober** [comment]
Got released with [`n8n@1.63.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.63.0)

**Comment by janober** [comment]
Got released with [`n8n@1.63.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.63.0)

**Pull request merged**
