### PR TITLE
Add container timezone handling

### PR DESCRIPTION
**Pull request by deurk**
Allows to change the timezone with the TZ env variable, useful for cron tasks and other things.

### CODE REVIEW

**Comment by deurk** [comment]
Still working on that, results are... inconsistent :)

**Comment by janober** [comment]
Thanks for the update and for looking into it in general! Always great to not just being made aware of a problem but also getting already the fix for it at the same time!

**Comment by janober** [comment]
Here also for reference the discussion in the forum:
https://community.n8n.io/t/handling-timezones/278/4

**Comment by deurk** [comment]
@janober This is now tested and ready to ship :)

Using `--env GENERIC_TIMEZONE=Europe/Berlin` will now make cron nodes and system commands match the same Berlin time.

**Comment by deurk** [comment]
@janober This is now fully tested and ready to ship :)

**Comment by janober** [comment]
@deurk I did just test it. Worked perfectly. Great work! Thanks a lot for that!

**Comment by janober** [comment]
@deurk Sorry had to change it again. Turned out always setting both is not a good idea. Had some very strange side effects with things like the postgres node. So is now closer to what you did initially.

So the n8n timezone and system timezone can not be set separately. Added also a short documentation:
https://github.com/n8n-io/n8n/commit/1b076a4763d236d78f01e4a31512b5ee952f43ae

Did re-release the current docker containers (0.30.0 & latest) to fix the related issues and that people like yourself, which are probably the minority right now, can set it explicitly if needed.

**Comment by deurk** [comment]
Interesting. Did you see the same side effects when running the container with both values set ?

**Comment by janober** [comment]
The problem occurs as soon as the system timezone gets set to something different then UTC. Postgres queries suddenly returned different results which made it a breaking change. So it seems best to leave it like it was and allow people to set it if they really need it.

**Comment by deurk** [comment]
Right.

I'll look into the issue though, curious to see if this is happening only on existing psql database (my guess is if n8n has been run from the start with the TZ set, issues are not happening).

**Comment by janober** [comment]
The table in question is totally independent of n8n so. Think it also has to do how the Postgres table has been set up. 

Problems we had were that the timestamp of fields returned were different from the ones we had to use to query data. So if the select-query did return "2019-10-28T14:35:04.327Z" and we wanted to then query for entries after that date, we had to use "2019-10-28T15:35:04.327Z". To get the fields returned "correctly" (so the same we have to use to query it) we had to set the timezone in the select explicitly: "t.created_at at time zone 'gmt'"

**Pull request merged**
