### PR TITLE
:zap: Zendesk improvements

### PR DESCRIPTION
**Pull request by RicardoE105**
as requested here: https://community.n8n.io/t/zendesk-custom-fields/1116?u=ricardoe105

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot. Merged it for now. It has to however get improved before it can get released as it is currently not clear how it can be used. The option "JSON Parameters" means normally in n8n that all parameters can be set in JSON format instead of via the UI. Here it works differently. Also, would I personally not have found the way to set custom fields like that. 

It should probably work more like on the HTTP Request Node. That Custom-Fields are on the top-level like Headers there. Then it is possible to add them via the UI one after another with "ID" (optionally: they can be loaded via API so that people can select via option field) and "value".

The "JSON Parameters" boolean parameter would still make sense, but if set also the "Additional Fields" would have to change to a single JSON-input field and not just the "Custom Fields".  Hope that makes sense. Thanks!

**Comment by RicardoE105** [comment]
> It should probably work more like on the HTTP Request Node. That Custom-Fields are on the top-level like Headers there. Then it is possible to add them via the UI one after another with "ID" (optionally: they can be loaded via API so that people can select via option field) and "value".

I actually thought about that but depending on the custom field the way to set the value is different. For example if the type is multi options    `"custom_fields": [{"id": 21938362, "value": ["hd_3000", "hd_5555"]}]`. The value is not just an value but an array. Maybe I can check the type and if the type is multi-select I can do a split conn the value field.

**Comment by janober** [comment]
That should be ok. For complex types that need arrays or similar people can still set "value" to expression and then return it like that. But for all others, it should have the users covered and should so make it quite easy for them to set.

**Comment by janober** [comment]
Got released with n8n@0.61.0

**Pull request merged**
