### PR TITLE
Added includeEmptyCells to Spreadsheet node

### PR DESCRIPTION
**Pull request by AxelRueweler**
For a project I missed an option to always have all the columns represented in the JSON (for Ifs and switches and so forth).

### CODE REVIEW

**Comment by janober** [comment]
Great can see how that can be helpful. Thanks a lot! Got merged and released with the next version.

**Comment by RicardoE105** [comment]
@AxelRueweler good addition. A community member was having issues with this and thought it was a bug. I added the same change and when was about to send the PR realized just already did. Thanks.

**Comment by bberenberg** [comment]
@janober do you have an eta on the next release when this will be included?

**Comment by janober** [comment]
Tomorrow or Thursday.

**Comment by janober** [comment]
Got released with n8n@0.98.0

**Pull request merged**
