### PR TITLE
Add Products support to Shopify node

### PR DESCRIPTION
**Pull request by YonatanRosemarin**
Add products create/get/getAll/update/delete to Shopify.
According to the documentation at https://shopify.dev/docs/admin-api/rest/reference/products/product?api

### CODE REVIEW

**Comment by oc666** [comment]
@janober Can you move this forward? 
Thanks, Ofer

**Comment by janober** [comment]
Ah yes sorry! Is already in Jira and assigned to be tested and reviewed by @RicardoE105. He sadly has currently incredibly much his plate and also I do not get to it right now which results in the reviews taking longer than normal. Hope however that we will be faster again with that soon.

**Comment by RicardoE105** [comment]
@oc666 just reviewed the node. Really nice work. Works perfectly, however, I will do the following improvements:

1 - All fields on a collection have to be organized alphabetically.
2 - The variant fixedCollection just has the field createdAt but according to the documentation it can have more fields.
image. Having just one field does not seem to be useful
3 - Since ID can be removed as the field is used for pagination and the node handles that for the user.
4 - Split long descriptions into multiples lines using the HTML line break <br>

can you take care of that? again nice work, usually I have to make changes but this was :ok_hand:

**Comment by YonatanRosemarin** [comment]
@RicardoE105 thanks for the elaborated  CR. Fixes were made and pushed

**Comment by RicardoE105** [comment]
@YonatanRosemarin ahh sorry, maybe it was not clear enough. I already made the changes just listed them so that you know what I changed.

**Comment by YonatanRosemarin** [comment]
@RicardoE105 - my bad, missed that. Again, thank you!

**Comment by RicardoE105** [comment]
I thank you @YonatanRosemarin for taking the time to contribute to the project.

**Comment by janober** [comment]
Great, thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.78.0

**Comment by YonatanRosemarin** [comment]
Thanks @janober  & @RicardoE105

**Comment by janober** [comment]
We thank you! Have a nice day!

**Comment by YonatanRosemarin** [comment]
Hi @janober ,
We have upgraded one of our instances installed by NPM to V0.78 and we don't see the change in it. Any idea?
image
image

**Comment by janober** [comment]
I guess it did update only the cli package but none of the other ones. Especially not the [n8n-nodes-base](https://www.npmjs.com/package/n8n-nodes-base) to 0.73.0 which contains all the node code. 

As npm is constantly making problems I always recommend people to run n8n in docker as upgrading there is very easy and works for sure.

**Comment by YonatanRosemarin** [comment]
Hi @janober - thanks, we ran n8n instance using docker and it seems to work great. One issue that we have is that our custom nodes types were changed so it does not recognize them now (for example one changed from "n8n-nodes-suitecrm.suiteCRM" to "CUSTOM.suiteCRM"). How can we run the docker and keep custom nodes types? (we already have multiple Workflows running in this environment and we don't want to re-create them). Thanks

**Comment by janober** [comment]
The simplest thing would be to copy the workflow in a text-editor. Rename there all the "types" (with replace) and then paste them back.

**Comment by YonatanRosemarin** [comment]
OK, thanks

**Pull request closed without merging**
