### PR TITLE
refactor(core): Mark all backend Enterprise Edition files and dirs

### PR DESCRIPTION
**Pull request by ivov**
## Summary

This PR ensures all backend Enterprise files and dirs are marked, either with `.ee.` infix for filenames or with `.ee` suffix for dirnames. The following were renamed and imports adjusted, but otherwise unchanged. 

> [!IMPORTANT]  
> `LICENSE.md` was adjusted to reflect the dir suffix convention. This change needs to be confirmed by @csuermann. 

Files:

- `packages/cli/src/services/project.service.ts` → `packages/cli/src/services/project.service.ee.ts`
- `packages/cli/src/secrets-helpers.ts` → `packages/cli/src/secrets-helpers.ee.ts`
- `packages/cli/src/scaling/worker-status.service.ts` → `packages/cli/src/scaling/worker-status.service.ee.ts`
- `packages/@n8n/permissions/src/combineScopes.ts` → `packages/@n8n/permissions/src/combineScopes.ee.ts`
- `packages/@n8n/permissions/src/hasScope.ts` → `packages/@n8n/permissions/src/hasScope.ee.ts`
- `packages/@n8n/permissions/src/types.ts` → `packages/@n8n/permissions/src/types.ee.ts`

Dirs:

- `packages/cli/src/environments` → `packages/cli/src/environments.ee`
- `packages/cli/src/evaluation` → `packages/cli/src/evaluation.ee`
- `packages/cli/src/external-secrets` → `packages/cli/src/external-secrets.ee`
- `packages/cli/src/ldap` → `packages/cli/src/ldap.ee`
- `packages/cli/src/sso` → `packages/cli/src/sso.ee`
- `packages/cli/src/workflows/workflow-history` → `packages/cli/src/workflows/workflow-history.ee`
- `packages/cli/src/permissions` → `packages/cli/src/permissions.ee`

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/PAY-1945

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Review by csuermann — APPROVED** [review]

**Review by netroy — APPROVED** [review]

**Review by insaramdev — COMMENTED** [review]
변경

**Comment by janober** [comment]
Got released with [`n8n@1.74.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.1)

**Comment by janober** [comment]
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)

**Comment by janober** [comment]
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)

**Pull request merged**
