### PR TITLE
Node continue on fail

### PR DESCRIPTION
**Pull request by krynble**
This PR improves the work done by https://github.com/n8n-io/n8n/pull/1737

- Fixed EmailSendNode as it was broken
- Updated test workflows script to add more testing cases and conditions
- Updated branch to follow latest changes on Master

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.131.0

**Comment by rpmcoding** [comment]
@krynble please can you add a fix for woocommerce like this.

**Comment by janober** [comment]
Got released with `n8n@0.197.0`

**Pull request merged**
