### PR TITLE
AWS DynamoDB: Scan data

### PR DESCRIPTION
**Pull request by mvhirsch**
Hey, thanks for finally merging #1602! 
Looking into 0.130.0, it looks awesome, but after refactoring, one operation was gone: [Scan](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Scan.html). For me it's somehow mandatory to explore data easily.

I re-added it, by using the dynamodb-code you built. Hopefully this gets merged faster than last time :grinning: 

Thanks for all your work! n8n is awesome!

### CODE REVIEW

**Comment by mvhirsch** [comment]
@janober is there something I need to add?

**Comment by janober** [comment]
Adding @ivov @RicardoE105 to have a look.

**Comment by mvhirsch** [comment]
@ivov @RicardoE105 can I help?

**Comment by RicardoE105** [comment]
@mvhirsch, thanks for your contribution. Instead of creating another operation for scanning, I moved it as an option within getAll since they share most of the parameters. 

We will let you know when it's released.

**Comment by janober** [comment]
Thanks a lot @mvhirsch ! Got merged with #2085

**Comment by mvhirsch** [comment]
Awesome! Thank you very much!

**Comment by janober** [comment]
Got released with n8n@0.134.0

**Pull request closed without merging**
