### PR TITLE
AWS DynamoDB Node

### PR DESCRIPTION
**Pull request by mvhirsch**
Hi folks,

I really love N8N. I've discovered a missing node: AWS DynamoDB. As I've only got a read-only access id I'm just able to do implement that: GetItem, Query and Scan operations. But still created "resource" and "operation" in case, someone is able to add additional functionality in future.

I would love to hear feedback from you!

I've tested it and it just works fine, too. Just a little questions I'm not sure about:

1. In "expression-attribute-values" I need an [object map as described here](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_AttributeValue.html). At the moment I'm just requiring any json input, expecting the user knows how to fill it. How could I improve that to be more intuitive?
2. The property names are way too long. How should I name them, without loosing future compatibility (e.g. distinguish between "FilterExpression" and "ProjectionExpression" and so on. See [properties described here](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_Query.html)

### CODE REVIEW

**Comment by RicardoE105** [comment]
@mvhirsch really cool. Thanks for the contribution.

> In "expression-attribute-values" I need an object map as described here. At the moment I'm just requiring any json input, expecting the user knows how to fill it. How could I improve that to be more intuitive?

You can do probably a fixCollection, with two fields key and value. Key would be the name of the property to set, and value can be set with an expression depending on the key type. It's not a perfect solution but it's an improvement.

https://docs.n8n.io/nodes/creating-nodes/node-elements.html#fixed-collection

> The property names are way too long. How should I name them, without loosing future compatibility (e.g. distinguish between "FilterExpression" and "ProjectionExpression" and so on. See properties described here

Not sure if I understand the question here.

**Comment by mvhirsch** [comment]
> You can do probably a fixCollection, with two fields key and value. Key would be the name of the property to set, and value can be set with an expression depending on the key type. It's not a perfect solution but it's an improvement.

That's perfect! Thank you!

Screenshot from 2021-03-26 09-40-36
 

> Not sure if I understand the question here.

Okay, I just overthought it. All fine here. Sometimes naming things is hard. Sometimes it's just okay :sweat_smile:

**Comment by mvhirsch** [comment]
@RicardoE105 is there anything I should do, to improve it? Or could it be merged right away?

**Comment by mvhirsch** [comment]
Since @ivov already refactores my branch, is this still needed? Should we close this PR?

**Comment by mvhirsch** [comment]
Any updates on this?

**Comment by ivov** [comment]
Normally, the original contribution is closed once the refactored version is merged. My refactoring is up for review by another team member. We are a small team so it may take time but it will be done.

**Comment by mvhirsch** [comment]
> Normally, the original contribution is closed once the refactored version is merged. My refactoring is up for review by another team member. We are a small team so it may take time but it will be done.

I see, thanks for the explanation :-)

**Comment by mvhirsch** [comment]
@ivov do you see any chance to get this updated soon? I already found a possible missing feature I need to add. But without knowing what's the base (either this branch, or the other) it's hard to develop. Any suggestion?

**Comment by janober** [comment]
Thanks a lot for your contribution! Got merged with #1602

**Comment by janober** [comment]
Got released with n8n@0.130.0

**Pull request closed without merging**
