### PR TITLE
fix(editor): Canvas showing error toast when clicking outside of "import workflow by url" modal

### PR DESCRIPTION
**Pull request by RicardoE105**
## Summary

FE attempted to import workflow even when the modal was closed - by clicking outside the modal.

Before:

https://www.loom.com/share/67ab4c920c334ecfa7ac1341603c882a

Now:

https://www.loom.com/share/8ce132a9edd2423a9995c05a07982c29

## Related tickets and issues
https://linear.app/n8n/issue/ADO-960/closing-import-form-url-modal-by-clicking-outside-causes-error

## Review / Merge checklist
- [x] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))

### CODE REVIEW

**Review by MiloradFilipovic — DISMISSED** [review]
Works as expected. I would love to see a quick test for this added also 🙏

**Review by MiloradFilipovic — DISMISSED** [review]
Nice! Thanks for addressing. One nitpick though: Does it make sense to move other tests that are testing workflow import (like [this one](https://github.com/n8n-io/n8n/blob/46516441c0a27ccb027297723bc4851165660c2b/cypress/e2e/7-workflow-actions.cy.ts#L132)) to this file also? Now we are having them in a few places which can be confusing

**Comment by RicardoE105** [comment]
Good catch, @MiloradFilipovic. That is most likely the same test. I will probably delete the one you mentioned and keep this separate file.

**Review by MiloradFilipovic — APPROVED** [review]
Looks good, thanks for addressing.

**Comment by janober** [comment]
Got released with [`n8n@1.36.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.36.1)

**Pull request merged**
