### PR TITLE
Evernote Integration (node)

### PR DESCRIPTION
**Pull request by RicardoE105**
Hey @janober,

As requested here https://community.n8n.io/t/evernote-integration/570

You might be wondering why I did use the Evernote package and the reason is cuz Evernote does not have a REST API. They use Apache Thrift which is sort of a framework for RPC communication. More info in there https://thrift.apache.org/

The other issue I encountered was trying to import the npm package using import but could not make work but using require. They also have types that you can find here https://www.npmjs.com/package/@types/evernote but when using them could not make work.

### CODE REVIEW

**Comment by janober** [comment]
Really cool! Thanks a lot. Will check it out.

I just checked the evernote npm module. It is installed only 524k large. So not that bad. But it would still be a problem if we would do that for each integration. Also, would it probably still in the "long-term" make sense to use some generic npm Apache-Thrift module to be able to use the same one for other integrations that require also require thrift.

**Comment by RicardoE105** [comment]
This is the fix I told you about on the email @janober. I have not been trying to use the Thrift library instead of the Evernote package without success, but I guess eventually I will get it done.

**Comment by janober** [comment]
@RicardoE105 Thanks a lot!

About the thrift-library. There is really no need to invest a lot of time now. Like I wrote would be more important in the long-term.

**Comment by janober** [comment]
Just for reference. Because Evernote does not seem to issue API-Keys for production anymore this integration has to wait till OAuth functionality got added to n8n and this integration then updated to use it.

**Comment by janober** [comment]
Closing this PR as it is open for a long time and because of ongoing issues with authentication (as it uses a not supported version of OAuth) is the node still not in a state that it can be merged.

**Pull request closed without merging**
