### PR TITLE
[WIP] Expand Freshdesk Node for Companies

### PR DESCRIPTION
**Pull request by derrickmehaffy**
TO-DO

- [x] Init basic company routes
- [ ] expand contact routes to attach to companies
- [ ] test routes
- [ ] code QA
- [ ] Documentation

This is a WIP PR to expand the Freshdesk node for additional options related to company management.

### CODE REVIEW

**Comment by RicardoE105** [comment]
Any update on this?

**Comment by derrickmehaffy** [comment]
> Any update on this?

Hi @RicardoE105 sorry I got a bit side tracked, I'll have a bit more time this week and this weekend that I might be able to finish it up.

**Comment by Joffcom** [comment]
Hey @derrickmehaffy,

How are you getting on with this one?

**Comment by derrickmehaffy** [comment]
> Hey @derrickmehaffy,
> 
> How are you getting on with this one?

I haven't had the time to finish it, going to close for now as we ended up not going with n8n

**Pull request closed without merging**
