### PR TITLE
:sparkles: Add Zendesk auth test for Api Token

### PR DESCRIPTION
**Pull request by GeylaniBerk**
This PR adds auth test for Zendesk API

Success:
zendesk_success

Failure:
zendesk_failure

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot for this PR. I did just run the code but I get this error:
Screenshot from 2021-11-05 09-51-10
Even though the credentials work totally fine for me. Meaning if I run "Tickets -> Get All" the request works even though the credential check says they are wrong. Do you have an idea why that could be the case?

**Comment by GeylaniBerk** [comment]
@janober , Thanks a lot for your quick review and feedback. I was using oauth2 token instead of api token and you had to use oauth2 token. Now I changed it to use api token, can you please retry it when you have time?

**Comment by janober** [comment]
Thanks a lot. Got merged and will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.149.0

**Pull request merged**
