### PR TITLE
Added feature to resolve alerts

### PR DESCRIPTION
**Pull request by rons4**

### CODE REVIEW

**Comment by RicardoE105** [comment]
@rons4 sorry for the late response. I will review it this week and provide feedback. Thanks for your contribution.

**Comment by rons4** [comment]
@RicardoE105 Thank you for your update. Sounds good and just let me know if you should need anything from my side.

I tested the alert / resolve feature with a simple file monitor. I really enjoy working with your platform.
image

**Comment by RicardoE105** [comment]
ahh glad you like to work with n8n. Actually it's @janober platform, I'm pretty sure he is also glad you like it. Thanks for your contribution.

**Comment by janober** [comment]
Thanks Yes I am. But is for sure not "mine" anymore rather "ours".

**Comment by rons4** [comment]
Thanks a lot @janober and @RicardoE105.

**Pull request merged**
