### PR TITLE
fix ipad node drag issue #1989

### PR DESCRIPTION
**Pull request by mutdmour**
- remove touch event because it's in a race condition with `stop` callback here https://github.com/n8n-io/n8n/blob/master/packages/editor-ui/src/components/mixins/nodeBase.ts#L294
- fixes drag issue in #1989 for iPads
- tested on iPad iOS 14 chrome and safari
- tested on iPad iOS 13 chrome and safari
- tested on iPad iOS 12 chrome and safari
- tested on phone Android 10 chrome (92) and opera
- tested on tablet Android 10 chrome, samsung and firefox 
- tested on tablet Android 9 chrome and firefox
- tested on tablet Android 8 chrome and firefox

### CODE REVIEW

**Comment by janober** [comment]
@mutdmour  This fixes one issue but sadly breaks something else. Now it is not possible to move on node-view around anymore after a node got created (tab on empty space without a node and then move the finger). Make sure to always do some deep testing when simply code gets removed as it was probably there for a reason. Thanks!

**Comment by mutdmour** [comment]
@janober thanks for the info. will try to be more careful next time

**Comment by mediana** [comment]
Is there any fix or update about this issue ?

**Comment by mutdmour** [comment]
@mediana sorry this got superseded by urgent work. will try again after we release the new canvas

**Pull request merged**
