### PR TITLE
fix(API): Fix workflow project transfer

### PR DESCRIPTION
**Pull request by benrobot**
## Summary

Transferring a workflow to a new project via the Public API was failing.

The unit test responsible for detecting this type of issue was only passing because there were no other workflows and projects in the database. After updating the test to match a more real-world scenario the test started to fail as shown in the screenshot below:
image

## Related Linear tickets, Github issues, and Community forum posts

none

## Review / Merge checklist

- [✅] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ n/a ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [✅] Tests included. 
- [n/a] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @benrobot,

Thanks for the PR, We have created "GHC-199" as the internal reference to get this reviewed.

One of us will be in touch if there are any changes needed, in most cases this is normally within a couple of weeks but it depends on the current workload of the team.

**Review by ivov — DISMISSED** [review]
Good catch! Thank you for your contribution.

**Comment by ivov** [comment]
@benrobot Thanks again for your contribution. Once the lint issues are fixed we can bring this in. Let us know if we can help or if you'd like for us to take over.

**Review by ivov — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.62.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.62.1)

**Pull request merged**
