### PR TITLE
Add new tools

### PR DESCRIPTION
**Pull request by mcolomer**
Add tool Communication/Get Personal Email By Social Network Profile (2021-10-15)
Add tool Geographic/Get Location By Parameters (2021-09-28)
Add tool Company/Get GitHub URI By Company's Domain (2021-09-16)
Add tool Company/Get YouTube URI By Company's Domain (2021-09-16)
Add tool Company/Get Pinterest URI By Company's Domain (2021-09-15)
Add tool Company/Get Instagram URI By Company's Domain (2021-09-14)
Add tool Product/Get ISBN13 Code By ISBN10 Code (2021-09-12)
Add tool Product/Get ISBN10 Code By ISBN13 Code (2021-09-11)
Add tool Product/Get Book By ISBN (2021-09-10)
Add tool Company/Get Facebook URI By Company's Domain (2021-09-08)
Add tool Company/Get Twitter URI By Company's Domain (2021-09-07)
Add tool Company/Get LinkedIn URI By Company's Domain (2021-09-06)
Add tool Product/Get Data By VIN Number (2021-08-05)
Add tool Product/Check VIN Number Is Valid (2021-08-04)
Add tool Communication/Get Search LinkedIn Contacts Url (2021-07-25)
Add tool Geographic/Get Time Data By Coordinates (2021-05-25)
Add tool Communication/Check Email Is Catchall (2021-05-13)
Add tool Geographic/Get Time Data By Postal Address (2021-05-06)
Add tool Communication/Get Email By Firstname, Lastname And Company (2021-05-01)
Add tool Finance/Get Swift Code Lookup (2021-04-27)
Add tool Image/Get OCR Text From Image (2021-04-26)
Add tool Geographic/Get Normalized Country (2021-03-31)
Add tool Communication/Get Parsed And Validated Phone (2021-03-30)

### CODE REVIEW

**Comment by mcolomer** [comment]
Added new tool "Crypto wallet checker"

**Comment by mcolomer** [comment]
Add tool: LinkedIn profile by phone

**Comment by mcolomer** [comment]
Add tool: LinkedIn profile by phone

**Comment by Joffcom** [comment]
Hey @mcolomer,

I was just about to review this one but I noticed something has gone a bit wonky somewhere and this PR seems to show 320 file changes, At a guess it is something that happened while merging from the master branch.

Any chance you could resubmit this PR with only your changes to make it easier to review?

**Comment by mcolomer** [comment]
Hi Joffcom!

Yes, this PR is really old.

I have published a new PR at
https://github.com/n8n-io/n8n/pull/3104

Let's continue the revision out there.

Thank you!

**Pull request closed without merging**
