### PR TITLE
Working Spotify Trigger Node

### PR DESCRIPTION
**Pull request by erin2722**
🎵 Here is a Spotify Trigger Node

This functionality was requested by the [community](https://community.n8n.io/t/spotify-node-partly-created/1592).

Right now it can trigger on:
- New songs added to a playlist
- New liked songs

### CODE REVIEW

**Comment by treyturner** [comment]
Hi @erin2722 , I really appreciate your work on the Spotify node. What happened to this trigger node?

**Comment by erin2722** [comment]
@treyturner Thanks for reaching out! I did not realize that I had closed this-- when the maintainers get the chance to take a look at this it should be ready to merge in!

**Comment by janober** [comment]
Thanks a lot @erin2722 and @treyturner! Yes we did also totally overlook this. Thanks, we will review.

**Comment by janober** [comment]
Thanks a lot @erin2722! We now thought about it for a while but will not merge it for now because of the Spotify API which does not have webhooks and also not a way to query a subset of the data. So for that reason did you have to implement the trigger the way you did. That implementation seems however to wasteful to release for production use.
Hope we can build on top of your code once their API improves. Thanks again!

**Pull request closed without merging**
