### PR TITLE
Adding Google Chat node

### PR DESCRIPTION
**Pull request by valentina98**
This node contains 5 resources with different operations.

**Media**
Download

**Space**
Get
Get All

**Member**
Get
Get All

**Message**
Create
Delete
Get
Webhook

**Attachment**
Get

### CODE REVIEW

**Comment by luizeof** [comment]
@valentina98 I was doing one, but yours is perfect. a long-awaited node. good work !

**Comment by RicardoE105** [comment]
Reviewed the node. Can you please address the issues below? Let me know if something it's not clear. I'm happy to help.

## media:download

- [ ]  Ask for the binary property to add the downloaded data to but it does not use it in the code?
- [ ]  resource description should end with a dot
- [ ]  resource description should be download instead of downloads

## space:getAll

- [ ]  Missing limit field when return all is false
- [ ]  Page token and page size are not needed there. Delete them.
- [ ]  It should return the array of objects. Get rid of the property spaces

## member:get

- [ ]  fix description

## member:getAll

- [ ]  Fix description
- [ ]  limit parameter missing when returnAll is set to false
- [ ]  Remove page size and page token
- [ ]  It should return the array of objects. Get rid of the property memberships

## message:create

- [ ]  Parent name should be renamed to Space ID and `Thread Key` and `Request ID` are optional parameters, hence should be under a collection.
- [ ]  Looks like it's not possible to build a complex message from the UI without using JSON. I would refer her/him to the Slack node, specifically to the message blocks
- [ ]  Update mask should be handled behind the scenes

## message:webhook

- [ ]  I would rename this else it's kind of confusing. Something like `incomingwebhook:create`

**Comment by RicardoE105** [comment]
@valentina98 thanks. Will review it again as soon as I can.

**Comment by RicardoE105** [comment]
Looking much better @valentina98. Can you please address the changes below? After that, I will move the node forward internally. Thanks very much.

# 20201213

- [ ]  Run [linter](https://docs.n8n.io/nodes/creating-nodes/nodelinter.html#options) to fix some formatting issues

## message:create

- [ ]  Load spaces from the API
- [ ]  Rename `Json parameter message` to `JSON Parameters`
- [ ]  Rename collection from `Query parameters` to `Additional Fields`
- [ ]  Add placeholder `Add Field` to collection

## message:delete

- [ ]  Return `{ "success": true }` instead of empty

## message:update

- [ ]  Rename `Json parameter message` to `JSON Parameters`

## member:getAll

- [ ]  Load spaces from the API

## member:get

- [ ]  Rename Name to Space Name

**Comment by RicardoE105** [comment]
@valentina98 any update about this?

**Comment by valentina98** [comment]
I made the changes. 
I'm sorry for the delay and thank you a lot for your feedback!

**Comment by RicardoE105** [comment]
@valentina98 have a couple of questions for you.

1. How did you test the attachment:get and media:get? I do not know what to set for 
2. Did you run the linter as I suggested in the latest review? I just did and there are still some issues that need to be addressed.
3. 
image

**Comment by valentina98** [comment]
@RicardoE105
1. I couldn't obtain an attacment name to test them. I searched a lot about it and I came to conclusion that bots can get only messages that they created
https://stackoverflow.com/a/61870947
and they have limted message types so they cannot send an attachment
https://stackoverflow.com/a/67737236/8966141
I used just the documentation to implemet tese two endpoints. And the Next Cloud node as a reference for the download endpoint.

2. It is my mistake, now they are fixed.

image

The error in the picture is because of a dash in the url.

**Comment by RicardoE105** [comment]
@valentina98 cool, then will remove those two endpoints in the meantime and review the rest. Thanks.

**Comment by valentina98** [comment]
Thank you, the feedback was very useful for me and I'll apply it in future development of nodes. Please, let me know if there is something else.

**Comment by janober** [comment]
Thanks a lot! Got merged with #2795 and released with `n8n@0.164.0`.

**Pull request closed without merging**
