### PR TITLE
fix(Cal Trigger Node): Update to support v2 webhooks

### PR DESCRIPTION
**Pull request by alishaz-polymath**
This PR adds support for a new Event trigger **MEETING_ENDED** and fixes the webhooks endpoint (used to be /hooks, now it's /webhooks)

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @alishaz-polymath,

The change looks good but if we merge this will it break for self hosted cal users that have not updated? We can work around this with light versioning so it works for new users and old users, I tried to find release notes to find the version change so I can get it implemented but was not successful.

**Comment by alishaz-polymath** [comment]
> Hey @alishaz-polymath,
> 
> The change looks good but if we merge this will it break for self hosted cal users that have not updated? We can work around this with light versioning so it works for new users and old users, I tried to find release notes to find the version change so I can get it implemented but was not successful.

Hey @Joffcom 
The changes are part of our private API repo. And since the API repo versioning is not the same as the calcom repo versioning, it might be trickier than we think. 
The endpoint change was done around 4-5 months ago while the new Event Trigger was added in https://github.com/calcom/cal.com/releases/tag/v1.9.0
What do you recommend in this case? 🤔

**Comment by alishaz-polymath** [comment]
For what it's worth, there have been major bug fixes, upgrades and feature changes in the past 4-5 months as well, so I'd probably recommend them to upgrade to one of the later versions. Perhaps we can proceed with the changes as they are currently as it's far more stable now anyway.

**Comment by alishaz-polymath** [comment]
Hi @Joffcom 
Could you please point me in the direction of the recommended way to version the trigger node in n8n? I am more than willing to set it up in accordance with that 🙏

**Comment by Joffcom** [comment]
Hey @alishaz-polymath,

That sounds good to me, If you take a look at the NocoDB node you can see the light versioning in action. I know it is such a small change that may not impact anyone but I am a big fan of playing it safe and you never know what users are self hosting.

**Comment by Joffcom** [comment]
@alishaz-polymath that looks good, I have not had a chance to test it but I will make an individual account on the site in the morning and see if we can get this into `0.217.0` this week.

**Comment by alishaz-polymath** [comment]
> @alishaz-polymath that looks good, I have not had a chance to test it but I will make an individual account on the site in the morning and see if we can get this into `0.217.0` this week.

Unfortunately I was unable to test it locally because I keep running into development build errors, even without any changes to the current n8n master branch. I'm on windows, just FYI. Could you please direct me to a documentation that I could follow step by step and test this out locally from my fork?
🙏

**Comment by alishaz-polymath** [comment]
> Hey @alishaz-polymath,
> 
> We have the [contributing guide](https://github.com/n8n-io/n8n/blob/master/CONTRIBUTING.md) which might help. What issues did you see?

This helped. Thanks. 🙏 

I could test locally and it did appear to have provided the option. 👍 
i would love it if you can test and confirm, and then we can get this resolved. Do I also need to provide necessary update to the docs?

**Comment by Joffcom** [comment]
Hey @alishaz-polymath,

I don't think any doc changes are needed, It looks like I just missed the release for this week so will be aiming for the 218.0 release next week.

Will get that testing done tomorrow.

**Comment by alishaz-polymath** [comment]
> Hey @alishaz-polymath,
> 
> I don't think any doc changes are needed, It looks like I just missed the release for this week so will be aiming for the 218.0 release next week.
> 
> Will get that testing done tomorrow.

Hey @Joffcom any update on how the test went, and when can we expect this to be merged?
Thanks in advance |🙏

**Comment by dayvista** [comment]
Is there anything I can help with to get this PR merged? I was going to create my own for this issue anyway.

I'm able to use Cal.com webhooks in the meantime, but this integration is necessary for non-technical users.

**Comment by Joffcom** [comment]
Hey @alishaz-polymath,

It fell down my list a little bit but I am planning to get this into the next release.

**Review by Joffcom — APPROVED** [review]

**Comment by Joffcom** [comment]
Hey @alishaz-polymath & @dayvista,

This looks good and I have approved the change, Once the E2E test is finished I will get it merged in and this change will go out in the next release of n8n.

**Comment by janober** [comment]
Got released with [`n8n@0.219.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.219.1)

**Pull request merged**
