### PR TITLE
Add CoinGecko node

### PR DESCRIPTION
**Pull request by dokime7**
Add CoinGecko node in order to get crypto coins data from coingecko.com

### CODE REVIEW

**Comment by dokime7** [comment]
That's my first Node, so feel free to correct me if needed :)

**Comment by RicardoE105** [comment]
@dokime7 really cool. Will check it out and let you know. Thanks very much.

**Comment by RicardoE105** [comment]
@dokime7 ok reviewed and functionality wise it was working well nice work. However, I made some changes here #980 adjusting formatting and keeping consistency with the other nodes. Can you please check it out and let me know if everything works as expected for you? Again, thanks very much.

**Comment by dokime7** [comment]
I've finished to improve the code.
Modifications have been made from your improvements at PR #980, so I think that you can close it (PR #980). Sorry for my misuse of Github...
Feel free to review before merging.
Thanks

**Comment by RicardoE105** [comment]
@dokime7 seems to be working as expected. It's right now under internal review and then will be merge. Thanks very much.

**Comment by dokime7** [comment]
Arfff sorry, I've added the commit 8a5b7c2 "Add Update on InvoiceNinja expenses" on this pull request but it's an error... :(
I wanted to create a new pull request for that.
Could you remove the commit on this pull request or tell me how I can do that please?
Thanks

**Comment by janober** [comment]
Thanks a lot! Got merged with #1009

**Comment by janober** [comment]
Got released with n8n@0.86.0

**Pull request closed without merging**
