### PR TITLE
feat(Postmark Trigger Node): Update credentials so they can be used in the HTTP Request Node

### PR DESCRIPTION
**Pull request by bramkn**
Add new way of doing credentials so they also show up in HTTP request node.
As we only have a trigger node now for postmark, this helps us a lot adding API requests through the HTTP request without the need to setup the credentials 2x.

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @bramkn,

Thanks for the PR, I am just going to check this one now quickly before signing off for the day.

**Comment by Joffcom** [comment]
Hey @bramkn,

I have given the trigger node a test and used the credential in the HTTP request node and all looks to be good. Thanks for the time you spent on this PR, I will get it merged now.

**Review by Joffcom — APPROVED** [review]

**Comment by Joffcom** [comment]
Thanks again @bramkn, This has now been merged and will be available in the next release.

**Comment by janober** [comment]
Got released with `n8n@0.205.0`

**Pull request merged**
