### PR TITLE
N8N-3516 migrate from lerna to turborepo

### PR DESCRIPTION
**Pull request by alexgrozav**
- Adds turborepo setup
- Adds npm workspaces support
- Removes lerna

New installation command is now `npm install` instead of `lerna bootstrap --hoist --no-ci`.

### CODE REVIEW

**Review by mutdmour — COMMENTED** [review]
looks good. still need to test.. but there's a couple of things that need to be updated still:
1. Docker image.. need to make sure it does not use lerna anymore and it builds correctly.. you can use the slack commands which i believe use the custom image.. 
https://github.com/n8n-io/n8n/blob/master/docker/images/n8n-custom/Dockerfile
2. contributing.md file
3. remove `lerna-debug.log` from `.gitignore` file..

**Comment by alexgrozav** [comment]
@mutdmour Thanks for the review. Removed all the remaining lerna references. Build also seems to be good now.

**Review by mutdmour — DISMISSED** [review]
lgtm.. still need to be tested..

**Review by ivov — COMMENTED** [review]
https://linear.app/n8n/issue/N8N-3516#comment-cead27ec

**Review by mutdmour — APPROVED** [review]

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with `n8n@0.190.0`

**Pull request merged**
