### PR TITLE
fix: Env expression evaluation in the frontend should show an appropriate error (no-changelog)

### PR DESCRIPTION
**Pull request by netroy**
https://linear.app/n8n/issue/ADO-95

### CODE REVIEW

**Review by ivov — COMMENTED** [review]
1. `ERROR:` in parameter input hint is out of place - this is an informational message. Might need an ad hoc exception.
2. Initial lowercase to match other error messages.
3. `failExecution: true` is not failing the execution (I expect that it would?) and even so we should not fail the execution for this as it is not an actual error.

image

**Comment by netroy** [comment]
This is the bets I could manage.
image

Perhaps we should look into modifying tmpl to allow adding metadata to the evaluated string, so that we can then use that show a warning labels above an evaluated expression.

**Review by ivov — COMMENTED** [review]
@maxtkacz I find the UX of this confusing:

- Standalone `$env` renders as `[Object: {}]`. 
- `$env.NON_EXISTING` renders green as empty string. We cannot know if it exists. Maybe this should be blue?
- `$env.NON_EXISTING` fails to add the key-value pair in Set? I would expect `propertyName: ''`.
- `[no preview available for $env expressions]` → I would expect `expression` in singular because this matches a single `$env` resolvable.
- Operating on the value results in operating on the string in the parameter input hint and inline expression editor output. Is this what we want? `[Array: ["[no preview available for $env expressions]"]]`
- Using another accesor produces `[undefined]`.

image
image
image
image

**Comment by nik8n** [comment]
1. Should probably also render `[no preview available for $env expression]`, no? Is that an easy fix?
2. Agree - if I remember correctly, we don't have blue currently in our design system for info. Max used yellow for that in one of his design protos. Is changing the color here easy? Otherwise, I think we can live with green.
3. I think `[no preview available for $env expression]` is the best output we can have here because it doesn't matter what comes after the $env if we can't preview that
4. Agree
5. Should also result in `[no preview available for $env expression]` in my opinion
6. Same as (5)

In my opinion we should always show  `[no preview available for $env expression]` as soon as we have the $env.

**Pull request closed without merging**
