### PR TITLE
:sparkles: Affinity node and trigger

### PR DESCRIPTION
**Pull request by RicardoE105**

### CODE REVIEW

**Comment by RicardoE105** [comment]
@janober just finished. Just a little detail. If I run the trigger then deleted and then run it again, it would show the following error: 

image

it happens after the webhook is created. Not sure what I'm doing wrong.

**Comment by janober** [comment]
Thanks a lot @RicardoE105! Very strange. It checks a few lines before if it is `undefined` or not and so that error "should" not happen. So it seems like that in the time between the check and the max. two promises (which are in-between) get resolved the webhook gets deleted again and so that error occurs. Try to have a proper look tomorrow...

**Comment by RicardoE105** [comment]
@janober found the issue. Now it's working fine.

**Comment by janober** [comment]
Great, thanks a lot got merged.

Sadly had to remove the "resolve" option as it did not work with some events like "field_value".

**Pull request merged**
