### PR TITLE
docs: Update Skip SSL to mention it is insecure (no-changelog)

### PR DESCRIPTION
**Pull request by Ten0**
Fixes part 1 of [this issue](https://community.n8n.io/t/n8n-forces-using-insecure-connections-fix-it/63262).

Looking up the forum, it looks like most people in the n8n ecosystem are unaware that checking the "Ignore SSL Issues" is a security hazard. [The team suggests using it to unaware users](https://community.n8n.io/t/self-signed-certificate-in-certificate-chain/20709/2), but most users just won't even know what SSL is.

This PR helps at fixing this security issue by letting people who might care about security know that checking this box *is* in fact a security issue.

(Specifically, checking "Ignore SSL issues" for example allows anyone on the same wifi as a running instance to steal any such credentials it may hold by doing ARP spoofing, and some people on the internet to steal them by doing IP spoofing or DNS spoofing.)

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Review by Joffcom — DISMISSED** [review]
Thanks for this

**Comment by Joffcom** [comment]
Hey @Ten0,

Thanks for the PR, We have created "GHC-513" as the internal reference to get this reviewed.

One of us will be in touch if there are any changes needed, in most cases this is normally within a couple of weeks but it depends on the current workload of the team.

**Comment by Ten0** [comment]
Test fails seem unrelated.

**Comment by Joffcom** [comment]
@Ten0 the lint failed tests are related to your changes, Are you able to run the linter to resolve them?

**Review by Joffcom — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.71.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.71.0)

**Pull request merged**
