### PR TITLE
:sparkles: Fetch saved tracks in Spotify node

### PR DESCRIPTION
**Pull request by gerardlouw**
* Add library resource type to Spotify node
* Add getUserTracks operation to Spotify node
* Add user-library-read to Spotify credential scope

### CODE REVIEW

**Comment by gerardlouw** [comment]
I manually tested the change as follows:
1. Did an `npm run build`/`npm build start` with my local changes.
2. Connected my Spotify credentials and saw I was now prompted to accept the additional permissions - accepted them.
3. Created a test Spotify node, saw that there was now a "Library" resource in the list, selected it, saw that the only option was "Get Saved Tracks" with the expected description and selected that.
4. Clicked "Run" with the default limit of 50, saw a list of 50 results with Spotify track JSON blobs, e.g.
```
{ ..., "type": "track", "uri": "spotify:track:0vEnsVSD4jiSJMuz3ITrOL" }
```
5. Clicked "Run" againn with "Return All" toggled, and after some time saw a list of 1046 songs -- checked the top and bottom ones which correspond to the top and bottom tracks I see under "Liked Songs" in my Spotify app.

**Comment by gerardlouw** [comment]
Btw, the reason for creating a new "Library" resource type is because the existing resources in the node seems to follow the categories in the API docs exactly, where this specific API appears under the "Library API" category:
https://developer.spotify.com/documentation/web-api/reference/#category-library

**Comment by RicardoE105** [comment]
@gerardlouw just tested it, and it's working fine. However, you made some changes to the docker-images.yml and docker-images-nightly.yml files. Can you please revert those changes? Thanks very much for your contribution.

**Comment by gerardlouw** [comment]
@RicardoE105 Thanks for the feedback, and sorry about that! I've removed the Docker commits. I'm a bit of a GItHub noob and I didn't realise that further pushes to my fork would automatically update the PR. Next time I'll use a feature branch.

**Comment by gerardlouw** [comment]
Hi @RicardoE105, thanks again for your earlier review. Is there anything else you think needs to changed? Given that I'm new to open source contributions on GitHub, I'm not sure what the next step is here.

**Comment by janober** [comment]
Thanks a lot. Got merged with #1550

**Comment by janober** [comment]
Got released with n8n@0.113.0

**Pull request closed without merging**
