### PR TITLE
feat: Expose license feature flags for free AI credits feature to frontend (no-changelog)

### PR DESCRIPTION
**Pull request by RicardoE105**
## Summary

Builds on top of https://github.com/n8n-io/n8n/pull/12362

- Expose license feature flags to the FE.
- Add new endpoint to the `ai.api.ts` file.
- Add experiment for the feature
- Make available `userClaimedAiCredits` in FE.

This is the ground work to be able to address -> https://linear.app/n8n/issue/ADO-2994/[n8n-fe]-add-cta-to-generate-the-credits-in-the-users-instance

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/ADO-2994/[n8n-fe]-add-cta-to-generate-the-credits-in-the-users-instance

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Review by mutdmour — DISMISSED** [review]

**Review by mutdmour — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.74.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.1)

**Comment by janober** [comment]
Got released with [`n8n@1.74.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.1)

**Comment by janober** [comment]
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)

**Comment by janober** [comment]
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)

**Pull request merged**
