### PR TITLE
feat(editor): Logs markdown block improvements

### PR DESCRIPTION
**Pull request by burivuhster**
## Summary

* Fix raw text showing as a markdown code block
* Enable syntax highlighting for markdown code blocks in logs

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/AI-325/improve-markdown-rendering-in-the-ai-log-view-add-code-highlight

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Comment by OlegIvaniv** [comment]
@burivuhster Looks so much better! One thing I noticed — there's still weird highlighting happening for nested `code` elements. Could we get rid of that?

https://github.com/user-attachments/assets/fd311d19-b9aa-4382-900c-aa74a32ab0cc

**Comment by burivuhster** [comment]
image
I copied the background color from the left chat panel. What do you think?

**Review by OlegIvaniv — APPROVED** [review]
Nice!

**Comment by Joffcom** [comment]
Got released with [`n8n@1.59.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.59.0)

**Pull request merged**
