### PR TITLE
fix(core): Remove HTTP body for GET, HEAD, and OPTIONS requests

### LINKED ISSUE #3620: n8n sending invalid GET requests
**Describe the bug**
n8n's axios library appears to send invalid GET requests with an HTTP body. While most services accept this, intermediate proxies often reject them. I have confirmed this occurs with both Github and Clockify nodes.

**To Reproduce**
1. Configure http_proxy and https_proxy environment variables to use an http proxy
1. Add a Github or Clockify node, potentially others
1. Configure a resource and operation that makes a GET request
    * Github: Resource: User, Operation: Get Repositories
    * Clockify: Resource: Workspace, Operation: Get all
1. Send the request
1. See error

Packet capture showing empty body with GET request:
SCR-20220630-ev4-2

Squid proxy error:
SCR-20220630-eu2

**Expected behavior**
GET requests should not have request bodies. Although not strictly prohibited by the spec, a GET body has no semantic meaning. Similar to Python `requests` library a GET request with a body should be considered invalid.
```
>>> requests.get(url='http://ipinfo.io', body='')
TypeError: request() got an unexpected keyword argument 'body'
```

**Environment (please complete the following information):**
 - OS: MacOS 12 & Docker Alpine
 - n8n Version: 0.184.0
 - Node.js Version: v16.15.1
 - Database system: SQLite & PostgreSQL
 - Operation mode: own & queue

**Additional context**
None

### PR DESCRIPTION
**Pull request by pemontto**
This PR fixes #3620.

Remove the request body if we're sending a `GET`, `HEAD`, `OPTIONS` or `TRACE` request. This should fix the bulk of these issues, however there maybe other helper functions that could be impacted by this 🐛.

Based on the `Request has body` property as defined here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods

_This likely wouldn't have been noticed if axios actually used the `CONNECT` method with http proxies_

### CODE REVIEW

**Comment by pemontto** [comment]
Have just noticed the helpers that used `convertN8nRequestToAxios` wouldn't have seen this problem due to these lines which calls out the exact same issue https://github.com/n8n-io/n8n/blob/86b3cc6e15e6bc4cea1ecae223bfaded1875127d/packages/core/src/NodeExecuteFunctions.ts#L717-L720

**Comment by pemontto** [comment]
Still seeing this issue on GET requests, also occurs for the Gitlab node... and probably many other nodes.

**Comment by pemontto** [comment]
Re. Axios `CONNECT` method:
- https://github.com/axios/axios/issues/4531
- https://github.com/axios/axios/issues/3384

**Comment by netroy** [comment]
Since we don't support `TRACE` (and doesn't seem like anyone else does), I'll remove it.

**Review by netroy — APPROVED** [review]
🎉

**Comment by janober** [comment]
Got released with [`n8n@1.34.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.34.0)

**Pull request merged**
