### PR TITLE
Add bcc field to EmailSend

### PR DESCRIPTION
**Pull request by neumann-d**
similar to cc field

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot @neumann-d! It just got merged and will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.55.0

**Comment by neumann-d** [comment]
Seems not included in current release, does it?

**Comment by janober** [comment]
Uh yes, it seems like I did not change the version number.

Please pull the latest docker image or use 0.55.1

**Pull request merged**
