### PR TITLE
fix(core): Improve axios error handling in nodes

### PR DESCRIPTION
**Pull request by agobrech**

### CODE REVIEW

**Review by netroy — DISMISSED** [review]
Once [workflow tests](https://github.com/n8n-io/n8n/actions/runs/4449654104/jobs/7814130967) pass, we can merge this 👍🏽

**Review by netroy — APPROVED** [review]
Code looks good to me.
If you can some unit tests for the new lines of code, that'd be great.

**Comment by janober** [comment]
Got released with [`n8n@0.222.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.222.0)

**Comment by janober** [comment]
Got reverted as it change the response for errors which caused multiple issues.

**Pull request merged**
