### PR TITLE
✨ add some not conditions to the if node

### PR DESCRIPTION
**Pull request by lublak**

### CODE REVIEW

**Comment by lublak** [comment]
@janober Is it desired that I split this pull request?
Currently I have also added the missing regex flags u and s in the switch node in this pull request, as they are already present in the if node.

**Comment by Joffcom** [comment]
Hey @lublak,

Normally it would be better to have them as 2 different requests, Out of interest when would you use a Not condition is it more for readability / ease of use instead of following the false output on an If for say a regex match.

**Comment by lublak** [comment]
@Joffcom It would be more readable and also if you want to work with multiple conditions. Something like should start with 'Foo' and not end with 'Bar'.

**Comment by Joffcom** [comment]
Hey @lublak,

That sounds fair, I will move it into my review queue and get back to you.

**Comment by janober** [comment]
Thanks a lot. Got merged with #2930

**Pull request closed without merging**
