### PR TITLE
ci: Ensure that eslint runs on all frontend code (no-changelog)

### PR DESCRIPTION
**Pull request by netroy**
also, 
* remove tslint from `design-system`
* setup prettier for `design-system`

### CODE REVIEW

**Review by ivov — COMMENTED** [review]
1. Let's remove `/design-system/tslint.json`?

2. `design-system/.editorconfig` still needed?

3. Should we lint the contents of `.storybook`?

4. `prettier **/**.{ts,vue} --write` Let's format all others as well? css, scss, js, md, mdx

5. `Button.stories.ts` still contains a TSLint exception.

6. These only trigger one issue each. Let's fix and remove from the list?
- `@typescript-eslint/ban-ts-comment`
- `@typescript-eslint/restrict-template-expressions`
- `@typescript-eslint/no-unused-vars`

7. `@typescript-eslint/member-delimiter-style` triggers no issues. Let's remove from the list.

8. `@typescript-eslint/naming-convention` triggers 220 issues. design-system might need its own options for this rule.

9. `import/no-extraneous-dependencies` triggers 80+ issues but seemingly easy to fix by moving a handful of deps to their right categories. Please disregard if time-consuming.

10. For any remaining rules that are `off`, let's set to `warn`?

**Comment by netroy** [comment]
> 1. Let's remove `/design-system/tslint.json`?

✅ 

>     2. `design-system/.editorconfig` still needed?

✅ 

>     3. Should we lint the contents of `.storybook`?

✅ 

>     4. `prettier **/**.{ts,vue} --write` Let's format all others as well? css, scss, js, md, mdx

✅ , but skipped `.md` files

>     5. `Button.stories.ts` still contains a TSLint exception.

✅ 

>     6. These only trigger one issue each. Let's fix and remove from the list?
>     * `@typescript-eslint/ban-ts-comment`
>     * `@typescript-eslint/restrict-template-expressions`
>     * `@typescript-eslint/no-unused-vars`

✅ 


>     7. `@typescript-eslint/member-delimiter-style` triggers no issues. Let's remove from the list.

✅ 

>     8. `@typescript-eslint/naming-convention` triggers 220 issues. design-system might need its own options for this rule.

✅ 

>     9. `import/no-extraneous-dependencies` triggers 80+ issues but seemingly easy to fix by moving a handful of deps to their right categories. Please disregard if time-consuming.

✅ 

>     10. For any remaining rules that are `off`, let's set to `warn`?

✅

**Comment by alexgrozav** [comment]
Took a look as well and looks good to me, but @ivov seems to have gone through a more thorough review on it. Will let you guys continue on this.

**Review by ivov — COMMENTED** [review]
Running `vitest run --coverage` and then formatting slows Prettier down to a crawl. We should add `coverage` to `.prettierignore`.

**Review by ivov — DISMISSED** [review]

**Comment by netroy** [comment]
> Running `vitest run --coverage` and then formatting slows Prettier down to a crawl. We should add `coverage` to `.prettierignore`.

Done.

Unfortunately `.prettierignore` [still doesn't merge rules](https://github.com/prettier/prettier/issues/4081) like `.gitignore`, `.npmignore`, and `.dockerignore` do 😞 .

**Review by ivov — APPROVED** [review]

**Comment by janober** [comment]
Got released with `n8n@0.203.0`

**Pull request merged**
