### PR TITLE
feat(Redis Node): Add support for continue on fail / error output branch

### LINKED ISSUE #8744: Continue (using error output) & Always Output Data logic missing in Redis Node
## When set to Continue (using error output)
It should be continuing on the error branch, instead it goes through the success branch with no data

Screenshot 2024-02-26 at 5 00 33 PM

## When set to Always Output Data
It should continue with error data but it just stops

Screenshot 2024-02-26 at 5 01 03 PM

## The Code
There is usually the logic for both of these operations in [this catch statement](https://github.com/n8n-io/n8n/blob/c0be43bdbed99c6bcceba662866667b8162dcf91/packages/nodes-base/nodes/Redis/Redis.node.ts#L628). Instead it is just throwing an error.

Screenshot 2024-02-26 at 5 04 37 PM

### Continue (using error output)
1. Add a Redis node that will cause an error
2. Set the redis node to _Continue (using error output)_
3. Run the workflow

You'll see it has an error and is continuing on the success branch with no data

   
### Always Output Data
1. Add a Redis node that will cause an error
2. Set the redis node to _Always Output Data_
3. Run the workflow

You'll see it does not output the data

### Expected behavior

Explained in bug description section.

### Operating System

Debian 12.5

### n8n Version

1.24.1

### Node.js Version

18+

### Database

SQLite (default)

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by Joffcom**
## Summary
This adds continue on fail support / error branch output, I had to move the `client.quit()` but in local testing it appears to be closing connections on fail, on continue, on normal end.

Current tests passed, Couldn't think of a way to improve them. During review it would be great if the reviewer could also make sure the clients are being closed in Redis and not kept open. 

## Related Linear tickets, Github issues, and Community forum posts
resolves #8744 
https://linear.app/n8n/issue/NODE-1177/redis-continue-on-fail-not-implemented

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Review by dana-gill — CHANGES_REQUESTED** [review]
Could you add a workflow or unit test for this please? :)

**Comment by dana-gill** [comment]
The other thing I noticed is that we're still returning an empty array for the `success` path. It seems a bit strange to me so could you explain if that's intentional, and if it is, why? :)

```
{
  "meta": {
    "instanceId": "ee90fdf8d57662f949e6c691dc07fa0fd2f66e1eee28ed82ef06658223e67255"
  },
  "nodes": [
    {
      "parameters": {
        "operation": "push",
        "list": "=string_key:2",
        "messageData": "=3"
      },
      "name": "Try to Error",
      "type": "n8n-nodes-base.redis",
      "typeVersion": 1,
      "position": [
        0,
        480
      ],
      "id": "d10532c9-ef10-4a1e-a3d1-65a0fc7201ac",
      "alwaysOutputData": true,
      "credentials": {
        "redis": {
          "id": "8c3UDUvvUFJ6aKyk",
          "name": "Redis account"
        }
      },
      "onError": "continueErrorOutput"
    }
  ],
  "connections": {},
  "pinData": {}
}
```

**Comment by Joffcom** [comment]
@dana-gill for the empty success it looks like Redis doesn't return errors for some things which is exciting. I will look at creating some errors for some of the empty results.

**Review by dana-gill — APPROVED** [review]
Let's merge this for now and create a follow up ticket to deal with tests and the success outputting on error in the future :)

**Comment by janober** [comment]
Got released with [`n8n@1.72.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.72.0)

**Pull request merged**
