### PR TITLE
:bug: Fixing nodes-base some nodes Network api call request Error.

### PR DESCRIPTION
**Pull request by saurabharch**

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @saurabharch,

There is a lot going on here, What are you actually changing? It looks like it is some formatting changes, image optimization and introducing a new library to check if the server is online?

**Comment by saurabharch** [comment]
n8n node check first system is connected with public IP or it has Internet connectivity, before requesting to the SaaS, IaaP, DaaS and etc service like which are third-party services, it makes base-node resilient and working.

**Comment by Susangriffis** [comment]
Public 


Sent from Yahoo Mail for iPhone


On Thursday, March 24, 2022, 08:23, saurabh kashyap ***@***.***> wrote:




n8n node check first system is connected with public IP or it has Internet connectivity, before requesting to the SaaS, IaaP, DaaS and etc service like which are third-party services, it makes base-node resilient and working.

**Comment by saurabharch** [comment]
> @saurabharch what about the other changes?
> 
> I will need to have a chat with the team internally as this includes another package. I like the idea of what it does but I am not sure if it actually solves a problem, Do you see any issues when using n8n with no internet connection at the moment?

I will update the other changes in nodes as soon as possible, yes I saw a when a node sends a fetch request to another remote server API or any third-party service which is not locally addressed it shows falsely show request is sent with status, ok but, this is a cause of using a bull.js in the CLI command for workflow automation which uses Redis as a pub-sub message broker for event-driven functions node function flag are not satisfied with proper error handling an event call.

**Comment by Joffcom** [comment]
Hey @saurabharch,

Just to double check do you only see the successful node runs when using n8n in queue mode? I would have expected the nodes to still fail unless the Continue on fail setting is checked.

**Comment by Joffcom** [comment]
Hey @saurabharch,

I was just about to check for any updates on this based on my last comment and I noticed you have changed the docker nightly image to use `saurabharch/n8n` this is not a change we would be able to merge in so it would need to be reverted or a new PR using a different branch.

**Comment by Joffcom** [comment]
@saurabharch you have 2 PRs now are they both the same thing? Is it worth closing this one and focusing on the other one?

**Comment by saurabharch** [comment]
> @saurabharch you have 2 PRs now are they both the same thing? Is it worth closing this one and focusing on the other one?



> a51ae53

close both [96ac0d3](https://github.com/n8n-io/n8n/commit/96ac0d39c7d9598449f755dbbf008ec3057b0389) and [44af195](https://github.com/n8n-io/n8n/commit/44af195279bb4ace27b2ef6a006032a0175466be) of these docker nightly build PR

**Comment by Joffcom** [comment]
@saurabharch they look to be commits rather than PRs. You have this one and #3160, I have been having a chat with the team internally though and as we still can't see what actual problem this is solving with the extra library it makes it tricky to review.

We think if there is a problem in queue mode when there is no internet connection it would be better solved in core than on a node level so it could be that we reject this PR unless we can get a way to reproduce the problem you are seeing.

**Comment by Joffcom** [comment]
Hey @saurabharch,

I am going to close this one for now as there are still some outstanding questions and there is another PR opened that seems to be the same thing.

Let me know if you have any questions.

**Pull request closed without merging**
