### PR TITLE
feat: Add tags operations and filter workflows by name in Public API

### PR DESCRIPTION
**Pull request by jburgers-chakray**
Hello,

This is the first time I contribute, so sorry in advance if I'm doing something wrong.

This pull request includes the following changes to de Public API:

Add an operation to list all the tags with pagination
Add an operation to get a tag by its ID
Add an operation to create a tag
Add an operation to update (the name) of a tag
Add an operation to delete a tag
Add an operation to get the tags of a workflow
Add an operation to update the tags of a workflow
Modify the getWorkflows operation to add the possibility of filtering by name

Thanks!

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @jburgers-chakray,

Thanks for the PR, I have created an internal ticket for the review which we will be tracking as `PAY-580`

**Comment by jburgers-chakray** [comment]
Hi @Joffcom,

Thanks, I have just updated the PR with the last changes in master. Like the migration of the integer primary keys to nanoids

**Comment by Joffcom** [comment]
Hey @jburgers-chakray,

We appreciate the effort you've put into this. However, we now requite that core changes are accompanied by sufficient tests to ensure their reliability and maintain the quality of our codebase.

Currently, this PR doesn't include any tests and I know we also have not introduced a lot of tests for this area yet. We understand that writing tests might not be everyone's area of expertise or interest. If you are willing and able to add tests, we can look at reviewing this again. Otherwise, we, unfortunately, won't be able to merge this component into the main branch at this time.

For now I am going to mark this as closed and we can always open it again in the future if needed, Let me know if you have any questions about this.

**Comment by jburgers-chakray** [comment]
Hello @Joffcom ,

I added tests when I added the new resources to the API:

- https://github.com/n8n-io/n8n/pull/6332/files#diff-b180f5d8eba23d94a1ad081e296492a2732d249c7aae33de86d07f46b1d4a803
- https://github.com/n8n-io/n8n/pull/6332/files#diff-86727ecf35047a69e8005acdf616b13f4a52a42b8f318e3715bdcc1db2139f49

Do I need to add more tests?

Thanks!

**Pull request closed without merging**
