### PR TITLE
Clockify Trigger Node

### PR DESCRIPTION
**Pull request by spam-n-eggs**
Clockify Basic Trigger Node that listens for time entry events.

### CODE REVIEW

**Comment by janober** [comment]
Great, thanks a lot got merged.

Made some changes:
- Fixed some formatting issues
- Added "polling: true" that polling times can be selected
- Made sure that user does not have to get requested with every poll request
- Fixed issue that it also works if the timezone is not UTC (their API is very strange in the way they expect the time as they expect the users local time but return UTC. So the workflow timezone must be identical to the timezone that is set in Clockify. If not it will not trigger in time.)

**Comment by spam-n-eggs** [comment]
@janober Thanks for reviewing, and thanks for catching the issue about Timezones - I have more enhancements to this in the works.

**Comment by janober** [comment]
Great! Looking forward to it!

**Comment by janober** [comment]
Got released with n8n@0.54.0

**Pull request merged**
