### PR TITLE
Upgrade mongodb client and allow conn string overrides

### PR DESCRIPTION
**Pull request by clonardo**
- Updated mongoDB client lib (old version does not support Mongo 4.2)
- Allow manual override of connection string for mongoDB node (if an override switch is set to true) -- this was making it impossible to connect to many server configurations
- Refactor utility functions and node description out of mongoDB node to improve readability and flexibility
- Added `clean:dist` script to clear out the `./dist` folder in each package
- Fixed a typo in console logging ("cought" -> "caught")

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot @clonardo !

Looks generally great (have to check it later properly) the following two formatting changes should, however, be reverted:
 - package.json got changed to tabs (everywhere tabs is correct except there, as npm seems to use spaces by default)
 - the files got changed to use double quotes instead of single quotes

**Comment by clonardo** [comment]
Hi @janober - I think that my local dev environment (which is VSCode with a global Prettier config needed for other projects) had a formatting rule conflict- I have updated the `.editorconfig` to be more explicit, and now automatic formatting works as it should- hopefully that's an acceptable solution, though I don't see any downside.

I'm new to contributing to this project (and very interested), so I haven't seen mention of a live chat for contributors (the forum is helpful, but real-time feedback seems to help a lot of other projects- whether on Gitter, Telegram, or Slack).  I've set up a Telegram group at [t.me/n8n_dev](url) - currently just me and a bot that could be useful down the road, but it might be a good way to keep momentum going.

**Comment by janober** [comment]
Thanks a lot for changing it and updating the ".editorconfig"!

Have to check it out the next days. But having had another short look I am not sure if that is the best idea with the overwrite. It would mean that the credentials are saved unencrypted in the workflow and that is something I tried very very hard to avoid. So is possible that I have to take that out.

Very great to hear that you are interested in contributing. We are always happy if new people join!

About the live-chat. I did not create one on purpose.
Initially, it always sounds like a great idea to have one but in my opinion, it is sadly not. With a forum like right now, people go there, check if the question they have got answered already and (normally) only if not, they ask. This answer is then saved "forever" and does not have to get answered again in 90% of the cases.
As soon as a live-chat exists that is sadly different. People simply go directly there, ask their question (normally one which got already answered 10x before) and leave. Till a new user comes which asks the same question again (as there is normally not a great search option and even if, people would not use it anyway).
This is very inefficient and costs the team a lot of time as it gets "interrupted" constantly and can so not work on bug-fixes, new features, ..., because of it.
For that reason did I only create the forum as I thought it is in the interest of everybody. It is great for the users, as over time almost all questions have been answered already (and people get their answer so way faster than in any live-chat) and also makes sure that bug-fixes and features get released asap as the team has more time. It is also great for the developers as they have more time pushing the project forward and answer the "new" question in the forum. Hope that makes sense.

**Comment by clonardo** [comment]
I've had some time to dig into the credentials API a little further, and I think that it would make sense to move the conn string override into the MongoDb.credentials to avoid exposing secrets. Does that make more sense? I can implement it today or tomorrow.

I am seeing some limitations in terms of validating acceptable values for forms (credentials + node props)- e.g., if I want to validate a given input based on another's value, is there a way to do that? Have you looked into tools like [Yup](https://www.npmjs.com/package/yup)?

Fair points on chat, I suppose it can go either way.

**Comment by clonardo** [comment]
Updated and moved the connection string override into credentials. Also extracted out some of the credential validation/parsing, and added basic credential typings.

One thing I noticed: although `ICredentialType` includes `properties: INodeProperties[];`, it does not appear that the UI is respecting the `displayOptions` field of `INodeProperties` on credentials. So, I was not able to have conditionally-displayed fields in the credentials UI (the same syntax was working in the node parameters UI). Not sure if I am missing something, but will revisit that.

**Comment by janober** [comment]
Thank you very much @clonardo ! Got now merged.

Sorry took longer as I still had to think about how I would like to have it work. I was not a big fan of displaying it as an additional overwrite. It felt kind of strange having all the options and then underneath overwriting almost all of them again. It would be confusing for users. Changed it now that the user can select if they want to set it via values or connection-string and depending on that it displays only the required values. For that also additional changes to the editor-ui were needed. For that reason, it would not have been possible for you to do it that way before.

Will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.66.0

**Pull request merged**
