### PR TITLE
Added Keep-Alive option to HTTP Request node

### PR DESCRIPTION
**Pull request by rcnavas**
Added option in HTTP Request node to enable/disable keep-alive.
The default is false.

### CODE REVIEW

**Comment by michael-radency** [comment]
Hello @rcnavas  thank you for your contribution, can you please provide insights of how to test keepAlive functionality and example of workflow where it is used?

**Comment by nivb06** [comment]
Hi @rcnavas, thanks for your contribution!
I'm closing this one for now as we couldn't find a use case to test the functionality added.
Feel free to reopen it once you have an answer for @michael-radency question from the previous comment
Thanks, n8nteam

**Comment by rcnavas** [comment]
Here is an issue that is likely solved with `Keep-Alive` option in this pull request: https://github.com/n8n-io/n8n/issues/3376

**Comment by michael-radency** [comment]
Hello @rcnavas can you achieve desired behavior by passing `forever: true` in option without modifying  agent directly? more [here](https://www.npmjs.com/package/request)
image

**Comment by rcnavas** [comment]
> Hello @rcnavas can you achieve desired behavior by passing `forever: true` in option without modifying agent directly? more [here](https://www.npmjs.com/package/request)
> image

Would this work with Axios?

**Pull request closed without merging**
