### PR TITLE
Add Discord Webhook node

### PR DESCRIPTION
**Pull request by NeOMakinG**
Creating this here so someone won't start to work on this and waste time !

Finishing it in the next days

### CODE REVIEW

**Comment by janober** [comment]
Great thanks! Looking forward to the node to be finished!

Yesm is a good idea to show that you are working on it like that!

**Comment by NeOMakinG** [comment]
@janober How would you handle throttling request on this ? 

Discord is limiting the requests from every endpoint, the node is of course failing if a lot of requests are sent in a while :'(

**Comment by janober** [comment]
Uh sorry, there is currently no global code to handle rate limiting in nodes. You would sadly have to code that yourself.

**Comment by NeOMakinG** [comment]
That should be fine now, let me know if something is wrong !

It can be implemented like that, but considering the fact that maybe the complete Discord API will be implemented later, I should maybe rename the node to "Discord" and refactor it without using credentials for the webhook url, then if someone wants to implement the whole API, it won't create any legacy issues !

What do you think about it ?

**Comment by janober** [comment]
Great, thanks a lot! I will try to check it asap.

Just one first comment. Renaming it later is not that easy as it would mean a breaking change. If the node does get renamed it would break it for everybody which started using it. So the node should already be named "Discord" now and should work in a way that it can be extended later to add the other API functionality.

**Comment by NeOMakinG** [comment]
Then don't accept this PR, I need to refactor it a bit to avoid extending issues, gonna work on it in the next days

Good night

**Comment by janober** [comment]
Ah ok. Good to know. Thanks a lot! Wish also you a good night!

**Comment by NeOMakinG** [comment]
That should be fine now :)

**Comment by NeOMakinG** [comment]
Noticed that there was a HTTP Request node that can do the exact same job, I think that build the base for someone who wants to implement the complete Discord API, but my job is a bit useless :P

**Comment by janober** [comment]
I had now a quick look. Sadly looks like some things are missing. When I look at their API here:
https://discordapp.com/developers/docs/resources/channel#create-message

It says to use the endpoint `/channels/{channel.id}/messages` can however not see it anywhere in the code. Is that supposed to be part of the Webhook-URL? If so, the node would not be extendable and could only do only one thing which is sending a message.
The base-URL and the endpoints should be separate.  So also the channel-id. It should be configurable via a parameter best loaded automatically so that the user can select the channel-name and does not have to look up the ID (but that is not that important and can also be added later). Similar what can be done in the Asana -Node:
https://github.com/n8n-io/n8n/blob/549a30c267c0c61923792174b5451edd600ef603/packages/nodes-base/nodes/Asana/Asana.node.ts#L438

Also did I not see any code for the authentication. How does that work? Is that also part of the webhook URL? If so it should be saved separately as a credential. Else that data would get saved in the workflow and would so be saved as clear-text in the database.

**Comment by NeOMakinG** [comment]
Hey @janober 

It's not linked with the Discord API, using webhooks doesn't force you to create a discord developer bot/account, you can create webhooks by going into the channel settings and that webhook can be used  to send message to this specific channel !

That's why I refactored this node in a way you can choose between "webhooks" and lately maybe Discord API, because you don't wan't to create a bot and use the complete discord API on every servers, it should be 2 features and there I worked on a node to use a Discord webhook !

**Comment by janober** [comment]
Ah great. If it turns out to be a problem in the future we can either increase it or make it configurable via a parameter.

**Comment by janober** [comment]
Got released with n8n@0.31.0

**Pull request merged**
