### PR TITLE
Allow ItemList to Extract a path from Object

### PR DESCRIPTION
**Pull request by luizeof**
Given a nested JavaScript object, the goal is to extract the object from a certain depth (path), without having to use the function node (a low-code form) and place it at the root:

For example, node Webhook always returns data like this:

image-a

If we only want to use the body, we have to use the node function (which is a problem for non-devs).

If using ItemList to extract the body, it actually throws an exception:

image-b

If we use Set, the result will put the items in a property (the goal is to put them at the root):

image-d

This pull request allows the ItemList to pull data from the given path from both arrays and objects by placing at the root (without a parent property):

image-c

### CODE REVIEW

**Comment by pemontto** [comment]
Is this not equivalent to using an expression `{{ $node["Webhook"].json["body"] }}`?

If this node did work for objects, I'd probably expect the keys to be split out into items, rather than returning a single item.

_Current output:_
```javascript
[
  {
    json: {
      item1: "1",
      item2: "2"
    }
  }
]
```

_Expected split output:_
```javascript
[
  {
    json: {
      item1: "1"
    }
  },
  {
    json: {
      item2: "2"
    }
  }
]
```

Or perhaps like this, which would make referencing items much easier without having to know what the `key` name is.
```javascript
[
  {
    json: {
      _key: "item1",
      _value: "1"
    }
  },
  {
    json: {
      _key: "item2",
      _value: "2"
    }
  }
]
```

**Comment by luizeof** [comment]
@pemontto is a way to extract properties from objects without using some snippet.

**Comment by pemontto** [comment]
@luizeof that expression can be created from the GUI.
n8n_-_▶️_My_workflow_2

However as this isn't splitting data, just extracting, this functionality might be better suited to the set node? That would require a PR to add the ability to operate on objects in addition to booleans, numbers, and strings.

**Comment by luizeof** [comment]
@pemontto Thanks for your time, I adjusted the description to be clear and objective.

**Comment by michael-radency** [comment]
Hello Luiz, I do working on improving itemLists node and because of changes your PR can not be merged, but I did add functionality based on it https://github.com/n8n-io/n8n/pull/2681

**Comment by nivb06** [comment]
Hi luizeof, thanks for your contribution!
We have decided to tackle this issue with the Item Lists node within a broader effort of improving this node
Closing this ticket for now
Thanks,
n8n-team

**Pull request closed without merging**
