### PR TITLE
fix(Bubble Node): Fix pagination issue when returning all objects

### PR DESCRIPTION
**Pull request by Joffcom**
Github issue / Community forum post (link here to close automatically): https://community.n8n.io/t/bubble-get-all-hanging-fails/23079

### CODE REVIEW

**Review by that-one-tom — APPROVED** [review]
Works fine, tested with 1, 2 and 3 results pages. Also working when there are 0 results.

**Comment by guillim** [comment]
I created the issue for the community here, adding the backlinks as well to this repo 
https://community.n8n.io/t/bubble-get-all-hanging-fails/23079

**Comment by that-one-tom** [comment]
> I created the issue for the community here, adding the backlinks as well to this repo https://community.n8n.io/t/bubble-get-all-hanging-fails/23079

Thanks for reaching out on the forum @guillim :)

You should get a notification on the forum automatically once this is resolved.

**Comment by guillim** [comment]
> > I created the issue for the community here, adding the backlinks as well to this repo https://community.n8n.io/t/bubble-get-all-hanging-fails/23079
> 
> Thanks for reaching out on the forum @guillim :)
> 
> You should get a notification on the forum automatically once this is resolved.

any timeline in mind ? i mean hours/days/weeks ? (our production notification tool is down right now)

**Comment by Joffcom** [comment]
Hey @guillim 

Will be merging today and it will be in the next release which will be this week.

For self hosted installs it will be available as soon as the release goes live for cloud it will take a bit longer.

If this is urgent for you a temporary solution would be to use the http request node and manually build out the request and loop.

**Comment by guillim** [comment]
how long from a github release to a cloud release on average ?

**Comment by janober** [comment]
Got released with `n8n@0.216.0`

**Comment by Joffcom** [comment]
@guillim it all depends on if any issues are found so it could be a few days or it could be a week.

**Pull request merged**
