### PR TITLE
Add additional parameters to Pipedrive getAll for Notes

### PR DESCRIPTION
**Pull request by zillarelli**
These are just a few of what's available. Before, there wasn't a parameter to specify which deal to retrieve notes from. This pull request adds parameters to allow filtering by Deal ID, Organization ID, and Person ID.

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot. Yes, it looks like the code is incomplete and we "forgot" to use the parameters.

Your code looks correct but it should probably be changed to use
```typescript
const additionalFields = this.getNodeParameter('additionalFields', i) as IDataObject;
addAdditionalFields(body, additionalFields);
```
like all the other methods to keep it consistent. Could you please adjust that. Thanks!

**Comment by Robarelli** [comment]
Thanks for the review! I did indeed try what you are suggesting, however it separated the additional fields into the body parameter  instead of the query string parameter, which the Pipedrive API endpoint didn't like or ignored for some reason. The only way I could get it to use the additional fields was to add them to qs.

**Comment by janober** [comment]
Ah yes, that makes a lot of sense. Did not see that it is a GET request. My mistake.

**Comment by Robarelli** [comment]
No problem. I'm sure that in the future it could be refactored a bit to add a function like addAdditionalFields but for query strings, which would make that part a bit cleaner.

**Comment by Robarelli** [comment]
I just realized that body and qs are both IDataObject, so I can use the same addAdditionalFields function but with the qs object instead of the body object.

**Comment by janober** [comment]
Great, thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.87.0

**Pull request merged**
