### PR TITLE
feat(Google Drive Node): Add Shared Drive support for operations download, delete and share

### PR DESCRIPTION
**Pull request by janober**
https://community.n8n.io/t/no-support-for-shared-drives-for-the-download-drive-node/12717
https://community.n8n.io/t/unable-to-download-file-via-google-drive-node/13926/3

### CODE REVIEW

**Comment by janober** [comment]
Got merged.

**Comment by janober** [comment]
Got released with `n8n@0.177.0`

**Comment by dominikmukrecki** [comment]
Greetings, it seems like a Google Drive Trigger node does not work with shared drives yet. Regards, Dominik.

**Comment by janober** [comment]
Please make sure to open a new issue for that @dominikmukrecki. As this now closed issue was about the Google Drive node (which got resolved) and yours is about the Google Drive Trigger node. For that reason, will this issue not be reopened and your 100% valid remark would probably get lost. Thanks!

**Comment by dominikmukrecki** [comment]
@janober thank you for the explanation, done :)

**Comment by dominikmukrecki** [comment]
https://github.com/n8n-io/n8n/issues/3358

**Pull request merged**
