### PR TITLE
update RundeckApi Credential

### PR DESCRIPTION
**Pull request by AndLLA**
this fix updates RunDeck Credential in order to support:
- testing 
- integration with the HTTP Request "Predefined Credential Type" mechanism

### CODE REVIEW

**Comment by janober** [comment]
Great, thanks a lot! Could you please also change that the node uses:
`this.helpers.requestWithAuthentication.call(this, credentialType, options)`
instead of
`await this.executeFunctions.helpers.request!(options)` [here](https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Rundeck/RundeckApi.ts#L36) and remove the headers. That makes sure that the node actually uses the authentication logic defined in the credentials instead of using its own logic. Else it could result in the test working fine but the node actually failing (as they do different things).

You can find an example [here](https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Ghost/GenericFunctions.ts#L46).

Thanks a lot!

**Comment by AndLLA** [comment]
hallo,
I added the requested fix, 
hope I got it right :)

Thanks !!!

**Comment by janober** [comment]
Thanks a lot. From a short look does it look correct. We will then do a proper review and merge soon. Have a great weekend!

**Comment by AndLLA** [comment]
Hi,
I updated the pull request, resolving a small conflict vs to the trunk.

**Comment by janober** [comment]
Thanks a lot for your contribution @AndLLA. Got merged and will be released with the next version.

**Comment by janober** [comment]
Got released with `n8n@0.199.0`

**Pull request merged**
