### PR TITLE
feat(core): Manage version control settings

### PR DESCRIPTION
**Pull request by flipswitchingmonkey**

### CODE REVIEW

**Review by krynble — APPROVED** [review]
LGTM

**Comment by krynble** [comment]
I'm not sure if you're planning on doing this now, but it'd be great to add tests for those endpoints

**Comment by flipswitchingmonkey** [comment]
> I'm not sure if you're planning on doing this now, but it'd be great to add tests for those endpoints

not forgotten, but will be part of a future pr

**Comment by janober** [comment]
Got released with [`n8n@0.226.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.226.1)

**Pull request merged**
