### PR TITLE
Add support for custom aws endpoints

### PR DESCRIPTION
**Pull request by janober**

### CODE REVIEW

**Comment by krynble** [comment]
This pull request is based on @Lngramos changes on PR #1271 

It adds the possibility to add customized endpoints for AWS services. 

These changes also help solve the problem reported by community member liushengyi here: https://community.n8n.io/t/aws-lambda-problems/3118

**Comment by Lngramos** [comment]
Thanks a lot, @krynble!

@janober had made a comment about hiding these options by default, I made an attempt at this but encountered a few challenges along the way. See my reply in the original PR: https://github.com/n8n-io/n8n/pull/1271#issuecomment-750939019

Any thoughts on how we can support that if a hard blocker to getting this merged in?

**Comment by janober** [comment]
Thanks a lot got merged!

@Lngramos Thanks. We added now a simple boolean parameter called "Custom Endpoints". By default it is `false` and so all are hidden and if it gets set to`true` all of them get displayed. That should be good enough.

**Comment by janober** [comment]
Got released with n8n@0.101.0

**Comment by Lngramos** [comment]
Thanks both, @janober and @krynble for getting this added in quickly. :raised_hands:

**Pull request merged**
