### PR TITLE
Enhancements and cleanup for MS Teams node

### PR DESCRIPTION
**Pull request by Goggin**
- Add option to limit groups to "member of" rather than whole directory
  - Defaults to "all" for compatibility
- Add option to Get All tasks to pull from a plan instead of just a group member
  - Defaults to "member" for compatibility
- Added in auto completion for plans, buckets, labels and members in update fields for tasks
- Update descriptions and normalize quotes for descriptions and display names

### CODE REVIEW

**Comment by Goggin** [comment]
@Joffcom  How do I go about getting a review done?  Should I also make a post on the community re: this PR?

**Comment by Joffcom** [comment]
Morning @Goggin,

We are still running through a few of the older node improvement PRs, I can see this one is on our internal review board it has a few others before it but we will get to it 👍🏻

**Comment by Goggin** [comment]
> Morning @Goggin,
> 
> We are still running through a few of the older node improvement PRs, I can see this one is on our internal review board it has a few others before it but we will get to it 👍🏻

Thanks for letting me know 👍

**Comment by janober** [comment]
Got released with `n8n@0.174.0`

**Pull request merged**
