### PR TITLE
fix(core): Resolve domains to IPv4 first

### PR DESCRIPTION
**Pull request by netroy**

### CODE REVIEW

**Review by Joffcom — APPROVED** [review]
I can't see this breaking anything

**Comment by luizeof** [comment]
This will solve a lot of problems we face with some VPS providers, thank you very much.

**Comment by DerEnderKeks** [comment]
Please revert this change. It disgusts me to see something like this being implemented. RFC 8305 exists for a reason.
People should fix their IPv6 setups and software should never be bent backwards to use legacy IPv4 over IPv6. If a domain has v6 records, they should always be preferred. Things like this are the reason why IPv6 isn't as dominantly used by now as it should be. If you keep it like this, you are part of the problem.

If you really feel like having this anti-feature, it should be an optional config option and certainly not a forced default.

**Comment by janober** [comment]
Got released with [`n8n@1.8.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.8.1)

**Comment by netroy** [comment]
> It disgusts me to see something like this being implemented

@DerEnderKeks When communicating with other people, **language matters**. Please read our [code of conduct](https://github.com/n8n-io/n8n/blob/master/CODE_OF_CONDUCT.md) and adhere to it, **to avoid getting blocked**.
In general, be kind to other, and give others a change to fix an issue before starting with the outrage.

**Comment by netroy** [comment]
@MeesJ sorry for the inconvenience. This will be fixed in https://github.com/n8n-io/n8n/pull/7272, and should hopefully go out in today's release.

**Comment by DerEnderKeks** [comment]
@netroy While my remark may have been inappropriate, it wasn't personal. Either way, I'm sorry, and thanks for making it configurable!

**Pull request merged**
