### PR TITLE
U proc integration

### PR DESCRIPTION
**Pull request by RicardoE105**
Small improvements to #795

### CODE REVIEW

**Comment by RicardoE105** [comment]
@mcolomer ok it seems to be working as expected. Will move this to internal review, after that it will be merged. (should not take as long as this first review). Just one small request. Can you please change the tool name to camelCase instead of what it's right now as all the other nodes use camelCase for the subtitle? for example get-company-by-ip should be getCompanyById.

**Comment by mcolomer** [comment]
Hi @RicardoE105 ,

We have updated branch #795 with your recommendations.

**Comment by RicardoE105** [comment]
Hey @mcolomer, just reviewed the node, and everything seems to be working as expected except for the names that should be camelCase. For example, check-email-exists-extended should be checkEmailExistsExtended. The name property is going to be rendered below the node when displayed on the UI. After this is fixed we should be ready to go.
 
image

```
{
         displayName: 'Check Email Exists' (extended),
         name: 'checkEmailExistExtended'
}
```

Make sure the changes are made on top of this PR. Thanks.

**Comment by mcolomer** [comment]
Hi @RicardoE105 ,

I think we are looking different PR. Is it possible?
I am currently pushing changes to branch uProc_integration and the tool looks this way:

image

I am checking last commit to this PR (#795) at https://github.com/n8n-io/n8n/pull/795/commits/02d1a42975c5603034fd319ccd88bcd3c20f4ef1 

If I check packages/nodes-base/nodes/UProc/json/tools.ts I get this
image

Tool names (k property) seems ok.

Could you check which PR do you have locally?

**Comment by RicardoE105** [comment]
@mcolomer sorry for the late response. Yeah, that is why I mentioned making sure the changes are made on top of my changes. We were testing different PR but even though the PR you were testing is still not working as expected. In the example, you showed me the `Check Email Exists Extended` should read like `checkEmailExistsExtended`. Let me know if something is not clear enough. Thanks.

**Comment by mcolomer** [comment]
Hi @RicardoE105 ,

I am not sure how to get your PR (#954) and merge with my PR (#795).
Trying this doesn't work for me.
`git merge origin/uProc_integration`

I have uploaded changes to #795 . Please check it if this makes the difference for you.
Now, display name appears this way
image

**Comment by janober** [comment]
Thanks a lot. Got merged with #1263

**Comment by janober** [comment]
Got released with n8n@0.99.0

**Pull request closed without merging**
