### PR TITLE
fix(Strapi Node): Fix issue with pagination

### LINKED ISSUE #5007: Strapi Return All functionality does not return all entries
**Describe the bug**
With the latest available n8n version, Strapi node Return All functionality does not return all entries.

Captura de pantalla 2022-12-21 a las 12 39 58

Internally, parameters for pagination are being used as pagination by offset, instead of pagination by page.
Page should start by 1, and should be incremented by 1 in every step, instead of incrementing it by pageSize (which causes in the second iteration to search for items in page 20).
See https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/sort-pagination.html#pagination-by-page for further details.

For an Strapi entity that has 44 entries:

Before changes:
Captura de pantalla 2022-12-21 a las 12 43 21

After changes:
Captura de pantalla 2022-12-21 a las 12 39 23

### PR DESCRIPTION
**Pull request by adrian-martinez-vdshop**
This PR fixes pagination issue when using the `Return all` flag. Fixes https://github.com/n8n-io/n8n/issues/5007.

Captura de pantalla 2022-12-21 a las 12 39 58

Internally, parameters for pagination are being used as pagination by offset, instead of pagination by page.
Page should start by 1, and should be incremented by 1 in every step, instead of incrementing it by pageSize (which causes in the second iteration to search for items in page 20).
See https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/sort-pagination.html#pagination-by-page for further details.

For an Strapi entity that has 44 entries:

Before changes:
Captura de pantalla 2022-12-21 a las 12 43 21

After changes:
Captura de pantalla 2022-12-21 a las 12 39 23

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @adrian-martinez-vdshop,

Thanks for the PR, Do you know if this change will prevent earlier Strapi V4 calls from working properly?

**Comment by adrian-martinez-vdshop** [comment]
@Joffcom It's fully backwards compatible, it does not change anything about the api url or params construction, only how page param values are calculated through iterations.

**Comment by adrian-martinez-vdshop** [comment]
Also, as it is contained within strapiApiRequestAllItems function, changes only applies to Return All functionality, which is broken at the moment (unless you have 20 entries or less in Strapi for the requested api).

**Comment by Joffcom** [comment]
Hey @adrian-martinez-vdshop,

Perfect, I shall give it a test soon on earlier versions of 4 and 3 just to be safe but it looks good so far.

**Comment by adrian-martinez-vdshop** [comment]
I forgot to mention that functionality is broken only for api v4. Changes are enclosed into a `if (apiVersion === 'v4') {` statement, so they should not affect api v3, which uses [pagination by offset](https://docs.strapi.io/developer-docs/latest/developer-resources/database-apis-reference/rest/sort-pagination.html#pagination-by-offset) instead.

It looks like when api v4 support was added, api v3 code was taken as the base, pagination was switched from offset to page, but numeric parameters were forgotten to be adapted properly.

**Comment by adrian-martinez-vdshop** [comment]
Any news on this one?

**Comment by Joffcom** [comment]
Hey @adrian-martinez-vdshop

Looks like I forgot to approve and hit the merge on it, I will get it done for the release next week.

**Comment by Joffcom** [comment]
`NODE-548`

**Review by Joffcom — APPROVED** [review]

**Review by Joffcom — APPROVED** [review]

**Comment by Joffcom** [comment]
Hey @adrian-martinez-vdshop,

Sorry for the delay on this one, This has now been merged and will be available in the next release.

**Comment by janober** [comment]
Got released with [`n8n@0.234.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.234.1)

**Pull request merged**
