### PR TITLE
Update GraphQL.node.ts

### LINKED ISSUE #1182: The GraphQL node's variables don't work
**Describe the bug**
This does not work; no variables are sent:

```
    {
      "parameters": {
        "values": {
          "string": [
            {
              "name": "data.id",
              "value": "appoint_treasury"
            },
            {
              "name": "data.schema",
              "value": "la_14396134"
            },
            {
              "name": "data.status.setup_state",
              "value": "pending"
            }
          ]
        },
        "options": {
          "dotNotation": true
        }
      },
      "name": "Set",
      "type": "n8n-nodes-base.set",
      "typeVersion": 1,
      "position": [
        430,
        1540
      ]
    },
    {
      "parameters": {
        "endpoint": "http://localhost:8080/v1/graphql",
        "requestFormat": "json",
        "query": "mutation Example($o: fivetran_connectors_insert_input!) {\n  insert_fivetran_connectors_one(\n    object: $o, \n    on_conflict: {\n      constraint: connectors_pkey,\n      update_columns: [setup_state, data]\n    }) {\n    id\n  }\n}\n",
        "variables": "={\n  \"o\": {\n    \"data\": \"{{JSON.stringify($json[\"data\"])}}\"\n    \"setup_state\": {{$json[\"data\"][\"status\"][\"setup_state\"]}},\n    \"remote_id\": {{$json[\"data\"][\"id\"]}}\n  }\n}",
        "operationName": "UpsertFivetranConnector",
        "headerParametersUi": {
          "parameter": [
            {
              "name": "x-hasura-admin-secret",
              "value": "={{ $env.LOGARY_M2M_HASURA_ADMIN_SECRET }}"
            }
          ]
        }
      },
      "name": "Insert Connector TEST",
      "type": "n8n-nodes-base.graphql",
      "typeVersion": 1,
      "position": [
        650,
        1540
      ]
    }
```

**Expected behavior**
Either an error message visible or the actual functionality.

### PR DESCRIPTION
**Pull request by haf**
Fix #1182 

image

Ref https://community.n8n.io/t/graphql-node-not-passing-variables/3069

### CODE REVIEW

**Comment by haf** [comment]
At least with this we understand what went wrong.

**Comment by janober** [comment]
Cool, thanks a lot. Makes a lot of sense. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.94.0

**Comment by haf** [comment]
Here? https://hub.docker.com/r/n8nio/n8n — this is where it matters for me.

**Comment by janober** [comment]
Yes also

**Pull request merged**
