### PR TITLE
FileMaker dataAPI node

### PR DESCRIPTION
**Pull request by airmoi**
Add support for FileMaker dataAPI

### CODE REVIEW

**Comment by janober** [comment]
Thanks. Just wanted to merge but realized that the whole file "FileMaker.node.ts" is still using spaces.

**Comment by janober** [comment]
@airmoi If you do not have time to change it, it is really no problem for me to do it. Just wanted to avoid it because of the attribution. However, if you prefer it just say a word and I take care of it. Thanks!

**Comment by airmoi** [comment]
Hi, sorry, I was pretty busy these last days.

Might be ok now. I don't understand why my IDE didn't detect correctly indent settings...

**Comment by janober** [comment]
@airmoi Great, thanks a lot! Will release a new version later in the day. About the IDE, maybe it needs some kind of special plugin or some setting has to be set to read the .editorconfig?

**Comment by janober** [comment]
Got released yesterday with n8n@0.36.1

**Comment by airmoi** [comment]
I just pulled the new version (was still using my dev environnement).
It seems there is an issue issue I didn't had during dev : credential are not recognized.
I have a message indicating : "... does not have any credentials of type "fileMaker" defined.
I think this is due to upper camel case on credential name I used (didn't figure out it was lower CC).
Can you confirm this is the reason crdentials are not recognized ?
I guess I did not have this issue as I'm using a mac with non case sensistive partition...

**Comment by janober** [comment]
I can confirm that. But is 100% my mistake. I changed it from "FileMaker" to "fileMaker" to be named in the same manner all credentials in n8n are. Doing that I have overlooked two things. Normally I check the functionality of all Nodes but because I do not own a mac I could sadly not here. Sorry about that! The issue got fixed and I try to release a new version with the fix and some other changes on the weekend.

**Pull request merged**
