### PR TITLE
Added MessageBird Node

### PR DESCRIPTION
**Pull request by Shraddha2104**
Hey,
📖 I am a part of the [MLH Fellowship](https://github.com/MLH-Fellowship).
✨ I created a MessageBird node for n8n as a part of getting started.
https://developers.messagebird.com/api/sms-messaging/

### CODE REVIEW

**Comment by Shraddha2104** [comment]
@RicardoE105 my CLA status is pending, I have already configured my email address accurately.
Could you please check?

**Comment by Shraddha2104** [comment]
CLA status shows pending

**Comment by janober** [comment]
The problem seems to be that it is waiting that also the GitHub user "Shraddha Shaligram" signs the CLA as according to the history also that "user" did commit code in this PR:
https://github.com/n8n-io/n8n/pull/660/commits
Maybe something was wrongly configured somewhere? But all good. We can also merge it like that as you did create all the changes and you did sign it already.

**Comment by RicardoE105** [comment]
Good work @Shraddha2104 got merged.

I made the following changes:

- Fixed indentation issues.
- Remove some unnecessary lines.
- Changed name from Mclass to Message Type.

If a change I made does not make sense simply get back to me.

**Comment by Shraddha2104** [comment]
Thank you!! @RicardoE105

**Pull request merged**
