### PR TITLE
feat: Add multiple workflows text search filtering E2E test scenarios (no-changelog)

### PR DESCRIPTION
**Pull request by alexgrozav**
Github issue / Community forum post (link here to close automatically):

### CODE REVIEW

**Review by netroy — COMMENTED** [review]
since this branch is missing the fix that already got merged. e2e tests should fail, right?

**Review by alexgrozav — COMMENTED** [review]
Trigger E2E

**Comment by alexgrozav** [comment]
@netroy 
image

**Review by netroy — APPROVED** [review]
Testing e2e again with updated master

**Comment by janober** [comment]
Got released with `n8n@0.214.0`

**Pull request merged**
