### PR TITLE
Added feature for Slack node: get and set your status

### PR DESCRIPTION
**Pull request by ToBeHH**
The current slack node is missing a way to get and set your status - the status text and the status icon. This PR is changing this. With this PR, you can change your Slack status based on calendar events (e.g. "I am in a meeting") or based on MQTT events (like [this](https://www.instructables.com/id/Slack-Status-Updater-With-ESP8266/))

### CODE REVIEW

**Comment by RicardoE105** [comment]
@ToBeHH Thanks very much. I made some improvements here #995. If you can review and provide feedback will be cool.

**Comment by ToBeHH** [comment]
@RicardoE105 When I review the PR, I only see my code. Regarding your changes: As I see, you have a different approach to it: You like to open the full API, even if the fields don't make sense at first glance (like changing the full name). But who are we to decide, if the user needs them or not, right? 
Overall your code looks much cleaner. I like that you use moment for unix time conversion. You also respect the time zone, which I did not.
One small thing: I am only confused by so much empty lines, esp. before and after the brackets of an if statement. But this is only a minor cosmetic thing. Overall it looks good to me. Thank you very much for picking it up!

**Comment by RicardoE105** [comment]
> When I review the PR, I only see my code. Regarding your changes: As I see, you have a different approach to it: You like to open the full API, even if the fields don't make sense at first glance (like changing the full name). But who are we to decide, if the user needs them or not, right?

Yeah exactly, that is what we usually do in all nodes. If we had left just status and someone later wanted to also be able to update the name, then we will have to add another operation just for that. Also semantically the status is part of the profile so I guess it makes sense to have it at under profile.

> I am only confused by so much empty lines, esp. before and after the brackets of an if statement. But this is only a minor cosmetic thing. Overall it looks good to me. Thank you very much for picking it up!

This is a good point, I have come to the realization that with the spaces (in my mind) it reads better. I guess it's a matter of taste.

We trank you very much for the contribution. We will let you know when is released.

**Comment by janober** [comment]
Great, thanks a lot for this addition!

Got merged with #995

**Comment by janober** [comment]
Got released with n8n@0.86.0

**Pull request closed without merging**
