### PR TITLE
⚡ add Wazzup node

### PR DESCRIPTION
**Pull request by pashkatrick**
Adding node of [Wazzup](https://kutt.it/fb5b6u)
Its a social message notification service

Doc will be here https://github.com/n8n-io/n8n-docs/pull/461

### CODE REVIEW

**Comment by RicardoE105** [comment]
@pashkatrick is this ready for review? I had a quick look, and for example, the resource channel does not show anything.

**Comment by pashkatrick** [comment]
> @pashkatrick is this ready for review? I had a quick look, and for example, the resource channel does not show anything.

yep, i thought :) 
channel is a Get request to get all connected account wazzup channels (like wa or inst). Needs only auth token to work, so its by design. 
But its my first node, maybe i done smth wrong

**Comment by RicardoE105** [comment]
@pashkatrick gotcha no problem. The get operations that return more than one item, we usually call them `Get All`. You have probably seen this in the other nodes. Also, we add two parameters to do the pagination for the user, returnAll and limit.

Thanks for your contribution.

**Comment by pashkatrick** [comment]
@RicardoE105 Thanks for your review. I add _returnAll_ flag, thats _true_ by default. Because of wazzup api doesn't support pagination :(
So i comment _limit_ field and add condition for _returnAll_. Pls, tell me, how should i do it better?

**Comment by RicardoE105** [comment]
@pashkatrick I tried to review this without success. For some reason, it does not let me create an API Key? According to the docs, you have to go to https://new72949065.wazzup24.com/settings/integrations/ and create an API Key, but there is no option to create such a thing. Perhaps, because I'm using the 3 free trial says?

**Comment by pashkatrick** [comment]
@RicardoE105 i forward a problem to service support and got an answer: "Good day! So far, the old integrations are working, but they are not displayed in any way. There is no way to do a new API setting yet, the developers are working on the issue"

They had an big release at last saturday, so i can suggest you a few tokens for tests:
there is for whatsapp - `8927c7db-1482-4b06-b40e-7e7840792c1a`
there is for instagram - `8a6d6c5f-32e6-46dd-9756-64bf8e8adc51`

_they will expire soon_

**Comment by pashkatrick** [comment]
any updates ? or reject ?)

**Comment by pashkatrick** [comment]
@RicardoE105 Support tell me, that function is bask - so you can try to create API key again

**Comment by RicardoE105** [comment]
@pashkatrick sorry for the late response. Added this to the backlog again.

**Comment by MedAliMarz** [comment]
Hey @pashkatrick , Thanks for the contribution. I have few change suggestions to facilitate the rest of the review process.

- It will be great if you split this PR into 2 separate ones, one for the wazzup node and another for the Telegram node changes. That way we keep a consistent commits log, Also that will mitigate merge conflicts. 
- It is possible to group all the resources under a single one named "Channel" with operations `get`, `sendMessage` and `sendFile` instead of having 3 resources using the same code, which will make adding channel support easier.
- Would you please remove the UTM query params from the URI used in the requests
- Please use the right error handling classes `NodeApiError`, `NodeOperationError` , You can find examples in other nodes
- for the get operation you can add the limit parameter and use the `.slice` method to reduce the output number

Let me know if there is anything unclear

**Comment by krynble** [comment]
Hey @pashkatrick

We haven't heard back from you. I made some tests with the node and the get channels operation returns a single element with all the channels. It would be better if  you could split this into multiple items.

Right now the output looks like this:

```
[{
	"json": [{
			"channelId": "123",
			"transport": "Telegram"
		},
		{
			"channelId": "465",
			"transport": "Whatsapp"
		}
	]
}]
```

It would be great if you could change it to be something like this:

```
[{
		"json": {
			"channelId": "123",
			"transport": "Telegram"
		}
	},
	{
		"json": {
			"channelId": "465",
			"transport": "Whatsapp"
		}

	}
]
```

I will be closing this PR from now but if you're still interesting in making this contribution, feel free to reopen.

Thanks!

**Pull request closed without merging**
