### PR TITLE
Support for binary data on webhooks

### PR DESCRIPTION
**Pull request by RicardoE105**
@janober This should solve this issue. https://community.n8n.io/t/handling-of-binary-data-in-webhook/1035?u=ricardoe105

To test it just go to postman, set the body to binary and upload a file.

image

Let me know if something.

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot but that can sadly not be merged. You removed a parameter and then added two totally different ones instead. That will definitely break a lot of workflows if we would do that.

**Comment by RicardoE105** [comment]
Dam. Yeah, I should not have deleted the rawBody one. if I add it back there should not be an issue since the other two fields are not gonna do anything by default.

**Comment by janober** [comment]
Great, thanks a lot got merged.

Made some adjustments:
 - Moved the parameters into the options. To keep it as clean as possible and to not confuse people unnecessarily
 - Display these parameters only for "POST"
 - Hide "Raw Body" if binary gets activated
 - Fixed that it returns a valid item (an item always has to contain a "json" property)
 - used the built-in `prepareBinaryData` method to detect the mime-type

**Comment by janober** [comment]
Got released with n8n@0.58.0

**Pull request merged**
