### PR TITLE
open edit window in postgres query

### PR DESCRIPTION
**Pull request by lublak**

### CODE REVIEW

**Comment by ivov** [comment]
We appreciate your contribution. This field already has rows, so the preference is not to use an edit window.

**Comment by lublak** [comment]
@ivov thanks for the review.
I just found it bad for design when a code editor is far too small to display a complex SQL when there is the possibility to also display it in a larger editor. Currently it's really not convenient and you can't get around copying the SQL into another editor so you can just look at it.

**Comment by ivov** [comment]
Agreed, I find the modal more convenient, but the above is the guideline I confirmed internally.

@RicardoE105 If you can please weigh in. Perhaps also removing the rows?

**Comment by RicardoE105** [comment]
@lublak @lublak to be honest I think both ways are ok. If we go with the @lublak approach then we would have to add the change to all the other database nodes.  @janober thoughts?

**Comment by ivov** [comment]
Discussed with Product - included now in https://github.com/n8n-io/n8n/pull/2188

**Pull request closed without merging**
