### PR TITLE
fix(Facebook Lead Ads Trigger Node): Fix issue with missing scope for business management 

### PR DESCRIPTION
**Pull request by spatialy**
Github issue / Community forum post (link here to close automatically): 

Community: https://community.n8n.io/t/facebook-lead-trigger-issue-with-permissions/32500

GH Issue: https://github.com/n8n-io/n8n/issues/7615

### CODE REVIEW

**Review by Joffcom — DISMISSED** [review]

**Comment by Joffcom** [comment]
Hey @spatialy,

Thanks for the PR, The team member that created the node has given it a test and it has not broken anything for normal users so we are going to get this merged in.

**Comment by Joffcom** [comment]
Hey @spatialy,

Are you able to fix the lint issue? Normally I would go for it but it looks like you used your master branch instead of a new one so I am unable to push the change.

**Comment by spatialy** [comment]
Great, I don't have great coding skills, but this one was simple and important for the community boost of this node. :)

Happy to help!

**Comment by spatialy** [comment]
Hi @Joffcom, I cleared the lint issues.

**Review by Joffcom — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.16.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.16.0)

**Pull request merged**
