### PR TITLE
✨ Add binary upload for Telegram

### PR DESCRIPTION
**Pull request by pemontto**
I ran into an issue when trying to send a camera image retrieved from Home Assistant to Telegram. The Telegram node currently only supports linking to existing media.

This PR adds the ability to upload binary data for sending animations, audio, documents, photos, stickers and videos.

n8n_-_▶️_My_workflow_2

### CODE REVIEW

**Comment by RicardoE105** [comment]
@pemontto thanks for your contribution. Made some changes to make it work similar to the other nodes. We will let you know when it's released.

**Comment by pemontto** [comment]
@RicardoE105 ahh much cleaner and makes much more sense than overloading the body, thanks!

**Comment by janober** [comment]
Thanks a lot @pemontto . Got merged with #2249

**Comment by janober** [comment]
Got released with n8n@0.140.0

**Pull request closed without merging**
