### PR TITLE
fix: Fix indentation in bash script for docker postgres init (no-changelog)

### PR DESCRIPTION
**Pull request by gumida**
## Summary
Hope I'm doing this correctly: I think the bash script `docker/compose/withPostgres/init-data.sh` is not working correctly as the intent before 'EOSQL' is not the right one?

This PR replaces the whitespace with a tab.

## Review / Merge checklist
- [x] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @gumida 

Did you test it after the change to see if it works?

**Comment by gumida** [comment]
> Hey @gumida
> 
> Did you test it after the change to see if it works?

Yes. Original init script:
```
temp1_postgres-1  | 2024-03-06 10:31:30.826 UTC [47] LOG:  database system is ready to accept connections
temp1_postgres-1  |  done
temp1_postgres-1  | server started
temp1_postgres-1  | CREATE DATABASE
temp1_postgres-1  |
temp1_postgres-1  |
temp1_postgres-1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init-data.sh
temp1_postgres-1  | /docker-entrypoint-initdb.d/init-data.sh: line 13: warning: here-document at line 6 delimited by end-of-file (wanted `EOSQL')
temp1_postgres-1  | /docker-entrypoint-initdb.d/init-data.sh: line 14: syntax error: unexpected end of file
temp1_postgres-1 exited with code 0
temp1_postgres-1  |
temp1_postgres-1  | PostgreSQL Database directory appears to contain a database; Skipping initialization
```

tab instead of space:
```
temp2_postgres-1  | 2024-03-06 10:36:32.131 UTC [47] LOG:  database system is ready to accept connections
temp2_postgres-1  |  done
temp2_postgres-1  | server started
temp2_postgres-1  | CREATE DATABASE
temp2_postgres-1  |
temp2_postgres-1  |
temp2_postgres-1  | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init-data.sh
temp2_postgres-1  | CREATE ROLE
temp2_postgres-1  | GRANT
temp2_postgres-1  | GRANT
temp2_postgres-1  |
temp2_postgres-1  | 2024-03-06 10:36:32.390 UTC [47] LOG:  received fast shutdown request
temp2_postgres-1  | waiting for server to shut down....2024-03-06 10:36:32.392 UTC [47] LOG:  aborting any active transactions
temp2_postgres-1  | 2024-03-06 10:36:32.396 UTC [47] LOG:  background worker "logical replication launcher" (PID 53) exited with exit code 1
temp2_postgres-1  | 2024-03-06 10:36:32.397 UTC [48] LOG:  shutting down
temp2_postgres-1  | 2024-03-06 10:36:32.398 UTC [48] LOG:  checkpoint starting: shutdown immediate
temp2_postgres-1  | 2024-03-06 10:36:32.431 UTC [48] LOG:  checkpoint complete: wrote 932 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.022 s, sync=0.007 s, total=0.034 s; sync files=308, longest=0.002 s, average=0.001 s; distance=4262 kB, estimate=4262 kB; lsn=0/1914218, redo lsn=0/1914218
temp2_postgres-1  | 2024-03-06 10:36:32.439 UTC [47] LOG:  database system is shut down
temp2_postgres-1  |  done
temp2_postgres-1  | server stopped
temp2_postgres-1  |
temp2_postgres-1  | PostgreSQL init process complete; ready for start up.
temp2_postgres-1  |
temp2_postgres-1  | 2024-03-06 10:36:32.527 UTC [1] LOG:  starting PostgreSQL 16.2 (Debian 16.2-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
```
See also: [SC1040 – ShellCheck Wiki](https://www.shellcheck.net/wiki/SC1040)

**Comment by Joffcom** [comment]
Perfect, I think we are safe to merge this then.

**Review by Joffcom — APPROVED** [review]

**Comment by johnyb0y** [comment]
@Joffcom @gumida Sorry about that. I missed that in my initial commit for the script update.

**Comment by janober** [comment]
Got released with [`n8n@1.33.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.33.0)

**Pull request merged**
