### PR TITLE
Add replyTo feature to Microsoft Teams

### PR DESCRIPTION
**Pull request by vuchl**
With a Message ID from `createMessage` or `getAll` one is now able to reply to a message in a threaded manner:
image

### CODE REVIEW

**Comment by RicardoE105** [comment]
@vuchl got checked, and it's working as expected. Thanks for your contribution. We will let you know when it is released.

**Comment by janober** [comment]
Thanks a lot @vuchl!

Looks good but could you please change it to be an optional option like it is for example on Slack. That makes things more consistent and also keeps the node slim with less repetition. Thanks!

**Comment by vuchl** [comment]
Hey @janober!

I am having trouble understanding this. The messsage ID is obligatory for replying to a message. Or do you mean consolidate Post a message and reply to a message? This would then result in different MS Graph routes. But if you mean it that way I can try.

Regards

**Comment by vuchl** [comment]
Alright I went with the consolidation aproach and was still able to post a message and reply to it afterwards:
image

**Comment by janober** [comment]
Thanks a lot for making the changes. Just got merged with #1479

**Comment by vuchl** [comment]
Thanks guys! Also great how you put that into real options. I was not aware of that. So it's a collaborative effort :)

**Comment by janober** [comment]
Got released with n8n@0.110.0

**Pull request closed without merging**
