### PR TITLE
🔃Add function to get currents parameters in loading function

### PR DESCRIPTION
**Pull request by BenoitTallandier**

### CODE REVIEW

**Comment by janober** [comment]
Cool. Thanks a lot! I just checked the code. That will be very helpful!

I fixed some styling issues I saw and renamed the function `getCurrentNodeParameters` to `getCurrentNodeParameter` and created another one `getCurrentNodeParameters` which really returns all parameters.

There are however still two issues: 
  1. Does not work with nested parameters like options
  2. Does not work when a parameter has an expression

Merged it for now anyway. Issue 1 is not that problematic for now. But issue 2 could cause quite some problems when somebody, for example, references a value from a parameter of another node.

**Comment by BenoitTallandier** [comment]
Ok, thank's for to improved my code 👍 
It's true, I didn't thought about that. I'll work on that :)

**Comment by janober** [comment]
Perfect thanks! Have a great day!

**Comment by janober** [comment]
Did fix issue that it did not work with expressions:
https://github.com/n8n-io/n8n/commit/a7d729842a06a2ab222a948c7560bfbde6811ea5

**Pull request merged**
