### PR TITLE
fix(n8n Node): fix resource locator not returning all items

### PR DESCRIPTION
**Pull request by Joffcom**

### CODE REVIEW

**Review by maspio — APPROVED** [review]
Looks good to me

**Comment by luizeof** [comment]
@Joffcom Node WhatsApp does not load all message templates. Does this pull correct operations of this type?

**Comment by Joffcom** [comment]
@luizeof this is only for the n8n node, the WhatsApp node may need something else as it might not be pagination and could be down to templates not being approved or something else.

**Comment by janober** [comment]
Got released with `n8n@0.199.0`

**Pull request merged**
