### PR TITLE
Feature/salesforce flow

### PR DESCRIPTION
**Pull request by RicardoE105**

### CODE REVIEW

**Comment by camcelroy** [comment]
@RicardoE105  Flow list looks good.  Hadn't occurred to me that the same limits used elsewhere could be used for that.
Naming adjustments are fine.
The raw JSON works good, but defining variables via UI didn't work.  Looks like there was a leftover reference to **inputVariable** which needs to be changed to **variablesValues** at  https://github.com/RicardoE105/n8n/commit/3b56dd918b3e0bf5dccf6726d823b26e800f8581#diff-42c29382da30b0e9e4ed6d8ea4c9b078R1970

**Comment by RicardoE105** [comment]
ahhh just fixed it. @camcelroy this will be merge soon. Again, thanks for your contribution

**Comment by camcelroy** [comment]
@RicardoE105 my pleasure.  Thanks for accepting.

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.87.0

**Pull request merged**
