### PR TITLE
feat(Qdrant Vector Store Node): Qdrant vector store support

### PR DESCRIPTION
**Pull request by Anush008**
## Summary
This PR intends to add [Qdrant](https://qdrant.tech/) as a supported vectorstore node to load and retrieve documents from in a workflow.

## Review / Merge checklist
- [x] PR title and summary are descriptive. 
- [x] Node/credentials documentation to be updated in https://github.com/n8n-io/n8n-docs/pull/1796.

### CODE REVIEW

**Comment by Anush008** [comment]
@netroy, could you please review?

**Comment by netroy** [comment]
Thanks for the PR 🙏🏽 

> @netroy, could you please review?

but **please don't mention random repo maintainers like this**. It's not helping anyone.

I for one can't really review this particular PR because I'm not familiar with this node. 

we'll try to route this issue to the correct maintainers as soon as we can.

**Comment by netroy** [comment]
This code looks very similar to the stuff @OlegIvaniv [is already working on](https://github.com/n8n-io/n8n/commit/47fc08ba04b3a5bc9800ca4595e3d357826525e5), probably based on #7807. 

I really wish that you had created an issue before starting to work on this PR 😞

**Comment by Anush008** [comment]
The initial PR was closed. So I assumed it is available to be taken up.

**Review by OlegIvaniv — CHANGES_REQUESTED** [review]
Hi @Anush008, I appreciate the work you've done here! There are a few linting issues; please run `pnpm lintfix` in the `packages/@n8n/nodes-langchain` directory to fix those automatically.
Other than that, the node works as expected in all three modes. I dropped a few comments about stylistic things that would be nice to improve, and I'd be happy to get this in 🙌.

**Comment by Anush008** [comment]
Should be resolved now.
https://github.com/n8n-io/n8n/pull/8080/commits/2881e63c050b2f198f34c0f00833abc7ee8dddec

**Review by OlegIvaniv — APPROVED** [review]
Thanks for the quick addressing of the review points, @Anush008! LGTM

**Comment by Joffcom** [comment]
Got released with [`n8n@1.23.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.23.0)

**Pull request merged**
