### PR TITLE
Added message type and message format options to Matrix node

### PR DESCRIPTION
**Pull request by laszabine**
I modified the Matrix node to allow creating messages of different type and different format: 

- message type (`msgtype`) can now be not only `m.text`, but also `m.notice` and `m.emote`, as per [Matrix specification](https://matrix.org/docs/spec/client_server/latest#m-room-message-msgtypes). 

- message format (`format`) can now be not only plain text, but also HTML. When HTML is selected, a new field appears called "fallback text", which serves to provide an alternate plain text message in case the Matrix client cannot render the HTML, as per [the same Matrix specification](https://matrix.org/docs/spec/client_server/latest#m-room-message-msgtypes). 

I've also created a PR to n8n-docs to adapt the documentation: https://github.com/n8n-io/n8n-docs/pull/273

### CODE REVIEW

**Comment by RicardoE105** [comment]
@laszabine just tested it and it seems to be working as expected. Thanks very much. We will let you know when is released.

**Comment by janober** [comment]
Thanks a lot. Got merged with #1162

**Comment by laszabine** [comment]
Thanks!

**Comment by janober** [comment]
Got released with n8n@0.94.0

**Pull request closed without merging**
