### PR TITLE
feat(KoBoToolbox Node): Add support for Media file API

### PR DESCRIPTION
**Pull request by Yann-J**
This PR adds support for CRUD operations on a KoboToolbox form's media files, i.e. Create, Get, Delete. These files are used as attachments to a form's content and are typically media files or csv to lookup some data form.

### List all attached files:

image

### Attach a new file:

image

### Download a file content:

image

### CODE REVIEW

**Comment by Yann-J** [comment]
Hello @RicardoE105 small nudge here as I think this one would be quick to review...

**Comment by Yann-J** [comment]
Hello! Gentle nudge here... Any timeline for the review?

**Comment by Joffcom** [comment]
Hey @Yann-J & @RicardoE105,

I missed this one as well, I take it removing the form option from the Hook Get All isn't going to cause any breaking issues?

**Comment by Yann-J** [comment]
@Joffcom it is not removed, I just removed the duplicated declarations and regrouped them.

**Comment by Joffcom** [comment]
@Yann-J so it is, I missed that change on the other option.

**Comment by Yann-J** [comment]
Indeed, not sure what this was doing here... Just removed it! Thanks @Joffcom

**Comment by Joffcom** [comment]
Hey @Yann-J,

Perfect, So we missed the release today but I will get this merged on Monday to the master branch so it will be in next weeks release.

**Review by Joffcom — APPROVED** [review]

**Comment by Joffcom** [comment]
Hey @Yann-J,

Thanks for the PR, This has been merged and will be available in the next release.

**Comment by janober** [comment]
Got released with `n8n@0.206.1`

**Pull request merged**
