### PR TITLE
Add wordpress post template option - N8N-3417

### PR DESCRIPTION
**Pull request by Zapfmeister**
This PR adds the option to select a specific wordpress post template when adding or updating a post.

### CODE REVIEW

**Comment by janober** [comment]
@Zapfmeister Is this PR complete? Because I can not see a change for a UI parameter that would allow the user to set it.

**Comment by Zapfmeister** [comment]
@janober isnt that the 	template?:string; within packages/nodes-base/nodes/Wordpress/PostInterface.ts?
Im trying to build a docker container to test the code, using the Dockerfile in docker/images/n8n, but it always throws the error:
`Initializing n8n process
There was an error initializing DB: "SQLite package has not been found installed. Try to install it: npm install sqlite3 --save"`

**Comment by Zapfmeister** [comment]
@janober fixed

**Comment by janober** [comment]
Thanks! Did you test your PR? Because please always make sure that it is working and tested before opening one

**Comment by Zapfmeister** [comment]
@janober yes, i tested it. its working. I changed it to an option type now, as otherwise you need to know the options.
Unfortunately i didnt find any way to query the available options, so i hardcoded the elementor options.

**Comment by michael-radency** [comment]
Hello @Zapfmeister I made some tweaks so not only elementor themes can be used

**Comment by Zapfmeister** [comment]
@janober can you please review? Should be good to be merged

**Comment by janober** [comment]
Thanks a lot for your contribution @Zapfmeister . It got merged and will be released with the next version.

**Comment by janober** [comment]
Got released with `n8n@0.185.0`

**Pull request merged**
