### PR TITLE
fix salesforce error while get all using nextRecordsUrl

### PR DESCRIPTION
**Pull request by YEriin**
The uri for using nextRecordsUrl to get all data in salesforce node is error. The right usage is fixed in this pr.

### CODE REVIEW

**Comment by RicardoE105** [comment]
@YEriin Sorry for the late response. I will try to review it this week. Will keep you posted. Thanks for your contribution.

**Comment by YEriin** [comment]
Is there any problem that may prevent this to be merged? @RicardoE105

**Comment by RicardoE105** [comment]
Have not had the time to test it. Sorry about that. We are small team. Will try to get to it tomorrow. @YEriin Thanks.

**Comment by YEriin** [comment]
Got it. plz notify me to come back to fix it if there is anything wrong :)

**Comment by RicardoE105** [comment]
Will do. Again thanks very much. @YEriin

**Comment by RicardoE105** [comment]
@YEriin works as expected. Will be merged soon and add it to the next release. Thanks very much.

**Pull request closed without merging**
