### PR TITLE
Updated Workflowexecute.ts

### PR DESCRIPTION
**Pull request by vaithiyanathan-sriram**
Will Write the Fail statement log for verbose

In verbose finish log is not been updated, have done necessary changes please review it and update the PR

### CODE REVIEW

**Review by allwyn-pradip — APPROVED** [review]
this logs update the required data only after this change

**Comment by janober** [comment]
Thanks for your contribution.

Sadly do however not understand why that change got made. For me it looks like all that got changed is the quotes which will result that one message will not actually print the value of "this.runExecutionData.waitTill" anymore, instead it will acutally print out the string "${this.runExecutionData.waitTill}" which seems less helpful.

**Comment by janober** [comment]
As we did not get an answer to the above question do I close the PR for now. You can however still answer and then open this PR again if it make sense.

**Comment by allwyn-pradip** [comment]
@janober -- we were trying to push the log data to an analytical tool to check on the execution, because of the bug we were only getting an execution start but not the completion, so we were not able to correlate. Hence the PR.

**Pull request closed without merging**
