### PR TITLE
U proc integration

### PR DESCRIPTION
**Pull request by RicardoE105**

### CODE REVIEW

**Comment by RicardoE105** [comment]
Continuing with #795.

Quick update here @mcolomer. I made some small improvements to the formatting. However, was not able to run it. The server breaks each time. Not sure what we are doing differently. Will try to find the error tomorrow.

**Comment by mcolomer** [comment]
Hi Ricardo,

How are you trying to run n8n server?
Could you share your method to reproduce the problem?

**Comment by RicardoE105** [comment]
Pull the changes here #795 and within the directory do

lerna bootstrap --hoist   
npm run build
npm run dev

**Comment by mcolomer** [comment]
Hi Ricardo,

I have tested this. 

Basically, I have checkout locally PR #795 in another branch.
After that, and following your instructions, everything runs ok.

This is a screenshot of UProc node with one of our last tools running in dev environment:
image

I am using NodeJS v10.13.0.

Could you share the returned errors in your machine?

**Comment by RicardoE105** [comment]
@RicardoE105 this is quite weird. Gonna recheck today. Thanks for checking on your side.

**Comment by janober** [comment]
Got released with n8n@0.99.0

**Pull request closed without merging**
