### PR TITLE
:zap: Add role parameter to user:update (Zulip)

### PR DESCRIPTION
**Pull request by RicardoE105**

### CODE REVIEW

**Comment by cmdntd** [comment]
How could I update this for n8n?

**Comment by janober** [comment]
I did create the docker image `n8nio/n8n:PR-2336-feature-zulip-extended` which contains the code of this PR that you can test.

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.149.0

**Pull request merged**
