### PR TITLE
:sparkles: Eventbrite Trigger

### PR DESCRIPTION
**Pull request by RicardoE105**
@janober will email you the token as always.

### CODE REVIEW

**Comment by janober** [comment]
Thanks @RicardoE105 . Got merged.

Made the following adjustments:
 - Changed that it returns the error message from "error.response.body.error_description" where Eventbrite API returns the error message at
 - Fix the issue, that if webhook creation did not work it did not error
 - Changed node default color to Eventbrite orange
 - Made it possible to directly resolve the data because else users would have a hard time getting it as the request also required the API-Key and so would have to add it a second time via a HTTP-Request node

**Comment by RicardoE105** [comment]
@janober cool. I did not realize it had to do a second request to get the data of the object.

**Comment by janober** [comment]
@RicardoE105 Yes I also just realized after I tried a regular request and not the test one that really no data does get sent. It is also the first time I have seen it work like that.

**Comment by janober** [comment]
Got released with n8n@0.44.0

**Pull request merged**
