### PR TITLE
Google Drive: Add support for creating folders and copying files for shared drives

### PR DESCRIPTION
**Pull request by curryy**

### CODE REVIEW

**Review by RicardoE105 — COMMENTED** [review]
Question. Would it not be better if we just set `supportsAllDrives` to true? Then it would work with both shared drives and your drives? Thoughts? Thanks for your contribution.

**Comment by curryy** [comment]
@RicardoE105 Thank you for your review. Google API sets this parameter to false by default. I think that it should be consistent with the API and not be set always to true. What do you think?

**Comment by RicardoE105** [comment]
I would set it to true as default. Correct if I'm wrong, but my understanding is that if it's set to true, it will work with both shares drives and your drives, right? 

If that is true and we add it as an extra parameter, someone not technical will have no clue that they have to turn this option to true to make it work with shared drives. 

Thoughts?

**Comment by curryy** [comment]
Good point 👍  I looked into it too technically. I set this parameter to true

**Comment by andreffs18** [comment]
Is there any news on this? Can we merge it?

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.114.0

**Pull request merged**
