### PR TITLE
Freshdesk Integration [WIP] 

### PR DESCRIPTION
**Pull request by RicardoE105**

### CODE REVIEW

**Comment by RicardoE105** [comment]
@janober Dude I had to comment the custom_fields option cuz freshdesk API does not have good documentation, I did exactly what the documentation says and keep getting the same error, weird. I did not want to keep losing time there.

Check it out and let me know, If someone needs to extend it I can do it, but I think that creating a ticket will be the most common use case.

**Comment by janober** [comment]
@RicardoE105 Thanks a lot is merged.

I had to fix the package.json file as commas were missing and so it did not build. I also fixed the order of the nodes as they were not alphabetically anymore.

Tags did sadly not work. Looks like the code for them was totally missing. Added it and works now fine. 

There were also problems with the status. They were somehow all wrong and setting to "Open" resulted in an error and the other ones did set the wrong one. That one is fixed.

There seems however still something wrong with the "source". So does setting it to "Chat" result in an error. Additionally, am I also not sure where it does get displayed.

**Comment by RicardoE105** [comment]
@janober weird gonna look into that 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RicardoE105** [comment]
yeah just checked the package.json issue when I resolve the merge issue I forgot to add the `,` at the end of the line. With regard to the tags seems to be working for me. Looking into the source issue @janober

**Comment by janober** [comment]
Got already merged and the issues fixed. So really just the source thing is open.

Strange that tags worked for you as when I tried it did not for me. Never added any tag. For example did it look like they did not get added at all to the body. Many of the properties did just get added to the options but never to the body unless I understood the code totally wrong.

**Pull request merged**
