### PR TITLE
Removing redundancies in Woo-Commerce node.

### PR DESCRIPTION
**Pull request by jacobburrell**
Removed a few redundant assignments for an iterative loop in the woo-commerce node.

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot @jacobburrell! 

Did you test all the options? Because on the first look (without having it tested myself) does it look like it would cause problems with some options like: categories, parent_id

**Comment by jacobburrell** [comment]
Thanks for pointing out the category option.

The way it's currently set up, it has to be mapped as done. I will revert "categories" assignment for now.

"parent_id" and all others I've tested works fine though.

In some instances, fields fail to get set because WooCommerce has its own logic that prevents setting some fields. i.e. setting a "virtual" product with a "weight" of 50 will not set the field. It will set the weight of the product is **not** virtual though.

**Comment by RicardoE105** [comment]
While I understand there is a lot of repeated code, I think this approach is better when someone who never has seen that node has to fix or modify the node, as right away you can see the parameters that are being sent and are needed. @jacobburrell

**Comment by jacobburrell** [comment]
Agreed it is nice to see the parameters being used @RicardoE105 
Aren't all the parameters already listed in the node's **NodeProperties** fields such as in [ProductDescription](https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/WooCommerce/ProductDescription.ts)?

I do like fields being shown at least once. I'm not sure listing them hard-coded out _again_ for the purpose of assignment in the interface adds much.

Perhaps we could [link](https://woocommerce.github.io/woocommerce-rest-api-docs/) a comment to the docs in comments?

Also, this potentially makes it easier to add new fields in if Woo Commerce changes their API in the future by adding fields.
A simple string field should work with an addition to the field in the **NodeProperties** without any other modification. 
Currently, you'd have to add it to NP and make the hard-coded assignment, adding a step for every additional field to add.

**Comment by RicardoE105** [comment]
Hey, @jacobburrell sorry for the late response.

> Agreed it is nice to see the parameters being used @RicardoE105
> Aren't all the parameters already listed in the node's NodeProperties fields such as in ProductDescription?
> 

 Yes, they are listed under NodeProperties however all of them use camelCase for the value type even thought the API can be camelCase, snakeCase, etc. I use the interface as a guide to not make mistakes. 

> Perhaps we could link to the docs in comments?


Agree, I try yo add the link to the documentation to each resource as shown [here](https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/WooCommerce/WooCommerce.node.ts#L583).

> Also, this potentially makes it easier to add new fields in if Woo Commerce changes their API in the future by adding fields.
> A simple string field should work with an addition to the field in the NodeProperties without any other modification.

Yeah, this certainly makes it easier as long as you do not add a parameter either fixedCollection or collection. In those cases, you will have to get those parameters individually.

I guess this is a matter of preference. If you check the nodes some of them have your approach and some of them have my approach.

As long as everything work is fine with me. Unless @janober has another opinion.

**Review by krynble — APPROVED** [review]
I just tested the changes by creating products on a WooCommerce instance and it's working fine.

I added some special fields like `upsellIds` and `crossellIds` and it's all good. All data is being saved correctly on Wordpress 5.8 and WooCommerce 5.5.2.

**Comment by janober** [comment]
Got released with n8n@0.133.0

**Pull request merged**
