### PR TITLE
Azure Service Bus fix

### PR DESCRIPTION
**Pull request by erbg**
Hello,

Wanted to submit a change to the AMQP Node (trigger and sender) which supports also Azure Service bus Topics.

To have Azure Service Bus Working, you need to set the new Connection Parameter "Transport Type" to tls, set User + Password to your SAS policy and Key.

Since Azure Service Bus sends data as Byte Array, I added an option to convert the byte Array back to String.#

Hope my changes are welcome.

PS: great project :)

### CODE REVIEW

**Comment by janober** [comment]
Sorry for the late reply. Now could finally test it at least in a way that it does not break existing behavior.

Can you please create another PR with just the AMQP changes without the TextTemplate node. Thanks

**Comment by erbg** [comment]
Sorry did not see that there was some other Commit in the PR. New PR is #1107

**Comment by janober** [comment]
Got merged with #1107

**Comment by janober** [comment]
Got released with n8n@0.91.0

**Pull request closed without merging**
