### PR TITLE
🐛  Fix api version for Jira server

### PR DESCRIPTION
**Pull request by romaincolombo-daily**
Hello.

This PR fixes 404 issues using Jira Server integration. Currently Issue Comment, Issue Attachment and User ressources are not working with Jira Server  

- For Jira server there is no version 3 of the API;
- For Jira server the comment body is not ADF format, but a simple string instead.
(first reported here: https://community.n8n.io/t/jira-node-fails-in-comments-and-attachment-actions/5115 )

Successfully tested over Jira Server v8.5.

### CODE REVIEW

**Comment by RicardoE105** [comment]
Thanks, very much for your contribution. A couple of things:

1 - Should not issueAttachment:getAll also have the API version set depending on the version?  https://github.com/n8n-io/n8n/pull/1866/files#R802

2 - Can you please fix the formatting issues. If you run `npm run tslint` you should be able to see the issues.

Let me know if you have questions.

**Comment by romaincolombo-daily** [comment]
Thanks for you feedback @RicardoE105.

1 - IssueAttachment:getAll had been implemented with API v2 since its first [commit](https://github.com/n8n-io/n8n/commit/46fe96b72c7230eed0ea67ea301314ec8bfdf5f2#diff-7ff6bccd9778f8d66c9ccf948e02e1a6c5119e4cbd29b37e0667af7ff74aed52R800). So it worked well already with Jira Server. 

My guess is it uses `/issue` endpoint (not directly `/attachment`) which has only been implemented with API v2 all over this n8n node. A matter of consistency? @janober co-authored the original PR, could you help us figure this out? 

However I don't have access to a Jira Cloud instance. I'd need help to validate this v2->v3 upgrade if we still want to do it.

2 - Sure, I'll lint it.

**Comment by RicardoE105** [comment]
@romaincolombo-daily makes sense. Thanks for the explanation. Yes, I wonder if the difference between version in the node it's because some resources are just implemented in the v3 🤔 . Also, we have never had a Jira server instance. We rely on community members like yourself to test it. Thanks very much.

**Comment by romaincolombo-daily** [comment]
You're welcome @RicardoE105 :). 

All the ressources exposed in this n8n node are both available in v2/v3. With this PR, I'm able to manage everything I see using Jira Server.
I suppose the previous contributors weren't aware of Jira Server limitations and used v3 because it was the latest documentation available? Indeed, I personally don't see a real value (feature-wise) to use v3 instead of v2 for these ressources. There seems to be no breaking change but this "ADF format" for text bodies on the API requests. 

Probably, a great move would be to use v2 only for server and v3 only for cloud all over this node. But I fear upgrading ressource naively from v2 to v3 would break some existing n8n workflows due to small API response changes (ie: again this ADF format for text instead of a simple string...).  So, this could be a bit challenging to do this "the right way" and is a bit out of scope of this fix IMO. What do you think?

I [pushed](https://github.com/n8n-io/n8n/compare/cc7580667bee8caa7a816234b9e28bc5f6f7637a..bd5d248aade5b9ceb27d984a924faafd579a1e77) the lint fixes in this PR. Let me know if it looks good to you now.

**Comment by janober** [comment]
Thanks a lot for your contribution @romaincolombo-daily ! Just got merged and will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.124.0

**Pull request merged**
