### PR TITLE
feat(Kafka nodes): Support for more SSL options when connecting to Kafka brokers

### PR DESCRIPTION
**Pull request by cylabr**
Support for more SSL options when connecting to Kafka brokers using Kafka nodes:
- SSL CA
- SSL Cert
- SSL Key
- SSL Key Passphrase

Useful when connecting to a Kafka cluster that supports client certificate based authentication.

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @cylabr,

Thanks for the PR, I have created an internal ticket for this which we are tracking as `NODE-598`

**Review by agobrech — CHANGES_REQUESTED** [review]
Thanks for your PR, it looks good however it would be great if you could use the password property to hide the content of the fields. You can have a look at the RabbitMQ credential on how it is done.

**Comment by cylabr** [comment]
@agobrech Thank you for your comment, I just pushed the changes you suggested.

**Comment by netroy** [comment]
[n8n now supports using custom root certs globally](https://github.com/n8n-io/n8n/pull/8705/files) since a month.
 
We'd really prefer if people could use that option, instead of having to add (and maintain) custom TLS support, or adding an option to completely disable TLS verification on individual nodes.

Closing this for now. But, if you think the custom root CA approach does not work, please let us know, and we can try to come up with a solution.
Also, sorry for not merging this 😞

**Comment by CallumDenby** [comment]
@netroy I may be mistaken, I'm not very well versed in the ins and outs of TLS, but this custom root CA approach still doesn't allow client certificate auth for the brokers does it?

We use client certificate auth for our Aiven-hosted Kafka instance and it seems without this PR we'd be unable to auth

**Comment by netroy** [comment]
@CallumDenby You are right. I misunderstood this as adding support for ignoring TLS verification (which unfortunately we have too much of).

I've created an internal ticket to implement and test this: `NODE-1552`.

**Comment by CallumDenby** [comment]
@netroy Is there anything that can be done from an external perspective to assist in getting this merged?

**Comment by cazacutudor** [comment]
@netroy any updates here ?

**Comment by pdany1116** [comment]
Hi @netroy, I am using Heroku Kafka and SSL certificates is the only way supported. Do you have news when this will get merged? It's currently blocking our development. Thank you!

**Comment by dlaurq** [comment]
Any updates or alternatives to use SSL on Kafka? @cylabr @netroy

**Comment by AnaDanielaDragan** [comment]
Hi @netroy @cylabr,
I see that this PR is closed, and I just wanted to check if there are any plans to merge it or if there's anything still pending. The SSL support for Kafka nodes is crucial for my work, and I’m really looking forward to using it. Any updates on this would be greatly appreciated!

Thanks again for your efforts on this feature!

**Comment by pdany1116** [comment]
Hi @cylabr, thank you for your work. I have extracted the nodes from this PR and published an npm package to use until the changes are merged in n8n. Thank you again! https://github.com/Agilefreaks/n8n-nodes-kafka-ssl

**Pull request closed without merging**
