### PR TITLE
added rawBody to webhooks

### PR DESCRIPTION
**Pull request by RicardoE105**
@janober added this so that we can use to verify the signature.

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot @RicardoE105 ! But does that work for you? Because when I test it, is for me `rawBody` never set because it is `undefined` in the Webhook-Node. Do also not understand right now why.
But even if it would work would it be added to the wrong data. Because it should be a Buffer and Buffers should not be part of "json" they should be in "binary" and then base64 encoded.

Also, would it probably be better to add "Options" to the Webhook-Node and one being something like "addRawBody". Because else we would start to add the body-data always twice even if the rawBody is probably only needed in way less than 1% of the cases. This is not a problem when small amounts of data get received, but if they get large and the workflow executions get saved, that would start to make a big difference.

**Comment by RicardoE105** [comment]
@janober I think as this would work better. What do you think?

**Comment by janober** [comment]
Really cool, thanks a lot! Got merged.

Did also find the reason why it did not work for me. The reason is that the rawBody only gets added for JSON-Requests. That is also something we should fix in the future.

The only changes I did is that I combined the "Options" and fixed the binary data as there was one level missing.

**Comment by janober** [comment]
Got released with n8n@0.40.0

**Pull request merged**
