### PR TITLE
fix(core): Support branches containing slashes in source control

### PR DESCRIPTION
**Pull request by ivov**
## Summary

https://linear.app/n8n/issue/PAY-1723/

## Related Linear tickets, Github issues, and Community forum posts

https://github.com/n8n-io/n8n/issues/9963

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Review by netroy — APPROVED** [review]

**Comment by ivov** [comment]
@netroy Can you please reapprove? Merged master, not sure why e2e keeps failing but they must be all flukes.

**Review by netroy — APPROVED** [review]

**Comment by netroy** [comment]
can you please check if 25-stickies test passes for you locally?

**Comment by ivov** [comment]
> can you please check if 25-stickies test passes for you locally?

I'll try on Monday. Hard to believe that this fix about slash-handling in source control could affect stickies.

**Comment by ivov** [comment]
Current run in progress here: https://cloud.cypress.io/projects/5hbsdn/runs/6061/specs?utm_source=github

Stickies and Scheduler node have been rather flaky.

**Review by netroy — APPROVED** [review]

**Review by netroy — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.52.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.52.0)

**Pull request merged**
