### PR TITLE
Add Deal description to Hubspot node

### PR DESCRIPTION
**Pull request by TySmith17**
This adds the field "Deal description" to the Hubspot node for deals. Let me know if there's anything else needed to be done.

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot. But did you test it? Because for me it looks like that it can not work as the field you did does never get used anywhere in the code.

**Comment by TySmith17** [comment]
Looks like i forgot to include that file :man_facepalming:, I went ahead and added it.

**Comment by janober** [comment]
Thanks a lot. I just tested. It looks like the Description for the update was in the node-code but the parameter was missing. Added it and then merged.

Will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.111.0

**Pull request merged**
