### PR TITLE
AWS Integration (SNS Publish and Lambda Invoke)

### LINKED ISSUE #31: AWS Integration
I think an integration with some AWS services would be a really good thing to have implemented. I will starting working in some of them, but it might take a while since I'm new with TS (though I have a lot of experience with AWS).

There would be multiple nodes (one for each AWS Service) but only a single credential provider, since all services require only and ACCESS_KEY and a SECRET and it can be used with multiple services.

## Services to integrate
The plus flag means that this item I consider less important or more difficult to implement.

### CloudWatch
* Trigger Alarm changes the state
* Send logs to CloudWatch Logs

### S3
* Upload a file to an S3 bucket
* Create a pre-signed link to an S3 Object
* Plus: Delete/Rename a file in a S3 bucket

### DyanmoDB
* Put an item
* Get item
* Plus: Query and Scan

### SNS
* Send message to topic

### SQS
* Send messages to queue
* Plus: Trigger Consume queue

### Lambda
* Start an execution

### SES
* Send email

### PR DESCRIPTION
**Pull request by mscansian**
Adds a simple integration with AWS (closes #31).
### AWS SNS
* Publish message to topic
### AWS Lambda
* Invoke a function

### CODE REVIEW

**Comment by janober** [comment]
Great thanks!
I will wait with merging till there is at least one node that uses the credentials else it would only confuse people.

**Comment by mscansian** [comment]
Actually this is work in progress. You can wait until I finish all the integrations to merge.

**Comment by mscansian** [comment]
BTW, I'm using the AWS SDK so I don't have to deal with request signature. If feasible, later I will remove this dependency and implement the requests directly.

**Comment by Stvad** [comment]
Is it a hard requirement not to use the sdk? IMO given the number of services/complexity aws provides usage of sdk is justified in in the long term

**Comment by janober** [comment]
@Stvad Let's say I would prefer it. I wrote about it here:
https://docs.n8n.io/#/create-node?id=node-development-guidelines

So if there is a very good reason to use the SDK it is OK. But would like to have as many of the important nodes directly available to users. Installing a custom SDK for each of them would mean hundreds of dependencies and all the bad stuff they bring. I think I did test last week and did install the AWS-SDK in an empty folder and it had afterward over 45 MB. Not sure how much would fall away because it is already part of n8n but still a lot for a single SDK. 

Meaning if we can avoid it we should. Else it is maybe best to split it out in an own package (what I tried to avoid until now). But everything is always up to discussion!

**Comment by Stvad** [comment]
I wonder if using modularized version of sdk would make things better (https://github.com/aws/aws-sdk-js-v3) so only services you integrate with would be required. It also comes with typescript support now.

**Comment by mscansian** [comment]
Hi guys, sorry but I've been busy the last couple of days. Intend to finish this PR by next week (basically just removing the AWS SDK dependency).

@Stvad I understand your point, but I think I might stay with @janober argument. We will probably use lots of services from AWS, but the usage scope is very limited. For instance, with SNS the only endpoints I use are ListTopic and Publish, not much else. I think it's a waste of space to install an SDK as big as the aws-sdk just for a few endpoint on some services. Modularized version also wouldn't solve the problem. Since we use a few endpoint of several services (and not the other way around) we would end up with all the modules installed anyway.

**Comment by janober** [comment]
@mscansian Thanks a lot for the update! Looking forward to merge it once it is ready. I am sure it will help a lot of people! Have a nice evening!

**Comment by mscansian** [comment]
@janober I think the PR is ready for review. I've removed the aws-sdk and made the calls directly to the API. I've also added a field called `operation` it serves no purpose at the moment (because each node has only a single operation) but it's there if someone wants to implement other behaviors in the future.

**Comment by janober** [comment]
@mscansian Really great, thanks a lot! Great that you were able to implement it without adding large dependencies! I will check it out tomorrow. Btw. if the node has only one operation it is OK to not have an operation-parameter for it even if later more will get added. The reason is that when a workflow gets saved it only saves the none default parameters. That means it saves exactly the same when no parameter exists then if a parameter has the default value. So it is no problem to add an operation-parameter later on as long as the default value gets set accordingly. Everything will simply work exactly the same.

**Comment by janober** [comment]
Thanks a lot! Tested it now and merged it. Works perfectly, great work! Just made a few changes like:

  - Fixed some linting issues (like using "const" or "let" instead of "var"), added some semicolons, ...
  - Fixed issue when only one topic exists in SNS
  - Added the correct default operation for SNS node
  - Only return the result of the Lambda node. As the other data is input data already anyway and should not be needed. And I thought if it turns out to be needed later we can still add it back again. But taking it away would be a breaking change and would so be more complicated
  - If the Lambda Function fails it also fails the node instead of it returning success and the error. Did that to work identically with all other nodes and to work properly with in-node functionality like retry on error.

**Comment by janober** [comment]
Is released with n8n@0.26.0

**Pull request merged**
