### PR TITLE
Use n8n user rather than root

### PR DESCRIPTION
**Pull request by aneurinprice**
Builds and runs.
For security reasons, run as n8n user rather than root. Docs updated.

[Reasoning](https://engineering.bitnami.com/articles/why-non-root-containers-are-important-for-security.html)

### CODE REVIEW

**Comment by maledorak** [comment]
Hi @aneurinprice, thanks for your work, I thought about the same fix yesterday.
Could you check mine belowing proposition?

We could use `node` user with uid 1000, which is already created in `FROM node:12.9.1-alpine` instead of creating new user with uid 1001.

When we use n8n (UID=1001) user, the `~/.n8n` files will be don't owned by your default user (UID=1000) on your host pc.

And when we use `node` (UID=1000) user, then `~/.n8n` files will be owned by your default host pc user.

**Comment by aneurinprice** [comment]
Hi @maledorak , thank you for your feedback. 

> We could use node user with uid 1000, which is already created in FROM node:12.9.1-alpine instead of creating new user with uid 1001.

We could do this, you are correct. However, I feel that having a separate n8n user would be beneficial to keep permissions to a mimium and to keep things separate from `node:12.9.1-alpine ` so that if they change things upstream, we do not have to rewrite out Dockerfile. I feel that this is not very important, but nice to have. The number of layers stays the same so there is no harm to have this extra separation.

> instead of creating new user with uid 1001.

I have now set this to be a static UID (Thank you for giving this idea).

> files will be don't owned by your default user (UID=1000) on your host pc.

Is this a problem? The good thing about containers is that we do not need to think about the host PC. I run everything in Kubernetes and cannot see a problem with this.

**Comment by aneurinprice** [comment]
@janober What are your thoughts on this?

**Comment by janober** [comment]
Very sorry for answering so late. It is all still very stressful. Thanks a lot for looking into that. The change makes total sense!

However, did not merge it yet because the change would break it for all users who are already using the docker image. That is obviosly nothing I want to do. So hoped I find a minute at some point to find a solution for that. The only thing I could come up so far is to create a symlink in the image. Any better ideas?

**Comment by aneurinprice** [comment]
@janober 
> Any better ideas?
I could add an if statement to something like this:

```
if [ -d /root/.n8n ]; then
    cp -r /root/.n8n /home/n8n/
else
    echo "Assuming new install"
fi
```
What do you think?

**Comment by janober** [comment]
@aneurinprice Where would you add that? I guess it either would have to go in a special startup script, which would have to get added, or in the n8n-cli (even though that would be an option it would be none I would be willing to choose). Also not sure if it would actually be a superior solution to a symlink. Right now I can just think of additional problems.
Can you please explain your thoughts why you think that would be a better approach. Thanks!

**Comment by mvhirsch** [comment]
One approach that might work here is to simply not change the user in Dockerfile (using `USER n8n`, but in entrypoint. That should check 1.) permissions of current /.n8n folder (if root, chown to n8n) and 2.) fork a new PID 1 process with chown'd n8n user, running node.

This way user n8n will be used, running node, which indeed enhances security (since non-root user is doing work, instead of root).

Changing `USER n8n` in Dockerfile would require a major break, which could be considered within a major-release (with additional hints in upgrade-path).

**Comment by janober** [comment]
Closing this as I just merged #287 from @mvhirsch which solves that for now in a none-breaking way.

**Pull request closed without merging**
