### PR TITLE
fix(editor): Fix saving and connecting on LDAP setup form

### PR DESCRIPTION
**Pull request by ivov**
https://linear.app/n8n/issue/PAY-1748

https://community.n8n.io/t/users-setup-with-ldap/50405

### CODE REVIEW

**Comment by Joffcom** [comment]
@ivov just gave this is a quick test locally and it looks to be working for me, Happy to approve if needed.

**Comment by ivov** [comment]
@Joffcom Thanks for testing! I synced with Ricardo and he'll take this over, ideally this needs a test as well.

**Review by RicardoE105 — DISMISSED** [review]

**Comment by ivov** [comment]
Thanks @RicardoE105 :)

@Joffcom Can you please approve now? His last commit invalidated e2e.

**Review by Joffcom — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.52.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.52.0)

**Pull request merged**
