### PR TITLE
added Type field in Task resource of salesforce

### PR DESCRIPTION
**Pull request by KetanSomvanshi**

### CODE REVIEW

**Comment by RicardoE105** [comment]
@KetanSomvanshi, thanks for your contribution. I had to make some changes as the field within salesforce it's called `TaskSubtype` and not `Type`. You can see the changes here: https://github.com/n8n-io/n8n/pull/2171

**Comment by janober** [comment]
Thanks a lot. Got merged with #2171

**Comment by janober** [comment]
Got released with n8n@0.137.0

**Comment by KetanSomvanshi** [comment]
Thanks @RicardoE105 @janober

**Pull request closed without merging**
