### PR TITLE
fix(KoboToolbox Node): fix hook logs not working correctly

### PR DESCRIPTION
**Pull request by Yann-J**
- Support more hook log API parameters
- Fix hook log retry

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @Yann-J,

It looks like you have removed the actions which we have added to all Operation options, They will need to be added back in before we can merge this.

With the change to Hook Logs if I was previously using Limit or Return All in my workflow what is going to happen now with this change?

**Comment by Yann-J** [comment]
OK, done, I guess I didn't know what those were...

**Comment by Yann-J** [comment]
Regarding the changes to Get Hook Logs, the pagination was never working. This API does in fact not support pagination, only date filters.

**Comment by Joffcom** [comment]
Hey @Yann-J,

Perfect in that case as it won't really break anything we can run with that and get it merged. 

With the Action we added it for a future feature to all of the nodes.

**Review by Joffcom — APPROVED** [review]

**Comment by janober** [comment]
Got released with `n8n@0.198.0`

**Pull request merged**
