### PR TITLE
:bug: Fixes issue #651 and #652

### PR DESCRIPTION
**Pull request by RicardoE105**

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot @RicardoE105. I am just wondering about the "as_user" parameter. If it is depreciated and gets deleted after it has been set why do we keep the parameter in the first place? Should it not be deleted? Else people will set it and wonder why it does not work.

I also realized that it still gets used for "update". Does it still work there?

**Comment by RicardoE105** [comment]
Yes, I thought about deleting it but it seems like that field now just does not have to be sent. 

That field on the UI it's deciding whether the username is shown or nor. The field username just makes a difference when the access token is a bot token, if it's a user token then makes no difference.  Check the example below.

Using a bot token, the first message using the username and the second message without it.

image

Using a user token, first message sending username and second message without it.

image

I guess we can add that to the description of the fields. Something like `this field will be ignored if you are using a user token`.

With regard to the as_user on the update operation, I missed that field, however, I just tested it with both tokens and seems to make no difference so I would say it's safe to delete it from the update operation.

Slack is killing with token types.

image

**Comment by janober** [comment]
Ah ok makes sense. Then we should at least add the description as you did propose.

**Comment by janober** [comment]
Great, thanks a lot got merged.

**Comment by janober** [comment]
Got released with n8n@0.71.0

**Pull request merged**
