### PR TITLE
fix(editor): Handle `localStorage` being blocked/unavailable

### PR DESCRIPTION
**Pull request by netroy**

### CODE REVIEW

**Review by mutdmour — COMMENTED** [review]
Thanks for the quick fix. Can you please add some tests if possible? Thanks

**Comment by netroy** [comment]
> Thanks for the quick fix. Can you please add some tests if possible? Thanks

Not sure how to test this. any suggestions?

**Comment by netroy** [comment]
I'm not really sure how to add tests for this. If you don't have any suggestions, maybe we can merge this?

**Comment by mutdmour** [comment]
sorry missed the comment before.. no concrete suggestions how to test this.. let's merge it then

**Review by mutdmour — APPROVED** [review]

**Review by mutdmour — APPROVED** [review]

**Review by mutdmour — DISMISSED** [review]

**Review by mutdmour — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.15.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.15.1)

**Pull request merged**
