### PR TITLE
[WIP] Create new node for Sendinblue API

### PR DESCRIPTION
**Pull request by BWunderlich**
Concerning the following community thread I started an implementation for the Sendinblue API:
https://community.n8n.io/t/sendinblue-integration/47

### CODE REVIEW

**Comment by SAVE-POlNT** [comment]
Hello sir , im looking forward for this , i can help you if it is not finished yet

**Comment by BWunderlich** [comment]
Sorry, this is my very first Pull Request. Do I have to do anything to get this going? What are the next steps?

**Review by Mehdi-YC — APPROVED** [review]
this new package worked for me in local

**Comment by janober** [comment]
@BWunderlich is it ready for review? Because it still is marked as WIP in the title and contains TODOs in the code.

**Comment by nivb06** [comment]
Hi @BWunderlich, I see that this PR is WIP for a very long time
Since we are doing a clean up of our repo, I will close it for now. If you want to put it out of WIP status, feel free to reopen it again

**Comment by dudts** [comment]
Will there be a sendin blue node on n8n anytime soon?

**Comment by RicardoE105** [comment]
@dudts https://github.com/n8n-io/n8n/pull/3532

**Pull request closed without merging**
