### PR TITLE
Coda Integration (node)

### PR DESCRIPTION
**Pull request by RicardoE105**
@janober  I implemented just the row resource cuz I believe is what most people would use. I wil email the credentials so that you can test.

as always let me know pal.

### CODE REVIEW

**Comment by RicardoE105** [comment]
@janober just realized they just have a sign in with Google -.-

**Comment by janober** [comment]
Great, thanks a lot. Will check it out.

**Comment by janober** [comment]
I just had a short look. I saw the following issues:
 - The "docId" is part of the credentials even though it should be able to be set on the node. It should only then be in the credentials if the AccessToken would only work for one specific doc. But because it will work for all it should be separate.
 - After the above got changed there should then probably be a dropdown to select the document via "loadOptions"
 - The operations currently always just takes the values of the first item as there is no loop. So if the node is for example set to "delete" and there are 10 items with different `rowIds` it would try to delete 10x the row with the id of the first item and not delete the other 9.

**Comment by RicardoE105** [comment]
@janober will check it out.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by janober** [comment]
@RicardoE105 Great, thanks a lot! Have a nice afternoon!

**Comment by RicardoE105** [comment]
@janober let me know.

**Comment by janober** [comment]
Thanks a lot! Will check.

**Comment by janober** [comment]
Great, thanks a lot got merged.

Had to make some adjustments:
 - It was still not possible to create/get multiple rows at once as it did always just read the first item
 - It worked differently than other similar nodes like Airtable and Google-Sheets. So did it, for example, return the RAW-API output instead of just the actual data in which people are normally interested in. For cases that people want the RAW data, I added a special option.
 - I added back the "loadOptions" you had removed to also be able to select the table
 - Renamed the "Filters" to "Options" as the naming was misleading as it did not just contain filters
 - Changes the resource name from "Row" to "Table" to make it future proof if other things like docs, folders, ... get added.

I also saw that in one case you change the incoming item-data.
https://github.com/n8n-io/n8n/pull/156/files#diff-e1ef5f0ef2f355c80d55e8eada36e9d9R106
That is not allowed as the items are always just references and if they get changed they will mess up data for other nodes.
Here the information about that in the docs:
https://docs.n8n.io/#/create-node?id=do-not-change-incoming-data

**Comment by RicardoE105** [comment]
@janober saw the changes now I get it. Will keep this in mind for future nodes. Thanks

**Comment by janober** [comment]
Great and thanks a lot for all your hard work!

**Comment by janober** [comment]
Got released with n8n@0.40.0

**Pull request merged**
