### PR TITLE
1SaaS v2 node release

### PR DESCRIPTION
**Pull request by wemakefuture**

### CODE REVIEW

**Comment by wemakefuture** [comment]
@CLAassistant singed it

**Comment by wemakefuture** [comment]
> [CLA assistant check](https://cla-assistant.io/n8n-io/n8n?pullRequest=3233) Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/n8n-io/n8n?pullRequest=3233) before we can accept your contribution.**2** out of **3** committers have signed the CLA.✅ Pascal-Sch✅ Joffcom❌ wemakefuture
> 
> **wemakefuture** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/n8n-io/n8n?pullRequest=3233) it.

https://github.com/wemakefuture @janober its signed please approve!

**Comment by Joffcom** [comment]
Hey @wemakefuture,

Are you sure it was signed using the WeMakeFuture account? One of our internal chaps had an issue the other day where they didn't have the same email used on their Github account and once they added it they were able to sign the license agreement. I am not sure if we actually can overwrite the license agreement though as that would make it less useful.

Just to set some expectations with review timelines we are still working through older node improvements and bug fixes before working on new nodes but to make things easier we are working on a community node repository that will allow loading custom nodes in an easier way so we wouldn't be blocking anyone that wants to use the node. More information on this can be found here: https://community.n8n.io/t/community-code-contributions-and-short-term-roadmap/13545

**Comment by wemakefuture** [comment]
@Joffcom that might be for bigger customers a nightmere if a developer pushes with its account and you now need to add the developer on the main account - securitywise speaking a nightmere... Would suppose different approach. Please take this as a feedback.

**Comment by wemakefuture** [comment]
@Joffcom  can you please update us on the status?

**Comment by Joffcom** [comment]
Hey @wemakefuture,

We are still not into the new node PRs yet, we are however about to release our Community Node feature which will allow users to easily install nodes from NPM in the n8n interface.

**Comment by Joffcom** [comment]
Hey @wemakefuture,

Thanks for the contribution, We have now created a Community Node Repository which is our preferred method for new node submissions.

Once a node has been published to the Community Node Repository users will be able to install the node from their n8n interface and will be able to use your node quicker, You will also be able to update the node as needed without needing to wait for the review process.

In the future we may reach out to you about including your node in our main release, But for now I am going to close this PR.

You can find more information in the links below, If you have any questions about this or need any help let us know.

Building Community Nodes: https://docs.n8n.io/integrations/community-nodes/build-community-nodes/
Submitting Community Nodes: https://docs.n8n.io/integrations/creating-nodes/deploy/submit-community-nodes/
Published Nodes: https://www.npmjs.com/search?q=keywords:n8n-community-node-package

**Pull request closed without merging**
