### PR TITLE
feat(HTTP Request Node): Add additional tests for HTTP response encoding (no-changelog)

### LINKED ISSUE #11654: HTTP Request node fails with quoted encodings.
### Bug Description

PR #9869 introduced a bug where HTTP responses that quote the encoding breaks the autodetected content.

n8n now tries to decode the content with the literal `"utf-8"` instead of `utf-8`.
image

Based on the [RFC7231](https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.1) quotes are allowed and expected:
```
   A parameter value that matches the token production can be
   transmitted either as a token or within a quoted-string.  The quoted
   and unquoted values are equivalent.  For example, the following
   examples are all equivalent, but the first is preferred for
   consistency:

     text/html;charset=utf-8
     text/html;charset=UTF-8
     Text/HTML;Charset="utf-8"
     text/html; charset="utf-8"
```

### To Reproduce

Make an HTTP request with `Response Format: Autodetect` to a server that quotes the charset/encoding.

### Expected behavior

Response is decoded with the unquoted string

### Operating System

n8n docker image

### n8n Version

1.51.0 to master

### Node.js Version

n8n docker image

### Database

SQLite (default)

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by pemontto**
## Summary

Fixes #11654

This PR removes quotes from the encoding.

## Review / Merge checklist

- [X] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Comment by Joffcom** [comment]
@pemontto would it be worth adding a test as well?

**Comment by pemontto** [comment]
@Joffcom it definitely would. Let me see if I can work it out!

**Comment by Joffcom** [comment]
Hey @pemontto,

Thanks for the PR, We have created "GHC-412" as the internal reference to get this reviewed.

One of us will be in touch if there are any changes needed, in most cases this is normally within a couple of weeks but it depends on the current workload of the team.

**Review by netroy — COMMENTED** [review]
This unfortunately fixes only a small part of the problem. There are over a dozen places in the repo that are parsing `content-type` header without checking for additional quotes.
The proper way to fix this would be to fix this in a single place, and by using [`parse` from the npm package `content-type`](https://www.npmjs.com/package/content-type#contenttypeparseres), instead of reimplemting that logic ourselves.

**Comment by pemontto** [comment]
@netroy strategically that sounds like a great choice. The focus of this PR was to fix the regression introduced by parsing the content-type in #11654

**Review by netroy — APPROVED** [review]

**Pull request merged**
