### PR TITLE
Wordpress Node [WIP]

### PR DESCRIPTION
**Pull request by RicardoE105**

### CODE REVIEW

**Comment by RicardoE105** [comment]
@janober just finished the POST resource. I will add the user resource as well and let you know so that you can test it.

**Comment by RicardoE105** [comment]
Hey pal,

@janober I think you can test now. I will email you the credentials.

**Comment by janober** [comment]
Really cool @RicardoE105 thanks a lot! Got merged.

Before I merged it I had to make some small changes:
 - some "option" fields had as default `[]` set instead of a string which caused errors
 - changed credential field `domain` to `url` as domain only suggest "example.com" which would not work as it expects the full URL. Also added placeholder text to make it even clearer/
 - simplified error handling a little bit by removing some try/catch blocks as they were not always needed
 - changed "name" property to be lower case ("Wordpress" => "wordpress")
 - changed the node color to have the Wordpress blue
 - renamed "Filters" to "Options" for `getAll` as it also includes none filters like "Order By"

Additionally did I have to deactivate the `delete` features: 
 - delete post did always return 404 for me 
 - delete user does not seem to be a way to define which user should be deleted

**Comment by janober** [comment]
Got released with n8n@0.44.0

**Pull request merged**
