### PR TITLE
feat(WebSocket Node): New node

### PR DESCRIPTION
**Pull request by michael-radency**

### CODE REVIEW

**Comment by amirhmoradi** [comment]
Hi @michael-radency @Joffcom 

I would love to see websocket trigger node in N8N. Could you please share the info why this WIP got closed/rejected?
Do you think we could get websocket support in the near future?

Thanks

**Comment by michael-radency** [comment]
Hello @amirhmoradi, time is main reason, it was my side project to check how n8n would work with sockets, for now I can not say if/when it will be continued, trigger works fine but options can be expanded, and also I need to add node for publisher/server

**Comment by jeroenvandiepen** [comment]
Are there any plans to develop this further and include it in n8n?

**Comment by bartekus** [comment]
As Im still fairly new to n8n so I would need some guidance to carry this implementation into fully operational state. Objective being to facilitate trigger/listening on top of the already implemented send functionality.

Please advice!

**Pull request closed without merging**
