### PR TITLE
Add clickup time tracking v2

### PR DESCRIPTION
**Pull request by ghost**
- fixed one typo
- extended getAssignees with task related API call
- added all V2 API calls for time tracking
- marked old API calls as deprecated

### CODE REVIEW

**Comment by RicardoE105** [comment]
@evomation just reviewed and made some improvements here #1010 . If you can check them out and provide feedback would be awesome. This will be now moved to internal review and then it will be merged. Again, Thanks very much.

**Comment by evomation** [comment]
@RicardoE105 I like your changes. In the first place I wondered why you deleted the fields to get a certain task, but now I understand the idea and appriciate it!

**Comment by janober** [comment]
Thanks a lot! Got merged a few days ago with #1010

**Comment by janober** [comment]
Got released with n8n@0.87.0

**Pull request closed without merging**
