### PR TITLE
fix(core): Use `exec` in docker images to forward signals correctly

### PR DESCRIPTION
**Pull request by guoard**

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @guoard,

Thanks for the PR, Which issue is this fixing? We made a change in v1 so I am wondering if this is reverting something we have now intentionally done.

**Comment by guoard** [comment]
Hello @Joffcom,

Thank you for your time.

I noticed an issue with the `docker-entrypoint.sh` file. Without the `exec` command, the signal doesn't forward to the container correctly. As a result, when running `docker exec -it n8n sh -c "ps auxf"`, the output shows additional process.

Before:
```
PID   USER     TIME  COMMAND
    1 node      0:00 tini -- /opt/n8n/custom-entrypoint.sh
    7 node      0:00 {custom-entrypoi} /bin/sh /opt/n8n/custom-entrypoint.sh
    8 node      0:07 node /usr/local/bin/n8n
   36 node      0:00 ps auxf
```

When the command `docker stop n8n` is executed, the container exits with a status code of `143`.

But, when using `exec` in the `docker-entrypoint.sh` file, the output improves as follows:

After:
```
$ docker exec -it n8n sh -c "ps auxf"
PID   USER     TIME  COMMAND
    1 node      0:00 tini -- /opt/n8n/custom-entrypoint.sh
    7 node      0:09 node /usr/local/bin/n8n
   35 node      0:00 ps auxf
```

Additionally, I observed that when executing `docker stop n8n`, not only does the container exit with a `0` code, but we also see this informative log within the container:

```text
Stopping n8n...
```

**Review by netroy — APPROVED** [review]
This definitely makes sense. Thanks for fixing this 🙏🏽

**Comment by janober** [comment]
Got released with [`n8n@1.1.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.1.0)

**Pull request merged**
