### PR TITLE
20200904 release

### PR DESCRIPTION
**Pull request by Sou1Aced**
# Details

Adding to ClockifyTrigger.nodes.ts to return information.

# Steps to test changes

1. Run "npm run dev" to view the website on your localhost.
1. Add Clockify trigger on the website.
1. Add your Clockify API Key and set the right workspace.
1. Execute and make sure it returns the right table of information.

### CODE REVIEW

**Comment by Sou1Aced** [comment]
@janober pull[bot] can not sign the CLA because it is just a bot, so I was hoping you could waive that one.

**Comment by janober** [comment]
Thanks a lot. But could you please create a new PR with a single commit. It looks like all that changed is 1 single line of code but there are 13 commits in that PR adding and removing things.

**Comment by Sou1Aced** [comment]
@janober Thank you for the feed back, I have cleaned it up. Let me know if there is anything else.

**Comment by janober** [comment]
Thanks a lot. Great. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.81.0

**Pull request merged**
