### PR TITLE
Fix slack as_user

### PR DESCRIPTION
**Pull request by inn0le**
See https://github.com/n8n-io/n8n/issues/652#issuecomment-651060385

### CODE REVIEW

**Comment by RicardoE105** [comment]
I just tested but I do not seem to notice the difference. I wonder what am I missing?

**Branch: master**

Test1
User token
as user set to true
image

Test2
User token
as user set to false
username ricardo
image

Test3
Bot token
as user set to true
image

Test4
User Token
as user set to false
username ricardo
image

**Your branch**

Test1
User token
 as user set to true
image

Test2
User token
 as user set to false
 username ricardo
image


Test3
Bot token
as user set to true
image

Test4
Bot token
as user set to false
username ricardo
image

**Comment by inn0kenty** [comment]
I got it. I use legacy user token.

My Test 1 and Test 2 on master:




And Test 1 and Test 2 on my branch:

**Comment by RicardoE105** [comment]
@inn0kenty yes, I was using the new tokens not a legacy one. Thanks for the clarification.

**Comment by janober** [comment]
Thanks a lot to both of you. Got merged and will be released with the next version.

**Comment by janober** [comment]
Just got released with n8n@0.73.0

**Pull request merged**
