### PR TITLE
📌 Pin chokidar verison

### PR DESCRIPTION
**Pull request by ivov**
3.5.3 is breaking the build

### CODE REVIEW

**Review by BHesseldieck — APPROVED** [review]

**Comment by ivov** [comment]
chokidar's own tests are failing, cannot tell why snyk is failing.

**Comment by janober** [comment]
Thanks a lot for fixing this. Got merged.

**Comment by TrySound** [comment]
https://github.com/paulmillr/chokidar/issues/1191

**Comment by janober** [comment]
Got released with `n8n@0.160.0`

**Pull request merged**
