### PR TITLE
feat(Google Ads Node): Update api version to v11

### PR DESCRIPTION
**Pull request by Joffcom**
https://community.n8n.io/t/google-ads-400-bad-request-error/21709

### CODE REVIEW

**Comment by boriside** [comment]
Please review and merge this PR - otherwise the google ads node is unusable.

**Comment by Joffcom** [comment]
Hey @boriside I have just checked and it is still in the internal review process, I will see if I can get bumped up a bit so we can merge it for the next release.

**Comment by boriside** [comment]
@Joffcom thank you- yes, google ads is one of the platforms with a lot of automation possible - looking forward to the node working again.

**Comment by Joffcom** [comment]
Hey @boriside hopefully it will be this week.

**Comment by boriside** [comment]
Hello @Joffcom we are still looking very much forward to it.

**Review by maspio — APPROVED** [review]

**Comment by janober** [comment]
Got released with `n8n@0.211.1`

**Pull request merged**
