### PR TITLE
ci: Set up Turborepo cache for GitHub actions runner (no-changelog)

### PR DESCRIPTION
**Pull request by ivov**

### CODE REVIEW

**Review by netroy — DISMISSED** [review]

**Review by netroy — COMMENTED** [review]
can we set this up for the `test` task as well?

**Comment by ivov** [comment]
> can we set this up for the `test` task as well?

To clarify, do you mean [this `test` task](https://github.com/n8n-io/n8n/blob/54e3838daed1f0931a04ba76cfd1ea7519c0e382/.github/workflows/ci-pull-requests.yml#L67)? I'd expect the tasks that run after TR is configured on the runner will check the cache?

**Comment by netroy** [comment]
I meant any step in any of the workflows that executes `pnpm test` or `pnpm build` should use this cache.

**Comment by ivov** [comment]
I originally did it only for PR checks because this action is experimental, but I added others now if you're okay with it. For `unit-test` in `ci-pull-requests.yml` from what I understand the cache should available, as it is configured during the first job `install`.

**Review by netroy — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@0.232.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.232.0)

**Pull request merged**
