### PR TITLE
Improved/bug fixed collecting of custom fields based on project and issue

### PR DESCRIPTION
**Pull request by jemos**
The current way of collecting custom fields from project and issue type was not working. While checking the source code I noticed that the endpoint used to collect the fields `/api/2/field` will take all existing fields from Jira and filter based on project and issue type. However, at least in my case Jira was not returning project and issue type information in these field entries. 

Looking for more information I found [this document](https://developer.atlassian.com/server/jira/platform/jira-rest-api-examples/#getting-metadata-for-creating-issues-examples) in Jira that describes the two official endpoints for querying the project/issue metadata depending on server version.

In this pull-request I'm using the endpoint for the older version for better backward compatibility. I'm not experienced in Typescript so feel free to suggest code corrections/improvements.

### CODE REVIEW

**Comment by jemos** [comment]
Looking again at Jira documentation, it seems that there could be different endpoints depending on the type of Jira deployment. The [Cloud API documentation](https://developer.atlassian.com/cloud/jira/platform/rest/v2/api-group-issue-fields/) does in fact refer to `/fields` endpoint, but it also supports the `/createmeta` endpoint. At first sight the later seems to better support both Jira deployments.

**Comment by RicardoE105** [comment]
Thanks very much for your contribution. We will let you know when is released.

**Comment by janober** [comment]
Thanks a lot. Got merged with #1877

**Comment by janober** [comment]
Got released with n8n@0.124.0

**Pull request closed without merging**
