### PR TITLE
MQTT node: Add SSL/TLS support

### PR DESCRIPTION
**Pull request by fredericalix**
I need to encrypt my mqtt data between my ESP32 and n8n.
I am not a JS/TS dev, but I did my best to add SSL/TLS cert support.

I tested my modifications and Regular and Triggers MQTT n8n run very well with my SSL certififcates..
The network traffic is correctly encrypted

### CODE REVIEW

**Comment by krynble** [comment]
Hi @fredericalix 

Sorry about the delay in reviewing this.

Also, pardon my ignorance but I have no idea how to set MQTT with SSL enabled and how to extract the certificates.

I would like to replicate the steps you did in order to test it. Can you point me to some instructions on how to do so?

Thank you!

**Comment by krynble** [comment]
Also, if you find it useful, feel free to share access to a testing instance. If you prefer, you can email me directly to omar@n8n.io

Thanks!

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.137.0

**Pull request merged**
