### PR TITLE
Feature/kubernetes deployment example

### PR DESCRIPTION
**Pull request by abelb01**
Added an example of a kubernetes deployment with a postgres DB that I figured others would find helpful and can build on.

### CODE REVIEW

**Comment by ChrisChinchilla** [comment]
So I found I could only get this to work if I removed the `storageClassName: "default"` lines

**Comment by asos-bradleyabel** [comment]
You’ll neeed an existing storage class. This deployment doesn’t create it. I just added in default as a placeholder. I can clarify that in a readme

**Comment by abelb01** [comment]
You’ll neeed an existing storage class. This deployment doesn’t create it. I just added in default as a placeholder. I can clarify that in a readme

**Comment by Joffcom** [comment]
Hey @abelb01,

Thanks for the time you spent on this one, We only keep basic deployment examples in our main repo now with our official ones being in our docs project althoguh we already have a couple of k8s examples in there.

For now I am going to mark this one as closed and maybe in the future if we start a community deployment guides project we can include this.

**Pull request closed without merging**
