### PR TITLE
feat(RabbitMQ Trigger Node): Add exchange and routing key options

### PR DESCRIPTION
**Pull request by teomane**
RabbitMQ trigger needs binding for some cases. For example, I need to consume some domain events in my application and they are published with routing key.

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @teomane,

Does this break anything if you don't have an exchange or routing key on the trigger? I am not that familiar with Rabbit but do the same options also not apply to other connections?

I would also move them to additional options if they are not required.

**Comment by teomane** [comment]
Exchange and queue are the fundamental components of RabbitMQ. Exchange enables the routing of messages to one or more queues. Mostly, exchanges are used to send a message in RabbitMQ. The association of a queue with an exchange is called “binding”. As is, during binding, you can provide the exchange (required) and the routing key (optional). Since the RabbitMQTrigger node only receives queue information, the binding process must be done through the RabbitMQ management interface.

This does not break anything if you don’t have an exchange or routing key. You can move them to additional options. An option like 'binding' would be great. When this option is selected, exchange is mandatory, and routing key can be provided optionally.

**Comment by Joffcom** [comment]
Hey @teomane,

Perfect, So the only thing I would do is drop them to `Add Options` as they are not a required to use the node that way if someone wants to use them they have the option to add them without causing any confusion.

**Comment by teomane** [comment]
Thank you for your response. Should I update the pull request to make this change?

**Comment by Joffcom** [comment]
Hey @teomane,

If you can that would be great, Sadly I can't do it because you have created the PR from your master branch rather than making a new branch for this.

**Comment by teomane** [comment]
Hey @Joffcom, I pushed the changes

**Review by Joffcom — DISMISSED** [review]

**Review by Joffcom — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.17.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.17.0)

**Pull request merged**
