### PR TITLE
feat(XeroOAuth2Api.credentials): add more scopes to Xero O Auth

### PR DESCRIPTION
**Pull request by jhaltercmu2020**
add more scopes to XeroOAuth2Api.credentials

### CODE REVIEW

**Comment by jhaltercmu2020** [comment]
@jspizziri FYI

**Comment by jhaltercmu2020** [comment]
@janober Could you take a look at this whenever you get the chance?

**Comment by mrogers-5s** [comment]
@janober Given that Justin's github account has been deleted, please close this PR in favor of https://github.com/n8n-io/n8n/pull/3156

**Comment by RicardoE105** [comment]
Closing in favor of #3156

**Pull request closed without merging**
