### PR TITLE
⚡ Add a Bot user option to Slack credentials

### PR DESCRIPTION
**Pull request by umireon**
Slack recommends New Slack apps use a Bot token.
https://api.slack.com/authentication/basics#scopes

It also fixes the icon problem posted on the forum.
https://community.n8n.io/t/slack-send-message-as-bot/4830/11

### CODE REVIEW

**Comment by RicardoE105** [comment]
@umireon thanks for your contribution. Jus checked the PR and that no matter you change the scopes the node would still use always the user's access token instead of the bot's access token. To change that behavior and actually use the access token depending on the tokenType, a change to [GeneticFunctions.ts](https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Slack/GenericFunctions.ts#L54) has to be made. Also, not sure if changing the authQueryParameters to type options will cause issues. You might need to add a different parameter and reference the value in the authQueryParameters. The Github OAuth2 credentials are a good example of who to reference values.

**Comment by umireon** [comment]
@RicardoE105 Thanks for your feedback!

I will take a look into GeneticFunctions.ts.

> You might need to add a different parameter and reference the value in the authQueryParameters.

This is exactly what I needed.

> The Github OAuth2 credentials are a good example of who to reference values.

Where can I find an example in https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Github/Github.node.ts?

**Comment by RicardoE105** [comment]
@umireon just made the change [here](https://github.com/n8n-io/n8n/pull/2086). Can you test it locally and let me know if that works and make sense to you? Thanks.

**Comment by umireon** [comment]
@RicardoE105 Sure, I will.

**Comment by Joffcom** [comment]
Hey @umireon,

Did you get a chance to test?

**Comment by michael-radency** [comment]
closed in favor of https://github.com/n8n-io/n8n/pull/2086 with additional changes

**Pull request closed without merging**
