### PR TITLE
Rocketchat Integration

### PR DESCRIPTION
**Pull request by RicardoE105**

### CODE REVIEW

**Comment by RicardoE105** [comment]
@janober done pal. Let me know if something.

**Comment by janober** [comment]
@RicardoE105 Are you online right now? Because just checked and saw that large parts use again spaces instead of tabs. I can fix it (takes literally a second) but then it would again list me instead of you. So wanted to check if you want to fix it instead.

**Comment by RicardoE105** [comment]
@janober I will fix it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by RicardoE105** [comment]
@janober can you comment on the line that has the issue? I think I do not quite understand it. Does your code editor show you the issue? If so, are you using visual studio code?

**Comment by RicardoE105** [comment]
@janober  My editor was not reading the .editorconfig file. It's fixed!

**Comment by janober** [comment]
Sorry was already in bed. Great thanks a lot! Will check and merge then later.

**Comment by janober** [comment]
Great, thanks a lot like always. Got merged!

**Comment by lknite** [comment]
For folks who come by later, a work-around to watch a channel or for a direct message, and send a webhook in response:
https://gitlab.com/lknite/webhook-chat-client

**Pull request merged**
