### PR TITLE
Intercom Node [WIP]

### PR DESCRIPTION
**Pull request by RicardoE105**

### CODE REVIEW

**Comment by RicardoE105** [comment]
@janober It's done, it allows you to create new leads on Intercom. Let me know if something, gonna email you with the info so that you can test it.

**Comment by janober** [comment]
Great thanks a lot! I will check. But think we have to be careful that we do not create a lot of nodes which do only one thing. It should probably normally at least support the 2-4 most important functions to not have to revisit the node directly again as soon as one person actually wants to use it.

Apart from that did I see that you always use "executeSingle" instead of "execute". I would advise against that. It is OK to use it for a very basic node we know we will probably do not have to extend in the future. But for all third party integrations using "executeSingle" will result in us having to rewrite it again in the future to use "execute". The reason for that is that as soon as functionality has to get added to query data (like here return all existing users) "executeSingle" can not be used anymore. Which means it has to be changed to "execute" anyway. That does not just cause a lot of unnecessary work down the road it also increases the risk of introducing new bugs.

**Comment by RicardoE105** [comment]
@janober Cool, gonna keep adding the list of features you told me about which are:

add/edit lead
add/edit user
add/edit company

I do agree with the executeSingle function, gonna change it to use execute!

**Comment by janober** [comment]
@RicardoE105 Great thanks a lot!

Sorry about the "executeSingle" function. That is really on me. I have to add something regarding that to the documentation.

**Comment by janober** [comment]
For now added at least a description here:
https://github.com/n8n-io/n8n/commit/af5c7e75fac8ed23ac01e77baed9ecdf09e93055

**Comment by RicardoE105** [comment]
@janober Hey, question? should not the options be using the display name instead of the name for the label the users see?

image

image

**Comment by janober** [comment]
@RicardoE105 Yes you are right. That looks like a bug.

**Comment by RicardoE105** [comment]
@janober it's not a bug. The properties inside options are name and value, I was using displayName and name. -.-

**Comment by janober** [comment]
Ah great to hear that it is not a bug. Not so great that it is inconsitent though...

**Comment by RicardoE105** [comment]
@janober hey, looks like when the id is not a number always shows the error

image

**Comment by RicardoE105** [comment]
@janober just noticed that when you copy a field from the json tab on the UI it copies the node.

image

{
  "nodes": [
    {
      "parameters": {
        "resource": "company",
        "operation": "view",
        "viewBy": "id"
      },
      "name": "Intercom",
      "type": "n8n-nodes-base.intercom",
      "typeVersion": 1,
      "position": [
        450,
        450
      ],
      "credentials": {
        "intercomApi": "intercom apikey"
      }
    }
  ],
  "connections": {}
}

**Comment by RicardoE105** [comment]
@janober I think it's done pal. Let me know if something or if I should add another resource.

**Comment by janober** [comment]
@RicardoE105 Great, thanks a lot! I will check tomorrow. Fixed the issue with the numbers you had. Could sadly not reproduce the copy issue. For me it really just copies the selected text for me. What OS and what browser are you using?

**Comment by RicardoE105** [comment]
>@RicardoE105 Great, thanks a lot! I will check tomorrow. Fixed the issue with the numbers you had. Could sadly not reproduce the copy issue. For me it really just copies the selected text for me. What OS and what browser are you using?

@janober Mmm I’m using Mac OS with google chrome. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by janober** [comment]
Great thanks a lot for your hard work. That node is now really very powerful!

Had to make some changes. Some fixes and some changes to make the node work closer to existing similar nodes like the Pipedrive one:
 - removed not needed "default" property from options
 - set defaults for boolean properties to "false" instead of empty string
 - renamed "Options" to "Additional Fields" for create/edit operations (as they are properties to set and not options and to work identically like similar nodes like Pipedrive)
 - renamed operation "view" to "get"
 - renamed operation "list" to "getAll"
 - fixed issue that it did not return companies/users/deals as separate items. So people would not have been able to use it directly without doing additional transformations with the data
 - made it possible to query all data with "list" (now "getAll") (before only the first 60 could be returned)
 - changed that update functionality works identically for all resources

Can you please check if you see any issues with my changes and if they make sense also in your eyes. Thanks a lot!

**Comment by RicardoE105** [comment]
Hey, @janober just checked everything makes sense. I was wondering when doing the node about pagination. I will keep this in mind for the upcoming nodes. Thanks.

**Comment by janober** [comment]
@RicardoE105 Thanks for creating the node (is an amazing addition!) and also for checking! I really have to add guidelines to the docs about things like that. To make it easier for developers and to make sure that the nodes all work in a similar fashion.

**Comment by janober** [comment]
Got released yesterday with n8n@0.36.1

**Pull request merged**
