### PR TITLE
[N8N-4265] Improve docker compose setup with postgres

### PR DESCRIPTION
**Pull request by netroy**
I was working on self-hosting this on AWS Fargate, and ported over some of the changes from there into the docker-compose setup.

[related PR](https://github.com/n8n-io/n8n/pull/3384)

### CODE REVIEW

**Comment by netroy** [comment]
would it be possible for you to look at  `execution_variables.executions_mode` on `Instance started` event on telemetry?

If not many users are using the `regular` mode, then it might not make sense to maintain a dedicated example for that.

**Comment by Joffcom** [comment]
Hey @netroy,

I am sure I can ask our product team to look into that but based on support questions and conversations I have had with users I would say the regular running mode is a lot more popular than queue mode.

**Comment by netroy** [comment]
@Joffcom move the `queue` mode stuff to a new example

**Comment by netroy** [comment]
@Joffcom does this look better?

**Comment by Joffcom** [comment]
Hey @netroy,

It does look good, Not had a chance to test it yet but I like it.

**Review by ahsanv — APPROVED** [review]

**Pull request merged**
