### PR TITLE
fix(OpenAI Node): Update node to account for URL in credentials

### PR DESCRIPTION
**Pull request by RicardoE105**
## Summary

Missed this one in https://github.com/n8n-io/n8n/pull/12175

## Related Linear tickets, Github issues, and Community forum posts

[https://linear.app/n8n/issue/ADO-2887/[n8n-nodes]-move-openai-base-url-option-to-credentials](https://linear.app/n8n/issue/ADO-2887/%5Bn8n-nodes%5D-move-openai-base-url-option-to-credentials)

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [x] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Review by mutdmour — COMMENTED** [review]
Looks good. Can you please add a unit test here? Thank you

**Review by mutdmour — APPROVED** [review]

**Review by mutdmour — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.74.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.1)

**Comment by janober** [comment]
Got released with [`n8n@1.74.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.1)

**Comment by janober** [comment]
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)

**Pull request merged**
