### PR TITLE
Extend ActiveCampaign functionality

### PR DESCRIPTION
**Pull request by quansenB**
This PR extends the ActiveCampaign nodes capabilities. 

- [x] CRUD Deal operations
- [x] Create and Update Deal Note
- [ ] Delete Deal Note - Not supported by AC API
- [x] Ecommerce Orders
- [x] Ecommerce Customers
- [x] Ecommerce Abandoned Cart
- [x] Ecommerce Order Products
- [x] Deepdata Connections

### CODE REVIEW

**Comment by quansenB** [comment]
This is ready for review now. I tried to stay as close to the preexisting coding style of the node as possible to keep it readable. The code and all new functionality is manually tested.

**Comment by janober** [comment]
@quansenB Wow really great! That looks like it is by far the most complex and powerful node n8n has after it gets deployed. Thanks a lot for creating it! It is very appreciated and I am sure very many users will be very happy about it!

Before having a deeper look. I wanted to ask if the changes you made could break workflows for anybody who uses the old version of the node. Like did any defaults change, anything renamed, any return data changed, any other behavior change, ...?

**Comment by quansenB** [comment]
@janober No, I did not change any of the previos functionality/generic functions/defaults etc.

**Comment by janober** [comment]
@quansenB Thanks a lot for the info. 

Just realized that the most files use spaces instead of tabs (which is the default for the project, just to keep everything the same). Can you please change that (normally is really just cut and paste and the IDE fixes it). I would do that myself but then they would get contributed to me in blame and as you wrote them that does not seem fair. Thanks a lot!

**Comment by janober** [comment]
Perfect. Thanks a lot for those great additions. Got merged. 

I will release a new version with it in the next 1-2 hours.

**Pull request merged**
