### PR TITLE
Disqus node

### PR DESCRIPTION
**Pull request by trojanh**
Adds Disqus Node with following Forum API support
  - [ForumDetails](https://disqus.com/api/docs/forums/details/)
  - [ListThreads](https://disqus.com/api/docs/forums/listThreads/)
  - [ListPosts](https://disqus.com/api/docs/forums/listPosts/)
  - [ListCategories](https://disqus.com/api/docs/forums/listCategories/)

These are the most important Disqus APIs as we need to mostly deal with comments for posts in a forum.

### CODE REVIEW

**Comment by janober** [comment]
Great, thanks a lot. Just checked it. Looks great except two things because they work differently than other nodes in n8n:

- There are some fields that have as default "[]" set (like for example "attach"). In regular fields, users should not be forced to type in data in JSON. They should rather just list that values comma-separated. The node itself should then split the values apart and add them as JSON to the request.
- All the "Get All ..." operations should actually return all the results like in other similar nodes. Example "Zendesk" at "Ticket -> Get All". Should normally have by default a limit set that is the max of what can be returned with single request and also have the option "Return all" which then returns all data by automatically making multiple paginated requests in the background.

It would be great if you could adjust that. Thanks a lot!

**Comment by trojanh** [comment]
@janober I tried sending the array as JSON and it was not working, it there any special way to send data, because below won't work as our `qs` is an object and the same keys will overwrite the old values?
`attach=v1&attach=v2`

above works from Postman but am not able to make it work using the `qs` object. 

Also, I have added returnAll method and it works fine.

**Comment by janober** [comment]
Thanks a lot for making the changes and creating the node in the first place. Really great!

I fixed now the remaining issues and made some improvements. Can you please check if everything looks correct to you. Thanks!

Will then release it with the next version.

**Comment by trojanh** [comment]
Changes look great @janober , thanks for helping me with that. There was a small change that was needed to the PR, so I have raised a PR here
https://github.com/n8n-io/n8n/pull/247

I have tested the array query parameters and they look great. Thanks again 👍

**Comment by janober** [comment]
Thanks for fixing the issues, just got merged.

The query parameter fix is a little bit ugly and annoying but sadly nothing we can do about it. At least it works now.

**Comment by janober** [comment]
Got released with n8n@0.50.0

**Pull request merged**
