### PR TITLE
Improve MongoDb node

### PR DESCRIPTION
**Pull request by bianpratama**
This PR improves MongoDb node:
- Organize each MongoDb node operations to its own files.
- Add `projection` and `objectIdFields` to list of options.
- Implement MongoDb projection to `find` operation.
- Add `handleObjectIdFields` and `handleObjectId` to utils, can handle array of `ObjectId` in the field or inside nested `$in`. They are used for parsing query with `ObjectId` in `find` and `delete` operations, and for parsing data with `ObjectId` in `insert`, `update`, and `bulkUpdate` operations. 
- Implement `bulkUpdate` operation.

### CODE REVIEW

**Comment by luizeof** [comment]
hello @bianpratama ... could you add [my pull requests](https://github.com/n8n-io/n8n/pulls?q=is%3Aopen+is%3Apr+author%3Aluizeof++mongodb) along with your work in this pull? I believe it could add up a lot and the n8n team could pay more attention to node mongoDB needs.

**Comment by michael-radency** [comment]
Hello @bianpratama , can you please merge current upstream master into your branch, there are some merge conflicts since MongoDB node was restructured a lot

**Comment by nivb06** [comment]
Hi @bianpratama, thanks for your contribution!
I'm closing this PR for the moment as per @michael-radency 's comment
Feel free to open it up again once the issue has been addressed

**Comment by michael-radency** [comment]
Hello @bianpratama I did continue your PR here: https://github.com/n8n-io/n8n/pull/3163, as I was not able to push updates to your branch

**Pull request closed without merging**
