### PR TITLE
Gmail node

### PR DESCRIPTION
**Pull request by erin2722**
Here is a Gmail Node for n8n!

### CODE REVIEW

**Comment by joffreyjochum** [comment]
Any idea of the date this feature will be available ?

**Comment by janober** [comment]
Should be released with the next version. It is currently under review internally and we are having some discussions about improvements before it gets merged.

**Comment by cristomoya-dev** [comment]
hello, the gmail node returns the message in mime format. Not very friendly for the normal user

**Comment by RicardoE105** [comment]
@cristomoya-dev thanks for the feedback. Just to make sure, you mean that the text of the email it's not there but the base64 encoded version of it?

**Comment by cristomoya-dev** [comment]
> @cristomoya-dev thanks for the feedback. Just to make sure, you mean that the text of the email it's not there but the base64 encoded version of it?

exacto, eso

**Comment by janober** [comment]
Thanks a lot @erin2722! Got merged with #856

@cristomoya-dev that problem got fixed.

Will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.78.0

**Pull request closed without merging**
