### PR TITLE
Change 21 node icons to SVG

### PR DESCRIPTION
**Pull request by tanay1337**
The code in n8n will have to be updated so that the SVG icons fit in well. This PR can be merged after that change is merged.

### CODE REVIEW

**Comment by RicardoE105** [comment]
YES @tanay1337

**Comment by RicardoE105** [comment]
@janober with the change you made I guess this can be merged right?

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.113.0

**Pull request closed without merging**
