### PR TITLE
feat: Allow `eslint-config` to be externally consumable

### PR DESCRIPTION
**Pull request by ivov**

### CODE REVIEW

**Review by netroy — APPROVED** [review]
Should we then also start publishing `@n8n_io/eslint-config` with the release process? Right now there is a version of this package on NPM, but it's very old and outdated, as we had manually published it.

**Comment by ivov** [comment]
> Should we then also start publishing `@n8n_io/eslint-config` with the release process? Right now there is a version of this package on NPM, but it's very old and outdated, as we had manually published it.

Ideally yes! We'd like to use this for the `@n8n/tournament`, the new tmpl replacement lib. But if it's too much trouble, I can just copy the files for now.

**Comment by ivov** [comment]
> > > Should we then also start publishing `@n8n_io/eslint-config` with the release process? Right now there is a version of this package on NPM, but it's very old and outdated, as we had manually published it.
> > 
> > 
> > Ideally yes! We'd like to use this for the `@n8n/tournament`, the new tmpl replacement lib. But if it's too much trouble, I can just copy the files for now.
> 
> or, we can manually publish this package one more time, after these changes are all in `master`

Thank you! Let me know if I can take care of it.

**Comment by janober** [comment]
Got released with [`n8n@1.1.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.1.0)

**Pull request merged**
