### PR TITLE
:sparkles: Send console.log messages to editor-UI

### PR DESCRIPTION
**Pull request by janober**
Makes it possible for nodes to send data to the session of the browser console which did start it. So will only work in "manual" mode.

Implemented for now that it forwards all `console.log` messages from Function & FunctionItem nodes. It will make it much easier to debug code in Function-Nodes as no access to the terminal output of the n8n instance is needed anymore.

Example:
Screenshot from 2021-05-22 11-32-46

### CODE REVIEW

**Review by ivov — COMMENTED** [review]
Awesome feature! We checked this with @BHesseldieck.

**Comment by janober** [comment]
Perfect, thanks a lot!
Removing that unnecessary `await` for `pushInstance.send` really made a lot of stuff so much simpler.

**Review by BHesseldieck — APPROVED** [review]

**Comment by janober** [comment]
Got merged.

**Comment by janober** [comment]
Got released with n8n@0.122.0

**Pull request merged**
