### PR TITLE
Update check-issue-template.yml

### PR DESCRIPTION
**Pull request by pragyamishra56**
Github issue / Community forum post (link here to close automatically):

### CODE REVIEW

**Comment by pragyamishra56** [comment]
This is my first pull request

**Comment by Joffcom** [comment]
Hey @pragyamishra56,

There are no file changes here, What change are you trying to make?

**Comment by pragyamishra56** [comment]
> Hey @pragyamishra56,
> 
> could you provide me more information did i mistake

**Comment by Joffcom** [comment]
Hey @pragyamishra56,

There is no actual change that I can see so I am not sure what you were trying to do so it is hard to know where the mistake is.

With the issue template check I am planning to remove it soon so it will be less of an issue.

**Pull request closed without merging**
