### PR TITLE
Add JSON params on company

### PR DESCRIPTION
**Pull request by dokime7**
- Add JSON params field on company create and update
- Hide Additionnal fields and Update fields when JSON params is used
- Move JSON body field from Update fields to primary fields (on contact update) to standardize with contact create and company.
- Remove "simple" field on company and replace by rawData field that do the same thing to standardize with contact

Unfortunately there is some breaking changes but I think that is needed because this Mautic node haven't the same behavior between its resources and operations.

### CODE REVIEW

**Comment by RicardoE105** [comment]
@dokime7, thanks for your contribution. However, you removed and renamed a couple of parameters. That sadly will be a breaking change. We try to avoid breaking changes as much as possible, especially in nodes such as Mautic, which is pretty popular in the community.

**Comment by dokime7** [comment]
Yes, I know, it's unfortunate that few fields are not consistent...🤢

Some examples:

- Contact / Create:
  - JSON Parameters true: the body field appears => OK
- Contact / Update:
  - JSON Parameters true: not body field appears but it's in Update Fields => ??

- Contact / Create:
  - RAW Data option is used to return full response
- Company / Create:
  - "Simple" field is used to return a non full response.......

Bad user experience with this node 😬

**Comment by dokime7** [comment]
So, I will revert all breaking changes and add only what I need.

**Comment by RicardoE105** [comment]
@dokime7 yes, agree. I think that was one of the first nodes I created. It definitely needs some improvements. Once node versioning is released, we will create a V2 of this node without breaking people's workflows.

**Comment by RicardoE105** [comment]
@dokime7, sorry for the late response. The question is, why do you want to send JSON instead of filling the fields directly. Is it because some parameters are missing? If so, which ones are missing so that I can add them?

**Comment by RicardoE105** [comment]
Also, do not understand the companyemail parameter. According to the API that parameter cannot be set when creating a contact? What am I missing? 

https://developer.mautic.org/#create-company

**Comment by RicardoE105** [comment]
The happens when the parameterspublishing only and minimal (company:getAll)? According to the API, those parameters do not exist.

https://developer.mautic.org/#list-contact-companies

**Comment by RicardoE105** [comment]
@dokime7 ok was able to figure the issue with the parameter. The documentation does not show all the parameters that can be set. Made some improvements [here](https://github.com/n8n-io/n8n/pull/2087). 

Thanks very much for your contribution.

**Comment by janober** [comment]
Got merged with #2087

**Comment by dokime7** [comment]
Sound good, thanks

**Comment by janober** [comment]
Got released with n8n@0.134.0

**Pull request closed without merging**
