### PR TITLE
Add .circleci/config.yml

### PR DESCRIPTION
**Pull request by reconsumeralization**

### CODE REVIEW

**Review by reconsumeralization — COMMENTED** [review]
Approve!

**Comment by janober** [comment]
Thanks for the PR but do not understand. We do not use circleci and we do not have planned to use it.

**Comment by janober** [comment]
I will close this PR for now as we are not using circleci and looks additionally also more like an example than something functional.

**Review by reconsumeralization — COMMENTED** [review]
Test

**Pull request closed without merging**
