### PR TITLE
Add MongoDB Aggregation (Aggregate)

### PR DESCRIPTION
**Pull request by luizeof**
Allows the use of Aggregation (https://docs.mongodb.com/manual/aggregation/).

> An aggregation pipeline consists of one or more stages that process documents:
> - Each stage performs an operation on the input documents. For example, a stage can filter documents, group documents, and calculate values.
> - The documents that are output from one stage are input to the next stage.
> - An aggregation pipeline can return results for groups of documents. For example, return the total, average, maximum, and minimum values.

## Example:

```js
[
   { $match: { status: "urgent" } },
   { $group: { _id: "$productName", sumQuantity: { $sum: "$quantity" } } }
]
```

On-Demand Materialized Views works fine, which makes the N8N a great view maintainer for reports:

```js
[
   { $match: { date: { $gte: startDate } } },
   { $group: { _id: { $dateToString: { format: "%Y-%m", date: "$date" } }, sales_quantity: { $sum: "$quantity"}, sales_amount: { $sum: "$amount" } } },
   { $merge: { into: "monthlybakesales", whenMatched: "replace" } }
]
```

### CODE REVIEW

**Comment by Daniel-Wist** [comment]
Hi, when will be this feature released ?
Thanks,
Stefan

**Comment by stefankranz** [comment]
Hi, when will be this feature released ?
Thanks,
Stefan

**Review by balasista — APPROVED** [review]

**Comment by balasista** [comment]
Tested it with a local copy and it works.

**Comment by stefankranz** [comment]
How can i install these code on my own n8n ?

**Review by michael-radency — APPROVED** [review]

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with `n8n@0.167.0`

**Pull request merged**
