### PR TITLE
GitHub: Adds operations to get and create PR reviews

### PR DESCRIPTION
**Pull request by jkettmann**
This PR adds two new operations to the newly created "Pull Request" resource of the existing GitHub node:

- get reviews for a PR
- create a review for a PR

I basically just copy-pasted existing code so I hope the code standards are met. Let me know if something should be changed :smile:

### CODE REVIEW

**Comment by jkettmann** [comment]
I'd like to use this functionality soon but I'm not sure how to proceed. Any thoughts? @janober @RicardoE105

**Comment by RicardoE105** [comment]
@jkettmann I'm sorry. We somehow missed this PR. Reviewing at this moment.

**Comment by RicardoE105** [comment]
Ok, I just reviewed it, and it's working fine. I just had to make some minor improvements. Again, very sorry we missed this PR. Thanks very much for your contribution. Looking forward to the next one. We will let you know when is released.

**Comment by janober** [comment]
Really sorry that we missed that one @jkettmann! Got now merged with #1346 and released with the next version.

Thanks a lot for your contribution!

**Pull request closed without merging**
