### PR TITLE
feat(Git) "Disable ceritificate check" option

### PR DESCRIPTION
**Pull request by salehjafarli**
## Summary

This pr adds new ``Disable certificate check`` boolean option to Git node to disable ssl verification. 

Note: I have noticed that Git addConfig option already helps to add key value git configuration to given repository. Unfortunately Git addConfig option doesn't help me during cloning operation because repository hasn't been created yet.

Please lmk if this change is okay, so i can provide tests

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Comment by netroy** [comment]
Can you please update the description to add more info about what problem this is trying to solve, and if any other users have reported this as a problem?

**Comment by salehjafarli** [comment]
> Can you please update the description to add more info about what problem this is trying to solve, and if any other users have reported this as a problem?
Hi, I want to be able to disable ssl certificate checks just like I can do it with http request node. I have tried to use addConfig option but that requires git repository and that adds config only for given repository but I need this during git clone.

**Comment by Joffcom** [comment]
@salehjafarli does this not help?

https://docs.n8n.io/hosting/configuration/configuration-examples/custom-certificate-authority/

**Comment by salehjafarli** [comment]
> @salehjafarli does this not help?
> 
> https://docs.n8n.io/hosting/configuration/configuration-examples/custom-certificate-authority/

Hi @Joffcom. I appreciate your answer, but the deal is I don't have certificate file to add it to certificate store that's why I want to ignore certificate check.

**Comment by netroy** [comment]
> I don't have certificate file to add it to certificate store

You don't need the private cert, you only need the public key, which can be extracted using `openssl s_client -showcerts`

**Comment by salehjafarli** [comment]
@netroy, thanks i will be closing the pull request then.

**Pull request closed without merging**
