### PR TITLE
Notion node V2

### PR DESCRIPTION
**Pull request by RicardoE105**

### CODE REVIEW

**Comment by todaysday** [comment]
Can you add
Add page updated event to trigger
as well
please

**Comment by RicardoE105** [comment]
@todaysday yes I'm adding everything you saw in the other PR to this one.

**Comment by todaysday** [comment]
@RicardoE105 thanks

**Comment by jubstuff** [comment]
Hi @RicardoE105, is there any way I can support this PR move forward?

Thank you for your work!

**Comment by RicardoE105** [comment]
@todaysday We had some issues with a bug in the workflow editor and notion. We found a workaround, and we are going to move it forward. It will be in either this week or next week's release.

**Comment by todaysday** [comment]
Hi @RicardoE105 
Could you please tell me how to update "person" field with n8n
I've tried notion user id and email and each time I have same error
photo_2021-12-08 12 47 13
Could you please give me a clue which value must be used to fill this field?

**Comment by todaysday** [comment]
> Hi @RicardoE105 Could you please tell me how to update "person" field with n8n I've tried notion user id and email and each time I have same error photo_2021-12-08 12 47 13 Could you please give me a clue which value must be used to fill this field?

@RicardoE105 did you have a chance to check me message? have you any clue for me?

**Comment by RicardoE105** [comment]
@todaysday You need to reference the ID. There seems to be a bug there. In the meantime, you can set it as an array instead of a single value. For example `{{ [$node["Set"].json["person"]] }}`. That should solve it. I will fix the issue in the V2.

**Comment by todaysday** [comment]
Thanks a lot

**Comment by janober** [comment]
Great, thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with `n8n@0.157.0`

**Pull request merged**
