### PR TITLE
fix(ci): Setup a separate workflow action to test for pushes on master

### PR DESCRIPTION
**Pull request by netroy**

### CODE REVIEW

**Review by ivov — COMMENTED** [review]
1. Reasonable to rename `tests.yml` to `ci-pull-requests.yml` and `test-master.yml` to `ci-master.yml`? Tests are only part of the checks.
2. Is there something available like `extends` to avoid duplication?

**Comment by netroy** [comment]
> 1. Reasonable to rename `tests.yml` to `ci-pull-requests.yml` and `test-master.yml` to `ci-master.yml`? Tests are only part of the checks.

Done

> 2. Is there something available like `extends` to avoid duplication?

From what I undestand, github doesn't support any easy ways to `include` stuf from other yaml files. Neither do they support yaml anchors.

**Review by ivov — APPROVED** [review]
> From what I undestand, github doesn't support any easy ways to include stuf from other yaml files. Neither do they support yaml anchors.

Possibly with [this](https://github.blog/changelog/2021-08-25-github-actions-reduce-duplication-with-action-composition/)? Can be tech debt though.

**Review by csuermann — APPROVED** [review]

**Comment by janober** [comment]
Got released with `n8n@0.193.0`

**Pull request merged**
