### PR TITLE
Feature/mqtt

### PR DESCRIPTION
**Pull request by RicardoE105**
Improvements to #862

### CODE REVIEW

**Comment by blackr8t** [comment]
Wow, that's a great code! It's a better feature! Thank you!! :)

**Comment by RicardoE105** [comment]
@blackr8t quick update. This is currently in an internal review and will be merged soon. Thanks.

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.80.0

**Pull request merged**
