### PR TITLE
SIGNL4 Node: Attachment Support

### PR DESCRIPTION
**Pull request by rons4**
Attachment support added for the SIGNL4 node.

### CODE REVIEW

**Comment by rons4** [comment]
I signed the CLA and it said something like "thank you for signing" but it seems it does not recognize it here.

**Comment by lublak** [comment]
@rons4 jear. You need to force push to trigger it after signing.
That's how it worked for me.

**Comment by rons4** [comment]
Thanks @lublak, I tried to change something and then did:
git push --force
It seems the CLA still shows as pending.
The CLA page shows: You have agreed to the CLA for n8n-io/n8n

**Comment by rons4** [comment]
Hello, just in case someone has the same issue, I had some issues with signing the CLA. I just changes my GitHub email address for this request and now it seems to work.

**Comment by RicardoE105** [comment]
@rons4 thanks for the contribution. However, can you please explain to me how is this different from what the node currently does? It seems like the only difference is that instead of sending the data using JSON, now it's sending the data using multipart/form-data. As far as I know, this node was working fine so why change it to send the data as multipart/form-data now?

Also now the operation `alert:send` returns a string instead of a JSON. This will break existing workflows that expect the data to be returned as JSON.

**Comment by rons4** [comment]
Hi @RicardoE105, thanks and the new functionality is the ability to send an attachment now. Therefore, the whole encoding was changed. The attachment parameter was present before but unfortunately attachments did not work. Now you can send an alert with an image or audio attachment.

You are right, the node should stay compatible with previous versions and there was an issue with the return text. I changed this and it should return a JSON object again.

By the way, is there any way to use "https" instead of the "request" module?

**Comment by RicardoE105** [comment]
@rons4 Gotcha. It's working because of a change in the API? Because I have in my mind, this was working just fine. Either way will check it out.

All HTTP request has to use the helper method `this.helpers.request!(options)` (Which uses the request library under the hood). I wonder why do you want to use the HTTP module instead. To send multipart-form/data using the request library check [here](https://www.npmjs.com/package/request#forms). 

Let me know if you have any questions.

**Comment by rons4** [comment]
Hi @RicardoE105, thanks and indeed attachments never seemed to work. To be honest I am not sure at what point the attachments parameter came in here. Anyway, now it is used and sends the attachment through to SIGNL4. There was no API change of SIGNL4 in this regards.

I used the manual approach for multipart-form/data because I had this code available. My question to use the "https" library instead of "request" came up because I saw a discussion on the n8n community mentioning that "request" was depreciated and that it might get replaced by another method.

I hope this makes sense.

**Comment by RicardoE105** [comment]
`Hi @RicardoE105, thanks and indeed attachments never seemed to work. To be honest I am not sure at what point the attachments parameter came in here. Anyway, now it is used and sends the attachment through to SIGNL4. There was no API change of SIGNL4 in this regards.`

I just checked, and I created the node with the attachment feature. Again, as far I remember, I tested it. You can check the commit [here](https://github.com/n8n-io/n8n/commit/a6a4eed711011eb8f9dfa7ede09e8efa2a51485c). Either way, if it does not, it does not work.

`I used the manual approach for multipart-form/data because I had this code available. My question to use the "https" library instead of "request" came up because I saw a discussion on the n8n community mentioning that "request" was depreciated and that it might get replaced by another method.`

Yes, exactly for that reason. We will soon be working on replacing the request library. If everybody uses the same method this.helpers.request!(options), we can change this function to change it for most of the nodes. I encourage you to use the built-in method.

As soon as that is added, I can review it again. Let me know if you have any questions. Thanks.

**Comment by rons4** [comment]
OK, great and thanks. I already use this.helpers.request!(options) to send the request. So, I guess all should be fine here now.

**Comment by janober** [comment]
Got released with n8n@0.105.0

**Pull request merged**
