### PR TITLE
feat: Add Plan and Execute Agent Type

### PR DESCRIPTION
**Pull request by MasonGeloso**
**Plan and Execute Agent Type Implementation**
Implementation of LangChain's experimental Plan and Execute agent type: https://js.langchain.com/docs/modules/agents/agent_types/plan_and_execute

https://github.com/n8n-io/n8n/assets/6699213/826f66c8-a314-4a89-8940-291317e39479

### CODE REVIEW

**Review by OlegIvaniv — COMMENTED** [review]
Thanks for this, @MasonGeloso!
Looks great, there's just one thing that would be great to add: configurable system message similar to what we have with other agent. 
The default for `humanMessageTemplate` in Langchain is:
```js
export const DEFAULT_STEP_EXECUTOR_HUMAN_CHAT_MESSAGE_TEMPLATE = `Previous steps: {previous_steps}

Current objective: {current_step}

{agent_scratchpad}

You may extract and combine relevant data from your previous steps when responding to me.`;
```

Other than that I'd be happy to get this in.

**Comment by MasonGeloso** [comment]
@OlegIvaniv I'll work on that today. Thanks for the feedback.

**Comment by MasonGeloso** [comment]
Screenshot 2023-11-07 at 9 22 47 AM

Done and PR updated.

**Review by OlegIvaniv — APPROVED** [review]
Thank you for adding the system message, LGTM!

**Pull request merged**
