### PR TITLE
Master <- Dev

### PR DESCRIPTION
**Pull request by omrijoyous**
Github issue / Community forum post (link here to close automatically):

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @omrijoyous 

Did you mean to put this PR in? Are you also bypassing our license to enable features?

**Comment by omrijoyous** [comment]
This PR was created by mistake, we only use this branch for our development environment since we are testing n8n functionality in house.
Here is what we are working on and testing.
- Added Elastic Search logic , this gives us more search capabilities.
- Added S3 integration for better data recovery.
- Made some changes around the way that environment variables are being used, we combined multiple environment variables into one, we made this for Redis and PostgresDB.
- We also faced an issue when running Postgres locally and remotely and this was because the db connection used an ssl setting that made some problems locally.

**Comment by Joffcom** [comment]
Hey @omrijoyous 

The bit I was interested in was the bypassing of the license to enable the enterprise features.

If these are required for your tests I am sure a trial license could have been issued.

I have passed this to our team internally to investigate further.

**Comment by omrijoyous** [comment]
No problem.

**Pull request closed without merging**
