### PR TITLE
Workflows in folders

### PR DESCRIPTION
**Pull request by romainminaud**
Github issue / Community forum post (link here to close automatically): https://community.n8n.io/t/arranging-workflows-in-folders/2197/40

### CODE REVIEW

**Comment by mutdmour** [comment]
Hi Romain.. Thanks for great work on this. We will take a look soon and share some feedback.

**Comment by MasonGeloso** [comment]
@romainminaud @mutdmour Did this get moved to another branch? I would love to see this feature merged with master then to ai-beta where I currently work from.

**Comment by Joffcom** [comment]
@MasonGeloso yes this has moved from this PR to another branch. A closed PR only means we have closed the PR it doesn't mean that something won't happen.

**Comment by danielgwilson** [comment]
What happened with this? Would love to help—serious need for us to stay on the platform

**Comment by hugorn** [comment]
How to follow this functionality?

**Comment by edsonalanis** [comment]
Any plans for this feature to go into production?
I believe that, like me, many in the community need this feature, because when we have a lot of projects it becomes unfeasible to maintain them only by tags.

**Comment by JeremieAlcaraz** [comment]
Totally agree... Some news about ? Thanks 🙏

**Pull request closed without merging**
