### PR TITLE
N8N-3123-node-metabase

### PR DESCRIPTION
**Pull request by agobrech**
Contain the new metabse node + the renovate token, for the reponses I made two type of responses that can be tried on the getAll operation for the Question ressource and the get operation on the Question ressource 

https://community.n8n.io/t/metabase-node/7738

### CODE REVIEW

**Review by krynble — APPROVED** [review]
LGTM

**Review by krynble — APPROVED** [review]
Looks good!

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with `n8n@0.188.0`

**Pull request merged**
