### PR TITLE
salesforce base url option added

### PR DESCRIPTION
**Pull request by taha-sonmez**
Unable to authenticate to Salesforce, if it has a custom domain. I've added a simple base url field to do the work.

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @taha-sonmez,

Thanks for the PR I have taken a quick look and this looks like it would currently break the current salesforce node for all users so in its current state we won't be able to accept this.

One solution could be to have a toggle option on the credential for "custom url" and if enabled it could hide the other options and show an input field where you could enter your url.

**Comment by taha-sonmez** [comment]
Hi @Joffcom ,

You are absolutely right. I've updated. Can you please review it again?

**Comment by Joffcom** [comment]
Hey @taha-sonmez 

It looks better but I still don't think it would work as the node itself is not looking for the url set in the credential.

We would also need you to sign the cla before we can accept this.

**Comment by taha-sonmez** [comment]
Hey @Joffcom,

It redirects me to the URL that I've provided in "Base URL".

Screenshot 2023-06-24 at 2 11 43 PM
Screenshot 2023-06-24 at 2 12 10 PM

**Comment by Joffcom** [comment]
Hey @taha-sonmez 

That is just for the credentials though the node itself is still set to use the normal urls for prod and sandbox.

**Comment by Joffcom** [comment]
Just adding that the internal ticket for tracking this is `NODE-613`

**Pull request closed without merging**
