### PR TITLE
Github OAuth support

### PR DESCRIPTION
**Pull request by RicardoE105**
@janober Did this as a test. But not sure how the tokens are gonna be refreshed? 

Should we detect the expired token error and use the updateCrendetials method and then retry the request?

### CODE REVIEW

**Comment by janober** [comment]
Great, thanks a lot. I will check it out later.

Because of the refresh. It takes care of that automatically here:
https://github.com/n8n-io/n8n/blob/oauth-support/packages/core/src/NodeExecuteFunctions.ts#L143-L169

So it simply makes the request with the token it has and if it gets a "401" response, it tries to refresh the token and then make the request again. That can be improved in a later step by checking first if the token is still valid before using it and refreshing it before the first request gets made to save some time. But not really a priority right now.

**Comment by RicardoE105** [comment]
@janober dude so cool. Looking forward to develop new nodes. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by janober** [comment]
Yes, I am also! It will finally open the door to finally create previously no possible integrations and keeps them simple to create at the same time.

**Comment by janober** [comment]
Thanks a lot! I did make, however, some changes to use the above mentioned specific OAuth request logic. Additionally, did I use special Github OAuth credentials that extend the base one and set some defaults (as the URLs are for example always the same for all users). That makes it a little bit simpler to set up.

Can you please check if the template loads still fine for you. Because for me it broke with your change. So I adjusted the code and hope that my change does now not break it for you again ;-)

**Comment by RicardoE105** [comment]
@janober just tested it and worked perfectly.

**Pull request merged**
