### PR TITLE
docker - support for saving binaries outside container

### PR DESCRIPTION
**Pull request by majso**
mapping of /data folder to host

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot. But we do not want that people save data to the `~/.n8n` folder. Only n8n should save data for |"internal" use (like config, nodes, database, binary-data,  ...). That is also the reason why it is a hidden folder (starts with a dot).
If anybody wants to persist data they should use another folder (literally any except `.n8n`).

**Comment by majso** [comment]
Hi, Thanks a lot for explanation. It would be great to have description how to map /data folder in docker-compose readme. Right now, at least for me, it is not possible to save binary file internally inside container because of permissions with default docker-compose settings.

**Comment by janober** [comment]
It is actually already part of the [documentation](https://docs.n8n.io/getting-started/installation/advanced/server-setup.html#docker-compose-example):
Screenshot from 2022-01-03 11-33-09

Did you not see that yet or is it not clear enough?

**Comment by majso** [comment]
Yes, it's my bad sorry, I didn't notice that in documentation.

**Pull request closed without merging**
