### PR TITLE
Add Mailcheck integration

### PR DESCRIPTION
**Pull request by nosovk**
Documentation will be here: https://github.com/n8n-io/n8n-docs/pull/484

### CODE REVIEW

**Comment by nosovk** [comment]
@tanay1337 may we merge?

**Comment by RicardoE105** [comment]
@nosovk I reviewed the PR and added some improvements. It's currently under internal testing. It might be included in the next release. We will let you know. Thanks for your contribution.

**Comment by janober** [comment]
Thanks a lot. Got merged with #1690

**Comment by janober** [comment]
Got released with n8n@0.117.0

**Pull request closed without merging**
