### PR TITLE
Add Baserow node

### PR DESCRIPTION
**Pull request by jrmi**
[Baserow](https://gitlab.com/bramw/baserow) is an open source Airtable alternative. This PR add a Baserow node to list, read, create, update data through the API.

### CODE REVIEW

**Comment by jrmi** [comment]
Ready for reviews. Documentation PR in progress.

**Comment by jrmi** [comment]
See also [documentation PR](https://github.com/n8n-io/n8n-docs/pull/562).

**Comment by ivov** [comment]
@jrmi Thank you very much for your contribution. Will review as soon as I can.

**Comment by janober** [comment]
Thanks a lot for your contribution. Got merged with #1938 and just released with n8n@0.129.0

**Comment by jrmi** [comment]
Good news thanks!

**Comment by kwmc-lucas** [comment]
Thanks for this.

I've added a Feature Request for a Baserow Trigger node on the forum: https://community.n8n.io/t/add-baserow-trigger-node/16131

**Pull request closed without merging**
