### PR TITLE
feat: docker images

### LINKED ISSUE #1624: the -rpi image does not work
**Describe the bug**
The `latest-rpi` image does not work, failing with `chown: cannot access '/home/node/.n8n': No such file or directory` everytime,

**To Reproduce**

```sh
docker run --rm n8nio/n8n:latest-rpi
```

**Expected behavior**
Should work.

**Environment (please complete the following information):**
irrelevant.

**Additional context**
Should also probably use the same Dockerfile as the amd64 image, just passing a different platform on build:

```sh
docker build -t n8n:0.114.0-rpi --platform linux/arm64 --build-arg N8N_VERSION=0.114.0 .
```

Also a good idea to create docker manifests (aka multi-architecture images) (can be done using `docker buildx` or `docker manifest`).

### PR DESCRIPTION
**Pull request by caarlos0**
- make the default image multi-arch
- improve github actions to create the multi-arch images
- remove the specific -rpi stuff

closes https://github.com/n8n-io/n8n/issues/1624

### CODE REVIEW

**Comment by crazy-max** [comment]
@caarlos0 Hey mate was going to send a PR too :laughing:. My action `crazy-max/ghaction-docker-buildx@v3` is archived. I suggest the following workflow instead:

```yaml
name: Docker Image CI

on:
  push:
    tags:
      - n8n@*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:14})
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: ./docker/images/n8n
          build-args: |
            N8N_VERSION=${{steps.vars.outputs.tag}}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/n8n:${{ steps.vars.outputs.tag }}
            ${{ secrets.DOCKER_USERNAME }}/n8n:latest
      -
        name: Build (debian)
        uses: docker/build-push-action@v2
        with:
          context: ./docker/images/n8n-debian
          build-args: |
            N8N_VERSION=${{ steps.vars.outputs.tag }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/n8n:${{ steps.vars.outputs.tag }}-debian
            ${{ secrets.DOCKER_USERNAME }}/n8n:latest-debian
```

**Comment by caarlos0** [comment]
ah nice! will rebase, thanks!

**Comment by ahsanv** [comment]
@crazy-max i have added your suggested change for reducing the image size as well here. feel free to review!

Also rebase with master.

Thank you both for the contributions! @crazy-max @caarlos0

**Review by crazy-max — APPROVED** [review]
Overall LGTM but we could improve build time by using a matrix strategy. It would also be good to allow building the image on PR to be able to detect regressions. I will create a follow-up PR with this.

**Comment by janober** [comment]
Thanks a lot got merged!

Cool @crazy-max looking forward to it!

**Comment by janober** [comment]
Got released with n8n@0.125.0

**Pull request merged**
