### PR TITLE
run a new external hook once active workflows have been initialized

### PR DESCRIPTION
**Pull request by sebto**
I need to run a code when all existing active workflows are initialized. I added a new external hook. Let me know if there is any specific consideration or if I need to change it.

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with `n8n@0.158.0`

**Comment by rmaroun** [comment]
@sebto how can you use this hook? same for the afterCreated hook?

**Comment by sebto** [comment]
@rmaroun Yes. I've used it like other external hooks.

**Comment by rmaroun** [comment]
@sebto can you share an example on how you used it in your code? or how you configure it? thanks

**Comment by sebto** [comment]
@rmaroun You need a js file that exports an object like this:
`
const hooks = {
	activeWorkflows: {
		initialized: [
			async () => {
				// something to do once all active workflows have been initialized
			},
		],
	},
};
`
Then, you should pass the path of that js file to n8n in this environment variable: `EXTERNAL_HOOK_FILES`.

**Comment by rmaroun** [comment]
@sebto where did you put your hooks.js file and when you add the .env file and give a value to your `EXTERNAL_HOOK_FILES` something like `"./hooks.js"` and then run `npm run start` it isn't working (not calling the external hook function in the hooks.js where I put a `console.log`. Can you share your setup?

**Comment by janober** [comment]
Why do you require this functionality?

**Comment by ralphsomeday** [comment]
@janober this functionality (externalHooks) helps to react to changes in n8n to send events to other services. For example could be that I have multiple n8n instances deployed and would like to centralize the executions results in a single database or any other use case that might come up for workflow hooks, execution hooks, credential hooks...

**Comment by rmaroun** [comment]
@janober this functionality (externalHooks) helps to react to changes in n8n to send events to other services. For example could be that I have multiple n8n instances deployed and would like to centralize the executions results in a single database or any other use case that might come up for workflow hooks, execution hooks, credential hooks...

**Comment by sebto** [comment]
@rmaroun I'm not sure if you have read [scaling n8n document](https://docs.n8n.io/getting-started/installation/advanced/scaling-n8n.html#how-it-works) or not.
I think the correct way to add more instances is to add workers and webhook servers. Then n8n centralize execution results itself.

**Comment by sebto** [comment]
@rmaroun You just need to add the absolute path of the js file into `EXTERNAL_HOOK_FILES`. I think the location of the file is not important. But, It depends on your use case. In my case, I had to add that file to cli package because It needed access to Db object. I added this external hooks because I had to start a central event listener right after all workflows got activated.

**Comment by rmaroun** [comment]
@sebto maybe this was not the best example but external hooks are a very nice way to be able to use n8n internal triggers to do an action and if needed send data out of n8n. I finally figured it out by putting the .js file in the `/packages/cli/bin` folder and it works.

**Pull request merged**
