### PR TITLE
fix(editor): Cap NDV Output View Tab Index to prevent rare edge case

### PR DESCRIPTION
**Pull request by CharlieKolb**
## Summary

`currentOutputIndex` may end up out of bound as `outputIndex` is not reactive. Rather than making it a ref which complicates user selection I prefer capping the public `currentOutputIndex` as this "remembers" the selected branch if it reappears (unless the user selected a new one in the meantime).

After:

https://github.com/user-attachments/assets/99485886-767a-4314-a1a7-d1f5df30668e

See ticket for before video.

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/ADO-2763/bug-ndv-outputview-breaks-when-on-outdated-tab-during-new-test-step

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Review by MiloradFilipovic — DISMISSED** [review]
Works as expected, kudos for adding a comment there 🙌🏻
Two questions though:
- Can we add a test for it?
- Is it easy to update the output panel as number of outputs change so we don't see the generic branch name at all?

**Comment by CharlieKolb** [comment]
They're great questions, I had the same ones for myself :D

There aren't any existing test for tabulation so it'd quite involved, and considering this PR merely narrows an invalid range to a valid one I'm tempted to forgo adding one here.

I considered updating the shown branches but I don't think we actually want this behavior, as the user might have relevant data in the selected tab.
If the user then messes with node settings that unexpectedly (to them) change the tab count, it would cause data to disappear without the user running the node, which seems less desirable than showing `Branch 1` and `Branch 2`.
Though I did not look into where those new branch names come from and if we can avoid that.

**Comment by MiloradFilipovic** [comment]
> They're great questions, I had the same ones for myself :D
> 
> There aren't any existing test for tabulation so it'd quite involved, and considering this PR merely narrows an invalid range to a valid one I'm tempted to forgo adding one here.
> 
> I considered updating the shown branches but I don't think we actually want this behavior, as the user might have relevant data in the selected tab. If the user then messes with node settings that unexpectedly (to them) change the tab count, it would cause data to disappear without the user running the node, which seems less desirable than showing `Branch 1` and `Branch 2`. Though I did not look into where those new branch names come from and if we can avoid that.

Makes sense, good to go on my end then

**Review by MiloradFilipovic — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.68.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.68.0)

**Pull request merged**
