### PR TITLE
feat(editor): add readonly state for nodes

### PR DESCRIPTION
**Pull request by cstuncsik**

### CODE REVIEW

**Review by alexgrozav — DISMISSED** [review]
Awesome work!

**Review by MiloradFilipovic — DISMISSED** [review]
Tested with the hard-coded `readOnly`values, looks good to me. Seems like it doesn't affect the current functionalities and will work good once credentials logic is added.

**Review by MiloradFilipovic — APPROVED** [review]
Approving again after conflicts are resolved.

**Comment by janober** [comment]
Got released with `n8n@0.200.0`

**Pull request merged**
