### PR TITLE
feat(core): Add endpoint to create free AI credits

### PR DESCRIPTION
**Pull request by RicardoE105**
## Summary

Builds on top of https://github.com/n8n-io/n8n/pull/12361

See context in the linear ticket below.

- Introduce new endpoint to create free AI credits managed credential. 
- Make sure managed credentials cannot be edited.
- Make sure to return the `isManaged` flag to the FE. We will need to this to hide the fields in the credentials modal.

## Related Linear tickets, Github issues, and Community forum posts

https://linear.app/n8n/issue/ADO-2998/[n8n-backend]-add-new-endpoint-to-save-managed-credentials

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Review by mutdmour — DISMISSED** [review]
LGTM

**Review by mutdmour — DISMISSED** [review]

**Review by mutdmour — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.74.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.1)

**Comment by janober** [comment]
Got released with [`n8n@1.74.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.1)

**Comment by janober** [comment]
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)

**Comment by janober** [comment]
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)

**Pull request merged**
