### PR TITLE
Asana node Improvements

### PR DESCRIPTION
**Pull request by einSelbst**
This adds some more functionality to the Asana node which we want to use for some github integration with asana.

- move task on board
- add/remove tag from task
- several loadOptions helper
- add comment to task
- set assignee & assignee_status on task

Thanks @RicardoE105 for your support. The following forum question is related https://community.n8n.io/t/some-question-regarding-the-asana-node-development/1728/4 . I haven't had time to integrate the following https://github.com/RicardoE105/n8n/commit/656fcdea2a255d4251c7d99ae23ad32a1a963e39 unfortunately as I don't really have time to do programming in the coming weeks.

### CODE REVIEW

**Comment by RicardoE105** [comment]
ahhh I had done a lot of improvements on the other branch and also the project getAll you did here. If I worked on top of what you did here I will have to redo the work again. It would be easier if I include what you did here into what I did in the commit RicardoE105@656fcde. The issue with doing so it's  Github will not attribute the latest changes to you. If you do not mind I can do so, but if you mind then you will have to include the changes I did in this commit RicardoE105@656fcde and then let me know to review again. Either way thanks for taking the time to contribute to the project.

**Comment by RicardoE105** [comment]
@einSelbst Ok, I included your changes on top of what I had done here https://github.com/n8n-io/n8n/pull/858. Depending on what you decide to do I can merge that PR or you can copy that into this branch so you get the attribution. Again, thanks. Nice work.

**Comment by einSelbst** [comment]
Thanks @RicardoE105 , I need to do a little bit more testing and will push then.

**Comment by einSelbst** [comment]
Hey @RicardoE105 , this is good from my side. 2 minor things, you usually didn't use `else if`, let me know if this is important for you so I can change it, but I thought it wouldn't be the case that e.g. two different operations would happen at the same time and an `else if` would safe the other conditions to be evaluated when one is matched also I admit the win is neglectable.

The other thing, I used `null` as a default value for **adding an assignee** to a task. Sending `null` actually unsets the assignee, which is functionality which I need. Because of the load options helper usually only actual users would be suggested. I can be overwritten tough. Maybe you have an idea how to cleanly allow to remove an assignee.

**Comment by RicardoE105** [comment]
@einSelbst just had a quick look and everything seems ok. Tomorrow will test again and let you know if something.  Thanks

**Comment by einSelbst** [comment]
@RicardoE105 any updates on this?

**Comment by RicardoE105** [comment]
@einSelbst finishing this today. Will keep you posted.

**Comment by RicardoE105** [comment]
Ok just finished and this is fine with me. The last changes can be found here #920. I Will now move this to internal review and then will be merged. Thanks @einSelbst

**Comment by einSelbst** [comment]
Thank you for your support @RicardoE105 !

**Comment by janober** [comment]
Thanks a lot. Got merged with #920

**Comment by janober** [comment]
Got released with n8n@0.81.0

**Pull request closed without merging**
