### PR TITLE
Replacing the /deep/ selector

### PR DESCRIPTION
**Pull request by ggirardi1**
https://community.n8n.io/t/editor-ui-building/778

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot @claassistantio! Can you please sign the Contributor License Agreement that I can merge the pull request.

**Comment by guilhermeagirardi** [comment]
Done!

**Comment by janober** [comment]
Great, thanks a lot! Got merged.

**Comment by janober** [comment]
Not really important but got released with n8n@0.52.0

**Comment by guilhermeagirardi** [comment]
🤟

**Pull request merged**
