### PR TITLE
feat(Google BigQuery Node): Node improvements

### PR DESCRIPTION
**Pull request by michael-radency**

### CODE REVIEW

**Comment by biozork** [comment]
I'm very much looking forward to these BigQuery node changes. 

@michael-radency do you know when it will be released ?

**Comment by Stockotaco** [comment]
I am as well. BigQuery for the win!

**Review by agobrech — DISMISSED** [review]
LGTM

**Review by agobrech — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@0.226.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.226.1)

**Pull request merged**
