### PR TITLE
feat(n8n Form Trigger Node): Add text area and password input types

### PR DESCRIPTION
**Pull request by yoshino-s**

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @Yoshino-s,

I have just given this a quick test and it doesn't appear to work, If this is not ready for review or untested could you change it to a draft until it is ready?

**Comment by Yoshino-s** [comment]
hey, i fixed the bug, and it works for me now

**Comment by Joffcom** [comment]
Hey @Yoshino-s,

That looks better, I have let the team know internally to see if we plan to accept PRs for the form trigger node yet. Out of interest how do you plan to use the 2 new field types?

**Comment by Yoshino-s** [comment]
We have a requirement to quickly generate a form for filling in username and password, as well as a piece of content containing line breaks, so we need to add the password type and textarea type.

**Comment by Joffcom** [comment]
Hey @Yoshino-s,

Can you fix the lint issue so we can get this merged? Normally I would get it done but as you used your master branch instead of creating a feature branch it won't allow me to do it.

**Comment by Yoshino-s** [comment]
The reason why I disabled eslint here is that the sorting here depends to a certain extent on the frequency of use and classification. For example, just lexicographic order does not meet expectations.

**Comment by Joffcom** [comment]
Hey @Yoshino-s,

That makes sense and we can change it in the future if needed. I think this is good to go and we are still in time for the 1.13.0 release assuming tests pass.

**Comment by Joffcom** [comment]
Hey @Yoshino-s,

Sorry to mess you around a bit here, I have had a quick chat with the UX team and we would like to keep the fields alphabetical as we believe this will make it easier for users to find the field type they are after.

**Review by Joffcom — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.15.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.15.1)

**Pull request merged**
