### PR TITLE
Add Facebook Graph API node

### PR DESCRIPTION
**Pull request by pestevez**
This PR adds a new node that simplifies the interaction with Facebook's [Graph API](https://developers.facebook.com/docs/graph-api/). The implementation is based mostly on the existing HTTP Request node, but with Graph API parameters and new credentials to store the access token.

When `continueOnFail` is set to `true`, the node uses the `failure` output and includes useful data included in the response headers.

The easiest way to generate an access token is using the [Graph API Explorer](https://developers.facebook.com/tools/explorer/).

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot @pestevez for creating this node and welcome to the n8n community!

I have to confess that I was at the beginning not sure if I should merge it or not. The reason is that specific n8n nodes should generally not require people to have any knowledge about the underlying API. If that is required, then they could also use the generic HTTP Request node. So the thinking was in the end if it adds "enough" additional functionality or makes it much simpler to have an additional node. In the end, did I conclude that it does do that. Additionally, did I also see that the API is quite large. So it will never be possible (or would make sense) to implement everything "natively". Meaning we will always need a "manual" mode as it is right now for the not so often needed functionality. The other "actions" which makes it possible to use the node without any knowledge about the API, can then simply be added to the node later.

Apart from that did I change the name of the node and also removed the error output. Agree to 100% that something like that makes incredibly much sense and can be very important to have. We have actually planned to add some similar functionality in the future. To make, however, sure that everything in n8n works as consistently as possible did I sadly have to remove it for now. I hope that is understandable.

**Comment by pestevez** [comment]
That's great @janober. The reasoning behind the node was that I tried a few workflows that used the generic HTTP Request node, and at some point it became very repetitive.

**Comment by janober** [comment]
Ah yes, can totally understand that. That is why I merged it as I can see that if somebody uses that endpoints a lot it can like that make it much easier.

Thanks again for creating the node and adding it to n8n!

**Comment by janober** [comment]
Got released with n8n@0.66.0

**Pull request merged**
