### PR TITLE
feat(core): Add Open ID support

### PR DESCRIPTION
**Pull request by RicardoE105**
Github issue / Community forum post (link here to close automatically):

### CODE REVIEW

**Comment by Candinya** [comment]
> Why was this closed? Is Open ID support covered by another feature not covered by the docs or is it no longer planned?

Seems like they've limited SSO feature to enterprise only, not for the community.  (refer to document https://docs.n8n.io/user-management/saml/setup/ )

**Comment by Minecraftschurli** [comment]
well yes but that SSO is via SAML and not OpenID (different protocol)

**Comment by kosssi** [comment]
I'm surprise too, they never talk about OpenID Connect. I would have used it for my little instance.

@RicardoE105 Your code works ?

**Comment by RicardoE105** [comment]
@kosssi It used to! It has been such a long time that there is no way this is working! I dropped it because, internally, it's not a priority. If you want this feature, upvote it in the community. The more votes, the more attention will get, hence the greater the chances of getting merged.

**Pull request closed without merging**
