### PR TITLE
:sparkles: AWS SNS trigger

### PR DESCRIPTION
**Pull request by RicardoE105**
@janober I was not able to test it using localtunnel nor ngrok for some reason AWS does not like the URL provided by them. But I used https://webhook.site/#!/b6b13e89-12b3-46f3-bd8c-0684b2c81476/d71ca657-8cdb-42bd-972a-1b3bf991447c/1 since AWS works with it and was able to test it "manually", taking the data from the page and hitting the local server with the same data using postman.  AWS is driving me crazy I have been doing for like 4 hours.

### CODE REVIEW

**Comment by janober** [comment]
Great, thanks a lot @RicardoE105 !

Btw. why do you need "localtunnel" or "ngrok"? Does the build-in n8n-tunnel not work for you? Or is that what you mean with "localtunnel"?

**Comment by RicardoE105** [comment]
@janober mmm I have never used and I had forgotten there is one build-in already.

**Comment by janober** [comment]
Uh wow, then development was much more complicated than it had to be ;-)

If you start n8n from the terminal in the cli folder with `./bin/n8n start --tunnel'` it should set up everything and simply work. You can test everything in n8n. And never had an issue that the URL did not get accepted.

**Comment by RicardoE105** [comment]
@janober so cool. I will use it next time. Thanks

**Comment by RicardoE105** [comment]
Even with the build in local tunnel will not work 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by janober** [comment]
Hm, very strange. If it does not work with that one, then there must be something else wrong. Because it is not different from what people will have set up themselves and so it would also not work for them which renders the node useless ;-(

**Comment by RicardoE105** [comment]
yeah, it's very weird since it works with all online webhook catchers. 

SNS works in a similar fashion than asana. After you subscribe to a topic they send a verification request with a token that you have to use to hit another endpoint and "validate" the subscription. However, Amazon does not like the local tunnel.

It looks like I'm not the only one having this issue.

https://forums.aws.amazon.com/search.jspa?mbtc=c975dd2d37170cc2834ef69e44ef73fad9016e78f8d3766316c0caaeb09a3072&q=sns+subscription+confirmation&x=16&y=13

But I have the feeling that with a proper deployment should work.

**Comment by janober** [comment]
But the problem I see is that there should not really be a difference between a "proper deployment" and the tunnel. For the outside world, both should look and work 100% identical. After all, all the tunnel does is to redirect data to n8n and then return the data n8n tells it to. I will check it out if I find the issue when I have some time. Maybe the tunnel behaves differently. But in that case, it has to be fixed as it is very important for testing.
Thanks!

**Comment by janober** [comment]
Ok fixed and merged it.

Would sadly really not have worked for anybody. There were two main problems. For a strange and unknown reason does Amazon:
 1. an urldecode and so converts the "%20" to spaces and so the webhook calls do never end up where they should end up. So made now sure that the node-names do not have spaces in them else it errors directly
 2. set the content-type to "text/plain" but sends JSON. For that reason does the body-parser not pick it up and the body was always empty.

So as a rough guideline we can really assume that if it does not work with the tunnel, it would not work at all.

**Comment by RicardoE105** [comment]
@janober dude how the heck did you figure that out? It was driving me crazy. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by janober** [comment]
Also drove me crazy and it took me also a while. I could not understand why the n8n-tunnel should not work. I was checking everything that could be different until I saw the URL in the Amazon Dashboard and spotted that it had spaces in it. So I then simply renamed the node and it "worked". At least it got now finally called. Then there was still the problem that it did not get any data. So had then to check why the requests did have an empty body. Saw that the content-type was wrong and so did google it. Which turned out to be the problem. Then just had to figure out a way to get the JSON for amazon without doing some kind of shady-stuff in the core-code and then it finally worked.
But like you said Amazon really does not make it easy.

**Comment by janober** [comment]
Got released with n8n@0.53.0

**Pull request merged**
