### PR TITLE
Added node for sms77.io

### PR DESCRIPTION
**Pull request by matthiez**
Hi,

I have added a new node for the sms77.io SMS gateway.
I hope it is all OK.

Thank you!

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot!

Sadly am not able to test the node as I always get the message "Es ist ein Fehler aufgetreten. Bitte überprüfen Sie die eingegebene Nummer." when I enter my mobile phone number to get the test-credits even though it is valid and the correct format. I will try again at a later point in time.

**Comment by matthiez** [comment]
Hi @janober,

thanks for responding.

Are you trying to create an account with free credits for testing?
You may use the dummy key "HeJyJSAvBWDn5RwNfhQGKZI6poCLk7pUXjpxctipYHWGsjoHtWNDI3d4De8gkoVe" to test the API. It wont actually send out messages though but it still validates the payload.

Thank you!

**Comment by janober** [comment]
Great thanks a lot @matthiez ! Made some minor adjustments and then merged it.

Will be released with the next version.

**Comment by janober** [comment]
Got released with n8n@0.66.0

**Pull request merged**
