### PR TITLE
Feature - Appwrite node

### PR DESCRIPTION
**Pull request by Saad-ISAA**
A node for [Appwrite](https://appwrite.io)
Requested [here](https://community.n8n.io/t/appwrite-node-request/7907) on the community forum.

The Node:
image

Operations:
image

Credentials Check:
image

### CODE REVIEW

**Comment by Saad-ISAA** [comment]
Can anyone guide how to resolve this issue SNYK issue which is failing this PR

**Comment by Saad-ISAA** [comment]
Can anyone help in regards to resolving this snyk check which is failing ?

**Comment by binaryfire** [comment]
It’d be great if this could be reviewed soon. Would love to see this integration added.

**Comment by Joffcom** [comment]
Hey @Saad-ISAA,

Thanks for the contribution, It looks like you have already published this node to the Community Node Repository which is our preferred method for new node submissions.

In the future we may reach out to you about including your node in our main release, But for now I am going to close this PR. If you have any questions about this or need any help let us know.

**Comment by Saad-ISAA** [comment]
Thanks @Joffcom yes I have published all my nodes to npm. Appetite and Zoho people

**Pull request closed without merging**
