### PR TITLE
Clever Cloud Cli implementation

### PR DESCRIPTION
**Pull request by wowi42**
Clever Cloud CLI Implementation.

API version coming soon

### CODE REVIEW

**Comment by wowi42** [comment]
Mainly based on the work of @ldoguin

**Comment by janober** [comment]
Thanks a lot. But for me, it sadly looks like this node would not be functional as it assumes that a special CLI is installed. If it is not (as it would be the case for almost all users) it would not function. Which means we can not merge a node like this. We would have to make sure that it is really functional for every user. So the code would have to get changed to use some kind of REST-API.

**Comment by RicardoE105** [comment]
Just checked and they have a REST API https://www.clever-cloud.com/doc/api/.

**Comment by wowi42** [comment]
@RicardoE105 the REST API is a possibility if you merge https://github.com/n8n-io/n8n/pull/1055 :-)

**Comment by wowi42** [comment]
@janober well noted

**Comment by janober** [comment]
Do not see a problem with #1055 being merged ;-)

**Comment by janober** [comment]
As #1055 got merged it can now be implemented like all other nodes via the REST API. So close this PR for now. Thanks!

**Pull request closed without merging**
