### PR TITLE
ci: enforce stricter PR title checking

### PR DESCRIPTION
**Pull request by ivov**
Thanks @krynble for the [parser](https://github.com/ivov/validate-n8n-pull-request-title/blob/master/src/parserContent.js) idea.

### CODE REVIEW

**Comment by ivov** [comment]
@netroy Feel free to edit title to verify functionality.

**Comment by netroy** [comment]
The markdown needs to be adjusted for the instructions to be more clearly visible.
image

**Comment by netroy** [comment]
@ivov can we make the generated instructions 
> Unknown `type` in PR title. Expected one of `feat`, `fix`, `perf`, `test`, `docs`, `refactor`, `build`, or `ci`.

instead of 

> Unknown `type` in PR title. Expected one of {feat,fix,perf,test,docs,refactor,build,ci}

**Comment by ivov** [comment]
image

**Review by netroy — APPROVED** [review]

**Comment by janober** [comment]
Got released with `n8n@0.198.0`

**Pull request merged**
