### PR TITLE
Adding Box Api Integration

### PR DESCRIPTION
**Pull request by bhat-nitish**

### CODE REVIEW

**Comment by RicardoE105** [comment]
@bhat-nitish Dude, this is cool. Thanks for contributing. I Will try to review today and keep you updated.

**Comment by bhat-nitish** [comment]
Thanks.

Note : The upload file integration is not built as I was not sure of mutlipart upload with metadata and file being in the same request. I saw another thread which had similar discussion. 

If I can use a custom module and build it, Please point me to an example and I can build it.

**Comment by bhat-nitish** [comment]
Added code for upload file by using 

1. File path from local - uses fs module
2. Binary Data from other nodes - uses Binary data

**Comment by janober** [comment]
As written via email did we sadly have to reimplement it in the end. So close now this PR for that reason as the other code got merged and released.

**Pull request closed without merging**
