### PR TITLE
Add Wekan node

### PR DESCRIPTION
**Pull request by dokime7**
Wekan node
https://wekan.github.io/

### CODE REVIEW

**Comment by dokime7** [comment]
Sorry, I don't understand why CoinCecko code commits is here... I just want to pull request Wekan node (commit 88fb6a8).

**Comment by RicardoE105** [comment]
@dokime7 do you have an instance that I can use for testing?

**Comment by dokime7** [comment]
Hi, I've sent an instance info on your mail :)

**Comment by RicardoE105** [comment]
@dokime7 thanks very much. This is really helpful.

**Comment by RicardoE105** [comment]
@dokime7 was trying to review the node but it seems like with the user I created I do not have permission to check most endpoints. Looks like the user making the request has to have admin permissions. I always get `forbidden`. Is there a way you can make me an admin?

**Comment by dokime7** [comment]
Oh, sorry, I just gave you the admin rights now.

**Comment by RicardoE105** [comment]
@dokime7 made some improvements but in general, was a really nice job, you took a lot of things into consideration 👍. I'm gonna move this to internal review and then will be merged. Would be awesome if you can keep the account you created a couple more days so that my coworkers can use it to review as well. Again, thanks very much. Hopefully, this will not be you last contribution ;)

**Comment by dokime7** [comment]
Your welcome :)
No problem, I let the Wekan test instance up for some weeks.

**Comment by janober** [comment]
Thanks a lot. Got merged with #1043

**Comment by janober** [comment]
Got released with n8n@0.87.0

**Pull request closed without merging**
