### PR TITLE
feat(Kafka Node): add key option for messages

### PR DESCRIPTION
**Pull request by jbacklund**
Add key to message.
Add key to properties.

https://community.n8n.io/t/add-key-to-kafka-message/18134

### CODE REVIEW

**Comment by nanderss** [comment]
Could this be merged? We really need this fix.

**Review by Joffcom — DISMISSED** [review]

**Comment by Joffcom** [comment]
Hey @jbacklund,

Thanks for the PR, I have just given it a test and it works as expected 👍🏻

**Review by Joffcom — APPROVED** [review]

**Comment by Joffcom** [comment]
@jbacklund merging now, Thanks again for this one 👍🏻

**Comment by janober** [comment]
Got released with `n8n@0.198.0`

**Comment by sdahlbac** [comment]
@janober yay! I was however surprised to not see author credited under https://docs.n8n.io/reference/release-notes/#n8n01980 Contributors

**Pull request merged**
