### PR TITLE
⚡️ ADD Twake node

### PR DESCRIPTION
**Pull request by BenoitTallandier**

### CODE REVIEW

**Comment by janober** [comment]
Really cool! Just had a very short look. It seems like you are using spaces instead of tabs. Could you please replace them. The reason is that if we would replace them, we would actually change literally every line of code and so it would all get attributed to the person which fixes the issue instead of you, which would not be fair.

**Comment by janober** [comment]
Great, thanks a lot for the fast turn-around!
We will try to review and merge soon!

**Comment by BenoitTallandier** [comment]
Ok thank you ! 🙏
If there are any changes to do, say me ;)

**Comment by janober** [comment]
Thanks a lot!

**Comment by RicardoE105** [comment]
Hey, @BenoitTallandier was reviewing you node but cannot find the API documentation. Can you please point me in the right direction. Also noticed neither the node nor the credentials are registered on the [package.json](https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/package.json) meaning it won't render on the UI.

**Comment by BenoitTallandier** [comment]
Hi @RicardoE105 
I added Twake in the package.json.
As Romaric response to you on crips, our documentation is "work in progress". We only have the french version at https://www.notion.so/Twake-API-v1-5081ab548cf94065bc0e9006d88233fb.
If you need something specific, I can translate you or answer to your question.

**Comment by RicardoE105** [comment]
I see @BenoitTallandier a couple of questions

1 - where do I find the public_id and private_api_key? 
2 - for the cloud version which is the base_url? I created an account for testing with the email teresa.zeron1@gmail.com. 
I'm guessing it's a part of https://web.twake.app/n8n_testing-main/Random-82754hecgd0h6g1heagb615g0242ac120i4-8379f072gd0h6g1heagacd2g0242ac120i4?
3 - For sending a message which fields are required and which ones are optional?

**Comment by RicardoE105** [comment]
got it. Thanks. However, on my account I cannot find the n8n connector to grab the workspace key. Check the image below.

image

**Comment by RicardoE105** [comment]
Forget it @BenoitTallandier  just realized the n8n connector it's just for the standard plan, I guess if you want to use the API with the free plan, you gotta use the public_id and private_api_key right?  I made some improvements here https://github.com/RicardoE105/n8n/commit/308da249f04c6c2de6762c1005ccf5ef708f9172 please check them out and let me know. The only issue it's I do not how to retrieve all channels on the account. Do the channels depends on the workspace? if so, how do I retrieve all workspaces?

**Comment by BenoitTallandier** [comment]
@RicardoE105 we built the n8n connector for the standard and free plan. It seems we have a problem. We will fix it as soon as possible.
When we finish fixing it, every user will be able to use the n8n connector, and public and private keys will be useless. What do you think about removing it from the optional field in the Twake credentials ? 
I'll let you know when we've solved the problem.

**Comment by RicardoE105** [comment]
I see @BenoitTallandier. Yeah, I can remove the public and private keys. let me know when the issue is fixed so that I can test the node. Thanks.

**Comment by BenoitTallandier** [comment]
@RicardoE105 We fixed our issue. Now you can try to install n8n connector inside your Twake workspace.

**Comment by RicardoE105** [comment]
@BenoitTallandier Cool now I can see n8n as an integration. I'm having trouble trying to retrieve the channels. I'm using this route GET https://api.twake.app/api/v1/channels, but I get route not found. Which is the correct route? Also, I noticed the allow_delete parameter has a fixed value everyone,  can this field take other values? If so which are they? and last but not least I wonder if the self-hosted version would have a workspaceKey for authentication or they would have to use the public keys? Thanks

**Comment by RicardoE105** [comment]
Hey @BenoitTallandier, one of my coworkers was reviewing the Twake node and noticed the following.

image

Can you update that on your side?

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.76.0

**Pull request closed without merging**
