### PR TITLE
fix(wekan Node): Fix authentication with new versions of Wekan

### LINKED ISSUE #4086: n8n with wekan
**Describe the bug**
Hello, I am a wekan user and login with its API brings the internal-server-error status code 500.

**To Reproduce**
Using latest wekan and latest n8n.

**Environment (please complete the following information):**

- OS: Ubuntu 22.04
- n8n Version latest
- Node.js Version 14.20

### PR DESCRIPTION
**Pull request by Joffcom**
Fixes #4086

### CODE REVIEW

**Review by DimDz — COMMENTED** [review]
It fixes the authentication as intented

**Comment by Limezy** [comment]
Hi all ! Is there any blocking point before that PR goes to merge ?
Can't wait to have my Wekan <-> n8n workflows working again 😄 
Thanks !

**Comment by Joffcom** [comment]
@Limezy looks like an issue was hit during review that I need to look into. I am off now until next Tuesday though so will hopefully be in the next release.

**Comment by Limezy** [comment]
Great, thanks for your quick feedback !

**Comment by Limezy** [comment]
Hi ! Any update ? 🚀 
Thanks !

**Comment by Joffcom** [comment]
Hey @Limezy,

Looks like it is still in review, the chap doing the review hit an issue during testing. I will have a chat with him tomorrow and see if we can get this sorted.

**Review by RicardoE105 — DISMISSED** [review]

**Review by RicardoE105 — APPROVED** [review]

**Comment by Limezy** [comment]
Thank you so much @Joffcom

**Comment by janober** [comment]
Got released with `n8n@0.196.0`

**Pull request merged**
