### PR TITLE
add more SpreadsheetFile options

### PR DESCRIPTION
**Pull request by lublak**
currently some issues with invisible input fields:
89F3SIxpzj

### CODE REVIEW

**Comment by lublak** [comment]
Collection type has some issues if the name is used more than once.

**Comment by Joffcom** [comment]
Hey @lublak,

Are you still working on this one? It is still in the draft state.

**Comment by lublak** [comment]
@Joffcom There were bugs in n8n itself that made this node impossible. I would have to check again whether it works now and I think a part has already been added by other people which I then have to throw out again in my pull request.

**Comment by Joffcom** [comment]
Hey @lublak,

No worries, As it is just a draft we can keep it as a draft until you mark it as ready for review or we can close it off while you check what has changed.

**Comment by nivb06** [comment]
Hi @lublak, have this bug mentioned above still prevent you from finishing working on this? We would like to start processing this PR soon. Let us know if you can change the draft status

**Comment by lublak** [comment]
@nivb06 sry for the late response.
I will look into it after the weekend :)

**Comment by lublak** [comment]
@nivb06 it take a bit longer because with the latest github version i can't build the project to test this:

grafik

**Comment by Joffcom** [comment]
Hey @lublak,

What happens if you use Node 16 does that clear up that error?

**Comment by lublak** [comment]
@Joffcom yes using node 16 works for me now. Now i can back to n8n development 😋 
https://github.com/webpack/webpack/issues/14532

**Comment by lublak** [comment]
its merged with the latest master branch, but not tested completely.
But the issue with glitching ui no longer exists.

**Comment by Joffcom** [comment]
Hey @lublak,

I am going to mark this as closed for now and in the future if you get any time to finish up on this let me know and we can look at it again. We do have plans to overhaul this node in the future anyway so some of the changes here may make it into that.

**Comment by lublak** [comment]
@Joffcom yes its fine.
Currently some hard time. :/ 
Whether I'll find enough time again is the question anyway.
I'm sorry.

**Pull request closed without merging**
