### PR TITLE
fix(Invoice Ninja Node): Fix payment types 2

### PR DESCRIPTION
**Pull request by CodeShakingSheep**
## Summary

As a follow-up of https://github.com/n8n-io/n8n/pull/10196 to fix https://github.com/n8n-io/n8n/pull/10196#issuecomment-2293656166 .

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Comment by CodeShakingSheep** [comment]
Also as a suggestion for the future to prevent these kinds of errors: Would it be possible to add a linter rule that prevents the lint tests from passing if there is a `displayOptions` object defined for a child parameter of a collection / fixed collection?

**Comment by Joffcom** [comment]
Hey @CodeShakingSheep,

Thanks for the PR, We have created "GHC-169" as the internal reference to get this reviewed.

One of us will be in touch if there are any changes needed, in most cases this is normally within a couple of weeks but it depends on the current workload of the team.

**Comment by CodeShakingSheep** [comment]
Hey @Joffcom ,
Thanks for your reply. As this prevents a whole workflow from executing, I believe it should get a high priority for reviewing. My workflows which have the payment create action, are inactive now. And I think this should also be backported. What do you think?

**Comment by Joffcom** [comment]
Hey @CodeShakingSheep 

Looking at it I was sure it worked when I tested it but it looks like I missed something when running it.

I will get this checked on Monday morning and we can work out what to do. If we do another patch release we can look at adding it.

**Review by Joffcom — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.56.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.56.0)

**Comment by CodeShakingSheep** [comment]
Can confirm it works fine now on my instance after upgrading to the latest version.

**Pull request merged**
