### PR TITLE
Sonos Node

### PR DESCRIPTION
**Pull request by VonRehberg**
This is a working sonos integration for n8n.

Could somebody please give feedback on whether this could already be merged?
How is documentation supposed to be delivered?
Unfortunately there is no automatic test so far, I need to investigate.

image

### CODE REVIEW

**Comment by VonRehberg** [comment]
Okay forget about the documentation question. I just found the repo 👍

**Comment by VonRehberg** [comment]
Worked on the documentation, but cannot finish unti this PR is merged as I need to create a sample workflow :-)

https://github.com/n8n-io/n8n-docs/pull/677

**Comment by VonRehberg** [comment]
Ready for review / merge.

**Comment by Joffcom** [comment]
Hey @VonRehberg,

Thanks for the contribution, We have now created a Community Node Repository which is our preferred method for new node submissions.

Once a node has been published to the Community Node Repository users will be able to install the node from their n8n interface and will be able to use your node quicker, You will also be able to update the node as needed without needing to wait for the review process.

In the future we may reach out to you about including your node in our main release, But for now I am going to close this PR.

You can find more information in the links below, If you have any questions about this or need any help let us know.

Building Community Nodes: https://docs.n8n.io/integrations/community-nodes/build-community-nodes/
Submitting Community Nodes: https://docs.n8n.io/integrations/creating-nodes/deploy/submit-community-nodes/
Published Nodes: https://www.npmjs.com/search?q=keywords:n8n-community-node-package

**Comment by VonRehberg** [comment]
FYI: Published now to [n8n-nodes-sonos](https://www.npmjs.com/package/n8n-nodes-sonos)

**Comment by janober** [comment]
That is great @VonRehberg! Thanks a lot for making that node available for everybody!

**Pull request closed without merging**
