### PR TITLE
feat(Telegram Node): Add support for local bot api server

### PR DESCRIPTION
**Pull request by ddzobov**
## Summary

Ability to set base URL in Telegram credentials when we want to use Telegram Bot API behind reverse proxy.
 
Example cases:
- when n8n installation placed in networks without internet access, so we should use proxies queries
- when we want to use telegram bot routing application that runs over webhooks
- when we want to track all queries to telegram and review/decorate them in some cases
- when we don't want to share original telegram bot tokens to applications and replace them with custom tokens
 
Example endpoints:
 - https://api.telegram.org/bot - default, public
 - https://localhost:9000/bot - custom, proxied

## Related tickets and issues
#2517

## Review / Merge checklist
- [x] PR title and summary are descriptive
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @ddzobov,

We closed a similar PR to this last year or the year before as it seemed like something that wasn't a general issue and was very specific.

As Telegram isn't something that can be self hosted I am not sure what benefit this adds, Can you provide more context?

**Comment by ddzobov** [comment]
> Hey @ddzobov,
> 
> We closed a similar PR to this last year or the year before as it seemed like something that wasn't a general issue and was very specific.
> 
> As Telegram isn't something that can be self hosted I am not sure what benefit this adds, Can you provide more context?

Yes, our instance of n8n installed without internet access, so we need to run requests to telegram api by reverse proxy. And we using telegram local bot server for handling webhooks.

Why it is a problem to include just one small specific option with default value?

**Comment by Joffcom** [comment]
Hey @ddzobov,

Are you not able to set the proxy option for the container so that the outbound traffic goes through your proxy? While it is not really a problem to add it this change would go against what we typically do which is only provide a url option for services that can be self hosted so if we were to allow it for this we would need to do the same thing for all nodes which may cause confusion for users.

**Comment by ddzobov** [comment]
> Hey @ddzobov,
> 
> Are you not able to set the proxy option for the container so that the outbound traffic goes through your proxy? While it is not really a problem to add it this change would go against what we typically do which is only provide a url option for services that can be self hosted so if we were to allow it for this we would need to do the same thing for all nodes which may cause confusion for users.

Yes, i'm not able to configure any proxies etc. I only can change n8n configuration.

I think that adding a little flexibility and remove hardcode will be better option. 
For example, some users making adapters for telegram servers for centralizing bot's microservices under one real bot. 
This is main reason why i made this PR because i can not use n8n for this.

**Comment by Joffcom** [comment]
Hey @ddzobov 

I still feel like this is something that will only be of use  for this one small case and it likely won't be needed by the wider community.

My personal thought is we should close this like we did with the other one and we should remain consistent with our approach. However I will check this with a couple of other team members to see why they think so that you have a fair review.

**Comment by ddzobov** [comment]
> Hey @ddzobov
> 
> I still feel like this is something that will only be of use for this one small case and it likely won't be needed by the wider community.
> 
> My personal thought is we should close this like we did with the other one and we should remain consistent with our approach. However I will check this with a couple of other team members to see why they think so that you have a fair review.

Many opensource telegram bot solutions allows to developers to set up base uri for telegram bot api:
- https://telegram-bot-sdk.com/docs/getting-started/configuration/#base-bot-url
- https://github.com/mast/telegram-bot-api/blob/master/README.md#api-configuration
- https://docs.python-telegram-bot.org/en/v20.7/telegram.ext.applicationbuilder.html#telegram.ext.ApplicationBuilder.base_url
- https://defstudio.github.io/telegraph/installation#configuration
- https://github.com/apimorphism/telegramium/#how-to-use

**Comment by ddzobov** [comment]
For example, many users (like me) using official Telegram Bot API server (https://github.com/tdlib/telegram-bot-api) by Telegram that removes many limitations from public Telegram endpoints 

> Download files without a size limit.
> Upload files up to 2000 MB.
> Upload files using their local path and [the file URI scheme](https://en.wikipedia.org/wiki/File_URI_scheme).
> Use an HTTP URL for the webhook.
> Use any local IP address for the webhook.
> Use any port for the webhook.
> Set max_webhook_connections up to 100000.
> Receive the absolute local path as a value of the file_path field without the need to download the file after a getFile request.

**Comment by SpiryaevSS** [comment]
I abosultely agree with ddzobov because this MR real usefull for everybody.

**Comment by dmb72** [comment]
I need this feature.

**Comment by badhitman** [comment]
Please do it. This will bring a lot of benefits. I give my word of honor!

**Comment by shevchenkoav** [comment]
Many are using the telegram bot api, it seems that the request itself defines the terms of private use. Please consider the request.

**Comment by ddzobov** [comment]
Any updates here?

**Comment by GuilhermeBarile** [comment]
I'd like to confirm that the features listed by @ddzobov are really worth having in n8n and only require setting the different base url for the telegram requests.

> > Download files without a size limit.
> > Upload files up to 2000 MB.
> > Upload files using their local path and [the file URI scheme](https://en.wikipedia.org/wiki/File_URI_scheme).
> > Use an HTTP URL for the webhook.
> > Use any local IP address for the webhook.
> > Use any port for the webhook.
> > Set max_webhook_connections up to 100000.
> > Receive the absolute local path as a value of the file_path field without the need to download the file after a getFile request.

**Review by Joffcom — APPROVED** [review]

**Comment by Joffcom** [comment]
Good news everyone...

This will be available in the next release of n8n 👍🏻

**Comment by janober** [comment]
Got released with [`n8n@1.43.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.43.0)

**Pull request merged**
