### PR TITLE
Update Strapi node

### PR DESCRIPTION
**Pull request by harshil1712**
Update Strapi node to work with Strapi@v4

### CODE REVIEW

**Comment by harshil1712** [comment]
@Joffcom updated the code based on your feedback. Can you take a look and let me know if anything needs to be changed? Thanks!

**Comment by Joffcom** [comment]
@harshil1712 It looks a lot better, I will have a proper look this afternoon. I am wondering if there is an easier / better option if the only change is `/api/` on the uri and the `.data` on the response 🤔.

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with `n8n@0.167.0`

**Pull request merged**
