### PR TITLE
refactor: Integrate `consistent-type-imports` in FE packages (no-changelog)

### PR DESCRIPTION
**Pull request by ivov**
https://linear.app/n8n/issue/N8N-6054/integrate-consistent-type-imports-in-fe-packages

### CODE REVIEW

**Review by edumaciel10 — COMMENTED** [review]
huge improvement

**Comment by netroy** [comment]
@edumaciel10 Please use regular comments when interacting on PRs here. All PR review comments by non team members are going to be marked as Spam.

**Review by netroy — APPROVED** [review]

**Review by alexgrozav — DISMISSED** [review]
This is awesome!

**Review by netroy — CHANGES_REQUESTED** [review]
The search bar is missing, and that is breaking some of the e2e tests 
image

**Comment by ivov** [comment]
> The search bar is missing

ESLint misfixed some imports. Re-fixed [this one](https://github.com/n8n-io/n8n/pull/5951/commits/acfbaa3d991e2174f8c15618713d3106a41866ea) but likely happening in other spots because e2e are still failing, plus the root cause is unclear. Coming back to this later.

**Comment by ivov** [comment]
Did some more research but no luck yet:
- Looked at options for `consistent-type-imports`
- Experimented - simulating usage of the component as a value inside `<script lang="ts" setup>` e.g. `import something from './somewhere'; const x = something;` does not trigger a false positive. Autodetection of import usage in the template is the issue.
- Skimmed through possibly related issues:
	- https://github.com/typescript-eslint/typescript-eslint/issues/4508
	- https://github.com/vuejs/vue-eslint-parser/pull/144
	- https://github.com/typescript-eslint/typescript-eslint/issues/3108
- Updated all ESLint packages to latest and restarted ESLint server:

```json
{
  "name": "@n8n_io/eslint-config",
  "private": true,
  "version": "0.0.1",
  "devDependencies": {
    "@types/eslint": "~8.4.10",
    "@typescript-eslint/eslint-plugin": "~5.45.1",
    "@typescript-eslint/parser": "~5.45.1",
    "@vue/eslint-config-typescript": "~8.0.0",
    "eslint": "~8.28.0",
    "eslint-config-airbnb-typescript": "~17.0.0",
    "eslint-config-prettier": "~8.5.0",
    "eslint-import-resolver-typescript": "~3.5.5",
    "eslint-plugin-diff": "~2.0.1",
    "eslint-plugin-import": "~2.26.0",
    "eslint-plugin-n8n-local-rules": "~1.0",
    "eslint-plugin-prettier": "~4.2.1",
    "eslint-plugin-vue": "~7.17.0"
  },
  "scripts": {
    "clean": "rimraf .turbo",
    "test": "jest"
  }
}
```

**Comment by ivov** [comment]
As discussed with @cstuncsik, I will add a check to [`consistent-type-imports`](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/src/rules/consistent-type-imports.ts) to ignore import statements where the path ends in `.vue` to prevent this misdetection on Vue files using Composition API.

**Comment by ivov** [comment]
Updated here: https://github.com/n8n-io/n8n/pull/6060

**Pull request closed without merging**
