### PR TITLE
Trello node improvements - N8N-3475

### PR DESCRIPTION
**Pull request by cxbitz**
adds the following operations to the Trello node - board resource:

- inviteMemberViaEmail:  Invite a new member to a board via email
- removeMember: Remove member from board using member ID
- addMember: Add member to board using member ID
- getMembers: Get all members of a board

getMembers:
Screen Shot 2022-04-24 at 10 00 39 AM

addMember:
Screen Shot 2022-04-24 at 10 01 29 AM

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @CxGarcia,

Thanks for the PR I am just in the process of reviewing it now, The changes look good and they work which is handy 👍🏻 I am just thinking about maybe moving the Board Member opertations to their own resource so just checking internally to see if that makes sense.

**Comment by CxGarcia** [comment]
hey @Joffcom

no prob 🙂 

I actually thought about putting these under a different resource but ended up doing it this way to keep it in line with how the Trello API is structured (all these operations are under the `/boards` slug)

lmk what makes the most sense to you and if necessary I can make the change

**Comment by Joffcom** [comment]
@CxGarcia out of interest when testing did you find that you can't add a user as an observer when using the invite by email option?

**Comment by CxGarcia** [comment]
> @CxGarcia out of interest when testing did you find that you can't add a user as an observer when using the invite by email option?

yes, it may be because observers only work in premium workspaces https://help.trello.com/article/791-changing-permissions-on-a-board

I'll add this in the description to avoid confusion

**Comment by janober** [comment]
Thanks a lot for your contribution @CxGarcia! Got merged and will be released with the next version.

**Comment by janober** [comment]
Got released with `n8n@0.177.0`

**Pull request merged**
