### PR TITLE
Add parent id to children blocks

### PR DESCRIPTION
**Pull request by RicardoE105**

### CODE REVIEW

**Comment by RicardoE105** [comment]
Continuing with #2815

**Comment by knshiro** [comment]
Even though adding the parent id solves the issue for almost all cases, I would still like the option to return the blocks as array.
1. There is no "group by key" node so I would need to add a function to do this each time I want to regroup blocks per page.
2. If there are 2 calls to the same page, it would be even harder to regroup the items per call.

So in my case I would continue using the http request node instead since it makes my life easier.

**Comment by janober** [comment]
@knshiro I totally see where you are coming from and totally agree that the current solution is not perfect. That is however consistent with how it works with other nodes in n8n. We definitely also have to make possible what you need, but that should not happen on a node-level. Because else we would have to add similar logic to every n8n node. To avoid that, would it be better to find a proper global solution instead that works everywhere.

**Comment by knshiro** [comment]
@janober 

I understand your concern but in my PR I didn't change the default behavior which is consistent with the rest, I just added this as an option.

Another way this could be done that would be consistent with the rest would be to add an option "Include blocks" in the get page operation/resource combo. What do you think?

**Comment by sirdavidoff** [comment]
It's very a valid problem: my preferred way of dealing with it would be to add a 'group by' operation to the 'item lists' node.

**Comment by knshiro** [comment]
I completely agree with adding the group by feature. I even already gave that feedback because I implemented it for something else.

One last try about why this is case is different:
Even though the endpoint is called get blocks, what it actually is "get page content" and I think we should not get stuck in the semantics but focus on actual use cases. 
So while your flow is to only work one page, treating the content of one page as multiple items can be useful to do things like actions per checklist items for example. If you treat multiple pages you want to get those page contents treated as that.
My use case for example, is to create a basic html rendering for each page I fetch. In that case, the block for me is just a part of the page, it's not an item I want to treat individually (e.g. to produce a <ul> I need to be aware of all the `bullet_list_items` in order to group them).

**Comment by janober** [comment]
Got released with `n8n@0.165.0`

**Pull request merged**
