### PR TITLE
fix(Elasticsearch Node): Fix issue stopping search queries being sent

### PR DESCRIPTION
**Pull request by Joffcom**
## Summary
This changes the API request to POST for Get Many so that the JSON body is correctly sent when using a search filter.

CleanShot 2024-10-29 at 18 17 34@2x

## Related Linear tickets, Github issues, and Community forum posts
https://github.com/n8n-io/n8n/issues/11258
https://linear.app/n8n/issue/NODE-1872/community-issue-elasticsearch-query-doesnt-apply

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Review by netroy — COMMENTED** [review]
can we add some tests?

**Comment by jerryhu1234** [comment]
Waiting for fix it!

**Comment by Joffcom** [comment]
Added tests-needed label, Will add proper tests during our next test creation session.

**Comment by Joffcom** [comment]
Added a very quick test

**Review by ShireenMissi — DISMISSED** [review]
Tested Manually too and it all works 🎉

**Review by ShireenMissi — APPROVED** [review]
LGTM 🎉

**Comment by janober** [comment]
Got released with [`n8n@1.73.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.73.0)

**Pull request merged**
