### PR TITLE
✨ Add ServiceNow attachment functionality - N8N-3415

### PR DESCRIPTION
**Pull request by pemontto**
This PR adds CRUD operations for SNow attachments - https://developer.servicenow.com/dev.do#!/reference/api/quebec/rest/c_AttachmentAPI

The only problem I'm having is the binary download functionality, I've tried various methods but can't seem to get the encoding working correctly. Would appreciate a 2nd set of eyes to help resolve that.

### CODE REVIEW

**Comment by pemontto** [comment]
@michael-radency 🙌  thanks for resolving that binary download, works great!

**Comment by janober** [comment]
Great, thanks a lot. Got merged.

**Comment by pemontto** [comment]
Thank you very much @RicardoE105 & @michael-radency 🙏

**Comment by janober** [comment]
Got released with `n8n@0.179.0`

**Pull request merged**
