### PR TITLE
Change placeholder text for tags dropdown in Open Workflow Modal

### PR DESCRIPTION
**Pull request by wohfab**
Changing placeholder text for tags dropdown to indicate tag filtering possibility.

### CODE REVIEW

**Comment by wohfab** [comment]
Requiring #2714

**Comment by mutdmour** [comment]
thanks @wohfab for the fix. Can you please merge the two PRs into one? 
https://github.com/n8n-io/n8n/pull/2714/files

**Comment by wohfab** [comment]
> thanks @wohfab for the fix. Can you please merge the two PRs into one? https://github.com/n8n-io/n8n/pull/2714/files

Thank you, @mutdmour. I made the changes via GitHub directly, and didn't find an option to combine them. Should've waited until I got home ;) 

I now have combined them in #2717. I hope, I didn't disturb the process too much.

**Comment by mutdmour** [comment]
no worries. it's just clearer this way. thanks for making the fix. closing in favor of https://github.com/n8n-io/n8n/pull/2717

**Pull request closed without merging**
