### PR TITLE
Alert before redirection / Dirty state management within Vuex

### PR DESCRIPTION
**Pull request by Rupenieks**
Built ontop of the work of @erin2722 . Thank you for your contribution.

### CODE REVIEW

**Comment by krynble** [comment]
Regarding Jira Ticket PROD-148 @janober.

Demo video with known issues: https://www.loom.com/share/541aacaf045745709c8827420f836c9b

**Comment by krynble** [comment]
Ah, one side note here:
- HtmlExtract.node.ts has type errors (unknown type Cheerio)

I resintalled dependencies but couldn't fix this. It's not related to the main task so I did not work on it. Not sure if it will persist once merged to master. Thought it would be good to mention.

**Comment by janober** [comment]
Thanks a lot @erin2722 @Rupenieks @krynble got merged.

**Comment by janober** [comment]
Got released with n8n@0.91.0

**Pull request merged**
