### PR TITLE
docs: Add section to tell contributors to install cypress before running e2e tests (no-changelog)

### PR DESCRIPTION
**Pull request by despairblue**
## Summary
I was wondering why cypress didn't install the necessary version automatically. I eventually found that there is a script for doing so.
I thought it makes sense to update the contributing guide to mentione that.

## Related tickets and issues
none

## Review / Merge checklist
- [x] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

### CODE REVIEW

**Review by Joffcom — APPROVED** [review]
The emoji probably isn't needed but it works

**Comment by despairblue** [comment]
> The emoji probably isn't needed but it works

I only added it to be in line with the other callout: 

https://github.com/n8n-io/n8n/pull/8466/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R214

I'm happy to remove it though. Let me know what you think :)

**Comment by Joffcom** [comment]
Didn't even notice it, shows how often I check that doc 😂 let's keep it to be consistent then

**Comment by janober** [comment]
Got released with [`n8n@1.27.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.27.2)

**Pull request merged**
