### PR TITLE
feat(Copper Node): Update credential to support HTTP Request node

### PR DESCRIPTION
**Pull request by jvdweerthof**
## Summary
- Add Copper credentials to HTTP Request node
- Add connection test for Copper credentials
- Use new authentication method in Copper Node
- Update the deprecated API endpoint url

Credentials in HTTP Request Node
Credential Test Fail
Credential Test Success

## Related Linear tickets, Github issues, and Community forum posts

- Update the deprecated API endpoint url: [Copper Changelog 18-08-2021](https://developer.copper.com/introduction/changelog.html#august-18-2021)

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @jvdweerthof,

Are you also going to update the node to use the new authenticate method?

**Comment by jvdweerthof** [comment]
Hi @Joffcom,

I thought for my first PR to n8n I would keep the scope small... :-) But your question makes sense and I guess is in scope.

I updated the node to use the new authentication method, the PR is already updated.

**Comment by Joffcom** [comment]
@jvdweerthof you beat me to it, I was about to fix it 👍🏻

**Review by Joffcom — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.49.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.49.0)

**Pull request merged**
