### PR TITLE
fix(core): Handle credential in body for oauth2 refresh token

### PR DESCRIPTION
**Pull request by RJiraya**
Fix credentials in body when option is activated for oauth2.

https://github.com/n8n-io/n8n/issues/9178

## Review / Merge checklist
- [x] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [x] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

### CODE REVIEW

**Comment by Joffcom** [comment]
@netroy if you get a chance could you give this a once over?

**Comment by netroy** [comment]
not sure why, but I'm unable to edit this PR. 
@RJiraya Can you please revert the changes in `pnpm-lock.yaml`, so that we can try running the CI while someone also reviews the change 🙏🏽.

**Comment by RJiraya** [comment]
Hello [netroy](https://github.com/netroy), it's done !

**Comment by RJiraya** [comment]
Have you had time to look at this request?

**Review by netroy — DISMISSED** [review]

**Comment by netroy** [comment]
@RJiraya Generally when opening PRs, I highly recommend not using the `master`/`main` branch, since it's likely that this branch will have some form of branch protection, preventing maintainers from editing the PR.
Because of this I can't push the formatting fixes. Can you please either cherry-pick [these](https://github.com/n8n-io/n8n/commit/e15f5269360f0ee93db1abf0ab8d5c4bb0fe83fe), or let me know if you can't, and I'll create a new PR to get this merged.

**Comment by RJiraya** [comment]
thanks @netroy, i'll remember for the next time :)
I have pushed you changes !

**Review by netroy — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.43.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.43.0)

**Comment by RJiraya** [comment]
Thanks, tested on my side and works perfectly well ! Thank !

**Pull request merged**
