### PR TITLE
feat(editor): Redesign Canvas Chat

### PR DESCRIPTION
**Pull request by OlegIvaniv**
## Summary

This PR transforms the canvas chat experience from a modal dialog into a dedicated resizable panel at the bottom of the canvas. This change improves usability and workflow efficiency by allowing users to interact with both the chat and canvas simultaneously.

https://github.com/user-attachments/assets/82c8f2e1-934a-424a-8127-877a28074160

### UI/UX Improvements
- Replaced modal-based chat with a persistent, resizable bottom panel
- Added drag handles for both vertical and horizontal resizing
- Implemented chat/logs panel width persistence using localStorage
- Added visual improvements to chat messages and input area
- Enhanced chat session management with clearer session ID display
- Improved keyboard navigation for message history
- Added textarea auto-resize functionality
- Redesigned logs panel with better visualization and navigation

### Technical Improvements
- Created new `CanvasChat` component to handle panel-based chat functionality
- Implemented responsive height constraints (30%-75% of window height)
- Added proper cleanup of resize observers and event listeners
- Better state management for panel dimensions
- Added unit test coverage for new components

## Usage
The chat panel can now be toggled using the chat button in the canvas toolbar. When enabled, users can:
- Resize the panel vertically (30%-75% of window height)
- Adjust the width ratio between chat and logs sections
- Navigate message history using arrow keys
- Preview and manage file attachments
- View execution logs alongside chat messages

## Testing
Added test suite covering:
- Panel resizing behavior
- Chat message handling
- Keyboard navigation
- Session management
- State persistence
- Error scenarios

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Review by alexgrozav — APPROVED** [review]
Awesome work on this!

**Review by alexgrozav — DISMISSED** [review]

**Comment by OlegIvaniv** [comment]
@alexgrozav Thanks Alex! Can you re-review please? I had to merge-in master & do some light font changes

**Review by burivuhster — APPROVED** [review]
🚀

**Comment by janober** [comment]
Got released with [`n8n@1.68.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.68.0)

**Pull request merged**
