### PR TITLE
feat(Odoo Node): Allow to perform an action on a model with the Odoo Node

### PR DESCRIPTION
**Pull request by Lanhild**
Github issue / Community forum post (link here to close automatically):

### CODE REVIEW

**Comment by Lanhild** [comment]
This PR allows users to perform an action on an Odoo model. I have tested my changes on all recent Odoo versions and it should work on odd versions as well like 13, 15, etc.

**Comment by mathop** [comment]
@Lanhild Thank you for working on it! Do you know what is needed for this PR to be merged? I'm happy to help with local testing or work on anything that may be missing.

**Comment by Lanhild** [comment]
@mathop No problem! I'm actually thinking about closing this current PR and make a new one to update the code changes I've made and also to include more actions/operations to the base node, such as database actions, etc.

A while ago, I've started a documentation about the [Odoo `/jsonrpc` API](https://github.com/Lanhild/odoo-api-docs). I've been inspired a lot by the n8n's Odoo node and added documentation on database actions via API, which made me think of adding them to the node.

**Comment by gonchik** [comment]
+1 for Odoo testing

**Comment by Lanhild** [comment]
@mathisgauthey It's not up-to-date. I'm closing it.

**Comment by llabusch93** [comment]
Hey, why this was not merged? It's urgently needed...

**Comment by mathisgauthey** [comment]
> Hey, why this was not merged? It's urgently needed...

I did something like it [here](https://github.com/n8n-io/n8n/pull/13937) and will eventually release my Odoo community upgrade as a PR to n8n when I get time to version it properly. It will include this as well!

**Pull request closed without merging**
