### PR TITLE
Feature/extended active campaign

### PR DESCRIPTION
**Pull request by RicardoE105**

### CODE REVIEW

**Comment by vanitom** [comment]
Hello,

Thank you @RicardoE105 for these improvements.

I do not understand but I have tried several times to sign the CLA. This is still not validated. Is this normal ?

**Comment by janober** [comment]
Thanks a lot @vanitom I just checked. You signed it successfully at as "vanitom": Sep 3, 2020 8:31:34 AM
The problem seems to be that the commits have been done not as user "vanitom" rather as user "Ronald Diquélou" and for that reason does it not recognize it. Do you have an idea why the user-names do not match?

**Comment by janober** [comment]
Btw. but no matter what. As you signed the license agreement it is all good. So thanks a lot!

**Comment by vanitom** [comment]
Sorry @janober . This is the name used professionally.
I just changed the information on my development directory for my next contributions.

**Comment by janober** [comment]
Makes sense and no problem at all.

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.83.0

**Pull request merged**
