### PR TITLE
fix: Typo fixes in various descriptions (no-changelog)

### PR DESCRIPTION
**Pull request by pengqiseven**
## Review / Merge checklist
- [x] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [x] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @pengqiseven 

Don't forget to sign the CLA so we can merge this 🙂

**Comment by Joffcom** [comment]
@pengqiseven the CLA is still not showing as being signed.

**Comment by Joffcom** [comment]
Hey @pengqiseven,

It is still not seeing it as being from your account, Do you have an email assigned to your GitHub account?

**Comment by pengqiseven** [comment]
> Hey @pengqiseven,
> 
> It is still not seeing it as being from your account, Do you have an email assigned to your GitHub account?

I have modified my email, it should be ready now.

Thank you for knowing. Please review again

**Review by Joffcom — APPROVED** [review]
Changes look good to me thanks for the PR 👍🏻

**Comment by janober** [comment]
Got released with [`n8n@1.40.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.40.0)

**Pull request merged**
