### PR TITLE
fix Crash: KafkaJSNotImplemented ,Snappy compression not implemented

### PR DESCRIPTION
**Pull request by gw123**
fix kafak trigger Snappy compression not implemented
https://github.com/n8n-io/n8n/issues/4444

### CODE REVIEW

**Comment by gw123** [comment]
hi @Joffcom  what can i do，  shoud i open a feature  request.
image

**Comment by Joffcom** [comment]
Hey @gw123,

At the moment it would just be a case of waiting for this to be reviewed. Because an extra package is being pulled in it can take a bit longer.

We also need to test the change and make sure it doesn't break anything for other users.

**Review by netroy — CHANGES_REQUESTED** [review]
`kafkajs-snappy` doesn't seem maintained. I've pinged the author to see if we can get it incorporated in `kafkajs`, and then maybe we can upgrade `kafkajs` in this repo.

**Comment by lismgmk** [comment]
@netroy hello. do you have any news about approval and merge this PR? my team and I will be grateful to you for merging it as fast as you can.

**Comment by netroy** [comment]
Still waiting for a response [here](https://github.com/tulios/kafkajs/issues/120).
I'd really like to avoid us adding yet another abandoned dependency, and would prefer if kafkajs could incorporate these changes.
If they don't, we might consider maintaining a fork instead.

**Comment by lismgmk** [comment]
@netroy what about simple create separate community node on current cafka node base with support snuppy compression, and don't care about abandoned dependency and main build?

**Comment by netroy** [comment]
@lismgmk think a separate community node would be a better solution here.

**Comment by lismgmk** [comment]
@netroy, do you have plans to create a separate Kafka community node? or maybe someone from your team? I’m interested in understanding whether to wait for this custom node from you or start doing it on my own.

**Comment by netroy** [comment]
> do you have plans to create a separate Kafka community node

Unfortunately we currently do not have a plan for this.
However if you decide to build it, I can try to help you out in personal capacity.

**Comment by netroy** [comment]
Either that, or someone takes up the [call for maintainership](https://github.com/tulios/kafkajs/issues/1603), to incorporate snappy support in kafkajs.

**Comment by lismgmk** [comment]
@netroy thank you for your willingness to help. I made and tested custom node for snappy and gzip https://www.npmjs.com/package/n8n-nodes-kafka-snappy.

**Comment by netroy** [comment]
Nice. I think you can remove the credential file, since you can use the kafka credential type that's already included in n8n.
We can also close this PR now 🙏🏽

**Comment by lismgmk** [comment]
@netroy ok, thanks I'l do it.

**Pull request closed without merging**
