### PR TITLE
[WIP] WhatsApp node

### PR DESCRIPTION
**Pull request by cxbitz**
so earlier this week WhatsApp made its cloud API available to all business accounts (more info [here](https://techcrunch.com/2022/05/19/whatsapp-ramps-up-revenue-with-global-launch-of-cloud-api-and-soon-a-paid-tier-for-its-business-app/)) and thought it would be a nice addition to n8n 🙂

Note:
The API is quite buggy still. For example, I am able to receive `template` based messages but not `text` nor `media` messages. There's already a bug report under investigation here: https://developers.facebook.com/support/bugs/382637050478627/?join_id=f23aafeb420999

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @CxGarcia,

How are you getting on with this one? Let me know if you need any help 👍🏻

**Comment by CxGarcia** [comment]
hey @Joffcom 

I plan on working on it throughout the week and have it ready by the weekend. I'll let you know if I need any help 🙂

**Comment by CxGarcia** [comment]
hey @Joffcom @janober 🙂

the base structure of the node is ready and working. for now, it can send text, media, and basic templated messages (although Wapp's API is buggy as mentioned in the description). There are 3 things still missing that I will keep working on:

1. trigger node
2. template components: template messages can have what the [spec](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#template-object) refers to as components, which can be passed to dynamic templates (`hello {{1}}`)  by adding the following parameters to the template property:
```json
"components": [
    {
        "type": "body",
        "parameters": 
        [
            {
                "text": "20000",
                "type": "text"
            }
        ]
    }
]
```
this is quite useful to take advantage of dynamic templates. I am trying to figure out what would be the best way to include this in n8n. what I thought is doing something like in the switch node, in this case, you would add x amount of components and parameterize them. I will keep on working on this one and lmk if you have any suggestions
3. media management: use WhatsApp's API to manage business' media

**Comment by Joffcom** [comment]
Hey @CxGarcia,

With the templates have you looked at what we do with the slack node when building a message? Could be the sort of thing you are after.

**Comment by CxGarcia** [comment]
thanks, @Joffcom I'll take a look

btw I realized that the Facebook trigger node already includes WhatsApp's triggers. however, this may not be straightforward to users (at least it wasn't for me) and I think there should be a dedicated trigger node for WhatsApp.

in this case, would it make sense to leave the functionality in both the Facebook node and WhatsApp node? if so I can just import WhatsApp's related functionality from `FacebookTrigger.node.ts` to avoid duplicating logic... if not, I can just move it to `WhatsAppTrigger.node.ts`

wdyt?

**Comment by voko3456** [comment]
Hi @CxGarcia can you please also add business management api to create templates  text and media templates types

**Comment by Ofabiojvalentim** [comment]
> hey @Joffcom @janober 🙂
> 
> the base structure of the node is ready and working. for now, it can send text, media, and basic templated messages (although Wapp's API is buggy as mentioned in the description). There are 3 things still missing that I will keep working on:
> 
> 1. trigger node
> 2. template components: template messages can have what the [spec](https://developers.facebook.com/docs/whatsapp/cloud-api/reference/messages#template-object) refers to as components, which can be passed to dynamic templates (`hello {{1}}`)  by adding the following parameters to the template property:
> 
> ```json
> "components": [
>     {
>         "type": "body",
>         "parameters": 
>         [
>             {
>                 "text": "world",
>                 "type": "text"
>             }
>         ]
>     }
> ]
> ```
> 
> I am trying to figure out what would be the best way to include this in n8n. what I thought is doing something like in the switch node, in this case, you would add x amount of components and parameterize them. I will keep on working on this one and lmk if you have any suggestions 3. media management: use WhatsApp's API to manage business' media

Maybe you can use set to handle parameters

**Comment by Shirkit** [comment]
Any news update on this?

**Comment by RicardoE105** [comment]
The Whatsapp node was released with [n8n@0.196.0](https://docs.n8n.io/reference/release-notes/#n8n01960)

**Comment by Einlight1** [comment]
Hello , i've tried it but i can't seem to find message type : interactive for catalog message type, can i be advised for this? thanks before

**Pull request closed without merging**
