### PR TITLE
fix(editor): Minor styling improvements in project settings page

### PR DESCRIPTION
**Pull request by MiloradFilipovic**
## Summary
- Using borderless icon in project header
image

- Cleaning up styling

## Review / Merge checklist

- [ ] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Review by tomi — COMMENTED** [review]
A before and after pic would be nice 🙏

**Comment by MiloradFilipovic** [comment]
> A before and after pic would be nice 🙏

Done

**Review by tomi — DISMISSED** [review]
Looks mostly good! Should we maybe add some more margin if the name is so long that it wraps?

image

**Comment by MiloradFilipovic** [comment]
> Looks mostly good! Should we maybe add some more margin if the name is so long that it wraps?
> 
> image

For sure

**Review by tomi — APPROVED** [review]
Thanks for addressing the feedback 🫶

**Comment by janober** [comment]
Got released with [`n8n@1.74.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.1)

**Comment by janober** [comment]
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)

**Comment by janober** [comment]
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)

**Pull request merged**
