### PR TITLE
refactor(core): Convert OAuth1/OAuth2 controllers to decorated controller classes (no-changelog)

### PR DESCRIPTION
**Pull request by netroy**

### CODE REVIEW

**Review by krynble — DISMISSED** [review]
I can't say that I've tested it all - I did test locally authenticating with a google account, it worked well, but I haven't tested applying overwrites neither OAuth1 since only X uses it and we don't have a working test account for it.

Have you tested the overwrites? I can try to deploy it to a cloud instance to check if it works fine, just let me know.

**Comment by netroy** [comment]
Tested with a few google oauth2 credentials, and also with twitter oauth1.

**Review by Joffcom — APPROVED** [review]
X is working and have tested some other oauth services like Google and Hubspot.

**Comment by janober** [comment]
Got released with [`n8n@1.16.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.16.0)

**Pull request merged**
