### PR TITLE
perf: Upgrade Vue

### PR DESCRIPTION
**Pull request by cstuncsik**

### CODE REVIEW

**Review by netroy — COMMENTED** [review]
while we are at it, could we please upgrade `vite`, `vitest`, and `vue-tsc` in the same PR ?

**Comment by cstuncsik** [comment]
@netroy @alexgrozav updated those packages as well

**Review by netroy — APPROVED** [review]
🙏🏽

**Comment by janober** [comment]
Got released with [`n8n@1.32.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.32.0)

**Pull request merged**
