### PR TITLE
fix(cli): Make it possible to activate inactive workflows

### PR DESCRIPTION
**Pull request by schroedan**
Github issue / Community forum post (link here to close automatically): #4753

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @schroedan,

Thanks for the PR, I have added a note to `N8N-3763` to let the team know there is something to review.

**Comment by jayjayb772** [comment]
I've been working with the n8n CLI the past few days and kept getting confused about why `n8n update:workflow --id=$ID --active=true` would output `Deactivating workflow with ID:`
I almost made a PR for this myself but I'm glad someone else noticed it too.

Thank you!!

**Comment by Jason-M-Spark** [comment]
Any update on this? I'd love for this to get fixed.

**Comment by despairblue** [comment]
@schroedan I took your commits, rebased them and merged them in: https://github.com/n8n-io/n8n/pull/8412

Thanks for fixing this ❤️

**Pull request closed without merging**
