### PR TITLE
Jackrudenko/unleashed

### PR DESCRIPTION
**Pull request by RicardoE105**
Hey, @erudenko thanks for the contribution. I made some improvements to the node if you can test locally and provide feedback it would be cool. With regard to the Google Sheets improvements you did, I reversed it on this PR and will review on another PR as they are different nodes. Thanks

### CODE REVIEW

**Comment by erudenko** [comment]
Thanks @RicardoE105 
Thanks for feedback and improvement. I will test it as soon as possible and will let you know about the result. Cheers.

**Comment by erudenko** [comment]
Hey @RicardoE105 Thanks for cleaning the code and proper naming all the stuff around.
I have checked everything on my side and everything looks good. 
Two things I changed:
- I have fixed date transformation for all request. 
- I have added pagination for request with limits (to be able process the data by pages)

My updates are here: 
#827 
Probably we could close this PR.

**Comment by janober** [comment]
Great, thanks a lot. Got merged with #827

**Comment by janober** [comment]
Got released with n8n@0.78.0

**Pull request closed without merging**
