### PR TITLE
feat(Ghost Node): Add support for lexical format

### PR DESCRIPTION
**Pull request by mcnaveen**
### Why this PR?
- This PR adds a lexical format to the Ghost node.
- Recently Ghost moved from mobiledoc to lexical as a main editor. 

References:
- https://forum.ghost.org/t/dev-team-question-whats-the-future-of-mobiledoc/39277/8
- https://forum.ghost.org/t/is-mobiledoc-removed-from-ghost/41949

### CODE REVIEW

**Comment by Joffcom** [comment]
@mcnaveen did you want to fix the lint errors so we can get this merged? I would be tempted to keep the default as MobileDoc for now as well.

**Comment by mcnaveen** [comment]
Sure sure. Will push the changes asap.

**Comment by mcnaveen** [comment]
Hi @Joffcom Done.

**Comment by Joffcom** [comment]
Hey @mcnaveen 

Perfect, will get that merged shortly,

**Review by Joffcom — APPROVED** [review]

**Comment by mcnaveen** [comment]
Finally, they updated the developer documentation. https://ghost.org/docs/admin-api#the-post-object

Any ETA on when this will be released? @netroy @Joffcom

**Comment by netroy** [comment]
@mcnaveen This will be released in `1.13.0` later today.

**Comment by mcnaveen** [comment]
Thanks @netroy 🎉

**Comment by janober** [comment]
Got released with [`n8n@1.14.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.14.0)

**Pull request merged**
