### PR TITLE
[N8N-4332] Setup Typescript incremental builds

### PR DESCRIPTION
**Pull request by netroy**

### CODE REVIEW

**Comment by ivov** [comment]
Does `skipLibCheck` skip type declaration files in our own packages in addition to those in third-party libs? Based on [this](https://www.typescriptlang.org/tsconfig#skipLibCheck), it looks like it skips all of them wherever located. If so, might it be worth converting our own `.d.ts` to `.ts` or `.types.ts` so ours are not skipped?

**Comment by netroy** [comment]
for now I've removed the `skipLibCheck` that were added in this PR.

**Comment by ivov** [comment]
Have you seen [this](https://github.com/vercel/turborepo/issues/839)? Can you help me understand how we expect the `incremental` flag to interact with Turborepo cache artifacts?

Having tested making a single change and rebuilding with and without this flag, I am not seeing any noticeable speed improvement:

- TR only, cache hit: 2.265s
- TR + flag, cache hit: 2.124s
- TR only, cache miss: 19.916s
- TR + flag, cache miss: 19.928s

```
Model Name: MacBook Pro
Model Identifier: MacBookPro17,1
Chip: Apple M1
Total Number of Cores: 8 (4 performance and 4 efficiency)
Memory: 16 GB
```

**Comment by netroy** [comment]
@ivov i hadn't seen that issue. I'll check it now.

Can you please delete your `tsc` cache (`rm -rf packages/**/tsconfig.tsbuildinfo`) and run the benchmark once more?

**Comment by ivov** [comment]
@netroy Could you please provide exact steps to be able to see the difference? The difference I'm seeing is negligible when building on top of `tsconfig.tsbuildinfo` vs. when using `rm -rf packages/**/tsconfig.tsbuildinfo`and then building, while ensuring that TR has a cache miss. Thanks.

**Comment by netroy** [comment]
I ran a few builds on this branch, and on master. To invalidate the build cache I also ran `tsc --build --clean` in every module.

For the `cli` package:

| Build | Time (seconds) |
| --- | --- |
| master | 20 |
| Incremental - no cache |  20 |
| Incremental - with cache | 5 |


image

For the `nodes-base` package:

| Build | Time (seconds) |
| --- | --- |
| master | 60 |
| Incremental (no cache) |  62 |
| Incremental (with cache) | 9 |

image


For the full build (turbo repo cache disabled):

On master:
image

On this branch, after the tsc cache is generated:
image

**Review by BHesseldieck — APPROVED** [review]

**Comment by janober** [comment]
Got released with `n8n@0.194.0`

**Pull request merged**
