### PR TITLE
Add RabbitMQ Exchange's Header parameter

### PR DESCRIPTION
**Pull request by stwonary**
This PR includes changes to RabbitMQ node to support:
- Custom Header options in exchange mode 

the below workflow can be used to test the added option.
```
{
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        250,
        300
      ]
    },
    {
      "parameters": {
        "mode": "exchange",
        "exchange": "direct",
        "exchangeType": "=x-delayed-message",
        "options": {
          "argumen": {
            "argument": []
          },
          "headers": {
            "header": [
              {
                "key": "x-delay",
                "value": "1001"
              }
            ]
          }
        }
      },
      "name": "RabbitMQ",
      "type": "n8n-nodes-base.rabbitmq",
      "typeVersion": 1,
      "position": [
        780,
        290
      ],
      "credentials": {
        "rabbitmq": "rabbitmq"
      }
    },
    {
      "parameters": {
        "functionCode": "items[0].json.timestamp = new Date().toString();\nreturn items;"
      },
      "name": "Function",
      "type": "n8n-nodes-base.function",
      "typeVersion": 1,
      "position": [
        470,
        290
      ]
    }
  ],
  "connections": {
    "Function": {
      "main": [
        [
          {
            "node": "RabbitMQ",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  }
}
```

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot. Sadly am I not able to build it. There seem to be some issues:
Screenshot from 2021-04-03 11-19-32

**Comment by stwonary** [comment]
sorry about that, I'm not a typescript expert, but seems to be the linter. I'll try to do a code refactoring for Typescript.

**Comment by stwonary** [comment]
It's fixed now. Please try again

This time I make sure that `npm run build` and `npm run test` ran without errors.

Thank you

Screenshot from 2021-04-03 14-07-52


Screenshot from 2021-04-03 14-08-58

**Comment by janober** [comment]
Thanks a lot! Got merged.

Made some improvements:
https://github.com/n8n-io/n8n/commit/51f066cbcd7a7d24c9e3885b8aef06d20d9d173d

- implemented headers also for queue mode
- allowed different value per item (before expressions just used the data of the first item for all)
- sorted options alphabetically

**Comment by janober** [comment]
Got released with n8n@0.115.0

**Pull request merged**
