### PR TITLE
fix: Fix template credential setup for nodes that dont have credentials (no-changelog)

### PR DESCRIPTION
**Pull request by tomi**
## Summary

Fix template credential setup for templates whose workflow includes nodes that require credentials but the workflow definition does not have them defined. Like for example https://n8n.io/workflows/1344-save-email-attachments-to-nextcloud/

**Before**:

https://github.com/n8n-io/n8n/assets/10324676/579174c6-0ea4-44b2-ad17-15d1ae163958

**After**:

https://github.com/n8n-io/n8n/assets/10324676/0262dc66-26ff-4ea6-aca3-ac6aafa310e5

## Related tickets and issues

https://linear.app/n8n/issue/ADO-1603/bug-show-credential-setup-for-nodes-that-dont-have-credentials-in-the

## Review / Merge checklist
- [x] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

### CODE REVIEW

**Comment by mutdmour** [comment]
on PR name, why no changelog?

**Comment by tomi** [comment]
> on PR name, why no changelog?

Since it's behind a feature flag I figured we might not want to include. WDYT, should we include it still?

**Review by mutdmour — DISMISSED** [review]
LGTM. Awesome job. Would be great to also add E2E tests for this edge case.

**Comment by mutdmour** [comment]
> > on PR name, why no changelog?
> 
> Since it's behind a feature flag I figured we might not want to include. WDYT, should we include it still?

I see. I would say it should still be included. But maybe a good question for @StarfallProjects.

**Comment by tomi** [comment]
@mutdmour added e2e test. Could you recheck?

**Review by mutdmour — APPROVED** [review]

**Comment by StarfallProjects** [comment]
> > > on PR name, why no changelog?
> > 
> > 
> > Since it's behind a feature flag I figured we might not want to include. WDYT, should we include it still?
> 
> I see. I would say it should still be included. But maybe a good question for @StarfallProjects.

With the changelog, we need to either:

- Only include things that are actually released from the user point of view
- Include everything, but clearly indicate when features aren't available yet

It gets confusing when we have "Release shiny new feature" only shiny new feature is actually still a couple of weeks away from being live.

**Comment by Joffcom** [comment]
Got released with [`n8n@1.24.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.24.0)

**Pull request merged**
