### PR TITLE
fix: Test failing for toDate from string extension test (no-changelog)

### PR DESCRIPTION
**Pull request by valya**

### CODE REVIEW

**Review by netroy — COMMENTED** [review]
How about we create a general utility function like this, that can be also used in the app (if needed):
```typescript
const getLocalISOString = (date: Date) => {
	const offset = date.getTimezoneOffset();
	const offsetAbs = Math.abs(offset);
	const isoString = new Date(date.getTime() - offset * 60 * 1000).toISOString();
	const hours = String(Math.floor(offsetAbs / 60)).padStart(2, '0');
	const minutes = String(offsetAbs % 60).padStart(2, '0');
	return `${isoString.slice(0, -1)}${offset > 0 ? '-' : '+'}${hours}:${minutes}`;
};
```

Then this test could be written as
```typescript
test('.toDate() should work on a string', () => {
	const date = new Date(2022, 0, 3);
	expect(evaluate(`={{ "${getLocalISOString(date)}".toDate() }}`)).toEqual(date);
});
```

**Comment by valya** [comment]
Happy to do that. Any idea where it'd live? If not, I'll just throw it in the test utils for workflow.

**Comment by netroy** [comment]
> Happy to do that. Any idea where it'd live? If not, I'll just throw it in the test utils for workflow.

For now `packages/workflow/test/ExpressionExtensions/Helpers.ts` could be a good place to put this in. We can move it elsewhere when we need to.

**Review by netroy — APPROVED** [review]
Thanks 👍🏽

**Pull request merged**
