### PR TITLE
improve function nodes (continueOnFail, performance)

### PR DESCRIPTION
**Pull request by lublak**
- add continueOnFail support
- do not JSON.stringify/parse binary data

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot for this PR, but I do not think it can be merged. Is for sure faster to not copy the binary data but now if somebody would make changes to the binary data (or the metadata like file-name) it would mess it up in other parallel branches.

**Comment by lublak** [comment]
@janober i shadow copy the binary with: Object.assign(newItem.binary, item.binary);
the binary data looks like this:
{
    filename: 'test.png',
    mimeType: 'png',
    data: 'base64:string'
}
 a shadowcopy should be completely sufficient or do i see it wrong?

**Comment by janober** [comment]
Thanks for your response. I will have a deeper look later.

**Comment by michael-radency** [comment]
Hello @lublak, can you please update to a latest master? some files was moved and there is many merge conflicts

**Comment by lublak** [comment]
@michael-radency yes i can do it in the next days :)

**Comment by michael-radency** [comment]
> some files was moved and there is many merge conflicts

thank you :)

**Comment by lublak** [comment]
@michael-radency please give it a try :)

**Comment by michael-radency** [comment]
> @michael-radency please give it a try :)

Hi @lublak , thank you, I will do after my current task

**Comment by michael-radency** [comment]
Hello @lublak your project structure still different then upstream, please do `git pull upstream master` and resolve merge conflicts

**Comment by lublak** [comment]
@michael-radency 

I used a push force to rebuild one completely from the latest n8n point. It was easier to just pull a new n8n version to work from that point.
grafik


The structure fits with the current structure.
grafik

**Comment by michael-radency** [comment]
Hello @lublak you need to add remote to your fork, as stated in CONTRIBUTING.md
1. Add the original n8n repository as `upstream` to your forked repository
    ```
	git remote add upstream https://github.com/n8n-io/n8n.git

**Comment by Susangriffis** [comment]
Please I seem not to understand everything about this yet.. I seriously need a legit help

**Comment by michael-radency** [comment]
> Please I seem not to understand everything about this yet.. I seriously need a legit help
in root folder of n8n repository is CONTRIBUTING.md file with some info about setup and contributing process

**Comment by lublak** [comment]
@michael-radency Just for your information. There are still no merge conflicts.
What you mean is that it just syncs with the master.
So I was a bit confused. I have merged the master again.
However, this should not have been a problem when testing out.

**Comment by michael-radency** [comment]
Thanks @lublak , there is no conflicts now, not sure what was causing problem, I will review this PR today

**Comment by michael-radency** [comment]
Hi @lublak please take a look at this workflow, unfortunately your approach will not work, as @janober mentioned above it will cause problems in parallel branches, as a result all filenames are renamed to one set in a node that executed last, you can compare it with master where all files renamed correctly.

`
{
  "name": "function nodes improvements PR",
  "nodes": [
    {
      "parameters": {},
      "name": "Start",
      "type": "n8n-nodes-base.start",
      "typeVersion": 1,
      "position": [
        300,
        360
      ]
    },
    {
      "parameters": {
        "functionCode": "return [\n  {\n    json: {\n      id: 1,\n      name: \"Jim\"\n    }\n  },\n  {\n    json: {\n      id: 2,\n      name: \"Stefan\"\n    }\n  },\n  {\n    json: {\n      id: 3,\n      name: \"Hans\"\n    }\n  }\n];"
      },
      "name": "Mock Data",
      "type": "n8n-nodes-base.function",
      "position": [
        880,
        480
      ],
      "typeVersion": 1
    },
    {
      "parameters": {
        "url": "https://n8n.io/n8n-logo.png",
        "responseFormat": "file",
        "options": {}
      },
      "name": "HTTP Request",
      "type": "n8n-nodes-base.httpRequest",
      "position": [
        870,
        680
      ],
      "typeVersion": 1,
      "alwaysOutputData": false
    },
    {
      "parameters": {
        "mode": "mergeByIndex"
      },
      "name": "Merge",
      "type": "n8n-nodes-base.merge",
      "position": [
        1130,
        580
      ],
      "typeVersion": 1
    },
    {
      "parameters": {
        "functionCode": "const binaryData = items[0].binary;\nconst data = items.map(item => {\n  binaryData.data.fileName = 'newName.png';\n  return {\n    json: item.json,\n    binary: binaryData\n  }\n});\n\nconsole.log(data[0].binary);\n\n\nreturn data;\n"
      },
      "name": "Function",
      "type": "n8n-nodes-base.function",
      "position": [
        1360,
        460
      ],
      "typeVersion": 1
    },
    {
      "parameters": {
        "functionCode": "const binaryData = items[0].binary;\nconst data = items.map(item => {\n  binaryData.data.fileName = 'otherName.png';\n  return {\n    json: item.json,\n    binary: binaryData\n  }\n});\n\nconsole.log(data[0].binary);\n\n\nreturn data;\n"
      },
      "name": "Function1",
      "type": "n8n-nodes-base.function",
      "position": [
        1340,
        800
      ],
      "typeVersion": 1
    },
    {
      "parameters": {},
      "name": "Merge1",
      "type": "n8n-nodes-base.merge",
      "typeVersion": 1,
      "position": [
        1640,
        660
      ]
    }
  ],
  "connections": {
    "Start": {
      "main": [
        [
          {
            "node": "HTTP Request",
            "type": "main",
            "index": 0
          },
          {
            "node": "Mock Data",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Merge": {
      "main": [
        [
          {
            "node": "Function",
            "type": "main",
            "index": 0
          },
          {
            "node": "Function1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Mock Data": {
      "main": [
        [
          {
            "node": "Merge",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "HTTP Request": {
      "main": [
        [
          {
            "node": "Merge",
            "type": "main",
            "index": 1
          }
        ]
      ]
    },
    "Function1": {
      "main": [
        [
          {
            "node": "Merge1",
            "type": "main",
            "index": 1
          }
        ]
      ]
    },
    "Function": {
      "main": [
        [
          {
            "node": "Merge1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "active": false,
  "settings": {},
  "id": 45
}
`

**Comment by nivb06** [comment]
Hi @lublak, thanks for contributing to n8n!
I am closing this PR, see @michael-radency comments above for detailed explanations

**Comment by lublak** [comment]
@michael-radency Hmmm okay. Currently I don't understand why. Because I copied it manually without json stringify and parse (because I think JSON stringify binary data is a bad idea).
I will look into and make a new pull request.

**Pull request closed without merging**
