### PR TITLE
refactor: Remove basic auth env vars from docker compose stacks

### PR DESCRIPTION
**Pull request by ivov**
https://linear.app/n8n/issue/N8N-6582/update-docker-compose-stacks-for-v1

### CODE REVIEW

**Review by netroy — CHANGES_REQUESTED** [review]
can you also remove this from the other `.env` files please?
image

**Review by netroy — APPROVED** [review]

**Comment by Joffcom** [comment]
@ivov @netroy as we are planning to remove MySQL / MariaDB in the future why not remove the MariaDB example as well?

**Review by netroy — APPROVED** [review]
Thanks 💟

**Comment by janober** [comment]
Got released with [`n8n@1.0.2`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.0.2)

**Pull request merged**
