### PR TITLE
New node for Rundeck API

### PR DESCRIPTION
**Pull request by lucaskenda**
I've added a new node for Rundeck (https://www.rundeck.com/).

### CODE REVIEW

**Comment by janober** [comment]
Great, thanks a lot @lucaskenda!

I saw that some of the files use spaces rather than tabs. Do you want to fix that? I could do it but then I would get attributed to the whole files instead of you who did actually write them.

**Comment by janober** [comment]
Thank you very much @lucaskenda!

I merged the node now. Made the following changes:
- Added "Resource" property to be easier extendable in the future and to work identically to other nodes
- Added operation "getMetadata" to query the metadata of a job
- Replaced Axios with the build-in request module to work identically to all other nodes and because Axios is not a dependency of the package and is only there because another package currently requires it
- changed that it directly requests data as JSON instead of XML and then converting it
- removed API version from credentials

**Comment by lucaskenda** [comment]
Excelent, thanks!
I've used API version like the Jenkins Rundeck plugin which requires the number to check if it can perform the request, but you are right, is nonsense.

**Comment by janober** [comment]
I understood where it came from but as it got only used to check if the request can be made, and if not in the worst case all it did was to say that it does not work, I thought I can safely remove it as the same would happen without it anyway. 
It is so simple one less thing that people can get confused by, as it, for example, confused me as I did first have no idea what to set there.

**Comment by janober** [comment]
Got released with n8n@0.56.0

**Pull request merged**
