### PR TITLE
fix(TimescaleDB Node): Update TimescaleDB logo (no-changelog)

### PR DESCRIPTION
**Pull request by noctarius**
The TimescaleDB logo is still the old brand design. Updated it to the current black version.

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @noctarius,

Thanks for the PR, Is this black logo preferred over the yellow?

**Review by Joffcom — APPROVED** [review]

**Comment by Joffcom** [comment]
@noctarius it is a white background in n8n but we have users that apply their own theme, If we change the standard colour scheme though we can always update the logo :)

**Comment by noctarius** [comment]
Sounds good to me :-)

**Comment by Joffcom** [comment]
@noctarius that has been merged :) I will let the web team know so we can change it on the site as well. Thanks again for the PR

**Comment by janober** [comment]
Got released with [`n8n@0.236.3`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.236.3)

**Pull request merged**
