### PR TITLE
✨ Add INSERT modifiers support in mySQL node

### PR DESCRIPTION
**Pull request by entrailz**
Allow for insert ignore - useful if you are wanting to insert data into an already established table with unique ids.

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot for your contribution!

But looking at it does it seem like something that should be rather an additional option on "Insert" than its own operation.

**Comment by entrailz** [comment]
> Thanks a lot for your contribution!
> 
> But looking at it does it seem like something that should be rather an additional option on "Insert" than its own operation.

I do agree - if I'm honest I'm not too confident in making that work so added it as a different operation.

**Comment by lublak** [comment]
@entrailz it should not to complex.
Just add an
`type: 'boolean',` 
, than get it with:
```ts
const ignore = this.getNodeParameter('ignore', 0) as as boolean;
```
and use it like this:
```ts
const insertSQL = 'INSERT' + (ignore ? ' IGNORE' : '') + ` INTO ${table}(${columnString}) VALUES ${items.map(item => insertPlaceholder).join(',')};`;
```

**Comment by janober** [comment]
Got released with n8n@0.116.0

**Pull request merged**
