### PR TITLE
fix bug with connections deleted when node is renamed

### PR DESCRIPTION
**Pull request by mutdmour**
fixes https://community.n8n.io/t/bug-node-connections-keep-getting-removed-latest-update-docker/9335

to reproduce issue:
1. create workflow with two nodes, save and refresh
2. add a free floating node and drag a connector to its endpoint (specifically the endpoint, not the node box)
3. rename added node

### CODE REVIEW

**Comment by thosanmaytinh** [comment]
please help fix this bug and merge it

**Comment by janober** [comment]
The bug is already fixed. So no need for anybody to help.

It will be reviewed and merged in time to be released with the next n8n version.

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with `n8n@0.151.0`

**Pull request merged**
