### PR TITLE
docs: Branding tweaks for Cal and Citrix ADC (no-changelog)

### PR DESCRIPTION
**Pull request by Joffcom**
## Summary
Moved automizy to hidden and added notices as the service may no longer exist
Renamed Citrix ADC to Netscaler ADC, We need to keep the `name` for the node and credential as `citrixAdx` to prevent a breaking change
Small update to Cal to change the display name to cal.com to fit with branding, Still fits the original structure.

Created Docs PR Here: https://github.com/n8n-io/n8n-docs/pull/2232 

## Related Linear tickets, Github issues, and Community forum posts
https://linear.app/n8n/issue/NODE-1462/small-node-branding-tweaks

### CODE REVIEW

**Comment by RicardoE105** [comment]
@Joffcom renaming Citrix won't break the people currently using it?

**Comment by Joffcom** [comment]
@RicardoE105 only if we change the `name` value we did this before with Brevo (https://github.com/n8n-io/n8n/pull/6521)

**Review by ShireenMissi — APPROVED** [review]
LGTM 🎉

**Comment by janober** [comment]
Got released with [`n8n@1.51.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.51.0)

**Pull request merged**
