### PR TITLE
:sparkles: Dropcontact node

### PR DESCRIPTION
**Pull request by RicardoE105**

### CODE REVIEW

**Comment by PaulineDropcontact** [comment]
Thanks, @RicardoE105 for your review.
It's perfect, only one little thing: our waiting time to have an optimal response from our algorithms is 45 seconds (and not 10 seconds)
Can we change it ?

**Comment by RicardoE105** [comment]
@PaulineDropcontact I set it to two 10 seconds because on my tests 10 seconds worked fine. But good to know. I will change it back.

**Review by PaulineDropcontact — COMMENTED** [review]
Perfect :)

**Review by PaulineDropcontact — APPROVED** [review]

**Review by PaulineDropcontact — APPROVED** [review]

**Review by PaulineDropcontact — APPROVED** [review]

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by PaulineDropcontact** [comment]
> Thanks a lot. Got merged.

Great :) thanks 💚

**Comment by janober** [comment]
Got released with n8n@0.148.0

**Pull request merged**
