### PR TITLE
Added Mandrill support

### PR DESCRIPTION
**Pull request by RicardoE105**
Hey I implemented the basic features to send either a template or a html email. Gonna keep adding support for all the fields on the api request to send emails.

### CODE REVIEW

**Comment by janober** [comment]
Really cool! Is already looking good. Tell me when it is ready to test and merge.

Wish you a great weekend!

**Comment by RicardoE105** [comment]
@janober you can test now, There is not free plan for Mandrill but I can send you an api key so that you can test it. Should I send it to your email?

**Comment by janober** [comment]
Really cool! Thanks a lot!

Yes, that would be great! Will however not get to it before Wednesday. Hope that is ok.

**Comment by RicardoE105** [comment]
@janober which is your email? gonna send you the key!

**Comment by janober** [comment]
@RicardoE105 Thanks a lot! It is jan@n8n.io

**Comment by janober** [comment]
Just did the initial check of your node. Looks like you put a lot of work into that. Really good work, it seems to be very powerful! 

The powerful is however also a little bit of a problem. As the node has a lot of options (which is great) but it seems like most of them are not needed all the time. Only the parameters which are always needed like: template, fromEmail, toEmail, subject, html, text 
Should be displayed by default. All other ones should only be added when the user really wants/needs them.
A good example of that is the "XML-Node". Most users should not have the need to change anything. So by default, the only thing that gets displayed is the name of the property to read from. But if they have to change the default behavior (or in your case to for example track clicks) they can add that parameter by themself. That makes, on the one hand, sure that people do not get intimidated the first time they add a node, it also helps a lot in seeing what a node is actually doing very fast and simple.

Another thing is that parameters like "Merge vars", "Metadata", "Recipient metadata", "Attachments" and "Images". Should not be JSON. People should be able to add multiple values via easy to use parameters. The JSON-Option is still important and should so also be possible but only if selected. You can see that for example in the "HTTP Request-Node". There parameters like "Headers" and "Query/Body Parameters" can either be set via the UI or the user can switch to "JSON" and create so everything dynamically.

The reason for that is that on the one hand non-programmers can still do all the basic things simply via the UI but programmers have at the same time still the possibility to make everything more dynamic and powerful.

For things like attachments should it also read from binary data properties. Like in the "Send Email-Node". In that properties, information like mime-type and data is already present as base64. So people just have to type in the name of the properties they want to add and do not have to worry about anything else. If you are not familiar with the binary-data you can check out this workflow:
https://n8n.io/workflows/3

Apart from that I just saw minor issues like that, for example, missing semicolons, shorthand object-literals which should get used and that it mixes tabs and spaces (the whole project uses tabs). If your IDE does not display that issues by default you can run the linter manually with: `npm run tslint`. It will then display you the lines in which problems got found.

The last thing is that some of the parameter descriptions do not start with a capital letter and do not end with a dot. Not a big issue but just to make all of them consistent between nodes.

If you have any problems or disagree with things I said simply get back to me.

**Comment by RicardoE105** [comment]
Hey @janober I did not know the existence of those options gonna make the corrections and let you know. Thanks

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by janober** [comment]
Great thanks!

Yes sorry, I definitely still have a lot to do on the documentation front. But if you ever have problems or questions I am always happy to help!

**Comment by RicardoE105** [comment]
@janober I'm making the changes and I have the following doubt: The attachments fields should be type json, fixedCollection and string (In case there is binary data I can reference to)?

**Comment by RicardoE105** [comment]
Hey, @janober this commit just includes changes on the UI, wanna make sure I have it right before changing the execute function. I did what you mention with the JSON switch but not sure how to add the binary option for attachments and images, I have them already as `fixedCollection` so the user can add each field easily and `json` so that advanced users can use it, but I need to add a string type as well for each of them so the user can reference the property which contains the binary data but not sure how to add this on the UI. Maybe another switch that says binary data? is it possible to change a switch value base on another switch? cuz If the user turns binary on I can turn the json switch off and show the attachments and images string fields.

**Comment by RicardoE105** [comment]
@janober I think I figured it out, in my mind something like this could work, check it out when you have time and let me know. 

Question? is it a bug that  `alwaysOpenEditWindow: true`  does not work with properties type `JSON`?

**Comment by janober** [comment]
The answer I did just finish before your last commit. Will check that now: 

Thanks a lot is looking good!

I was wondering why you moved "subject", "text" and "html" in options. Are they not required fields?

When in not JSON mode there seems to be something wrong with "Headers". It is only possible to add one value but not remove it. Also should that field probably be "multipleValues: true" that will also fix the first issue I guess). Sure the data sent will not be an array but out of that array an object can be generated. Which makes sense as people should be able to set multiple header values if I understand it correctly.

About your problem with the binary-property. What you could do is to simply add a second option to the "attachmentsUi". The great thing about "fixedCollection" is that you can define multiple different such "collections" to choose from. Currently, you have only one kind defined (which has: type, name, and content). You can simply define a second block in the "options" array. This one would then not contain 3 different fields it could only contain one string field to set a binary-property-name. The users could then select which they want to add when they press the "Add-button". Either the one that currently exists or the one to get the data from a binary property. Hope that makes sense. If not simply get back to me.

**Comment by janober** [comment]
I just checked your last commit. I agree that it would work like that but I think it is a little bit confusing if there are multiple fields at the same time visible to define the same data. So still think the approach with the multiple values in the "fixedCollection" will be easier to understand and clearer for users.

**Comment by RicardoE105** [comment]
cool @janober did not you can have multiple options in a `fixedCollection`. Regarding the subject", "text" and "html" in options, yes you are right they are not required on the API.

**Comment by janober** [comment]
Great! Then all good.

About the "alwaysOpenEditWindow" in combination with "json". That was really a bug. Did just fix it. Thanks for telling me about it!

**Comment by RicardoE105** [comment]
@janober  The issue with doing it like this is that the user can set both properties so which one should I use when this happens?

image

**Comment by janober** [comment]
That should not be an issue as you can simply set both. It could be quite possible that the user wants to send on attachment which is in the binary-data and another one from the json-data (like if he actually wants to attach a JSON file).

**Comment by RicardoE105** [comment]
@janober When you add an item and them remove the option's name stay there, should not the layout be back like in the picture number one when there is not any item added. 

image

**Comment by janober** [comment]
@RicardoE105 Yes you are right. That is a known bug I never had time to properly look into. The issue is probably that the parent-item stays behind and does not get cleaned up once the last child-item got removed.

**Comment by RicardoE105** [comment]
@janober also If you do not set a placeholder on the property type `fixedCollection` the default message should be `Choose Option To Add` to keep the standard right?

image

**Comment by janober** [comment]
@RicardoE105 Sorry do not understand what you mean.

**Comment by RicardoE105** [comment]
@janober the `choose option to add` should be Upper Case to keep the standard.

**Comment by janober** [comment]
@RicardoE105 Ah yes, now I understand. You are right. Thanks got fixed.

**Comment by janober** [comment]
Great thanks a lot for the changes! Looked now great so merged it. 

Had to however make some cosmetic changes
- added some commas
- changed some descriptions (like adding dots and splitting into multiple lines as some were very long)
- fixed indentation (was mixed spaces & tabs)
- changed resource name from "messages" to "message" (as they are normally always singular)

I will release a new version of n8n the next days with your integration in it. Thanks for your hard work!

**Pull request merged**
