### PR TITLE
feat(RabbitMQ Trigger Node): Make message acknowledgement and concurrent processing configurable

### PR DESCRIPTION
**Pull request by janober**

### CODE REVIEW

**Comment by tinti** [comment]
Hi @janober,

Is this related to https://github.com/n8n-io/n8n/pull/3272 ?
Should I close it?

**Comment by janober** [comment]
@tinti it is related but not the same as your PR allows more fine-grained control as it achieves something similar via a special node. So please leave the PR open for now.

**Comment by janober** [comment]
Got merged.

**Comment by janober** [comment]
Got released with `n8n@0.179.0`

**Pull request merged**
