### PR TITLE
fix(core): Restore old names for pruning config keys

### PR DESCRIPTION
**Pull request by ivov**
## Summary

https://github.com/n8n-io/n8n/pull/11507 renamed the poorly named pruning config keys in the schema object, but it turns out the internal structure of the schema object is being relied on externally via `N8N_CONFIG_FILES`, so this PR renames back those keys until we can deprecate and drop this env var in v2.

## Related Linear tickets, Github issues, and Community forum posts

https://github.com/8gears/n8n-helm-chart/issues/125

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Review by tomi — CHANGES_REQUESTED** [review]
If I have a `config.json` file like this:

```json
{
	"executions": {
		"pruneData": true,
		"pruneDataMaxAge": 30,
		"pruneDataMaxCount": 100
	}
}
```

and I start n8n with `N8N_CONFIG_FILES=config.json pn start` it works on `1.66.0` but not with latest master or this branch. The pruning config needs to be under `executions`. Also could we add tests for this so it doesn't break a seconds time?

**Comment by ivov** [comment]
>under `executions`

Good catch! Fixed

>tests for this

Let's add tests for this separately for all remaining schema keys? As it's a more general issue and we should include this PR in today's release.

**Comment by tomi** [comment]
> > under `executions`
> 
> Good catch! Fixed
> 
> > tests for this
> 
> Let's add tests for this separately for all remaining schema keys? As it's a more general issue and we should include this PR in today's release.

Fair enough. Ideally we should include a test for the case that broke in the first place. But we can merge this to get it on the release. Should add the tests after this so we don't forget

**Review by tomi — APPROVED** [review]
🚀

**Comment by ivov** [comment]
Tracking here: https://linear.app/n8n/issue/PAY-2265/add-tests-for-all-old-config-schema-keys

Merging this might need to wait for the MySQL tests fix, as yesterday unrelated tests MySQL kept failing on CI.

**Comment by janober** [comment]
Got released with [`n8n@1.69.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.69.0)

**Pull request merged**
