### PR TITLE
Add Harvest Node

### PR DESCRIPTION
**Pull request by trojanh**
Add Harvest API for 
- [x] CRUD for `TimeEntry` 
- [x] Add ReturnAll function
- [x] Read - `Clients`
- [x] Read - `Projects`
- [x] Read - `Contacts`
- [x] Read - `Company`
- [x] Read - `Invoice`
- [x] Read - `Task`
- [x] Read - `Users`
- [x] Read - `Expenses`
- [x] Read - `Estimates`

### CODE REVIEW

**Comment by trojanh** [comment]
@janober for some reason while working on this PR, every time I did `npm run dev` I was getting following `git status`. Also, many node logos were not loaded in the node dropdown including the one I created in this PR. 

image

**Comment by janober** [comment]
Really cool! Thanks a lot @trojanh just got merged.

Made some changes:
 - simplified some things. Especially remove unnecessary try/catch blocks
 - fixed some small lint issues
 - renamed some fields to "fit" to API
 - moved some required fields out of options

Also tried to fix "createByDuration" and "createByStartEnd". Did you test them? Because for me it looks like they could never have worked as they did send the data as query-string instead of via the body. Also were some of the parameters named wrong. In case you did not test it. Please make sure that you always test everything before you create a pull request. I can sadly not always catch everything and if I know that stuff got already tested before, the chance is higher that only working stuff gets released.

And somehow even though now all the data that gets sent to the API is correct "createByStartEnd" does still not work like I would have expected it to. It somehow seems to totally ignore "started_time" and "ended_time".

Can you please check my changes if they look OK for you. Thanks a lot!

**Comment by trojanh** [comment]
sorry @janober , but I missed testing those ones, I had them working in postman but I missed correcting it in the node. After your change, `createByDuration` is working fine. Thanks

To make `createByStartEnd` we will need to follow this: 

> You should only use this method to create time entries when your account is configured to track time via start and end time. You can verify this by visiting the Settings page in your Harvest account or by checking if wants_timestamp_timers is true in the [Company API](https://help.getharvest.com/api-v2/company-api/company/company/).

Is there a place where we can show this to the user, other than the input tooltip  ?

**Comment by janober** [comment]
Ah ok, then it makes sense now. Thanks a lot for explaining.

No there is sadly no other location right now. 

Thanks again for the great work! Got released with n8n@0.51.0

**Pull request merged**
