### PR TITLE
Fix/continue on fail

### PR DESCRIPTION
**Pull request by MedAliMarz**
This PR update 148 nodes to support continueOnFail, and refactor 11 nodes:

<details>
<summary><b>The updated nodes:</b></summary>

- Compression
- Crypto
- DateTime
- EditImage
- EmailSend
- ExecuteCommand
- ExecuteWorkflow 
- Ftp
- Function
- FunctionItem
- OpenWeatherMap
- ReadBinaryFile
- ReadPdf
- RssFeedRead
- SpreadsheetFile
- Switch
- WriteBinaryFile
- Xml
- ActiveCampaign
- Affinity
- Airtable
- Amqp
- ApiTemplateIo
- Asana
- AwsLambda
- AwsSns
- AwsComprehend
- AwsRekognition
- AwsS3
- AwsSes
- AwsSqs
- Bitly
- Box
- Brandfetch
- Chargebee
- CircleCi
- Clearbit
- ClickUp
- Clockify 
- Cockpit
- Coda 
- CoinGecko
- Contentful
- ConvertKit
- Cortex
- CustomerIo
- DeepL
- Demio
- Discourse 
- Disqus
- Drift
- Dropbox
- Freshdesk 
- GetResponse
- Ghost 
- Github
- Gitlab
- GoogleAnalytics
- GoogleBooks
- GoogleCalendar
- GoogleContacts 
- GoogleDrive
- Gmail
- GoogleSheets
- GoogleSlides
- GoogleTasks
- YouTube
- Gotify
- GraphQL
- HackerNews
- Harvest
- HtmlExtract
- Hubspot
- Hunter
- Intercom
- InvoiceNinja
- Kafka
- Line 
- LinkedIn
- Mailchimp
- MailerLite
- Mailgun
- Mailjet
- Mandrill
- Matrix
- Mattermost
- Mautic
- Medium
- MessageBird
- MicrosoftExcel
- MicrosoftOneDrive
- MicrosoftOutlook
- MicrosoftTeams
- Mindee 
- Mocean
- MondayCom
- MongoDb
- MySql
- Nasa
- NextCloud 
- OpenThesaurus
- Orbit
- PagerDuty
- PayPal
- Peekalink
- Phantombuster
- PostHog 
- ProfitWell
- Pushbullet 
- QuickBooks
- Raindrop
- Reddit
- Rocketchat
- S3
- Salesforce
- SendGrid 
- SentryIo
- Shopify
- Signl4
- Slack
- Spontit
- Spotify
- Stackby
- Storyblok
- Strapi 
- Strava 
- Taiga
- Tapfiliate 
- Telegram
- TheHive
- Todoist
- TravisCi
- Trello
- Twilio
- Twist
- Twitter
- Uplead
- UProc
- Vero
- Webflow
- Wekan
- Wordpress
- Xero
- Yourls
- Zendesk
- ZohoCrm
- Zoom 
- Zulip

</details>

<details>
<summary><b>The refactored nodes:</b></summary>

- Clockify
- Discourse
- Ghost
- GoogleContacts
- Line
- Mindee
- Pushbullet
- Strava
- Strapi
- Tapfiliate
- Zoom
</details>

### CODE REVIEW

**Comment by krynble** [comment]
Hey @MedAliMarz Thank you for the great contribution!

I was having a look and noticed some small errors when running `npm run tslint`.

Question: were you able to test if the changes broke anything? While applying the changes were you able to test if the behavior works as expected?

Thanks again!

**Comment by MedAliMarz** [comment]
> Hey @MedAliMarz Thank you for the great contribution!
> 
> I was having a look and noticed some small errors when running `npm run tslint`.
> 
> Question: were you able to test if the changes broke anything? While applying the changes were you able to test if the behavior works as expected?
> 
> Thanks again!

Hey @krynble , just added some fixes for the lint issue, concerning the expected behavior i've added some testing workflow to validate the changes. Please let me know if there is any recommended changes!

**Comment by krynble** [comment]
Thanks for the fixes @MedAliMarz 

Now that 0.119.0 has been released some files are now conflicting.

Could you please also fix these?

Thanks again!

**Comment by MedAliMarz** [comment]
> Thanks for the fixes @MedAliMarz
> 
> Now that 0.119.0 has been released some files are now conflicting.
> 
> Could you please also fix these?
> 
> Thanks again!

Hi @krynble , i merged the master branch and resolved the conflicts, please let me know if there is any further changes.

**Comment by krynble** [comment]
Closing in favor of https://github.com/n8n-io/n8n/pull/1996

**Pull request closed without merging**
