### PR TITLE
Add pagination for more than 100 items

### PR DESCRIPTION
**Pull request by Enrique66**
It would be helpful if you could add the option to expand the pagination to more than 100 items.

### CODE REVIEW

**Comment by RicardoE105** [comment]
If you want to return more than 100 items just set returnAll to true. Did you try that?

**Comment by Enrique66** [comment]
> If you want to return more than 100 items just set returnAll to true. Did you try that?

Hello Ricardo, yes a tried that first  and the result is:
ERROR: 400 - {"object":"error","status":400,"code":"validation_error","message":"query failed validation: query.start_cursor should be not present, instead was `\"48fb332a-49eb-4234-9ff4-04c8220633b2\"`."}

Whith limit less than 100 not problem.

**Comment by RicardoE105** [comment]
@Enrique66 got it. Found the issue. Sadly this PR does not completely fix the issue. I created a PR that completely fixes the issue. Anyways, thanks very much for your contribution. We will let you know it's released

https://github.com/n8n-io/n8n/pull/1907

**Comment by janober** [comment]
Thanks a lot @Enrique66 ! We just merged #1907

**Comment by janober** [comment]
Got released with n8n@0.126.0

**Pull request closed without merging**
