### PR TITLE
docs: Fix docker URL on README.md (no-changelog)

### PR DESCRIPTION
**Pull request by Valgueiro**
## Summary
Looks like the repo was outdated.

image
## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [x] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [x] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Comment by netroy** [comment]
Thanks. but this is a duplicate of #12294.
We can merge either, once one of the contributors signs the CLA.

**Comment by Joffcom** [comment]
Hey @Valgueiro,

Thanks for the PR, We have created "GHC-611" as the internal reference to get this reviewed.

One of us will be in touch if there are any changes needed, in most cases this is normally within a couple of weeks but it depends on the current workload of the team.

**Review by netroy — APPROVED** [review]

**Comment by netroy** [comment]
Thanks 🫶

**Comment by janober** [comment]
Got released with [`n8n@1.74.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.1)

**Comment by janober** [comment]
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)

**Comment by janober** [comment]
Got released with [`n8n@1.74.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.74.0)

**Pull request merged**
