### PR TITLE
Jackrudenko/unleashed

### PR DESCRIPTION
**Pull request by erudenko**
I have added pagination and fixed dates transformation.

### CODE REVIEW

**Comment by erudenko** [comment]
This PR is continue of work from #825

**Comment by RicardoE105** [comment]
@erudenko Quick question, I wonder why you added the page field, the pagination it's already done by the node. The page field it's not nedded

**Comment by erudenko** [comment]
If I don't have a page number I can select all the records or just first page.

Sometimes there are too much data to handle just with one request. So it would be cool to have a way to iterate and process it page by page.

Cheers.

**Comment by janober** [comment]
Great, thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.78.0

**Pull request merged**
