### PR TITLE
Grist node

### PR DESCRIPTION
**Pull request by alexmojaki**
Hello! This is a regular node for https://www.getgrist.com/, a spreadsheet-database hybrid. The product and API are similar to AirTable so I've used that as the basis for this node.

Community request: https://community.n8n.io/t/grist-integration/7462

Unfortunately I haven't been able to get nodelinter working:

```
$ npx nodelinter --target /home/alex/work/n8n/packages/nodes-base/nodes/Grist/Grist.node.ts      
No --config option specified, attempting to autodetect...

(node:29963) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getEnd' of undefined
    at Function.Collector.getLineNumber (/home/alex/work/n8n/node_modules/nodelinter/dist/services/Collector.js:63:93)
    at /home/alex/work/n8n/node_modules/nodelinter/dist/services/Logger.js:42:50
    at class_1.MiscellaneousValidator.run (/home/alex/work/n8n/node_modules/nodelinter/dist/services/subvalidators/MiscellaneousValidator.js:37:61)
    at Validator.runSubValidator (/home/alex/work/n8n/node_modules/nodelinter/dist/services/Validator.js:82:39)
    at /home/alex/work/n8n/node_modules/nodelinter/dist/services/Validator.js:76:19
    at Array.forEach (<anonymous>)
    at Validator.run (/home/alex/work/n8n/node_modules/nodelinter/dist/services/Validator.js:73:38)
    at validatorVisitor (/home/alex/work/n8n/node_modules/nodelinter/dist/services/Traverser.js:22:45)
    at visitNode (/home/alex/work/n8n/node_modules/nodelinter/node_modules/typescript/lib/typescript.js:83594:23)
    at Object.visitEachChild (/home/alex/work/n8n/node_modules/nodelinter/node_modules/typescript/lib/typescript.js:83868:62)

$ npx nodelinter --print --target /home/alex/work/n8n/packages/nodes-base/nodes/Grist/Grist.node.ts
  ERROR   Invalid option: Unknown option passed in: "--print" 
```

Any idea what's wrong? It gives a sensible error message for missing files and it shows lots of lint errors for other files. I don't know how to extract logs since `--print` isn't working.

Tomorrow I will write docs and make a PR in https://github.com/n8n-io/n8n-docs . Apart from that this PR is ready. I've gone through the checklist, tested all the operations and options well, including multiple items and continue on fail. It should be easy to figure out and test for yourself. You'll just need to sign up for a free account on https://www.getgrist.com/ and create a new document to test with.

Thanks for making an awesome product! n8n seems really cool!

### CODE REVIEW

**Comment by ivov** [comment]
Thank you very much for your contribution.

The `--print` issue has been fixed. Will look into the `getEnd()` issue and review the PR soon.

**Comment by ivov** [comment]
Closing here, the refactoring will soon be merged.

**Comment by janober** [comment]
Thanks a lot. Got merged #2158

**Comment by janober** [comment]
Got released with n8n@0.141.0

**Pull request closed without merging**
