### PR TITLE
⚡ TheHive: Add Mark as Read operation to alerts

### LINKED ISSUE #1226: TheHive Node - Alert Update keeps status: "New"
**Describe the bug**
Using TheHive Nodes - Action: Alert Update Ignored, don`t work, keeping status as "New"

**To Reproduce**
1. Create The Hive Node 
2. Action Alert - Update
3. Define the ID of Alert
4. Status type: Ignored
5. Run the Node

**Expected behavior**
The alert triggered should be updated with the new status: Ignored, but keeps the "New".

### PR DESCRIPTION
**Pull request by mluhta**
~~TheHive 4 uses a different API endpoint for marking alerts as read than TheHive 3, and the node currently has no way to mark alerts as read in TheHive 4. This PR adds operation "Mark as Read" to Alert resource when the API version is set as v1.~~

TheHive uses API endpoints ` /api/alert/<alert_id>/markAsRead ` and ` /api/alert/<alert_id>/markAsUnread ` to mark alerts as read or unread. They aren't currently implemented so this PR adds both operations.

Fixes #1226, as marking alert as read sets its status as Ignored.

### CODE REVIEW

**Comment by mluhta** [comment]
TheHive 3 does it actually the same way, and it needs the new operation too. I'll make the changes later today.

**Comment by nadouani** [comment]
Thanks @mluhta for the PR

The alert `markAsRead` and `markAsUnread` apis are available in TheHive 3 and 4, so I think that you can remove the version check.

**Comment by mluhta** [comment]
@nadouani Should we add the Mark as Unread operation aswell?

**Comment by RicardoE105** [comment]
@mluhta just tested, and it's working as expected. Thanks for your contribution.

**Comment by janober** [comment]
Thanks a lot. Got released with #1541

**Comment by janober** [comment]
Got released with n8n@0.112.0

**Pull request closed without merging**
