### PR TITLE
Clockify Node

### PR DESCRIPTION
**Pull request by RicardoE105**

### CODE REVIEW

**Comment by Sou1Aced** [comment]
Wow, you changed a lot. There is so much you did that I didn't even think of. I definitely still have a lot to learn about N8N. I'm still pretty new to this and not sure how best to give feedback, but the stuff I noticed while testing it was:
* If you try to use Clockify Trigger to bring in a bunch of time entries and then use those to make multiple Projects it throws an error if it runs into a duplicate. In my case I had 50 time entries brought in through the trigger to test, but they were only on 2 projects. It successfully made the project attached to the first entry, but when it got to the second entry (which was for the same project) it threw an error and immediately stopped, saying that the project existed already so it never made the second project that was attached to the later time entries. 
project
    * The same happens for Tags.
tag
* For Time Entry creation, when given information from the Clockify Trigger, it doesn't seem to like the use of expressions for the "Project ID" or "Tag IDs" fields. I couldn't find any values to put in them that did not cause an error (name and id don't work for Project ID and name, ID, the item as a Raw Value and the tag array as a raw value don't work for Tag IDs). 
time entry
* Also for Time entry creation, if you pick specifically from the drop down for "Project ID" and "Tag IDs" and use expressions for the rest of the fields, it does successfully create the Time Entries, but the returned value in the node only displays a single entry even though it created 50 different entries from the information brought in by the Clockify Trigger
return
* A minor thing, but it was giving me an error here at the top in the Clockify.node.ts because it was written as "tagDescription", changing it to "TagDescription" fixed it for me.
TagDescription


These are things that I was trying to go for in my merge request, but if that isn't how you guys wanted N8N to be used then I understand that and that also, obviously, makes these points I listed above not a problem and can be ignored. The rest of it works beautifully. When given information with no expressions the Create, Get, Get All, Update and Delete parts all work exactly as expected and I didn't run into any problems. Sorry that was rather long, I am not the best at this kind of stuff and wanted to make sure I explained what I was trying to say well enough, but I may have rambled on a bit. Let me know what you think about this because I am learning a lot from how you set up your changes.

**Comment by RicardoE105** [comment]
> Wow, you changed a lot. There is so much you did that I didn't even think of. I definitely still have a lot to learn about N8N. 

Ahh no problem at all, actually the exact thing happened to me when I started out contributing to the project. You can check 
[here](https://github.com/n8n-io/n8n/pull/94) 🤣 . Still today I'm learning about n8n.

> If you try to use Clockify Trigger to bring in a bunch of time entries and then use those to make multiple Projects it throws an error if it runs into a duplicate. In my case I had 50 time entries brought in through the trigger to test, but they were only on 2 projects. It successfully made the project attached to the first entry, but when it got to the second entry (which was for the same project) it threw an error and immediately stopped, saying that the project existed already so it never made the second project that was attached to the later time entries.

Can you please share the workflow so that I can have a proper look? Also If you can elaborate in what you are trying to achieve would be cool.

> For Time Entry creation, when given information from the Clockify Trigger, it doesn't seem to like the use of expressions for the "Project ID" or "Tag IDs" fields. I couldn't find any values to put in them that did not cause an error (name and id don't work for Project ID and name, ID, the item as a Raw Value and the tag array as a raw value don't work for Tag IDs).

The expresions should have worked as you mentioned. So I guess something weird is happening there. Again, with the workflow I will be able to have a proper look.

> A minor thing, but it was giving me an error here at the top in the Clockify.node.ts because it was written as "tagDescription", changing it to "TagDescription" fixed it for me.

Just fixed this. Thanks.

> Sorry that was rather long, I am not the best at this kind of stuff and wanted to make sure I explained what I was trying to say well enough, but I may have rambled on a bit. Let me know what you think about this because I am learning a lot from how you set up your changes.

ahh no problem at all, I thank you for taking the time to put all all together and for contributing to the project.

Please let me know if you have any other questions, I'm happy to help. Sorry that I could not help more, but hopefully with more info we will be able to figure it out.

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.86.0

**Pull request merged**
