### PR TITLE
[WIP] Datagma node

### PR DESCRIPTION
**Pull request by d4vidsha**
## **Preparation**

- [x]  Set up your editor for code formatting (indentation, new lines, linting). If you use Visual Studio Code, you can use the **[[TSLint extension](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin)](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-tslint-plugin)** for linting.
- [x]  Get credentials (e.g., Client ID, Client Secret, API key, user login, user password, website URL) for the service you are building a node for.

## **Development**

- [x]  Open a pull request as early as possible with `WIP` in the pull request title.
- [x]  If you are creating a node requested by a community member, make sure to comment on the feature request in the **[community forum (opens new window)](https://community.n8n.io/c/feature-requests/5)**.
- [x]  Ensure complementary operations to each resource (e.g., create, delete) have been added.
- [x]  Ensure the node works with multiple items via one input.
- [x]  Ensure the parameters have the correct type.
- [x]  Mind the defaults: if the service has a default as true, keep it as true. Changing default values can break the existing workflows of the users.
- [x]  Check if the node disposes of everything properly, in particular, if connections were properly closed.
- [x]  Check your code using **[[Nodelinter](https://docs.n8n.io/nodes/creating-nodes/nodelinter.html)](https://docs.n8n.io/nodes/creating-nodes/nodelinter.html)** to ensure a clean lint **before** submitting your pull request

## **Testing**

- [x]  Test "create" and "update" operations with all fields/operations.
- [ ]  Test the `continueOnFail` option with a Function node. (For example, a Widget node has a GET operation that takes a widgetId and returns information on the widget. To test that the workflow continues on fail, set the Widget node to continue on fail, create a Function node, return a valid and an invalid widgetId, connect the Function node to Widget node, and run the workflow. The Widget node should show two items: one with information on the widget and another one with the error from having passed an invalid ID.)

## **Code formatting**

- [x]  Ensure the branch lints cleanly by running `npm run lint`.
- [x]  Ensure the indentation is correct. Check this in the editorconfig.
- [x]  Ensure there are no extra spaces. Check this in the editorconfig.
- [ ]  Code comment dividers inside if-branches.
- [x]  Use "create/delete" verbs for operations, except for tags, where you should use "add/remove".

## **Errors and Outputs**

- [ ]  Ensure empty API responses return `{ success: true }`.
- [ ]  Ensure the error responses are handled and displayed correctly (e.g., malformed requests, requests with invalid credentials) and use the current format. You can check this by making failing requests to the API.
- [ ]  Check if the response can be simplified and add a simplify function (e.g., **[[SecurityScorecard node](https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/SecurityScorecard/GenericFunctions.ts)](https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/SecurityScorecard/GenericFunctions.ts)**).
- [ ]  Ensure the response from `Create` is consistent with `Get`.
- [ ]  Ensure the response from `Get All` is consistent with `Get`.

## **Presentation**

- [ ]  Ensure the primary menu contains only required parameters.
- [ ]  Ensure a JSON object is not shown in a single column in Table view.
- [ ]  Make sure all GetAll operations have the fields `return` and `limit`.
- [ ]  Ensure the property subtitle is set.
- [ ]  Make sure the pagination (if any) is working correctly. Set Limit 1.

## **Writing**

- [ ]  Ensure all descriptions are correct and end with a period.
- [ ]  Ensure that most descriptions exist, excluding redundant ones.
- [ ]  Ensure IDs in displayNames are capitalized (i.e.: "IDs", not "ids" or "Ids").
- [ ]  Ensure that IDs, if multiple, have descriptive qualifiers.
- [ ]  Ensure the `name` property in `description` in the node class is written in camelCase.
- [ ]  Ensure the file name and the Class name are identical.

## **Branding**

- [ ]  Ensure the name of the service is written correctly (e.g., "GitHub" not "Github"). If the node is a trigger node, ensure it is named as such, by adding "Trigger" after the service name (e.g., "Trello Trigger").
- [ ]  Ensure the logo is either a PNG or SVG, ideally the latter. **[[Vecta](https://vecta.io/symbols)](https://vecta.io/symbols)** is a good website to find SVGs of different applications.
- [ ]  If the logo is an SVG, ensure the canvas is a perfect square. If the logo is PNG, ensure it is 60x60 pixels and compressed.
- [ ]  Ensure the border color of the node matches the branding of the service.

## **Nice-to-haves (optional)**

- [ ]  Add handler for `continueOnFail`. This feature is included in some of the newest nodes (e.g **[[Lemlist node](https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Lemlist/Lemlist.node.ts)](https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Lemlist/Lemlist.node.ts)**) to continue the workflow even if the node's execution fails.
- [ ]  Remove `required: false` and `description: ''` in the node descriptions (e.g., **[[Lemlist node](https://github.com/n8n-io/n8n/tree/master/packages/nodes-base/nodes/Lemlist/descriptions)](https://github.com/n8n-io/n8n/tree/master/packages/nodes-base/nodes/Lemlist/descriptions)**).
- [ ]  At call site, specify first `body` and then `qs`.
- [ ]  At call site, prepend the endpoint with slash `/` (e.g., "/campaign").

### CODE REVIEW

**Comment by d4vidsha** [comment]
Hey @Joffcom! Was wondering if we can get this reviewed soon, my client wants to add this to the official n8n. Are there any other processes that I need to do to get this completed as fast as possible?

**Comment by Joffcom** [comment]
Hey @d4vidsha,

We are working on the improvements to existing nodes at the moment as the main focus for clearing down some of the PRs that have been waiting as there are ways you can load custom nodes into n8n.

I have taken a quick look at this one and there appears to be multiple package files added which are not needed and 2 images for the node an SVG and the PNG that is being used. I noticed the codex file is also missing (the *.node.json file) which we like to have. 

Have you also ran `npm run lint` that can help show some issues that we would normally pass back on.

**Comment by d4vidsha** [comment]
Thanks for the feedback @Joffcom, really appreciate it.
Do you have an ETA on when improving existing nodes are finished? So that I have a timeframe to work around, thanks :)

**Comment by Joffcom** [comment]
That is a good question, we want to get through them fairly quickly and have a few people working on them. I will let you know when we start looking at new nodes. 

What you can do you for your client is follow the steps here: https://docs.n8n.io/nodes/creating-nodes/create-n8n-nodes-module.html that will allow them to use your node in n8n with very little effort.

**Comment by d4vidsha** [comment]
Sounds good, I'll take a look at these

**Comment by d4vidsha** [comment]
Hey @Joffcom, any ETA on when the team will begin looking at new nodes? I am asking on behalf of my client 😄

**Comment by d4vidsha** [comment]
Hey @Joffcom,
Well the story is, my client's client wants to continue using n8n.cloud without dealing with the technicalities of setting up a custom node, so they are happy to wait for the official rollout of the Datagma node. I'll pass your message along and say your team is still in the process of node improvements, thanks for your help 👍

**Comment by Joffcom** [comment]
Hey @d4vidsha,

That explains it 🙂

@nivb06 what are your thoughts here?

**Comment by d4vidsha** [comment]
Hello again @Joffcom,
is there anything I can do to bring this all together? Like writing authentication docs if necessary? I see that most nodes have one of these and just want to do the best I can to get it all completed smoothly.

**Comment by Joffcom** [comment]
Hey @d4vidsha,

You could pop the docs together if you wanted to, to be honest though while it will make life easier when / if we merge the node it won't move it up the list yet.

We still have a few older PRs to look at before we start to tackle new nodes then it will be handled from oldest to newest with the most requested by the community being handled first.

I have been chatting to Raphael about this one as well.

**Comment by d4vidsha** [comment]
Thank you all for this info!

**Comment by Joffcom** [comment]
Hey @d4vidsha,

Thanks for the contribution, It looks like you have already published this node to the Community Node Repository which is our preferred method for new node submissions.

In the future we may reach out to you about including your node in our main release, But for now I am going to close this PR. If you have any questions about this or need any help let us know.

**Pull request closed without merging**
