### PR TITLE
feat(core): Add batching and other options to declarative nodes

### PR DESCRIPTION
**Pull request by janober**
## Summary
Adds support for
- Batch processing
- Ignore SSL Issues
- Proxy
- Timeout

to all declarative nodes.
Screenshot from 2024-03-24 11-57-54

FYI:
1. Instead of getting added under "Options" to the regular Parameters does it get added under Node-Settings. The reason is the parameters get displayed and hidden on nodes depending on the `displayOptions`. So do different Resource -> Operation combinations often share parameters or have totally separate ones.
As there is no easy way (for sure possible, but none that would not increase the scope of this originally simple and fast extension) of ensuring that the options get reliably displayed properly for all combinations, did we decide to move it into Node-Settings.
2. OpenAI Node: As the OpenAI-Node got reimplemented a while ago and does not now use the declarative style anymore, will it only be available if the old node does get used. 

## Related tickets and issues
https://community.n8n.io/t/langchain-and-openai-nodes-should-be-able-to-parallel-requests-like-http-node/40383/2

## Review / Merge checklist
- [x] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

### CODE REVIEW

**Comment by pemontto** [comment]
Excited to see this! A few questions if you don't mind:

1. Will the batching settings be configurable by the end-user, node developer, or both?
2. Will there be a mechanism to handle back-off when we receive 429s?

**Comment by janober** [comment]
@pemontto to your questions
1. What this PR does is to expose batch options by default via the UI to the users. Currently, there is no way for node developer to overwrite it or set different defaults.
2. No sadly not

Both things could obviously be added in the future if there is a strong demand

**Review by michael-radency — APPROVED** [review]
LGTM, I had to add `// eslint-disable-next-line complexity` for `runNode`, but I guess this is expected here

**Comment by janober** [comment]
Got released with [`n8n@1.46.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.46.0)

**Comment by juniorgregio** [comment]
@janober good evening, is this adjustment now available for the community edition?
I just updated to 1.46.0, but the OpenAI node does not find this batching option at any time

**Comment by janober** [comment]
It is available in all versions. The problem is just hat the OpenAI node got changed for different reasons and is now not declarative anymore for that reason did it not work with that node anymore. Will however work with v1 of the node. So if you change it to that one it should work. Let me know if you do not know how.

**Comment by juniorgregio** [comment]
> It is available in all versions. The problem is just hat the OpenAI node got changed for different reasons and is now not declarative anymore for that reason did it not work with that node anymore. Will however work with v1 of the node. So if you change it to that one it should work. Let me know if you do not know how.

Thank you for the quick return, I don't know how to use the node v1. Could you teach me? Thanks

**Comment by juniorgregio** [comment]
@janober is there any desire or plan to make openai declative again? 

about changing the node version, I used GPT and it told me that I need to change the configuration files on the server, is that it?

**Comment by janober** [comment]
@juniorgregio Sorry, did miss your answer.

To get version 1 of the node you can simply copy the following and paste it into n8n:
```
{
  "nodes": [
    {
      "parameters": {
      },
      "id": "ef1a6b15-1248-446e-a61d-fc93192420c0",
      "name": "OpenAI",
      "type": "n8n-nodes-base.openAi",
      "typeVersion": 1,
      "position": [
        420,
        460
      ]
    }
  ],
  "connections": {},
  "pinData": {}
}
```

Sadly, it is not currently planned to make it declarative again, as it would bring other disadvantages that are very specific to the node and its usage (details would be too complex to explain right now). Sorry.

**Comment by juniorgregio** [comment]
> Desculpe, faltou sua resposta.
> 
> Para obter a versão 1 do nó, você pode simplesmente copiar o seguinte e colá-lo em n8n:
> 
> ```
> {
>   "nodes": [
>     {
>       "parameters": {
>       },
>       "id": "ef1a6b15-1248-446e-a61d-fc93192420c0",
>       "name": "OpenAI",
>       "type": "n8n-nodes-base.openAi",
>       "typeVersion": 1,
>       "position": [
>         420,
>         460
>       ]
>     }
>   ],
>   "connections": {},
>   "pinData": {}
> }
> ```
> 
> Infelizmente, atualmente não está planejado torná-lo declarativo novamente, pois traria outras desvantagens que são muito específicas para o nó e seu uso (detalhes seriam muito complexos para explicar agora). Desculpa.

Thanks for the feedback @Jon, it's helped a lot but I still have questions about where exactly to paste it on the N8N?

**Pull request merged**
