### PR TITLE
docs: Fix spelling issue in Gmail trigger node

### PR DESCRIPTION
**Pull request by neverabsolute**
IDK how I noticed this

### CODE REVIEW

**Comment by neverabsolute** [comment]
Don't think any of these are applicable, probably one of the smallest cosmetic contributions possible

**Comment by cubedhuang** [comment]
LGTM!

**Comment by nebulatgs** [comment]
LGTM!

**Comment by GoldenStack** [comment]
LGTM!!!!

**Review by Joffcom — APPROVED** [review]

**Review by csuermann — APPROVED** [review]

**Pull request merged**
