### PR TITLE
feat(editor): Add project sharing

### PR DESCRIPTION
**Pull request by cstuncsik**

### CODE REVIEW

**Review by krynble — COMMENTED** [review]
Screenshot 2024-03-08 at 16 08 57

In this modal, can we also add the project's email, splitting the name? Also the "Add projects..." dropdown placeholder can be replaced with "Share with..." so it's a bit more agnostic wdyt?

All else is looking great, looking forward to merge Danny's changes so we can see it all working together! We might have to make small design adjustments here and there.

**Comment by krynble** [comment]
Also one thing I've noticed in the image above is that it doesn't show the current user's project as part of the list, is it becaues the API is missing the proper information?

**Comment by cstuncsik** [comment]
@krynble 

> In this modal, can we also add the project's email, splitting the name? Also the "Add projects..." dropdown placeholder can be replaced with "Share with..." so it's a bit more agnostic wdyt?

It is prepared, when the backend returns the projects name in the format of "Firstname Lastname <email@addre.ss>" it will show it. Now what you see is the fallback in case of improper format or missing email

> Also one thing I've noticed in the image above is that it doesn't show the current user's project as part of the list, is it becaues the API is missing the proper information?

It should not show the users personal project only if the home project of the workflow is the same. In that case it doesn't make much sense
So in general if the home project is among the selectable project it is not shown

Or it wouldn't matter and we need to show it?

**Review by krynble — APPROVED** [review]
I'll approve so e2e tests can run and then if it makes sense to fix something now, by all means let's do it, but if not, it's fine to wait until Danny's other changes to workflow sharing are done and we then fix all at once.

**Pull request merged**
