### PR TITLE
feat(core): Rate-limit login endpoint to mitigate brute force password guessing attacks

### PR DESCRIPTION
**Pull request by netroy**
N8N-7294

## Review / Merge checklist
- [x] PR title and summary are descriptive
- [x] Tests included

### CODE REVIEW

**Review by tomi — DISMISSED** [review]
Code LGTM. Would it be possible to add a test for this? Send multiple requests and expect that 429 is gotten eventually

**Comment by netroy** [comment]
> Would it be possible to add a test for this?
Done

**Review by tomi — DISMISSED** [review]
🚀

**Review by tomi — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.36.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.36.0)

**Pull request merged**
