### PR TITLE
Date Helper node

### PR DESCRIPTION
**Pull request by RicardoE105**
@janober  this would help with this https://community.n8n.io/t/help-not-been-able-to-import-external-modules/686/3?u=ricardoe105

I found an issue on the UI. When you put an expression on an input type options you get the following error:

image

image

I think that validation should not happen when you set an expression. 

Let me know @janober

### CODE REVIEW

**Comment by janober** [comment]
@RicardoE105 Sorry I do not understand. Why should it not validate when the value gets set via an expression. If an option-field has the allowed values "a" and "b" and an expression sets it to "c" it would still be wrong and not supported.

**Comment by RicardoE105** [comment]
@janober when you set an expression it's likely that the value you are setting is not supported like the example. Maybe not an issue but it was a little confusing to me.

With regard to setting a custom format, I did it so that if you want to set a custom format you just add an expression on the select but I do not know if that would be obvious for newcomers, maybe adding another optional field called "custom format" would make more clear?

**Comment by janober** [comment]
Ah ok now I understand the problem. 

In that case, the error is 100% correct. Option-fields normally only work with the options that get provided. Others are invalid. In the case, you describe it would be best to add an option "Custom Format" like you proposed which if selected displays another field in which the custom format can be added.

Another thing. I am not sure about is, if we should create a separate node for each different "transformation need" or if it would be better to have one generic "transform node".  The reason behind that is 
It makes it simpler if there is only one node that does transformations and people do not have to look through all nodes if it maybe got named differently that they thought it would be named
Would avoid node-bloat
Would make it much simpler to add additional transformations (add another option to an existing node instead of having to create a new node every time)
Other transformations that would probably be needed for different use cases in the future would, for example, be text (upper case, lower case, camelCase to snake_case, ...), numbers (text to number, decimal to hex, ...), ...

What do you think?

**Comment by RicardoE105** [comment]
Perfect will add that custom format field.

About how to organize the nodes I think it would be easier for newcomers and not very techy people to have a different node depending on the transformation like "dates and times", "numbers", etc. I would suggest giving all the transformations nodes the same color so they are easily identified and maybe it's own section or subsection. When I say subsection I mean where they are right now but within its own internal section "Transformations nodes".

@janober

**Comment by RicardoE105** [comment]
@janober done. This last commit would do the trick.

**Comment by janober** [comment]
Great, thanks a lot. Got merged. Still not 100% sure if the nodes should be really separate but let's do it for now like that.

Made some changes:
- Added description texts
- Changed that timezones are optional (as default is probably to simply not change it) and if either from- or to- is set but not the other one it uses the workflow-timezone instead
- Fixed issue that it ignored "fromTimezone" if "fromFormat" was set
- Made it possible to use dot-notation to also transform data on lower levels
- Fixed issue that binary data got lost

**Comment by RicardoE105** [comment]
@janober just checked the changes. Dam I missed a lot of things but learning. Will keep that in mind for future nodes. Thanks. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by janober** [comment]
Thats totally normal. Everybody does. That is why it is why a second pair of eyes is always helpful. Keep up the amazing work!

**Comment by janober** [comment]
Released with n8n@0.51.0

**Pull request merged**
