### PR TITLE
fix(editor): Active toggle incorrectly displayed as inactive in execution view

### PR DESCRIPTION
**Pull request by ivov**
https://linear.app/n8n/issue/PAY-1666

### CODE REVIEW

**Review by cstuncsik — DISMISSED** [review]

**Comment by ivov** [comment]
Re-running e2e: https://github.com/n8n-io/n8n/actions/runs/9549595305

**Review by cstuncsik — APPROVED** [review]

**Comment by mutdmour** [comment]
Please make sure to add tests @ivov

**Comment by janober** [comment]
Got released with [`n8n@1.47.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.47.0)

**Comment by janober** [comment]
Got released with [`n8n@1.47.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.47.0)

**Pull request merged**
