### PR TITLE
MySQL node

### PR DESCRIPTION
**Pull request by ericHao22**
add MySQL node Inspired by Postgres node

### CODE REVIEW

**Comment by janober** [comment]
@ericHao22 Thanks a lot for creating this integration! Really great! I will try to review and merge it the next days.
Just had a short look but was wondering how hard you think it would be to remove the "knex" dependency? The reason is that I want to try to avoid adding dependencies unless there is no way around it. The reason is that most dependencies have other dependencies which each can cause problems, security vulnerabilities and in general, would n8n explode very soon.
 Knex is one of the packages which by itself has a lot of other dependencies and if I install it by itself it is already 13 MB large (to compare mysql2 is just 2.5 MB).

**Comment by ericHao22** [comment]
@janober Thank you for your reply. I think it would not do many work to remove "knex" dependency. The reason why I choose knex is because I prefer to use query builder to setup SQL in a functional way. However, "mysql2" is not like "pg-promise" to provide helper to do that kind of job for us, and that is what "knex" devote on. knex also do many work to be compatible with different driver, and that may be the reason to cause the problem you mentioned above. But we indeed can make SQL string by ourselves without it. Therefore, do you think it is suitable to use "mysql2" with raw SQL string? Thank you.

**Comment by ulentini** [comment]
Hello guys, I would love to have MySQL available, @janober do you have a roadmap for this?
Thanks!

**Comment by GiuMex** [comment]
Thank for the integration guys. I'm really looking forward to having it.

**Comment by janober** [comment]
Very sorry for the delay. Still very crazy right now. Should however get better in two weeks.

@ericHao22 It would be really great if you could remove the knex dependency if it is like you described. Will then review and merge it asap.

**Comment by ericHao22** [comment]
Sorry for coming back late. @janober I had finished removing knex dependency from this MySQL node. Could you help me review it again? Thank you.

**Comment by janober** [comment]
Thanks a lot @ericHao22 for taking care of that! Will check it later today and merge.

**Comment by janober** [comment]
Great work. Thanks a lot. Got merged.

Only fixed one lint issue and renamed the node. Will try to release a new version of n8n with it tomorrow.

**Comment by ericHao22** [comment]
No problem. Look forward to seeing the release of new version.

**Pull request merged**
