### PR TITLE
Add remaining CRUD apis to Harvest

### PR DESCRIPTION
**Pull request by trojanh**
- Add Create/Update for `Project`, `Client`, `expense`, `invoice`, `estimate`, `contact`, `User`
- Refactor some code.

### CODE REVIEW

**Comment by janober** [comment]
Great thanks a lot! Because of the refactoring, it is hard for me to see if there are any breaking changes. Can you please confirm that even though the code changed, it would still work exactly the same for people who already use it in workflows. I just want to be 100% sure to not break it for anybody.

**Comment by trojanh** [comment]
I had tested it before raising this PR and it should work as expected @janober .

**Comment by janober** [comment]
I ment less if it works in general more if it works 100% the same for existing users.

**Comment by janober** [comment]
Great thanks a lot for adding all those features. It is now really an incredible complete node.

Sadly, however, was my fear correct and it would have broken it for existing users as you renamed parameters. Especially the "resource" one which means it would have broke it for all users.
It is NEVER allowed to change the name of a parameter, rename its values or change the default. If any of those things get done, it will break the node for existing users.
I really have to write some kind of documentation/checklist for that. Because right now that is not mentioned anywhere. I added it to my to-do list and hope to get to it soon.

Additionally to reverting the renaming did I do the following:
- ordered parameter options alphabetically
- fixed some parameters types as many were string but were supposed to be "boolean", "option" or "number" 
- changed top-level parameter names to all be camelCase

So thanks again for all the hard work! Is merged now.

**Comment by janober** [comment]
Got released with n8n@0.52.0

**Comment by trojanh** [comment]
Sorry @janober that you had to take that trouble I was really not aware of those rules and when you said it should for previous versions i assumed it was to do with the old functionality.

I will check these conditions when I make changes to existing nodes in future. Thanks for making the changes and releasing it @janober.

**Comment by janober** [comment]
No deed to apologize! It is on me. Like I wrote I have to document such things. If I do not do that I can not expect people to know and follow rules I did never specify. Sure if you are however a mind-reader and you ignored them anyway, it is on you ;-)

So thanks again for all the hard work! Really great to have you on board!

**Pull request merged**
