### PR TITLE
Request redirect #1331

### LINKED ISSUE #1331: HTTP request follow redirects option does not work
**Describe the bug**
When the option "Follow HTTP 3xx redirects" is selected (it is by default), the request does not get redirected when a status code 3xx is received. 

**To Reproduce**
1. Create HTTP Request node.
2. Point to endpoint that you know requests 3xx status.
3. Submit request.
4. Observe Status code error returned.

**Expected behavior**
When an HTTP status code in the range of 3xx is received in the request chain, the client should respect the redirect and follow the navigation expected for redirection.

**Environment (please complete the following information):**
 - OS: Raspbian Linux 10 - Docker Container
 - n8n Version: 0.100.0-rpi (Experienced the issue on previous versions as well)
 - Node.js Version: v12.19.1 (pre-installed in Image)

**Additional context**
image

### PR DESCRIPTION
**Pull request by mutdmour**
- resolves https://github.com/n8n-io/n8n/issues/1331
- currently, http node can only follow redirects for GET requests.. It does not follow the redirects for post/put/patch requests.
- this adds the option to follow all redirects including put/delete/patch/post
- related logic in request library https://github.com/request/request/blob/3c0cddc7c8eb60b470e9519da85896ed7ee0081e/lib/redirect.js#L54

### CODE REVIEW

**Comment by janober** [comment]
Thanks. Best check with @krynble as he rewrites everything to axios and he so also have to support that.

**Comment by krynble** [comment]
Thank you @janober and @mutdmour 

All good, I have already covered the redirects. The default is a bit different across libraries but it should all work.

**Review by krynble — APPROVED** [review]

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.133.0

**Pull request merged**
