### PR TITLE
feat(OpenAI Node): Add a node to work with OpenAI

### PR DESCRIPTION
**Pull request by janober**
https://community.n8n.io/t/openai-api-gpt-3/10890

### CODE REVIEW

**Review by edumaciel10 — COMMENTED** [review]
Good

**Comment by luizeof** [comment]
Working!

CleanShot 2022-12-15 at 12 48 24

**Comment by janober** [comment]
Thanks a lot for testing!

**Comment by janober** [comment]
Got released with `n8n@0.208.0`

**Pull request merged**
