### PR TITLE
test: Add e2e tests for PRs

### PR DESCRIPTION
**Pull request by mutdmour**
Github issue / Community forum post (link here to close automatically):

### CODE REVIEW

**Review by mutdmour — COMMENTED** [review]
test

**Review by mutdmour — COMMENTED** [review]
test

**Review by mutdmour — COMMENTED** [review]
test

**Review by mutdmour — COMMENTED** [review]
test

**Review by alexgrozav — APPROVED** [review]
Awesome work!

**Comment by janober** [comment]
Got released with `n8n@0.211.2`

**Pull request merged**
