### PR TITLE
Merging master into oauth-support

### PR DESCRIPTION
**Pull request by TMaYaD**
Makes #441 mergeable.

### CODE REVIEW

**Comment by janober** [comment]
There is already #441 and still quite some work left so close this for now.

**Comment by TMaYaD** [comment]
#441 is for merging oauth-support into master.
This one is for resolving the conflicts on oauth-support because I can't write to that branch.

**Comment by janober** [comment]
Ah sorry did not see that

**Comment by janober** [comment]
I sadly had to merge it, in the end, myself as it was impossible for me to review the changes that have been made like this. Hope that makes sense. But thanks a lot!

**Comment by TMaYaD** [comment]
Yeah, No problem!

**Pull request closed without merging**
