### PR TITLE
fix(Discord Node): Remove unnecessary requirement on parameters

### PR DESCRIPTION
**Pull request by nihaals**
## Summary
The PR removes the requirement on 2 fields: the `content` and the `description` of embeds. Discord requires neither of these fields and as they weren't required in the v1 node, it prevents migrating to the v2 node for users not providing one of them. Discord does require *something* to be sent however, whether an attachment, an embed or content, so this could be used instead if necessary.

## Review / Merge checklist
- [x] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [x] ~~[Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.~~ (v2 is not documented)
- [x] ~~Tests included.~~ (If more complex requirements are set then a test should be added although I haven't worked with n8n's tests before)

### CODE REVIEW

**Comment by Joffcom** [comment]
@michael-radency Can you remember why we made this change?

**Comment by michael-radency** [comment]
> @michael-radency Can you remember why we made this change?

this was added during review process, @nihaals thanks for PR, I did add some description to this error

**Review by michael-radency — DISMISSED** [review]
LGTM

**Review by Joffcom — APPROVED** [review]

**Comment by Joffcom** [comment]
Got released with [`n8n@1.23.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.23.0)

**Pull request merged**
