### PR TITLE
fix(SSH Node): Cleanup temporary binary files as soon as possible

### LINKED ISSUE #11303: ssh node not closing file connections in temp folder
### Bug Description

image
am using ssh node to download the file from server and process it am not saving the downloaded file in anywhere in workflow. 
ssh node saves the file in temp folder and pass it to next node.
connection to file saved in temp folder created by ssh node is not closed properly those handles not closed until i restart n8n 
attached screen shows how many connections open 

when it comes around 8400 am getting following error from node

Error: EMFILE: too many open files,

### To Reproduce

try to download and process the file using ssh node. 

### Expected behavior

even after work flow completes connection to temp folder not closed properly. 

### Operating System

Winodws server 2019

### n8n Version

1.63.4

### Node.js Version

20.17.0

### Database

SQLite (default)

### Execution mode

main (default)

### PR DESCRIPTION
**Pull request by netroy**
## Summary
This PR updates the SSH node to handle temporary binary files the same way as all the other nodes do, and cleans them up as soon as the node is done using them, instead of keeping the file-descriptors open until the node is finished executing.

## Related Linear tickets, Github issues, and Community forum posts
NODE-1882
Fixes #11303

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Comment by Surenthiran** [comment]
please approve this changes quick if it works, i need this as soon as possible.

**Comment by netroy** [comment]
> please approve this changes quick if it works, i need this as soon as possible.

we can't approve this until we have first tested this enough to be sure that it actually fixes the issue you are facing.
If you want to help test this, we can create a custom docker image for you.
However if you are using n8n via npm, then you'll have to wait until someone has had the time to test and verify this change.

**Comment by Surenthiran** [comment]
i dont know docker has this problem or not, am having this issue in windows npm deployment. 

am ready to setup test environment in my server to test it let me know how can i help.

**Review by Joffcom — APPROVED** [review]
- Tested default and filesystem binary data modes
- Uploaded 27 txt files and FD remained at ~36 before this change it was ~62
- Tested download and commands to be safe and no issues found

**Comment by Surenthiran** [comment]
Thank you guys!

**Comment by janober** [comment]
Got released with [`n8n@1.65.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.65.0)

**Pull request merged**
