### PR TITLE
feat(credentials/XeroOAuth2Api): Add API scopes

### PR DESCRIPTION
**Pull request by mrogers-5s**
Add additional scopes to the Xero OAuth API config

### CODE REVIEW

**Comment by mrogers-5s** [comment]
@janober This is effectively a replacement PR for https://github.com/n8n-io/n8n/pull/2861 so that we can sign the CLA

**Comment by Joffcom** [comment]
Hey @mrogers-5s,

I have just been looking at this one, What is the benefit of adding these scopes? I don't think the node currently requires them so it seems a bit odd unless I have missed something.

**Comment by mrogers-5s** [comment]
@Joffcom We ran into a handful of cases recently that we needed those scopes for some Xero automations that we built for our accounting team (e.g. attaching report spreadsheets to invoices).

We've been relying on a fork of n8n for a bit, but would like to avoid doing that long term, and thought it likely other users could benefit from these additional scopes.

**Comment by Joffcom** [comment]
Hey @mrogers-5s,

Is that issues with the standard node? I had assumed that we use the scopes we need for the node operations, If you have an example of one that doesn't work that would be great.

**Comment by Joffcom** [comment]
Hey @mrogers-5s,

For now I am going to mark this one as closed as we are not able to find a case where the extra scopes are needed, If you are able to provide a test workflow that triggers the issue with the standard Xero node let me know and we can open this one up again 👍🏻

**Pull request closed without merging**
