### PR TITLE
Add Trello Attachment API

### PR DESCRIPTION
**Pull request by trojanh**
- Adds [Trello Attachment API](https://developers.trello.com/reference#attachments) to allow listing, fetching(GET), deleting and adding new attachments using URL for a card.

### CODE REVIEW

**Comment by janober** [comment]
Great, thanks a lot. Really cool, got merged.

- moved "Attachment" option to the top of the list to keep it alphabetically
- renamed "list" -> "getAll" (not really because it is better just to be consistent with other nodes)
- changed that "getAll" returns attachments as separate items instead of one item which is an array
- fixed parameter descriptions
- made "MIME Type" optional for "create" as even if uploaded via their UI it does not get set
- made "Name" option for "create" as it uses by default the name of the file

**Comment by trojanh** [comment]
Great @janober. Thanks

**Comment by janober** [comment]
Got released with n8n@0.48.0

**Comment by janober** [comment]
Ah and happy to welcome you as contributor!

**Pull request merged**
