### PR TITLE
Adding options to run queries as transactions

### PR DESCRIPTION
**Pull request by krynble**
This PR extends https://github.com/n8n-io/n8n/pull/1478

Added a flag to control how to execute queries against the database.

This change affects Postgre, CrateDB, QuestDB and TimescaleDB.

Comparisons were ran with this version comparing to previously and it's all good according to changes that were implemented in https://github.com/n8n-io/n8n/pull/1577

### CODE REVIEW

**Comment by krynble** [comment]
Hey @lublak 

Thanks for your contribution. This is now in review and should be merged soon. I made a few improvements to standardize the code and it should be merged soon.

Postgres received a few other updates and now this branch has conflicts. I will fix these so it can be merged again.

**Comment by lublak** [comment]
Hey @krynble,

thank you for your answer.
I also just wanted to ask. So no stress.

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.117.0

**Pull request merged**
