### PR TITLE
Paypal Integration [WIP]

### PR DESCRIPTION
**Pull request by RicardoE105**

### CODE REVIEW

**Comment by RicardoE105** [comment]
@janober dude, I'm having an error every time I run the node 

image

Not sure what I'm doing wrong, maybe cuz I used a select inside a fixedCollection?

**Comment by RicardoE105** [comment]
@janober forget it, saw the issue. My brain is not working well hahaha.

**Comment by RicardoE105** [comment]
@janober The resource requested by the customer is done, but not sure what resource I should add now. Are you familiar with PayPal?

**Comment by janober** [comment]
@RicardoE105 No sadly have also no idea right now what else would be important. If nobody else writes anything in the forum I think it is fine in this case to just release it with that one function and add other ones if people request them. Guess at some point it would probably be more important to create a PayPal-Trigger-Node but that is also very lowe priority till somebody actually asks for it.

**Comment by janober** [comment]
Thanks a lot! Checked it now. Again great work! Got merged. Made a few changes:
- fixed some typos
- fixed files-names as it did not build as sometimes a capital "p" for Pal and sometimes not
- renamed option "delete" to "cancel" as it still stays behind and so is not an actual delete
- changes some parameter descriptions like added line-brakes
- fixed indentation in package.json
- split into "Payout" and "Payout Items" as that makes it a little bit less confusing (even though the PayPal structure does not make it easy).
- with the above split, I could rename the "getAll" to "get" as it was not a "getAll". A "get" returns always one specific item (for example by id), a "getAll" returns the same items and then simply all or depending on a filter. Before "get" and "getAll" did not work exactly like that (again because of the PayPal structure which does not fit perfectly here). But still think like it is now it is a little bit clearer (even though still far away from perfect)

Please check my changes and tell me if you disagree with things I did. Thanks!

**Pull request merged**
