### PR TITLE
introduce quick base node

### PR DESCRIPTION
**Pull request by tflanagan**
I copied heavily from various other nodes to figure this out. Wasn't too hard, but more documentation would help.

This PR introduces a node for [Quick Base](https://www.quickbase.com/).

Operations:
- Delete File
- Delete Records
- Download File
- Run Query
- Run Report
- Upsert Records

The settings pages of a few of these are pretty unrefined, but I'm unfamiliar with the available types and possible configurations. Hopefully someone here can help guide that part forward.

### CODE REVIEW

**Comment by janober** [comment]
Really cool! Thanks a lot @tflanagan!

We will review and then either get back to you or merge.

Totally agree with the documentation. We are already working on it and hope we can release it in the next few weeks.

**Comment by tflanagan** [comment]
@janober great!

Gleaning information from other integration setups, I believe I've refined the configuration pages as much as I can.

**Comment by RicardoE105** [comment]
Hey @tflanagan, I made some improvements to make the node work similar to the other 'databases' nodes. If you can run locally and provide feedback would be cool. Thanks.

**Comment by tflanagan** [comment]
Hey @RicardoE105, thanks for your help conforming the code.

While most things look good, are an improvement in general, and I support, I'm a bit against some of the generic database terms/practices that have been applied, replacing Quick Base specific terms/practices that Quick Base users (would be users of this integration) would already know, be familiar with, and are documented as such in Quick Base's documentation. I understand the thinking behind it, and I don't discount these changes at all, but I believe this is a step in the wrong direction.

Here are my thoughts:

- In the Credentials, `Realm` has been replaced by `Hostname`. `Realm` is a Quick Base term that refers the the subdomain of the Quick Base account. I'd like to revert this change.
- I saw the `Resource`+`Operation` combo in other integrations and tried to apply it to Quick Base, but I didn't like it, it's too clunky. The main thing about Quick Base is that it isn't really a SQL database. By all appearances and for most discussions, you can think of it as one, but it really isn't.
I'd like to remove this concept and go back to the single `Operation` dropdown that directly correlates to Quick Base's API.
- `Record:Create` / `Record:Create/Update` has been split from `Upsert Records`. Quick Base's RESTful API doesn't have distinct `Create` or `Update` operations, only an `upsert`.  I'd like to revert this.
- `Record:Create` / `Record:Create/Update` has a strange input interface. I'm unsure how to add values for various fields. I enjoy the improvements for the `Update Key` functionality (should be renamed back to `Merge Field ID` to match Quick Base's terms), but the combination of `Columns` and `Fields` doesn't make sense/work. It looks like it's trying to automatically inherit data from the previous node. I don't think this is accurate or desired. I believe the user should be able to define this via n8n's Expressions.
I completely understand that the previous interface left nothing to be desired, but it did allow for multiple records to be created and for control over various inputs. Perhaps we can apply the methods used in other places to allow for us to build this data structure in an easy to use way.
- `Record:Create` / `Record:Create/Update` changes the delimiter from `.` to `,`. While I understand in most databases, a comma is used. In Quick Base, a period is used.
- `Record:Create` / `Record:Create/Update` the `Simple` switch renames the object keys from Field ID's to Field Names. This is very dangerous as Quick Base makes it extremely easy for users to change the Field Names. I high recommend reverting the key renaming aspect of the `Simple` switch.
- `Record:Get All` is labeled `Get All` but has a `Return All` boolean defaulting to false. Either should be renamed, have the boolean default to true or remove the boolean.
- `Record:Get All` I enjoy the `Options` dropdown, but it causes extra work. The `Where` and `Select` options should always be shown. Very rarely is a `where` or `select` clause omitted, Quick Base actually recommends against it. Always save the user four clicks vs minimalism. Which at this point, the `Options` dropdown is only housing two options, so it should probably just be removed in general.
- `Record:Get All` has had the `skip` property removed.
- `Record:Get All` / `Report:Run` this split is strange. Circling back to the second bullet point, I think we should revert to the directly correlated  `Operation` dropdown.
- `Report:Run` has had the `skip` property removed.
- `Report:Run` / `Report:Get` should have `Table ID` before `Report ID`.
- In testing I've found that going through the various configuration pages, without credentials selected, I am receiving this error in the console:
```
ERROR RESPONSE
TypeError: Cannot read property 'hostname' of undefined
    at Object.quickbaseApiRequest (/****/n8n/packages/nodes-base/nodes/QuickBase/GenericFunctions.ts:23:38)
    at Object.getTableFields (/****/n8n/packages/nodes-base/nodes/QuickBase/QuickBase.node.ts:91:46)
    at LoadNodeParameterOptions.getOptions (/****/n8n/packages/core/src/LoadNodeParameterOptions.ts:94:52)
    at /****/n8n/packages/cli/src/Server.ts:706:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at /****/n8n/packages/cli/src/ResponseHelper.ts:121:17
```
Looks like when it is trying to load configuration options, a scenario of no credentials (or `tableId`) hasn't been checked for.

**Comment by RicardoE105** [comment]
I understand where you are coming from, but there is a reason why all 'database' nodes work similarly. If I'm an n8n user who uses Postgres (or MySQL, Airtable, Google Sheets), wanting to change to QuickBase, the changes would be either none or very simple (Basically just switching nodes). Else people would have to make a lot of changes in the workflows when switching nodes. Also, if you know how to use one of the 'database' nodes, we want you to learn how to use the Quickbase node as quickly as posible.

> In the Credentials, Realm has been replaced by Hostname. Realm is a Quick Base term that refers to the subdomain of the Quick Base account. I'd like to revert this change.

We usually use across the board, either subdomain, domain, or hostname. Users familiar with n8n will know what we are referring to. Either way, there is a placeholder in case this field name is not exact enough.

> I saw the Resource+Operation combo in other integrations and tried to apply it to Quick Base, but I didn't like it, it's too clunky. The main thing about Quick Base is that it isn't really a SQL database. By all appearances and for most discussions, you can think of it as one, but it really isn't.

Again, we usually use resource/operation in all nodes since they usually consume a REST API like this node. If we leave just operation and decide to all more functionality to the node, we would end up with one big selection. Also, the API is organized like that, using resources and operations.

I do not have experience with Quickbase, but it seems to have all the concepts a relational database has. 

> Record:Create / Record:Create/Update has been split from Upsert Records. Quick Base's RESTful API doesn't have distinct Create or Update operations, only an upsert. I'd like to revert this.

Actually, now it has the operations create, update, and upsert. The endpoint does not just upsert. It depends on how you set the parameter. For example, it won't upsert if the merge field is the Record ID#, which is the id created by the table. The upsert seems to work just when the merge field is a unique field different from the Record ID#. By separating all functionalities, we can help the user provide the correct parameters depending on what they want to do.

> Record:Create / Record:Create/Update has a strange input interface. I'm unsure how to add values for various fields. I enjoy the improvements for the Update Key functionality (should be renamed back to Merge Field ID to match Quick Base's terms), but the combination of Columns and Fields doesn't make sense/work. It looks like it's trying to automatically inherit data from the previous node. I don't think this is accurate or desired. I believe the user should be able to define this via n8n's Expressions.

If you have this input: 

`{ name: 'ricardo',  age: 1 }`

and the Table ID is table1

it will be mapped automatically to:

For row/create

`{  from: 'table1', data: [ {  0: { value: ricardo }, 1: { value: 12  } } ]  }
`

For row/update

with the Update Key `id` with value 12

`{  from: 'table1', data: [ {  0: { value: ricardo }, 1: { value: 12  },  3: { value: 12 } } ]  }
`

For row/upsert

with the Update Key `id` with value 12 and `Merge Field ID` id

`{  from: 'table1', mergeFieldId: 4, data: [ {  0: { value: ricardo }, 1: { value: 12  },  4: { value: 12 } } ]  }
`
> but the combination of Columns and Fields doesn't make sense/work.

Columns make it easy to pick the just columns you want. The node before the Quickbase node can return extra data it's not needed for the Quickbase node. That is when the columns field comes into play.

Fields decide what data the operation it's gonna return.

Columns affect the input, and Fields affect the output. 

You have to think not just about what the node does but how it plays out with the other nodes. This is probably why you are using n8n in the first place, connecting it with other systems/APIs in an easy way.

> Record:Create / Record:Create/Update changes the delimiter from . to ,. While I understand in most databases, a comma is used. In Quick Base, a period is used.

Sorry, I do not understand this. Do you mean the column delimiter? 

> Record:Create / Record:Create/Update the Simple switch renames the object keys from Field ID's to Field Names. This is very dangerous as Quick Base makes it extremely easy for users to change the Field Names. I high recommend reverting the key renaming aspect of the Simple switch.

This is to make it easier for the other nodes to consume that data. Let's say you want to save that data to Google Sheets after the data is stored on Quicktabase. To achieve this, you can simply connect the Google Sheets node afterward, and it will do the job. Unlike with the raw data, I would have to add a function node in between and write a javascript code that maps that data to something that n8n and the Google Sheets node understand. Either way, you can always set it to false, and it will return the data within any changes. 

> I enjoy the Options dropdown, but it causes extra work. The Where and Select options should always be shown. Very rarely is a where or select clause omitted, Quick Base actually recommends against it. Always save the user four clicks vs minimalism. Which at this point, the Options dropdown is only housing two options, so it should probably just be removed in general.

You are probably right that it saves a few clicks but goes against what we decided to do things the "n8n" way and not the application way.  Would be inconsistent if we would do it differently for this one node and we are currently trying to make things more consistent. Maybe if we change our thinking in the future it would get changed in v2 of the node.

> Record:Get All / Report:Run this split is strange. Circling back to the second bullet point, I think we should revert to the directly correlated Operation dropdown.

Back to answer  2

> Record:Get All has had the skip property removed.

It's removed cuz the pagination is handled for you.

Report:Run / Report:Get should have Table ID before Report ID.

Agree. Got fixed.

> Error handling has dropped the qb-api-ray. This is a valuable unique identifier for debugging issues with Quick Base. When required to open a support ticket with Quick Base for any reason, this ID helps tremendously.

Ah, interesting. I did not know about this property. I just added it to the error message.

Error handling has dropped the description property. Quick Base returns their errors in three parts (usually), code via response HTTP code, message, and description. The description property usually contains the most valuable error information.

This got added. Now it shows the description.

**Comment by tflanagan** [comment]
I understand the desire for conforming to other nodes to make it easier to switch. Personally, I think I'd do it differently.

I don't expect you to be familiar with Quick Base. The RESTful API is relatively new. They also have an XML based API which is not as much fun to use.

I'm still confused about the input/output of Create/Update, but I'll just leave it as my inexperience with n8n and defer to you.

I think the only thing missing is the `skip` property. I understand when fetch all is true it is handled for you, but when it is not true, we should allow the user to specify it. Can't think of a use-case off the top of my head, but I'm sure one exists.

**Comment by janober** [comment]
Uh sorry just realized that I forgot to update here.

The node got merged with #1161 and released with n8n@0.95.1

**Pull request closed without merging**
