### PR TITLE
docs: Update docker-compose.yml example to Postgres 16 and update initialization script

### PR DESCRIPTION
**Pull request by johnyb0y**
This PR updates the example docker-compose.yml to use Postgres version 16. 
Before this change it was Postgres 11, [**which is EOL since November 9, 2023**.](https://www.postgresql.org/support/versioning/)

Since the default permissions on the public schema have changed since Postgres 15, we also need to update the included Initialization script. Before, the insecure default was to allow everyone (PUBLIC) to create objects in schema public. Now only the database owner can do that, unless you grant extra privileges. Therefore we need do that for our POSTGRES_NON_ROOT_USER.

I have done a quick test deployment and created some example workflows and found no problems.

Edit: I also looked at the docs and only found a mentioned link to the docker-compose.yml example file in the github repo, which doesn't need to be updated.

## Review / Merge checklist
- [x] PR title and summary are descriptive. **Remember, the title automatically goes into the changelog. Use `(no-changelog)` otherwise.** ([conventions](https://github.com/n8n-io/n8n/blob/master/.github/pull_request_title_conventions.md))
- [x] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [ ] Tests included.
   > A bug is not considered fixed, unless a test is added to prevent it from happening again.
   > A feature is not complete without tests.

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @johnyb0y,

Thanks for the PR, Would you be able to update the other example that uses Postgres as well?

**Comment by johnyb0y** [comment]
> Hey @johnyb0y,
> 
> Thanks for the PR, Would you be able to update the other example that uses Postgres as well?

Hi @Joffcom
Sure. I appended the commits on this PR.

**Comment by Joffcom** [comment]
Thanks @johnyb0y, This looks good to me but just to be safe I would like to ask @netroy to give it a quick review as well, I believe he is out today and will be back tomorrow so another couple of days and this should be good to go.

**Comment by johnyb0y** [comment]
@Joffcom Sure, no problem. Please let me know if I can be of further help here.

**Review by netroy — CHANGES_REQUESTED** [review]
We should probably add some more info about how to migrate a postgres container from 11 to 16, as the container by default won't run a `pg_upgrade`.

**Comment by johnyb0y** [comment]
Thinking about it some more, maybe we can meet somewhere in the middle. 
We could add a general notice somewhere in the docs which refers the user to official instructions on how upgrading a Postgres database works in general.
Regardless of if it is a dockerized database or not.
What do you think?

**Comment by johnyb0y** [comment]
How about this then: I could add a general comment inside of the compose file that the version of postgres needs to be pinned to a major version like "16" and that upgrading an existing Postgres database requires more steps than changing the version number inside the compose file. With a referral to official Postgres upgrade instructions. 

If that sounds good to you I could amend this PR. 
Otherwise we can go with your suggestion.

**Review by netroy — APPROVED** [review]
We'll take care of updating any docs in a separate PR. let's get this merged.

**Comment by janober** [comment]
Got released with [`n8n@1.31.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.31.0)

**Pull request merged**
