### PR TITLE
Add IRC node

### PR DESCRIPTION
**Pull request by DanielOaks**
This is a node for IRC (Internet Relay Chat).

I've based a lot of the structure of this off the Matrix node, with a custom lil IRC client so we don't rely on any external libs. 

Still to be done:

- [x] Plug in tests for message parser.
- [x] Compress logo SVG.
- [x] Plug in SASL PLAIN account login.
- [x] Handle nickname already exists numeric.
- [x] Handle erroneous nickname numeric.
- [x] Handle can't join channel numerics (can't join, wrong key, etc).
- [x] Handle can't send message numerics (`+n`, `+m`, etc).
- [x] Make it work with multiple items.
- [x] Plugin real logging.
- [x] Get rid of hacky `console.log` logging.
- [x] Follow proper node submission checklist.
- [x] Write documentation inc. default `nick` function for e.g. `name<randomdigits>` like `n8n1230, n8n9384, n8n2947`.

### CODE REVIEW

**Comment by DanielOaks** [comment]
Functionality-wise this node should be complete. If someone knows more about Collections and FixedCollections they could 
probably guide me towards making the node interface slightly nicer to read when the different options are expanded though.

I've yet to write up the documentation for this node and the IrcNetwork credentials, will do so before it's merged in.

**Comment by DanielOaks** [comment]
Initial documentation is being worked on over here. Not done yet, need to look at the 'fetch resources and operations from API stuff' but it should help with testing this out:
https://github.com/DanielOaks/n8n-docs/tree/irc/docs/nodes/nodes-library/nodes/Irc
https://github.com/DanielOaks/n8n-docs/tree/irc/docs/nodes/credentials/Irc

**Comment by janober** [comment]
@DanielOaks Thanks for this contribution. Just to be sure we understand correctly. That is theoretically ready from your side to be reviewed? Just wonder as it still has `[WIP]` in the title.

**Comment by DanielOaks** [comment]
Oh! My bad, I forgot to remove that from the title, thanks for the ping @janober.

Yes, this is ready to be reviewed. As a note I've ordered the credential properties to make sense from a 'leaving things as defaults' perspective, which is why the more important ones are near the top and less important ones are near the bottom.

**Comment by Xstar97** [comment]
@ivov do you have any eta on this node being officially added?

**Comment by Joffcom** [comment]
Hey @DanielOaks,

Thanks for the contribution, We have now created a Community Node Repository which is our preferred method for new node submissions.

Once a node has been published to the Community Node Repository users will be able to install the node from their n8n interface and will be able to use your node quicker, You will also be able to update the node as needed without needing to wait for the review process.

In the future we may reach out to you about including your node in our main release, But for now I am going to close this PR.

You can find more information in the links below, If you have any questions about this or need any help let us know.

Building Community Nodes: https://docs.n8n.io/integrations/community-nodes/build-community-nodes/
Submitting Community Nodes: https://docs.n8n.io/integrations/creating-nodes/deploy/submit-community-nodes/
Published Nodes: https://www.npmjs.com/search?q=keywords:n8n-community-node-package

**Comment by DanielOaks** [comment]
@Xstar97 Just an FYI, this node is now published as `n8n-nodes-irc` – available over here: https://www.npmjs.com/package/n8n-nodes-irc

I'll be moving the docs over to the appropriate place soon, but if you're interested please feel free to give it a shot and give any feedback!

**Comment by Joffcom** [comment]
Hey @DanielOaks,

Nice work 🙌🏻

**Pull request closed without merging**
