### PR TITLE
fix(QuickChart Node): generate binary filename

### PR DESCRIPTION
**Pull request by rfdez**
When you try to send an attachment on the Pushover Node the following error happens:

n8n

I don't really know what it's the reason but the filename in the `binaryData` object is empty. When setting one by default the Pushover API doesn't response with the error

n8n-after

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @rfdez,

That mostly looks ok, My concern would be what happens if there is no mimetype set would that cause an error? It looks like we should probably also add a filename option to the Quickchart node or at least automatically generate one.

**Comment by rfdez** [comment]
> Hey @rfdez,
> 
> That mostly looks ok, My concern would be what happens if there is no mimetype set would that cause an error? It looks like we should probably also add a filename option to the Quickchart node or at least automatically generate one.

You are right, adding the `filename` property in the Quickchart node or generating it should work because the error happens when the `filename` property in the attachment options is empty. If the `contentType` is not set the error doesn't happen.

I tried adding a filename in the Quickchart node and keeping the Pushover node without my changes and it works.

n8n-quickchart-before

n8n-quickchart-after

I added a hardcoded filename value in the Quickchart node

image

If you tell me what I should use as filename value or how I should generate it, I can do it

**Comment by Joffcom** [comment]
Hey @rfdez,

Good question, I am not sure what a good name value would be. Maybe a uuid would do the job so that each image has a unique name.

**Comment by rfdez** [comment]
Hi @Joffcom,

I just added the `filePath` generation with an uuid as filename and the format in the `chartOptions` as extension

**Comment by Joffcom** [comment]
Hey @rfdez,

I will get this tested this week so we can merge it.

**Comment by Joffcom** [comment]
Hey @rfdez,

Sorry for the delay I will hopefully be back on track with this one before the end of the week

**Pull request closed without merging**
