### PR TITLE
refactor: Forbid access to workflows when enterprise features is unavailable

### PR DESCRIPTION
**Pull request by krynble**

### CODE REVIEW

**Review by ivov — COMMENTED** [review]
1. I think de-duplicating `getSharedWorkflowIds` might not be best, as it requires comments on both callsites to explain what we are doing, adds indirection, and makes the class less self-sufficient. This is a case where I would keep the two slightly different methods and so avoid having a separate helper, even calling them differently to make this more explicit: `getSharedWorkflowIdsForOwner` and `getSharedWorkflowIds` But I can also see the opposite approach, so up to you.
2. Getting 22 tests failing on all DBs but CI is passing. If you test locally they all pass?

**Comment by netroy** [comment]
> 2. Getting 22 tests failing on all DBs

seems to all pass https://github.com/n8n-io/n8n/actions/runs/3490578998

**Review by netroy — COMMENTED** [review]
The code all seems fine to me. but I don't have enough context to approve the PR.

**Comment by krynble** [comment]
@ivov 
1. I thought about it and it's a tricky thing since we want class heritage to solve the UM problems without over engineering. And this basically means overriding existing methods in the ee version. That's exactly what I did, although I see it might be confusing. I've changed the function name to avoid confusing the helper with the service method.
2. It's all passing to me, and considering CI passed I guess there might be an issue with your setup maybe?
@netroy thanks for checking!

**Review by ivov — APPROVED** [review]
1. Thank you, I can see both sides, so deferring to you.
2. Locally no longer failing so please disregard.

**Comment by janober** [comment]
Got released with `n8n@0.203.1`

**Pull request merged**
