### PR TITLE
refactor(core): Add telemetry for RBAC roles

### PR DESCRIPTION
**Pull request by ivov**
Add telemetry for RBAC roles, see [requirements](https://linear.app/n8n/issue/PAY-1067/add-telemetry-events-for-adding-and-assigning-admin-users#comment-184619fe).

### CODE REVIEW

**Review by krynble — APPROVED** [review]
Given the user's controller is completely untested and adding a test simply for a telemetry event won't improve the quality, I've created a [Linear Ticket](https://linear.app/n8n/issue/PAY-1139/add-tests-to-user-controller) to address testing this controller.

**Comment by ivov** [comment]
It's tested here? `packages/cli/test/integration/users.api.test.ts`

**Comment by krynble** [comment]
Sorry, you're right @ivov , but we still have the problem that it's not covering inviting new users, just updating existing one's roles.

**Comment by ivov** [comment]
That's in `invitations.api.test.ts`?

**Comment by krynble** [comment]
Ah it does exist 🤔  so maybe we should be adding a check to make sure the telemetry call is made whenever this action happens

**Comment by janober** [comment]
Got released with [`n8n@1.21.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.21.0)

**Pull request merged**
