### PR TITLE
:sparkles: MQTT-Node

### PR DESCRIPTION
**Pull request by RicardoE105**
as requested here https://community.n8n.io/t/mqtt-publishing-node/2806

### CODE REVIEW

**Comment by ChristianRiesen** [comment]
Hi @RicardoE105 
I'm the original requester. Is there a reason why this hasn't been merged yet?

**Comment by RicardoE105** [comment]
HI @ChristianRiesen 

When you send a message, it seems to be 3 ways of sending that node. QoS: 1, 2, and 3. For some reason, I can get the trigger to receive the message (from the sender) when the message uses a QoS: 3. Aside from that, it seems to work as expected with QoS 1 and 2. Any clue what the issue might be?

**Comment by ChristianRiesen** [comment]
Here is a really good post describing the QoS: https://www.hivemq.com/blog/mqtt-essentials-part-6-mqtt-quality-of-service-levels/

With level 0 you should get at most once, 1 at least once, and with 2, exactly only once. But that is not set on the topic but on the client. So if you talk to a broker and send it with 2 then yeah that should always work, but so should 1, or you are not getting a good error response. And with 0, well that's sort of udp style fire and forget and if it doesn't get there, no big deal. But the same is true for the client reading the messages, which does NOT have to match the client sending. So you could send with QoS 0 and listen with QoS 2, but the sender to broker still might loose the message.

Just looking at the code real quick the only other thing I can't say for certain is, are you using the exact same client for both mqtt or are you instantiating a new one for the sender node? If so are you using the same client id? If two instances and they both share the same id, then that could also cause problems, each client, even from the same machine, needs its own unique id.

**Comment by RicardoE105** [comment]
> Just looking at the code real quick the only other thing I can't say for certain is, are you using the exact same client for both mqtt or are you instantiating a new one for the sender node? If so are you using the same client id? If two instances and they both share the same id, then that could also cause problems, each client, even from the same machine, needs its own unique id.

I'm instantiating different a new one for each sender. Gotta try with the different client IDs thought. Will do it as soon as I have time and will keep you posted. Thanks.

**Comment by ChristianRiesen** [comment]
Yeah MQTT is particular on that one. Try random ones, maybe with a n8n prefix or so, that would make a lot sense for mqtt.

**Comment by gonzunigad** [comment]
Will this be merged? :)
It would be a great addition

**Comment by RicardoE105** [comment]
Dropping this in favor of #1705

**Comment by janober** [comment]
Got merged with #1705

**Comment by janober** [comment]
Got released with n8n@0.118.0

**Pull request closed without merging**
