### PR TITLE
:zap: Add manageable acknowledge for services

### PR DESCRIPTION
**Pull request by m2scared**
Add the option to acknowledge or not acknowledge messages coming from
some trigger services.

The current implementation reuses `sendResponse` logic from node
`RespondToWebhook`.

### CODE REVIEW

**Comment by m2scared** [comment]
Hi,

This is an initial idea for adding manageable acknowledge for Trigger nodes such as MQTT, RabbitMQ, Kafka and etc. There are room for improvement since it is using `sendResponse` logic from the `Webhook` family nodes.

Maybe this should have its own `sendResponse`? Is is handling properly the `error/shutdown` path?

I would love to hear what could be improved.

**Comment by Joffcom** [comment]
Hey @m2scared,

I like the idea, I am not sure if "Respond to trigger" is too generic though as it wouldn't do anything for any of the other trigger nodes at the moment (apart from webhooks).

Would it maybe be better as an option in the RabbitMQ node for now if possible? Do you also have an example of when you may use this?

**Comment by m2scared** [comment]
> Hey @m2scared,

Hi @nivb06,
 
> I like the idea, I am not sure if "Respond to trigger" is too generic though as it wouldn't do anything for any of the other trigger nodes at the moment (apart from webhooks).

Understood. I used this name because it can be reused in other "queue" nodes that support NACK such as Kafka.

> Would it maybe be better as an option in the RabbitMQ node for now if possible? Do you also have an example of when you may use this?

I agree. My use case is: the event should be acknowledge only if the workflow succeeds. Currently this is not possible with n8n as far as I know. Is there any other way to archive this?

I will change the patch only for RabbitMQ.

**Comment by Joffcom** [comment]
No other way I can think of to handle it at the moment, Makes sense that you would only want to ack a success as well. In the past when implementing a logging system for file transfers with an MQ broker (Websphere I think it was) we would just post a sucess message to a queue / topic and include the original MQ ID as a header but I guess something like that would depend on how the interacting systems are working together.

**Comment by m2scared** [comment]
> No other way I can think of to handle it at the moment, Makes sense that you would only want to ack a success as well. In the past when implementing a logging system for file transfers with an MQ broker (Websphere I think it was) we would just post a sucess message to a queue / topic and include the original MQ ID as a header but I guess something like that would depend on how the interacting systems are working together.

I am not quite sure if I understood. Do you have examples? Code?

It seems possible to do since there is a similar behavior with 'webhook' and 'respond to webhool'. My current implementation uses `createDeferredPromise` and works as expected. I don't know if it will work with worker n8n nodes.

**Comment by michael-radency** [comment]
Hello @m2scared , thank you for your contribution, as for now it seems that RespondToTrigger node is redundant and too tied to RabbitMQTrigger node, as this node only hold boolean value it probably can be replaced with an option in RabbitMQ trigger node. 

Would be great if you can share workflow with setup where you are using this node, as it will clarify use case and gives  possibility of alternative solution without necessity to add additional node.

RabbitMQTrigger uses amqplib, [here](https://amqp-node.github.io/amqplib/channel_api.html#channel_ack) is documentation that can be useful.

**Comment by nivb06** [comment]
Hi @m2scared, I will be closing this as of @michael-radency's comments.
Feel free to reopen this or open a new PR based on Michael's comments
Thanks!

**Pull request closed without merging**
