### PR TITLE
Added function to calculate content-length when using multipart/form-data

### PR DESCRIPTION
**Pull request by krynble**
Relates to issue https://github.com/n8n-io/n8n/issues/2423

When doing file uploads the `Content-length` header was not being set correctly.

This PR fixes this by adding this information.

Tested with user provided scenario and it worked fine now.

### CODE REVIEW

**Comment by dolohow** [comment]
Shouldn't axios add content-length header automatically?

**Comment by krynble** [comment]
Hey @dolohow 

It does add it only when `data` is a stream or buffer as can be seen here: https://github.com/axios/axios/blob/c5fe05bdff82e0fa4ace9a832e75052e1ee297f0/lib/adapters/http.js#L90

When `data` is an instance of `FormData` it does not calculate length. Strangely enough, `FormData` contains a `getHeaders` function that returns the `Content-type`, estabilishing the `boundaries` but it does not add `Content-Length`.

I hope this clarifies the goal of this function! Let me know if you have any questions!

**Comment by janober** [comment]
Thanks a lot for fixing this. Got merged.

**Comment by janober** [comment]
Got released with n8n@0.149.0

**Pull request merged**
