### PR TITLE
feat(core): Allow for hiding usage page via environment

### PR DESCRIPTION
**Pull request by freyamade**

### CODE REVIEW

**Review by krynble — APPROVED** [review]
Maybe move the `hideUsagePage` inside the `enterprise` block, sibling to the features attribute, WDYT?

**Comment by freyamade** [comment]
I guess it might be an enterprise feature? All I know is it's being hidden on cloud :thinking:

**Comment by krynble** [comment]
I think this is fine actually, you can merge it as is. We can change later if needed.

**Comment by janober** [comment]
Got released with `n8n@0.208.0`

**Pull request merged**
