### PR TITLE
U proc integration

### PR DESCRIPTION
**Pull request by mcolomer**
Added n8n reference in user agent.

Added new tools:
+ Get ASIN code by EAN code
+ Get EAN code by ASIN code
+ Get Email by social profile
+ Get Email by Fullname and Company's domain
+ Get Email by Fullname and Company's name

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot @mcolomer ! But it looks like a lot of the changes are just the indentation. It would be good if it would fix it if it was wrong before, but it rather does the opposite. It brings it into the wrong format. So it changes it from tabs -> spaces, but the whole project is using tabs. Can you please have another look at the PR and und all of those changes and make sure that only for the required changes a PR gets opened and that all of that changes use the same format as n8n (tabs, single quotes, ...). Thanks!

**Comment by mcolomer** [comment]
Hi Jan,

Thank you for your feedback.

Changes are related with new tools added to file
packages/nodes-base/nodes/UProc/Json/Tools.ts

Applying tabs makes Tools.ts bigger. Does it make sense for you or must be minified to avoid extra size?
Could you confirm me please?

Thank you

**Comment by janober** [comment]
Just wanted to merge your PR but it looks like the Tools.ts file is invalid. Looks like not everything is escaped properly. You have for example: `'ed':'Get book by author's surname',` which cause problems

**Comment by mcolomer** [comment]
Hi Jan,

Firstly, apologies. I have escaped all single quotes between '' with \.
I have launched n8n locally and it works ok.

Could you check it please?

Thank you!

**Comment by janober** [comment]
Thanks a lot. Works now fine and got merged.

**Comment by janober** [comment]
Got released with n8n@0.113.0

**Comment by mcolomer** [comment]
Thank you Jan!

**Pull request merged**
