### PR TITLE
refactor(core): Clean up empty parent dirs in filesystem

### PR DESCRIPTION
**Pull request by ivov**
In binary data filesystem mode, the following nested path structure allows us to delete all binary data associated with an execution by deleting the relevant `/binary_data` dir.

```
/workflows/{workflowId}/executions/{executionId}/binary_data/{uuid}
/workflows/{workflowId}/executions/{executionId}/binary_data/{uuid}.metadata
```

Note that in future `/workflows/{workflowId}/executions/{executionId}` might also contain execution data as well, so the binary data service during pruning deletes _only_ the `binary_data` dir, leaving the parent dir `/{executionId}` intact. 

However, if this parent dir is empty as a result of the binary data pruning, it ends up cluttering up the filesystem. This PR removes the parent `/{executionId}` dir when empty after binary data pruning.

### CODE REVIEW

**Review by netroy — COMMENTED** [review]
Why don't we switch to deleting `workflows/${workflowId}/executions/${executionId}` instead of `workflows/${workflowId}/executions/${executionId}/binary_data/`?
That would be less code, and less load on the event-loop.

**Comment by ivov** [comment]
> Why don't we switch to deleting `workflows/${workflowId}/executions/${executionId}` instead of `workflows/${workflowId}/executions/${executionId}/binary_data/`? That would be less code, and less load on the event-loop.

My reasoning is that the binary data service should _only_ delete binary data. We adopted this nested path structure foreseeing that other kinds of data for an execution might be stored here as well, so if we let the binary data service delete the entire `/{executionId}` dir, the binary data service might inadvertently end up deleting data that is not binary. 

> Note that in future `/workflows/{workflowId}/executions/{executionId}` might also contain execution data as well, so the binary data service during pruning deletes _only_ the `binary_data` dir, leaving the parent dir `/{executionId}` intact.

Unless we want to move responsibility for binary data deletion to the execution service? In another PR?

**Comment by ivov** [comment]
I'll find a better approach.

**Comment by netroy** [comment]
> My reasoning is that the binary data service should _only_ delete binary data

This the hard decision to make, on one hand semantic decoupling is important in code, on the other hand doing it this way performs much worse than asking the operating system to recursively delete `/workflows/{workflowId}/executions/{executionId}`. 🤔

**Pull request closed without merging**
