### PR TITLE
improvement in the oauth event error handling

### PR DESCRIPTION
**Pull request by devphoenix2404**
Github issue / Community forum post (link here to close automatically):
- Updated error handling
- Added file for track down the errors.

### CODE REVIEW

**Review by shubham773 — COMMENTED** [review]
The constants before the error-callback response can be removed now as they are not getting used. Also, we can log the errors before the response.
We also need to add the error-callback to the final catch block.

**Comment by devphoenix2404** [comment]
> The constants before the error-callback response can be removed now as they are not getting used. Also, we can log the errors before the response. We also need to add the error-callback to the final catch block.

Updated code with the latest one.

**Comment by Joffcom** [comment]
Hey @devphoenix2404,

Thanks for the PR, Looking at this PR it is hiding the error state rather than showing it which is fairly important. If the HTML page can contain the error message it would be better but before we can do a proper review and think about accepting this one you will need to go through the CLA process.

As a temporary solution you could look at running your own fork of n8n for your project which would allow you to use this change and any others you want a bit quicker.

**Comment by devphoenix2404** [comment]
Hi @Joffcom 
"accepting this one you will need to go through the CLA process."
I've done the sign-in and [recheck](https://cla-assistant.io/check/n8n-io/n8n?pullRequest=5492) it also. But it's still in same state. Can you please check it why it's like that.
Thanks

**Comment by Joffcom** [comment]
Hey @devphoenix2404 

It is normally because the email address or username for the commit isn't matched with a GitHub user account.

For this one the username in the message is `gouravphoenix`, don't forget about the rest of the message as well 🙂

**Comment by devphoenix2404** [comment]
Hey @Joffcom 
May I know from where did you get the `gouravphoenix` username?
As I have check https://github.com/gouravphoenix doesn't exist and https://github.com/devphoenix2404 is the one exist and I've raised the PR from this username `devphoenix`.

And yes, we have already updated the changes in our project but it will be better if you guys approve the suggested changes and update your current repo. 
Thanks

**Comment by Joffcom** [comment]
Hey @devphoenix2404 

The username is in the cla message that says why it isn't accepted for the commit.

The PR still appears to hide the error reason as well which for most users will be an issue.

**Comment by devphoenix2404** [comment]
Hi @Joffcom 
I don't see as it reflects the devphoenix2404.
Can you please help me to find it out, where I can see the CLA message?

image

**Comment by devphoenix2404** [comment]
Hi @Joffcom 
Created a new [PR](https://github.com/n8n-io/n8n/pull/5555) by my team member and closing this.

**Pull request closed without merging**
