### PR TITLE
[WIP] Stripe Triggers node

### PR DESCRIPTION
**Pull request by lucafaggianelli**
webhook endpoint for all stripe events

### CODE REVIEW

**Comment by janober** [comment]
@lucafaggianelli Cool thanks a lot! Will check, try and merge tonight.

**Comment by janober** [comment]
Just had a very fast first look. Is it possible to add/delete webhooks via the Stripe API? Because it looks like currently people would have to manually copy the URL and add it via the UI.

**Comment by lucafaggianelli** [comment]
Yes it is possible from Stripe API. So n8n can manage the creation of webhooks? Any example? As I took the code from Chargebee trigger and didn't see any

**Comment by lucafaggianelli** [comment]
Ahh cool, I saw the Github trigger that creates webhooks, I'm going to implement the same mechanism. Furthermore, I forgot to add Stripe to package.json nodes list... I flag this PR as WIP

**Comment by janober** [comment]
Ah great to hear! Yes, that is possible with n8n. It was very important for me to make it as convenient and easy as possible for the users.

Yes the Chargebee-Node is I think actually the only one which does not do it as their API did not allow it. Already wrote them an email about it. So hope it is maybe possible in the future.

Some nodes where the automatic creation can be seen:

**Github**
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Github/GithubTrigger.node.ts

**Pipedrive**
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Pipedrive/PipedriveTrigger.node.ts

**Telegram**
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Telegram/TelegramTrigger.node.ts

**Comment by janober** [comment]
Ah just saw your answer. Great, thanks a lot!

**Comment by lucafaggianelli** [comment]
I'd like also to verify the webhook signature, but I need the raw request body data as with the parsed body doesn't work, though I could add this later.

https://stripe.com/docs/webhooks/signatures#verify-manually

**Comment by janober** [comment]
Thanks a lot! Great work! Will check it out tomorrow. Yes I had the problem with the verification before. For some it is enough to simply JSON.stringify the data some other ones need the original binary data to do that. That is sadly not possible right now like you said. But thanks for the info!

**Comment by janober** [comment]
Perfect! I just tested it and it works great. Is merged. I only changed the name of the node to be consistent with the other Trigger-Nodes and fixed a linting issue.

Will be released with the next version later today.

**Comment by janober** [comment]
Is released with n8n@0.26.0

**Pull request merged**
