### PR TITLE
🎉 Cockpit node

### PR DESCRIPTION
**Pull request by terenaa**

### CODE REVIEW

**Comment by janober** [comment]
Great, thanks a lot! I will check it out.

Can you please tell me the website of this service/project? The name "cockpit" is simply too generic and there is no reference I could find in the code as it seems to be a self-hosted service.

**Comment by terenaa** [comment]
It's [getcockpit.com](https://getcockpit.com) :)

**Comment by janober** [comment]
Great, thanks a lot @terenaa ! Got merged.

Made some adjustments:
 - Renamed some Operations (get -> getAll, save -> create)
 - Made sure that Collection->getAll returns only the entries. And added option to return data raw (as returned by API)
 - Replaced resourceName with collection/form/singleton with automatic loading of available data
 - Renamed "Additional Fields" to "Options"

Some things which should probably still be changed before it can be released are:
 - Adding parameter "Return All" with "Limit" like all nodes have that offer "getAll" operation (example Pipedrive)
 - Instead of the "data" field for "create" and "update" it should probably work like on the HTTP Request Node fpr with Headers. There it is possible to add them either via the UI one by one with Key & value or as JSON.

**Comment by terenaa** [comment]
It's good to hear that!

However, I have some thoughts about what you said.

It was a good idea to rename some operations, I left old names by accident (in previous solution they were included in endpoint URL).

`getAll` will return only the entries if you set `Simple` attribute to 1, raw data otherwise, so there is no need to add another parameter.

In my humble opinion autoloading in this case is danger. I didn't use it intentionally, since API keys in Cockpit may be restricted to single endpoint, e.g. `/collections/get/posts` and may have no permissions to read `/collections/listCollections`. I couldn't find any fallback for such type of field, so in the worst case user wouldn't be able to use the node. Furthermore, it breaks [Reuse parameter names](https://docs.n8n.io/#/create-node?id=reuse-parameter-names) rule.

Adding parameter (or operation?) `getAll` is good idea, since Cockpit hasn’t got any default limit. The `limit` field is placed in Options set, so  a clever way needed to do it right.

Changing `data` field for “create” and “update” is a very good idea! I forgot about such smart way to do it!

Do you want me to make "before release" improvements or prefer to do it on your own?

**Comment by janober** [comment]
Thanks a lot!

Good to know about the "simple" option. I did not see that. I left the "raw" option and make it set the "simple" one and then did remove the "simple" option. I also moved the "limit" to the top-level and removed it under "options". The reason for that is to make all n8n nodes as similar as possible. As that is the format and the naming people already know from other nodes. It is important to try to keep it as consistent as possible as that makes it easier for the users.

With the autoloading. Yes, that makes sense. But people would still have been able to set the value as expression in the worst case. But you are right that is for sure not perfect. So change now the frontend to simply display a string-field if parameters failed to load from the server. It will still display that there was a problem but people will then be able to simply type it in manually. So hopefully the best of both.

About the "Reuse parameter name" rule. You are totally right that brakes it. But that is actually the most important only then when the value should be kept if changing for example the "Operation" from "delete" to "update" and represents generally the same data. So people should use "entityId" instead of "deleteId", "updateId", ... in the "resourceName" case I think it is a grey area. It kind of represents similar kind of data but there is no overlap as "forms" are totally separate from "collections". Also is it as "resourceName" much more confusing for users. If it says "Collection" or "Form" they know directly what it is about. If it says "Resource Name" they probably do not.

Made all of the changes except the "data" field. It would be great if you could take care of that. Thanks!

**Comment by janober** [comment]
@terenaa Did you have another look at the "data" field? Because I would like to release a new version and I can not unless it got changed.
If you have no time is also OK. Simply tell me and I will.

**Comment by terenaa** [comment]
@janober I have a plan to finish this part today :)

**Comment by janober** [comment]
Really cool! Thanks a lot!

**Comment by janober** [comment]
Got released with n8n@0.61.0

**Pull request merged**
