### PR TITLE
Nextcloud integration

### PR DESCRIPTION
**Pull request by zahidcoder**
Integrated the functionalities of Nextcloud applications (Deck, Notes, Tables, Talk) into n8n.

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @zahidcoder,

Thanks for the PR, We have created "GHC-253" as the internal reference to get this reviewed.

One of us will be in touch if there are any changes needed, in most cases this is normally within a couple of weeks but it depends on the current workload of the team.

**Comment by Joffcom** [comment]
Hey @zahidcoder,

Thanks for the PR, We have created "GHC-253" as the internal reference to get this reviewed.

One of us will be in touch if there are any changes needed, in most cases this is normally within a couple of weeks but it depends on the current workload of the team.

**Comment by Joffcom** [comment]
Hey @zahidcoder,

Thanks for the PR, We have created "GHC-253" as the internal reference to get this reviewed.

One of us will be in touch if there are any changes needed, in most cases this is normally within a couple of weeks but it depends on the current workload of the team.

**Comment by zahidcoder** [comment]
Hey@Joffcom,
Yes, sure I will revert the changes in json, and also update the template for PRs.

**Comment by zahidcoder** [comment]
## 🩺 Description



Integrated Nextcloud functionalities (Deck, Notes, Tables, Talk) into n8n, enabling users to automate and manage their Nextcloud data seamlessly within n8n workflows.

## 🔗 Related Issues



- Fixes #ISSUE_NUMBER

## 🧪 How Has This Been Tested?



- Unit tests for each Nextcloud resource and operation
- Manual testing using n8n instance to ensure all operations perform as expected
- Reverted unnecessary JSON changes as per feedback

## 📋 Checklist



- [x] I have read the [Contributing Guidelines](https://github.com/n8n-io/n8n/blob/master/.github/CONTRIBUTING.md)
- [x] My code follows the code style of this project
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [x] All new and existing tests passed

## 💡 Additional Information



- Reverted changes in JSON files as they are not required
- Added comprehensive unit tests to ensure no breakage of existing functionalities

**Comment by zahidcoder** [comment]
Creating new PR with template

**Pull request closed without merging**
