### PR TITLE
fix(core): Fix AddMfaColumns migration for sqlite (no-changelog)

### PR DESCRIPTION
**Pull request by netroy**
When ever we have migrations that use `.addColumn` or `.dropColumn`,  typeorm recreates tables for sqlite. so, we need to disable foreign key enforcement for sqlite, or else data in some tables can get deleted because of `ON DELETE CASCADE`

[This has happened in the past](https://github.com/n8n-io/n8n/pull/6739), and we should really come up with a way to prevent this from happening again.

### CODE REVIEW

**Review by mutdmour — DISMISSED** [review]

**Review by ivov — DISMISSED** [review]
We might need a script to enforce this.

**Review by OlegIvaniv — APPROVED** [review]
Re-run e2es

**Review by RicardoE105 — APPROVED** [review]

**Comment by netroy** [comment]
Looks like we can only merge this after someone from @n8n-io/migrations-review approves as well.

**Review by mutdmour — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.5.1`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.5.1)

**Pull request merged**
