### PR TITLE
:zap: List operation now can download attachaments automatically

### PR DESCRIPTION
**Pull request by RicardoE105**
https://community.n8n.io/t/how-to-send-attachments-using-mailgun-node/2979/4

### CODE REVIEW

**Comment by janober** [comment]
Thanks a lot. Got merged.

**Comment by richardjlo** [comment]
@janober should this work in n8n cloud already?

**Comment by BHesseldieck** [comment]
@richardjlo will be part of the next version release which you then can select in your cloud panel 👍🏼

**Comment by janober** [comment]
Got released with n8n@0.95.0

**Pull request merged**
