### PR TITLE
:sparkles: Emelia Nodes

### PR DESCRIPTION
**Pull request by chlec**
Emelia (cold-mailing platform https://www.emelia.io) nodes for n8n. Including a basic actions node and a trigger node (triggered when a campaign activity occurs)

### CODE REVIEW

**Comment by RicardoE105** [comment]
@chlec really cool. We will review as soon as we have time. Thanks.

**Comment by RicardoE105** [comment]
@chlec I was reviewing the PR and wondering if there is an endpoint to retrieve all the currently active webhooks? I saw you used `/webhook/webhook` to create the webhook but could find documentation about it. Can you point me out in the right direction? Thanks for your contribution.

**Comment by chlec** [comment]
@RicardoE105 yes actually there is no documentations about the webhooks. But you can get all of them on this route `/webhook` with GET.

**Comment by RicardoE105** [comment]
@chlec got it, thanks. Another question. Whenever I create a webhook, I Inmedially (Do not do anything in the Emelia UI) receive a post to the `hookUrl` with the following data in the body. Any idea what might be happening there?

```
{
  event: 'REPLIED',
  contact: {
    firstName: 'Jean',
    lastName: 'Dupont',
    phoneNumber: '0238690101',
    email: 'jean.dupont@gmail.com',
    company: 'Microsoft'
  },
  date: '2021-02-17T23:21:36.339Z'
}
```

**Comment by chlec** [comment]
Well, it was initially to send some samples data to Zapier after webhook creation, it should be fixed in few minutes.

**Comment by RicardoE105** [comment]
@chlec ahh got it thanks. Last question. Do all events have the same JSON structure? does always the contact comes?

```
{
  event: 'REPLIED',
  contact: {
    firstName: 'Jean',
    lastName: 'Dupont',
    phoneNumber: '0238690101',
    email: 'jean.dupont@gmail.com',
    company: 'Microsoft'
  },
  date: '2021-02-17T23:21:36.339Z'
}
```

**Comment by chlec** [comment]
@RicardoE105 yes the JSON structure always remains the same, and there is always a contact linked to an event.

**Comment by janober** [comment]
Thanks a lot. Got merged with #1455

**Comment by janober** [comment]
Got released with n8n@0.109.0

**Pull request closed without merging**
