### PR TITLE
feat(GitLab Node): Add support for pagination on getIssues

### PR DESCRIPTION
**Pull request by antondollmaier**
The GitLab API to get issues uses pagination:

https://docs.gitlab.com/ee/api/issues.html#list-issues

The default behavior is to limit to 20 results per page.

The GitLab node does not respect this pagination.

I adjusted the existing parameters for `returnAll` and `limit`,
so the node now retrieves either all results of the search,
or limit to the given number.

Additionally, I extended the filter to support the parameter
`search`, searching for the parameter in the title and description
of issues.

Tests of the Gitlab node do not exist, so I did not add them.

Disclaimer: I'm no developer. I followed the CONTRIBUTING guide. 
Could you let me know if additional changes are needed to merge this feature?

### CODE REVIEW

**Comment by Joffcom** [comment]
Hey @antondollmaier,

Thanks for the PR, Looking at it the choice taken doesn't follow our normal design process. If you wanted to create a Get Many / Get All option instead like most of our other nodes have we can accept that and merge it in.

What do you think?

**Comment by antondollmaier** [comment]
Hi @Joffcom,

> Looking at it the choice taken doesn't follow our normal design process. If you wanted to create a Get Many / Get All option instead like most of our other nodes have we can accept that and merge it in.

I'm uncertain of what you are asking: I did re-use the existing inputs for "return All" as well as the "Limit" input field, which is already in use for other node actions (get All releases, ...):

Screenshot of change in the PR

Adding the "Search" field was just a bonus after reading the GitLab API.

Would you be kind enough to let me know what I need to add/modify/implement so I can get the "get issues from repository" node to actually fulfill its description?

Best,
Anton

**Comment by Joffcom** [comment]
Hey @antondollmaier,

Looks like there are some lint issues that need to be resolved as well if you get a chance.

**Comment by antondollmaier** [comment]
Hi,
> Looks like there are some lint issues that need to be resolved as well if you get a chance.

Now that I've found that I can lint in each module/node individually and that "pnpm lintfix" is a thing as well, I've pushed the changes.
I hope that GitHub will squash my changes, so the PR is just one commit.

**Review by Joffcom — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.17.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.17.0)

**Pull request merged**
