### PR TITLE
fix(Redis Node): Add support for username auth

### PR DESCRIPTION
**Pull request by netroy**
## Summary

This PR adds support for username auth on Redis and RedisTrigger nodes.

To test this, you can use the following docker-compose snippet to start a redis container to test these nodes with:
```yaml
services:
  redis-auth:
    image: redis/redis-stack
    container_name: redis-auth
    restart: unless-stopped
    environment:
      REDIS_ARGS: "--requirepass password --user username on >password ~* allcommands --user default off nopass nocommands"
    ports:
      - "8001:8001"
      - "6379:6379"
```

## Related Linear tickets, Github issues, and Community forum posts

NODE-2174

## Review / Merge checklist

- [x] PR title and summary are descriptive. ([conventions](../blob/master/.github/pull_request_title_conventions.md)) 
- [ ] [Docs updated](https://github.com/n8n-io/n8n-docs) or follow-up ticket created.
- [x] Tests included. 
- [ ] PR Labeled with `release/backport` (if the PR is an urgent fix that needs to be backported)

### CODE REVIEW

**Review by dana-gill — CHANGES_REQUESTED** [review]
In general, this looks good 😄 It looks like CodeCoverage is complaining about not being able to test [this line](https://github.com/n8n-io/n8n/blob/e9b9dcded362428b71b584991b0f7e2efe781555/packages/nodes-base/nodes/Redis/utils.ts#L30). Could you add a `utils.redisConnectionTest` test? I think checking that `setupRedisClient` is called with the right credentials should suffice.

**Comment by dana-gill** [comment]
Just to note as well: I tested this a bit differently from the PR description. Here is what I did:

- Logged into my cloud account of Redis Stack
- Created a new credential on n8n using the connection string from Redis Stack. I didn't explicitly create a user on Redis Stack so my username (which Redis automatically assigned to me) was `default`
- Successfully tested the Info node using the new credential

My previous credentials also worked without having to change anything ✅

**Review by dana-gill — COMMENTED** [review]
What's the purpose of moving the `tests` to a `__tests__` folder? I feel like it introduces a slightly new way to structure the tests

**Review by dana-gill — APPROVED** [review]
`__tests__` make sense :)

**Review by dana-gill — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.73.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.73.0)

**Pull request merged**
