### PR TITLE
Mailchimp Integration (trigger)

### PR DESCRIPTION
**Pull request by RicardoE105**
Hey pal @janober 

You have the credentials to test this. Please use the test list. Sadly you are not gonna be able to fire a webhook to a domain created with localtunnel when you create the webhook. This is because Mailchimp does some sort of validation with the domain.

When the webhook is going to be created they send a GET request to validate it as you can see here

image

### CODE REVIEW

**Comment by janober** [comment]
Ah yes, that is not great if they send data normally via POST but do the test via GET. Should however not be a problem. You can simply register both. That is how for example the Trello-Trigger Node works as they do exactly the same. You can find it here:
https://github.com/n8n-io/n8n/blob/master/packages/nodes-base/nodes/Trello/TrelloTrigger.node.ts

Hope that helps.

**Comment by RicardoE105** [comment]
@janober NICE. I did not know this was possible. Thanks

**Comment by RicardoE105** [comment]
@janober I added the GET method but by the time Maichimp tries to verify the URL which is when executing the create function the GET route has not been registered yet, so when the request hits the server gets 404. I have understood that the webhook is registered when you run it and after the first request is deleted.

The Trello "verification" works cuz it happens after the webhook is created unlike Mailchimp that it happens when creating the webhook and if that does not work then the webhook is not created.

**Comment by RicardoE105** [comment]
It will work on production mode though as long as the workflow is activated.

**Comment by RicardoE105** [comment]
@janober Tested it on production and worked well.

**Comment by janober** [comment]
@RicardoE105 Great, thanks a lot. Got merged.

I was actually wondering why it would not work when testing as it should first create the webhook endpoints locally and then run the code in the "create" function. So I wanted to debug it but realized very fast that there was nothing to debug as it worked already without any changes. If "Execute Workflow" gets pressed it creates the webhook correctly, receives the data and deletes it. So all perfect. However, still wonder why it did not work for you.

**Comment by janober** [comment]
Sorry forgot to update here. Got released with n8n@0.39.0

**Pull request merged**
