### PR TITLE
⚡️ Infobip node

### PR DESCRIPTION
**Pull request by Yann-J**
Support for Infobip API to send and receive SMS (possibly in the future Whatsapp / voice...)

### CODE REVIEW

**Comment by Yann-J** [comment]
Hello @ivov wondering if this one can be looked at soon?

Thx!

**Comment by ivov** [comment]
@Yann-J Thank you for your contribution and apologies for the delay.

@nivb06 is responsible for prioritizing PRs and should be able to provide an answer.

**Comment by nivb06** [comment]
Hi @Yann-J, echoing @ivov's thanks for the contribution
We would very soon reach out to new node contributors, asking them the upload their nodes to npmjs.com, since as we speak the feature that would allow an easy npm package upload to n8n is being built.
Therefore, we won't merge new node PRs anytime soon

**Comment by Joffcom** [comment]
Hey @Yann-J,

Thanks for the contribution, We have now created a Community Node Repository which is our preferred method for new node submissions.

Once a node has been published to the Community Node Repository users will be able to install the node from their n8n interface and will be able to use your node quicker, You will also be able to update the node as needed without needing to wait for the review process.

In the future we may reach out to you about including your node in our main release, But for now I am going to close this PR.

You can find more information in the links below, If you have any questions about this or need any help let us know.

Building Community Nodes: https://docs.n8n.io/integrations/community-nodes/build-community-nodes/
Submitting Community Nodes: https://docs.n8n.io/integrations/creating-nodes/deploy/submit-community-nodes/
Published Nodes: https://www.npmjs.com/search?q=keywords:n8n-community-node-package

**Pull request closed without merging**
