### PR TITLE
fix jiraSoftwareCloud fields.assignee

### PR DESCRIPTION
**Pull request by MyCupOfTeaOo**
image

### CODE REVIEW

**Comment by RicardoE105** [comment]
According to the JIRA cloud API, when sending the assignee, it should use the property id as the picture below. If we merge it like that, it will break the JIRA cloud. I guess we need an If condition there. If it's Jira cloud, send it with the property id and, if not, send it with the property name. Did you test it with name and it worked or just made the change? I have not been able to test it since I do not have a JIRA server deployment to do so.

image

Here the link to the API https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-rest-api-3-issue-post

**Comment by MyCupOfTeaOo** [comment]
> According to the JIRA cloud API, when sending the assignee, it should use the property id as the picture below. If we merge it like that, it will break the JIRA cloud. I guess we need an If condition there. If it's Jira cloud, send it with the property id and, if not, send it with the property name. Did you test it with name and it worked or just made the change? I have not been able to test it since I do not have a JIRA server deployment to do so.
> 
> image
> 
> Here the link to the API https://developer.atlassian.com/cloud/jira/platform/rest/v3/#api-rest-api-3-issue-post

have a new commit,i test it success with name on my jira self-hosted

**Comment by janober** [comment]
Thanks! But does it really work and got tested properly?
For example, does the `getUsers` function which gets used to query the users to use in the select-field still return the user-id and not the user-name. Meaning currently it would set the user-id as user-name in the hosted version?!?!
And if that is wrong, it has to be tested if the other parameters which use the `getUsers` as `loadOptionsMethod` also expect the user-id instead of the user-name and everything has to get changed accordingly if needed. I really want to make sure that if we fix something we:
  1. fix it properly
  2. hopefully everywhere 
  3. do not break anything else

Thanks!

**Comment by MyCupOfTeaOo** [comment]
> 谢谢！但是它真的有效并且经过了适当的测试吗？
> 例如，`getUsers`用于查询用户以在选择字段中使用的函数是否仍返回用户ID而不是用户名。这意味着当前它将在托管版本中将用户标识设置为用户名？！？！
> 并且如果这是错误的，则必须测试使用`getUsers`as 的其他参数是否`loadOptionsMethod`也希望使用用户ID而不是用户名，并且如果需要，所有内容都必须进行相应更改。我真的想确保如果我们解决问题，我们将：
> 
> 1. 正确修复
> 2. 希望到处都是
> 3. 不要破坏其他任何东西
> 
> 谢谢！
Well, in fact, loadOptionsMethod has nerver been bale to run on my self-hosted jira service, I think the problem may be here.
image
image
image
image
getOptions can only get the default values,and the default values here are all corresponding to the "cloud",This obviously leads to an error,which obviously causes getCredentials to throw an error, Can get the values I are configuring when getOptions is called?

**Comment by janober** [comment]
Yes, you are right Projects would not have worked right now. Got fixed:
https://github.com/n8n-io/n8n/commit/98ac9d93bce9ef041bea501b88f38ee3c107452c

All the other ones, however, should work unless also they also need different endpoints. For the `getUsers` method it would probably need similar code to return the name instead of the id as value.

**Comment by MyCupOfTeaOo** [comment]
image
image
After observing the code, I modified here, the type does not correspond here, I have tested all the functions of the issue on the self-hosted jira server, I think this modification should not affect the jira cloud, but because I do not have jira The cloud environment omits the test here, can you help me test it here, thank you

**Comment by janober** [comment]
Great, thanks a lot got merged.

I made some minor improvements. Can you please check if everything still works fine for you. Thanks!

**Comment by janober** [comment]
Got released with n8n@0.67.0

It sadly contains a few breaking changes so please make sure to check here before upgrading:
https://github.com/n8n-io/n8n/blob/master/packages/cli/BREAKING-CHANGES.md

**Pull request merged**
