### PR TITLE
feat(HTTP Request Node): Option to provide SSL Certificates in Http Request Node

### PR DESCRIPTION
**Pull request by michael-radency**
## Summary
new option in HTTP Request node that allows to provide certificates as a separate credentials
image
image

image

## Related tickets and issues
https://linear.app/n8n/issue/NODE-1153/http-node-add-client-certificate-support#comment-2c67e5ea
https://community.n8n.io/t/ssl-certificate-for-http-request/6086/1
https://community.n8n.io/t/http-with-client-certificate-auth-request/20753

### CODE REVIEW

**Review by netroy — CHANGES_REQUESTED** [review]

**Review by netroy — DISMISSED** [review]
besides one comment, LGTM

**Review by netroy — DISMISSED** [review]

**Review by netroy — APPROVED** [review]

**Comment by janober** [comment]
Got released with [`n8n@1.40.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%401.40.0)

**Comment by vbarrier** [comment]
Hi how to use it? I try on 1.40.0 & 1.41.0 I don't see this option (and SSL Certificate credentials either)

(on a fresh new n8n setup)

**Comment by michael-radency** [comment]
Hello @vbarrier, you need to enable SSL Certificates in node's settings(cog icon), after that selector would be available in node's parameters

**Comment by vbarrier** [comment]
Thank you! But now I'm still missing the credentials part.

credentials-ssl-https

No options in Credentials settings to create one.

**Comment by vbarrier** [comment]
> Thank you! But now I'm still missing the credentials part.
> 
> credentials-ssl-https
> No options in Credentials settings to create one (in the node or in the credentials list)

Any insight @michael-radency?

**Comment by vbarrier** [comment]
I don't know if there is some cache on credentials list but it finally appears.

**Comment by lukasabino** [comment]
I'm testing this functionality, in the Certificate part, can I pass the location of the .CRT file?

How is the usability of this itself?

I'm using N8N as queue mode in Docker Swarm.

image

**Comment by muneebmercans** [comment]
I have a pfx certificate, in which field should I add it?
Also the value is of string type, so should it be a path to the certificate or the content of certificate?

Screen Shot 2024-05-22 at 1 52 06 PM

**Comment by netroy** [comment]
> I have a pfx certificate, in which field should I add it?

Answered [here](https://community.n8n.io/t/n8n-http-request-with-ssl-certificate-auth/46502/3)

**Pull request merged**
