### PR TITLE
enable header clicks on tags

### PR DESCRIPTION
**Pull request by mutdmour**
- enable clicks on tags container in header
- keep selection in workflow open disabled

### CODE REVIEW

**Review by BHesseldieck — APPROVED** [review]
:shipit:

**Comment by janober** [comment]
Sorry, 100% on me! Thanks a lot for fixing what I did mess up!

**Comment by mutdmour** [comment]
no worries. 😊

**Comment by janober** [comment]
Got released with n8n@0.122.2

**Pull request merged**
