### PR TITLE
refactor(core): Use injectable classes for db repositories (part-1) (no-changelog)

### PR DESCRIPTION
**Pull request by netroy**
N8N-5289

### CODE REVIEW

**Comment by RicardoE105** [comment]
@netroy was testing it with MySQL and got this message in the console.

https://github.com/typestack/typedi/issues/636

image

The error happens when I execute a workflow. Also, the workflow fails, even though it was working before.

**Comment by RicardoE105** [comment]
I looked, and we cannot get an InternalHooks instance without initializing the database. 

https://github.com/n8n-io/n8n/pull/5955

**Review by krynble — APPROVED** [review]
Code looks all right, had the same issue as Ricardo but the latest commit fixed it for me as well.

Also working fine with queue mode.

**Comment by netroy** [comment]
the failing e2e test is coming from master.

**Comment by janober** [comment]
Got released with [`n8n@0.224.0`](https://github.com/n8n-io/n8n/releases/tag/n8n%400.224.0)

**Pull request merged**
